### ISSUE TITLE
Autolayout support

### ISSUE THREAD

**Issue by adad184** [ibireme/YYText#1]
实现 intrinsicContentSize 以及 preferredMaxLayoutWidth

**Comment by wonderffee** [comment]
ls想表达什么麻烦说清楚啊

**Comment by puttin** [comment]
@wonderffee 我猜测 @adad184 的意思是支持
不设置高优先级 的`.Width`或`.Height`时, view 根据 `contentHuggingPriority` 和 `contentCompressionResistancePriority` 能正常显示的意思

**Comment by ibireme** [comment]
稍后会添加支持～ 感谢提出～

**Comment by adad184** [comment]
希望能把YYText的架构 详细的讲解一下 :]   代码写得非常棒!

**Comment by yimiaodaren** [comment]
我目前就遇到过问题，用xib在cell上添加了一个UIView设置Class为YYLabel.. 并且设置了自动布局，距离左边上边.  然后我cell刷新时设置text或者attText 结果都是看不见，于是我强制了YYLabel的宽度和高度，还是看不见文字

**Comment by ibireme** [comment]
如果单行文字内容的高度大于 Label 的高度，可能会造成这种结果。
这个问题之后会进行优化。

**Comment by seedotlee** [comment]
+1
然后使用storyboard设置class和module貌似也识别不出来

**Comment by yupliang** [comment]
@ibireme 怎么估算出显示attributestring的高度？CTFramesetterSuggestFrameSizeWithConstraints，demo里怎么检索不到这个方法？

**Comment by ibireme** [comment]
文本排版和宽高查询现在可以用 YYTextLayout，Readme.md 里有提到。

**Comment by LiweiDong** [comment]
所以。。现在使用autolayout的controller里不能使用YYText？

**Comment by ibireme** [comment]
可以用，只是需要手动添加约束或者手动调整frame。

**Comment by LiweiDong** [comment]
用的autolayout   在viewdidload里计算了文本高度 并设置label的约束，用背景色看label的frame是正确的，但显示的文本高度却不够  缺几行文字。

在viewdidappear里又重新设置了一遍textlayout和约束  才能正常显示文本。

用什么方法可以在viewdidload里强制刷新文本？

**Comment by LiweiDong** [comment]
不管多高的文本    总是缺少最后两行文本

**Comment by SawyerEve** [comment]
在使用YYTextSimpleEmoticonParser的情况下YYTextLayout计算高度好像不是很准确

**Comment by wy19901227** [comment]
目前 xib中设置了attributeStr后，高度自适应吗？ 还是说得手动计算？

**Comment by wy19901227** [comment]
@adad184 当时一直在找为什么UILable可以自适应text的api，原来是有intrinsicContentSize方法，那如果YYLable增加了类似intrinsicContentSize的方法，那就完全支持autolayout了。

**Comment by kejinlu** [comment]
@SawyerEve  的确是个问题 ，@ibireme YYTextLayout计算尺寸的时候，并不会考虑对应的YYLabel所设置的一些东西，比如行数的约束，比如parser的解析等

**Comment by zuocai1993** [comment]
感谢YY大神的分享。  我在插入完图片后   再编写文字  字体变小 这个要做什么处理哦

**Comment by skyline75489** [comment]
@kejinlu  使用 `YYLabel` 自己的 `textLayout` 属性也不可以吗？按道理的话，使用 `YYLabel` 本身的 `textLayout` 属性算一下 `textBoundingSize` 得到的就是 `intrinsicContentSize` 了。

**Comment by ibireme** [comment]
已添加 AutoLayout、Interface Builder 支持。
如果还有问题，可以再新建 issues 讨论。
