### ISSUE TITLE
swift 中使用pod方式引用不到YYImage

### ISSUE THREAD

**Issue by seedotlee** [ibireme/YYText#10]
具体报错如下

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_YYAnimatedImageView", referenced from:
      objc-class-ref in NSAttributedString+YYText.o
      objc-class-ref in YYTextView.o
  "_OBJC_CLASS_$_YYImage", referenced from:
      objc-class-ref in UIPasteboard+YYText.o
      objc-class-ref in YYTextView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ibireme** [comment]
1. 把 Cocoapods 更新到最新版。
2. Podfile 里，把 YYImage 放在 YYText 之前。

看看是否还有问题

**Comment by seedotlee** [comment]
使用的是最新版Cocoapods

貌似还是不行，同样的错误

**Comment by seedotlee** [comment]
使用普通方式导入库与YYWebImage的@interface YYImage : UIImage <YYAnimatedImage>冲突 
`duplicate interface definition for class`

**Comment by ibireme** [comment]
贴一下你的 Podfile 我测试一下

**Comment by seedotlee** [comment]
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

# swift
pod 'Alamofire', '~> 3.0.0'
pod 'SwiftyJSON', '~> 2.3.0'
pod 'CryptoSwift'
pod 'KeychainSwift', '~> 2.0'
pod 'ObjectMapper', '~> 0.17'
pod 'XCGLogger'
pod 'SwiftDate', '~> 1.1'
pod 'NSDate+TimeAgo'
pod 'SnapKit'

# objective-c
#pod 'YYImage'
pod 'YYText'
pod 'YYWebImage'
pod 'MJRefresh'
```

还有几个development pods 应该没有什么影响

**Comment by seedotlee** [comment]
@ibireme 还有是我的是deployment target 8.0

**Comment by seedotlee** [comment]
我现在移除掉YYImage 和YYText 之后
YYWebImage也编译不过了，之前是可以的。。。

**Comment by ibireme** [comment]
1. 之前的依赖判断是在编译时进行的，看来可能会由于链接顺序导致问题。现在改成了运行时的依赖判断。你再更新一下 pod 试试，更新完成后 clean 一下工程。
2. YYWebImage 包含 YYImage，如果你已经添加了 YYWebImage，那就没必要在添加 YYImage 了。这个稍后我会更新文档说明。

**Comment by seedotlee** [comment]
谢谢，这么快反馈

pod 中只使用了

```
pod 'YYWebImage'
pod 'YYText'
```

在YYText的framework里面还是报 YYImage 重复定义
我没有引用添加YYImage

不知道是不是pod或者xcode的bug，我全文搜索也只找到一个

```
@interface YYImage : UIImage <YYAnimatedImage>
```

**Comment by ibireme** [comment]
我这里暂时检测不出问题了。。测试工程也能正常构建。

你可以尝试新建一个工程，只引用 YYWebImage 和 YYText 两个库，然后构建看看是否有问题。

如果没问题，你可以试试把你的项目中这两个库先删除掉，然后 pod update，工程 clean。之后再添加回来，确保是最新版本。

如果还有问题，发一下你的cocoapod版本、Xcode版本和错误日志。

**Comment by seedotlee** [comment]
简直把我坑死了。。。
各种清空缓存都不行，然后我把代码复制到另外一个目录再去`pod update`之后竟然就可以了

所以可以得出肯定是xcode的缓存的问题
最终还是通过 
`window->projects` 在这里面找到自己项目，彻底的remove之后才编译成功

引起这个错误的原因就是因为之前应用了YYWebImage 之后又添加了YYImage，造成重复定义
然后一直无法清除这个缓存错误。

最后，谢谢你的一直跟进

**Comment by linqing-lu** [comment]
如果在Podfile中使用了 use_frameworks! 就会有这问题。

**Comment by zzgo** [comment]
同样的问题，在使用YYKit时报错。。。看上面的解答，要分别引入几个库，然后因为我使用了yymodel，还要重新去加前缀。
感觉有点蛋疼，希望作者大大想办法解决这个冲突问题。。

**Comment by looseyi** [comment]
如果引用了YYWebImage 和 YYImage/WebP 这种在swift 的static lib module下这个就解决不了啊  Duplicate interface definition for class 'YYImage'
