### ISSUE TITLE
YYLabel  在6 plus 真机上的问题。

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#100]
我是这样 使用YYLabel的
        YYLabel* ll=[[YYLabel alloc]init];
        ll.frame=CGRectMake(0, 10, [UIScreen width], 40);
        ll.numberOfLines=0;
          NSMutableAttributedString* str=[[NSMutableAttributedString alloc]initWithString:[NSString stringWithFormat:@"积分:%@\n点击查看积分详情>>",responseDictionary[@"integral"]==nil?@"0":responseDictionary[@"integral"]] attributes:nil];
         [str yy_setFont:[UIFont systemFontOfSize:12] range:NSMakeRange(str.length-10, 10)];
         [str yy_setFont:[UIFont systemFontOfSize:17] range:NSMakeRange(0, str.length-10)];
         str.yy_alignment=NSTextAlignmentCenter;
         str.yy_color=[UIColor whiteColor];
         ll.attributedText=str;

5，6 ，6plus的模拟器都没问题， 在6plus真机上 会由于label的frame不够大，而显示不全。
不全图片
![image](https://cloud.githubusercontent.com/assets/8086633/12061539/cd3b2e14-afc3-11e5-9258-801dfc26360e.png)
6p'lus 模拟器正常。
![image](https://cloud.githubusercontent.com/assets/8086633/12061542/de3520b2-afc3-11e5-9e3c-0a6fb852a23a.png)
所以，我只能把高度调为45，才解决这个问题。是不是这种方式  有问题。

**Comment by ibireme** [comment]
模拟器和真机应该是一致的啊。。这么用看着也没问题啊。。
我猜，可能是字体相关的问题？

**Comment by wy19901227** [comment]
字体用的是系统默认字体。

发自我的 iPhone

**Comment by ibireme** [comment]
难道是文字太多了？

这个，建议尽量提供更多的空间给文字。如果拿不准，可以先计算一下文字显示大小，再根据大小来赋值。

**Comment by wy19901227** [comment]
我感觉我给的空间是够，因为5，6上边都能显示，但是在6plus真机上大小不够了，我想是不是因为6plus的frame机制问题，比如我设置一个高度10的view.在6plus标准模式上显示出来发现高度是要比10打的，这点，我不是很懂。

发自我的 iPhone

**Comment by ibireme** [comment]
frame 机制肯定是一致的。。

你可以试试按照 readme 中 `文本布局计算` 这段代码，计算一下那段文本实际需要占用的页面大小。
