### ISSUE TITLE
部分 api 被废弃了，是我导入YY版本太低了么

### ISSUE THREAD

**Issue by buzai** [ibireme/YYText#101]
/Users/Desktop/coco/cocop/Pods/YYKit/YYKit/Text/String/NSAttributedString+YYText.m:656:32: 'kCTCharacterShapeAttributeName' is deprecated: first deprecated in iOS 9.0

**Comment by ibireme** [comment]
kCTCharacterShapeAttributeName 这个属性是 CoreText 的，我只是简单的把这个封装了一下。

**Comment by buzai** [comment]
嗯谢谢，我把你的那部分去掉了，应该没问题吧

**Comment by ibireme** [comment]
没问题。这个属性应该没人会用。
