### ISSUE TITLE
开启异步绘制在tableviewCell中的Label，加载更多数据后直接reloadData，会有明显的闪烁。

### ISSUE THREAD

**Issue by pandaBilbo** [ibireme/YYText#103]
contentLabel = YYLabel()
        contentLabel.top = iconImageView.bottom + kCellContentTextMargin
        contentLabel.left = nickNameLabel.left
        contentLabel.width = kCellContentTextWidth
        contentLabel.displaysAsynchronously = true
        contentLabel.ignoreCommonProperties = true
        contentLabel.fadeOnHighlight = false
        contentLabel.fadeOnAsynchronouslyDisplay = false
        self.addSubview(contentLabel)
开启异步，这里加载更多数据tableview reloadData后文字会明显闪动，关闭异步不会出现闪烁现象

**Comment by ibireme** [comment]
见这个讨论：https://github.com/ibireme/YYKit/issues/64

**Comment by wy19901227** [comment]
这是因为realoadData的时候，所有可见的cell都会刷新，而刷新的时候首先会被clear，所以建议你根据自己cell的model，赋值的时候如果是同一个model，就不进行赋值。这样就可以解决刷新闪烁的问题

发自我的 iPhone

**Comment by pandaBilbo** [comment]
是的，通过赋值的时候判断是不是同一个model可以解决，使用insert行的方式也可以。thanks

**Comment by wy19901227** [comment]
加载更多后，insert加载的第一个吗？
发自我的 iPhone

**Comment by pandaBilbo** [comment]
数据多了几个就插入了几行
