### ISSUE TITLE
项目中的图文混排全部替换为YYText了，提出一个疑问

### ISSUE THREAD

**Issue by HebeTienCoder** [ibireme/YYText#105]
想实现微信朋友圈的效果，长按出现复制menu，底部的背景border还是高亮状态，何时取消高亮由自己决定。找了一下貌似没找到相关方法，目前是改了一下你的源码实现的，不知道能否让它原生支持？或者是已经支持，我没有找到？谢谢您的贡献！

**Comment by ibireme** [comment]
默认好像是不支持。
需要这个需求的人我觉得并不多，加上这些会让 API 更加复杂。。。

**Comment by HebeTienCoder** [comment]
哦哦，好吧，感谢回答

**Comment by HebeTienCoder** [comment]
YYTextLayout可以支持NSCoding吗？

**Comment by ibireme** [comment]
不支持。。因为 YYTextLayout 包含 CoreText 的对象，而这些对象不支持 NSCoding 协议。。

**Comment by HebeTienCoder** [comment]
好吧。。我还想直接把它缓存起来的😁

**Comment by ibireme** [comment]
嗯。。貌似可以加上，但是 Encode 时只能保存 NSAttributedString 和 YYTextContainer，Decode 时也得用这两个东西再重新初始化一遍。。 有空我加一下吧。

**Comment by HebeTienCoder** [comment]
恩恩好的！感谢！！！

**Comment by ibireme** [comment]
https://github.com/ibireme/YYText/commit/4447d54cfd74628cc25326b7693def1189a31811

**Comment by HebeTienCoder** [comment]
真是太效率了！！！！！
