### ISSUE TITLE
关于YYTextVerticalAlignment定义的问题

### ISSUE THREAD

**Issue by qwhu** [ibireme/YYText#106]
在YYTextDemo中的Text Attachements里面，最后一行的五个小表情和一个大表情，源代码设置的五个小表情的alignment是YYTextVerticalAlignmentCenter，大表情的alignment是YYTextVerticalAlignmentBottom。
正常来说，我期望的结果是：小表情应该是在所在行居中显示。
实际结果是：小表情在所在行靠底部显示。
然后，我修改大表情的alignment为YYTextVerticalAlignmentCenter，这样倒会让小表情居中显示。

**Comment by ibireme** [comment]
这块儿可以看一下 [NSAttributedString+YYText.h#L620-L648](https://github.com/ibireme/YYText/blob/master/YYText/Utility/NSAttributedString%2BYYText.h#L620-L648) 注释的示意图。

首先 attachment 会放到一个容器内（attachment holder），然后这个容器会根据 alignment 对其到其所在的文本行。attachment 也可以调整它在容器内的位置。

**Comment by qwhu** [comment]
多谢回复。细看了一下 NSAttributedString+YYText.h#L620-L648 注释的示意图，感觉还是没有理通，按我的理解alignment控制的是attachment holder在所在行的位置，实际的测试结果更像是控制的attachment content在attachment holder里面的位置（这个地方的测试情况也有些疑惑的地方，修改alignment属性，会引起attachment holder的高度发生变化），按照目前的代码设计，都不能通过设置attachment本身的信息来让它在所在行居中显示。

**Comment by ibireme** [comment]
首先，用这个方法创建 Attachment：

    + (NSMutableAttributedString *)yy_attachmentStringWithContent:(id)content
                                                      contentMode:(UIViewContentMode)contentMode
                                                   attachmentSize:(CGSize)attachmentSize
                                                      alignToFont:(UIFont *)font
                                                        alignment:(YYTextVerticalAlignment)alignment

content 是表情图片
contentMode 是 UIViewContentModeScaleToFill
attachmentSize 是表情需要显示的大小
font 是所在文本行的字体
alignment 是 YYTextVerticalAlignmentCenter

如果还有问题，可以直接用这个方法试试：

    + (NSMutableAttributedString *)yy_attachmentStringWithEmojiImage:(UIImage *)image
                                                            fontSize:(CGFloat)fontSize

**Comment by qwhu** [comment]
细看了一下代码，理解alignment的含义了，代码写的很赞👍。
