### ISSUE TITLE
报个yy_attachmentStringWithContent的bug

### ISSUE THREAD

**Issue by qwhu** [ibireme/YYText#107]
yy_attachmentStringWithContent带alignment参数的方法里面，设置alignment=YYTextVerticalAlignmentTop的case：
        case YYTextVerticalAlignmentTop: {
            delegate.ascent = font.ascender;
            delegate.descent = attachmentSize.height + font.descender;
            if (delegate.descent < 0) delegate.descent = 0;
        } break;
此处计算delegate.descent存在问题，应该是要改成delegate.descent = attachmentSize.height -font.ascender。
另外 if (delegate.descent < 0) delegate.descent = 0;设置delegate.descent=0的同时应该也需要设置delegate.descent=attachmentSize.height。

**Comment by ibireme** [comment]
UIFont.descender 是负数，RunDelegate.descent 需要的是正数，我看着应该没有错啊。

**Comment by qwhu** [comment]
把YYTextAttachmentExample里面所有图片和表情的alignment改成YYTextVerticalAlignmentTop就能看出问题了，我理解UIFont.descender是负数，RunDelegate.descent是正数的，所以RunDelegate.ascent + RunDelegate.descent 应该要等于attachmentSize.height。

**Comment by ibireme** [comment]
回家来调试了下看看，果真是有问题啊。。
我改一下，感谢提 bug～
