### ISSUE TITLE
YYLabel高亮问题

### ISSUE THREAD

**Issue by donggelaile** [ibireme/YYText#109]
把YYLabel放到cell上后点击时会响应点击事件，但是不会变成高亮模式设置的颜色等。放到self.view上或window上是可以的。但是不知道为什么放cell上点击就不行了，长按才会变成高亮模式的属性设置。

**Comment by ibireme** [comment]
设置一下 TableView：

    tableView.delaysContentTouches = NO;
    tableView.canCancelContentTouches = YES;

如果还有问题，可以参考下我的 Demo： [YYTableView.m](https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/YYTableView.m)、[YYTableViewCell.m](https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/YYTableViewCell.m)

**Comment by donggelaile** [comment]
感谢回答，因为我的tableView是放在横向scrollView上的，所以要两个滑动类都设置tableView.delaysContentTouches = NO;
tableView.canCancelContentTouches = YES;  就可以了。  谢谢。

**Comment by brownfeng** [comment]
解决了我的问题!!! 谢谢大佬
