### ISSUE TITLE
正则表达式匹配有bug

### ISSUE THREAD

**Issue by seedotlee** [ibireme/YYText#11]
如果text是预先赋值进入的，那渲染就没有问题

但是在后续手动输入一个匹配项之后，所有的字符都被认为是匹配的

好像是effectiveRange取区间有问题

<img width="375" alt="e4bd1e10-65d2-4435-a36b-3e9bcbeb313e" src="https://cloud.githubusercontent.com/assets/5188604/11037878/2746aa3e-873b-11e5-8762-3b02af6795bd.png">

**Comment by ibireme** [comment]
啊。。这个只是演示 TextBinding 特性的，正则表达式最开始就有问题我也懒得改了。。😝

**Comment by seedotlee** [comment]
额，这应该不是正则表达式写错了吧，好像是动态setAttribute的时候出现了问题
正则匹配正确，但是后面的数据不刷新

**Comment by ibireme** [comment]
我记得貌似是选取字符串和后续添加 binding 时有些问题，当时只是为了做个 Demo 来演示删除时的效果，所以并没有仔细修改。。。

**Comment by seedotlee** [comment]
额，那这个bug有修复计划么？

**Comment by ibireme** [comment]
目前不影响控件的功能演示，暂时不修复。
稍后有时间会再看下。。。
