### ISSUE TITLE
YYLabel中提供的sizeThatFits函数取到的size为0

### ISSUE THREAD

**Issue by ohswift** [ibireme/YYText#110]
YYLabel中提供的sizeThatFits，在没有设置bound和frame时，取到的size都是0。在该函数下先添加：_innerContainer.size = size;
后计算正常。不知道这样改会不会导致其他问题。

**Comment by ibireme** [comment]
加上 _innerContainer.size = size; 后，会修改内部文本容器的大小。。。
这个方法稍后会优化一下。

**Comment by ibireme** [comment]
fixed: https://github.com/ibireme/YYText/commit/9338ce9c6bb86052c57522cb1ea8f105313721d6
