### ISSUE TITLE
请教下yylabel的超链接响应问题

### ISSUE THREAD

**Issue by zyt520ham** [ibireme/YYText#111]
你好，YYText 很强大，但是当我在一个view上放置一个YYLabel时，当这个view有触摸事件时，yyLabel的超链接就都无法响应了，想请教下，这个问题，怎么解决呢？

**Comment by ibireme** [comment]
YYLabel 是重写了 UIResponder 的 touchesBegan: touchesMoved: touchesEnded: touchesCancelled: 这四个方法实现的触摸检测。你可以检测一下你用到的 View 是否有其他触摸事件和 UIResponder 的这几个方法有冲突。

比如你用了 UIGestureRecognizer，可以调节一下 gesture.cancelsTouchesInView 和 gesture.delaysTouchesBegan 属性来避免冲突。

**Comment by zyt520ham** [comment]
非常感谢您的回复，你帮我解决了大问题，很想加您的qq好友，与您一起探讨iOS的代码，我的qq：121816758

**Comment by ibireme** [comment]
额。。我只在工作中用一下 QQ，平时不怎么用的。。
有问题的话提 Issues 就好～

**Comment by zyt520ham** [comment]
帅哥，我又遇到一个响应的问题，请教下，我在一个UIView上添加了一个yytextView，然后UIView上有个UIGestureRecognizer，我设置了 gesture.cancelsTouchesInView = NO，gesture.delaysTouchesBegan= NO，导致点击yytextView也会响应gesture
问题很棘手，麻烦下，万分感谢

**Comment by bellchen** [comment]
请问怎么调整tableView.delaysContentTouches 和 tableView.canCancelContentTouches 属性？？全部设置为NO？
