### ISSUE TITLE
介绍该更新了

### ISSUE THREAD

**Issue by bottotl** [ibireme/YYText#112]
[NSMutableAttributedString yy_attachmentStringWithContent:image contentMode:UIViewContentModeCenter attachmentSize:image.size alignToFont:font alignment:YYTextVerticalAlignmentCenter];

应该修改为

    [NSMutableAttributedString attachmentStringWithContent:image contentMode:UIViewContentModeCenter attachmentSize:image.size alignToFont:font alignment:YYTextVerticalAlignmentCenter];

**Comment by ibireme** [comment]
YYKit 里面的 Category 方法都是没有前缀的，但是拆分出来的每一个独立组件都是有 yy_ 前缀的。
