### ISSUE TITLE
咨询一下text里头带有emoji的情况

### ISSUE THREAD

**Issue by shiablue** [ibireme/YYText#113]
假设我的 yylabel 只有一行。带有 emoji 和不带 emoji 的情况下计算出来的 yylabel 高度不一样。这个情况要怎么处理才能让它们计算出来的高度一致？

**Comment by ibireme** [comment]
中文、英文、Emoji 字体的高度都是不一样的，所以行高肯定也是不一致的。

**Comment by shiablue** [comment]
好吧。谢谢。
