### ISSUE TITLE
textview 中的 placeholder

### ISSUE THREAD

**Issue by seedotlee** [ibireme/YYText#114]
稍微看了下源码，为什么textview中的placeholder要使用image渲染上去呢？当只有纯文本的时候，字体和分辨率看起来怪怪的，与textfield的placeholder效果相差有些大

所以我建议是否可以根据placeholder的类型来确定显示在textview上的是image还是纯文本呢？

**Comment by ibireme** [comment]
这里这个 placeholder 是富文本，而且还支持某些自定义属性（比如 YYTextShadow/YYTextBorder），所以还是要自己手动画出来的。。即使用 UILabel 来显示，UILabel 内部也是绘制成图片来显示的呀～

"字体和分辨率看起来怪怪的" 是什么效果，能给个截图来对比说明一下吗?

**Comment by seedotlee** [comment]
比如说如下截图，我设置的字体和颜色都是一样的，但使用textview的placeholder渲染出来的效果就不是很好。

![7162747d-0b0d-4679-9146-4b1e2d7bc282](https://cloud.githubusercontent.com/assets/5188604/12252017/6446b726-b90e-11e5-98f5-a25434d991c4.png)

**Comment by ibireme** [comment]
翻了一下 UITextField 的 placeholder 默认颜色。。

    textView.placeholderTextColor = [UIColor colorWithRed:0 green:0 blue:25/255.0 alpha:44/255.0];

这样应该就一致了。

**Comment by seedotlee** [comment]
额，这不是颜色的问题，字体渲染出来也不一样的哦。。。

我都把textfeild的attributedPlaceholder设置成一样的了，出来的效果就那样了

```
 contentTextview.placeholderText = "细化描述能让响客们更好地帮助您解决".loc()
 contentTextview.placeholderTextColor = style.placeholderColor()
 contentTextview.placeholderFont = UIFont.systemFontOfSize(14.0)          
      
 let attributes = [
        NSForegroundColorAttributeName: style.placeholderColor(),
        NSFontAttributeName : UIFont.systemFontOfSize(14.0)
 ]
let atrrString = NSAttributedString(string: "准确的标题，能吸引响客们的注意".loc(), attributes:attributes)
        titleTextfield.attributedPlaceholder = atrrString
```

**Comment by ibireme** [comment]
let textField = UITextField()
    textField.frame = CGRect(x: 10, y: 100, width: 300, height: 20)
    textField.font = UIFont.systemFontOfSize(14);
    textField.placeholder = "准确的标题，能吸引响客们的注意";
    self.view.addSubview(textField)
    
    let textView = YYTextView()
    textView.frame = CGRect(x: 10, y: 120, width: 300, height: 20)
    textView.font = textField.font
    textView.placeholderText = textField.placeholder
    textView.textContainerInset = UIEdgeInsetsZero
    textView.placeholderTextColor = UIColor.init(red: 0, green: 0, blue: 25/255.0, alpha: 44/255.0)
    self.view.addSubview(textView)

这样效果就一致了：
![2016-01-12 2 13 24](https://cloud.githubusercontent.com/assets/839283/12256274/1186e00a-b937-11e5-9729-c0404596e0eb.png)

UITextField 那个颜色，应该是经过内部处理，调整了 alpha 的值，所以你直接调颜色是对不上它的显示效果的。。

**Comment by seedotlee** [comment]
嗯，是的，设置了就可以，我这里开始没有变化是因为 xcode 应用缓存造成的。。。挺坑的。。
cmd+shift+k 就可以了。。。
