### ISSUE TITLE
请教下 YY 大神，关于 YYTextView 字数统计问题？

### ISSUE THREAD

**Issue by geekdmm0xff** [ibireme/YYText#115]
如果是使用系统输入法，在输入拼音的时候，输入框中是显示拼音的，这样字数统计那里如果不做处理就会把拼音计算上去。
我在网上看到通过监听 UITextViewTextDidChangeNotification 通过判断textview高亮部分完成。但是我使用了您的 YYTextView 监听 YYTextViewTextDidChangeNotification，使用拼音输入法时不进入通知响应方法？请问该怎么解决呢

**Comment by ibireme** [comment]
先在 delegate 的 textViewDidChange: 里处理吧。。
稍后我会改一下 YYTextViewTextDidChangeNotification 的通知时机。

**Comment by geekdmm0xff** [comment]
我在 textViewDidChange:  里面试了一下输入拼音还是不能进入。
static const NSInteger kMaxValue = 140;
- (void)processLimit:(YYTextView *)textView {
    NSString *toBeString = textView.text;
    UITextRange *selectedRange = [textView markedTextRange];//获取高亮部分
    UITextPosition *position = [textView positionFromPosition:selectedRange.start offset:0];
    if (!position) { // 没有高亮选择的字，则对已输入的文字进行字数统计和限制
        if (toBeString.length > kMaxValue) {
            NSRange rangeIndex = [toBeString rangeOfComposedCharacterSequenceAtIndex:kMaxValue];
            if (rangeIndex.length == 1) {
                textView.text = [toBeString substringToIndex:kMaxValue];
            } else {
                NSRange rangeRange = [toBeString rangeOfComposedCharacterSequencesForRange:NSMakeRange(0, kMaxValue)];
                textView.text = [toBeString substringWithRange:rangeRange];
            }
        }
    }
}
请问我这样写有问题吗？这样写还是不能正确读取

**Comment by ibireme** [comment]
哦，你的需求是 “当字数大于某个值时就禁止再输入更多了”，那这样写会更好一些：


    static const NSInteger kMaxValue = 140;
    - (BOOL)textView:(YYTextView *)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString *)text {
        NSMutableString *str = textView.text.mutableCopy;
        [str replaceCharactersInRange:range withString:text];
        if (str.length > kMaxValue) {
            return NO; // too long
        }
        return YES;
    }

**Comment by geekdmm0xff** [comment]
![image](https://cloud.githubusercontent.com/assets/10804912/12235135/be4c88ca-b8ac-11e5-9578-db294711702b.jpeg)
我最开始就是这样的，可是中文拼音就统计不准确了。我其实现在一个单词都还没输入，但是它把待选的拼音也统计进去了

**Comment by ibireme** [comment]
那。。试试这样：

    static const NSInteger kMaxValue = 140;
    - (void)textViewDidChange:(YYTextView *)textView {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            NSString *toBeString = textView.text;
            UITextRange *selectedRange = [textView markedTextRange];//获取高亮部分
            UITextPosition *position = [textView positionFromPosition:selectedRange.start offset:0];
            if (!position) { // 没有高亮选择的字，则对已输入的文字进行字数统计和限制
                if (toBeString.length > kMaxValue) {
                    NSRange rangeIndex = [toBeString rangeOfComposedCharacterSequenceAtIndex:kMaxValue];
                    if (rangeIndex.length == 1) {
                        textView.text = [toBeString substringToIndex:kMaxValue];
                    } else {
                        NSRange rangeRange = [toBeString rangeOfComposedCharacterSequencesForRange:NSMakeRange(0, kMaxValue)];
                        textView.text = [toBeString substringWithRange:rangeRange];
                    }
                }
            }
        });
    }

**Comment by geekdmm0xff** [comment]
原来这样子啊，由于是异步的，再同一个调用栈里就不行了，感谢大神不厌其烦解答，感谢！
