### ISSUE TITLE
请教一个maximumNumberOfRows的问题

### ISSUE THREAD

**Issue by icoder33** [ibireme/YYText#117]
您好 尊敬的作者 我采用的是生成textLayout赋给label的方式 其中一段代码如下

    YYTextContainer *container = [YYTextContainer containerWithSize:CGSizeMake(SCREEN_WIDTH - 24, MAXFLOAT)];
    container.maximumNumberOfRows = 6;
    string.yy_lineBreakMode = NSLineBreakByCharWrapping;
    container.truncationType = YYTextTruncationTypeEnd;
    container.truncationToken = [[NSAttributedString alloc] initWithString:@"..."];
    YYTextLinePositionSimpleModifier *mod = [YYTextLinePositionSimpleModifier new];
    mod.fixedLineHeight = FONT_SIZE * LINE_HEIGHT_MULTIPLE;
    container.linePositionModifier = mod;
    YYTextLayout *textLayout = [YYTextLayout layoutWithContainer:container text:string];

个人跑起来完全没问题 但是同事一样的代码 就会崩 提示的是Modifier所处理的lines是7 而实际只有6 越界的问题 不知道这是怎么一回事

**Comment by ibireme** [comment]
这是个已知 bug，应该在一个月前修复了：https://github.com/ibireme/YYText/pull/84 试试更新代码到最新版看看～

**Comment by icoder33** [comment]
非常感谢答疑 他应该就是没update
