### ISSUE TITLE
为何YYTextView 的 YYTextAttachment 图片会遮挡文字呢？

### ISSUE THREAD

**Issue by ljlin1520** [ibireme/YYText#118]
为何YYTextView 的 YYTextAttachment 图片会遮挡文字...

UITextView 效果
![image](https://cloud.githubusercontent.com/assets/11867343/12288041/be5e27e6-ba0b-11e5-9579-240c923a8b77.png)

YYTextView 效果
![image](https://cloud.githubusercontent.com/assets/11867343/12288084/1c749a36-ba0c-11e5-9028-cab97a4d3101.png)

        var text:NSMutableAttributedString!
        if textView.attributedText == nil {
            text = NSMutableAttributedString()
        } else {
            text = NSMutableAttributedString(attributedString: textView.attributedText)
        }
        
        // Heiti SC 字体。。
        let ascent = parser.picFont.pointSize * 0.86;
        let descent = parser.picFont.pointSize * 0.14;
        let bounding = CGRectMake(0, -0.14 * parser.picFont.pointSize, parser.picFont.pointSize, parser.picFont.pointSize);
        let delegate = YYTextRunDelegate()
        delegate.ascent = ascent
        delegate.descent = descent
        delegate.width = bounding.size.width
        
        let textAttachment = YYTextAttachment()
        textAttachment.contentMode = .ScaleAspectFit
        textAttachment.contentInsets = UIEdgeInsetsMake(ascent - (bounding.size.height + bounding.origin.y), 0, -descent - bounding.origin.y, 0);
        textAttachment.content = image
        let atr = NSMutableAttributedString(string: YYTextAttachmentToken)
        atr.setTextAttachment(textAttachment, range: NSMakeRange(0, atr.length))
        let ctDelegate = delegate.CTRunDelegate()
        atr.setRunDelegate(ctDelegate, range: NSMakeRange(0, atr.length))
        text.insertAttributedString(atr, atIndex: selectedRange.location)
        text.appendAttributedString(atr)
        textView.attributedText = text

**Comment by ibireme** [comment]
你可以试试直接用这三个已经封装好的方法：https://github.com/ibireme/YYText/blob/master/YYText/Utility/NSAttributedString%2BYYText.m#L552-L673

或者仿照这几个方法来自己创建 Attachment。

**Comment by ljlin1520** [comment]
@ibireme  非常感谢你的回答。我用了你封装好的方法，并且调试模式也打开了。
使用Top | Center时，图片后面的字符串换行会被遮挡，使用Bottom 时图片前面的字符串会被遮挡。
似乎是因为图片占位只有一行的原因，如何让它的占位和它的大小一致呢？

Top
![image](https://cloud.githubusercontent.com/assets/11867343/12288874/e778f35c-ba12-11e5-97b9-b4dd743641b0.png)
 
Center
![image](https://cloud.githubusercontent.com/assets/11867343/12288977/afaca724-ba13-11e5-8bb8-4b451dd8e8d3.png)


Bottom
![image](https://cloud.githubusercontent.com/assets/11867343/12288952/739fb2da-ba13-11e5-830b-8eaf090a6c98.png)


        text.appendAttributedString(NSAttributedString.attachmentStringWithContent(image, contentMode: .Center, attachmentSize: image.size, alignToFont: parser.defualtFont, alignment: .Center))
        textView.attributedText = text

**Comment by ibireme** [comment]
这。。是不是设置了什么 linePositionModifier 之类的东西，把行文本行固定了？

**Comment by ljlin1520** [comment]
找到原因了，YQTextLinePositionModifier 限制了行高。
非常感谢你回答。

**Comment by ljlin1520** [comment]
但有个新问题，换了一行的时候，空白了一大段。
![image](https://cloud.githubusercontent.com/assets/11867343/12292882/f84d93be-ba2a-11e5-9f74-4ae865fe12f1.png)

**Comment by ibireme** [comment]
这个。。这是怎么用的啊。。能贴一下具体的使用代码吗？

**Comment by ljlin1520** [comment]
textView = YYTextView()
        textView.textContainerInset = UIEdgeInsetsMake(12, 16, 12, 16)
        textView.contentInset = UIEdgeInsetsMake(0, 0, YQComposeToolbar.toolBarHeight, 0)
        textView.extraAccessoryViewHeight = YQComposeToolbar.toolBarHeight
        textView.showsVerticalScrollIndicator = false
        textView.alwaysBounceVertical = true
        textView.allowsCopyAttributedString = false
        textView.textParser = parser
        textView.delegate = self
        textView.inputAccessoryView = UIView()

        textView.placeholderText = "写点什么吧..."
        textView.placeholderTextColor = UIColor.lightGrayColor()
        textView.placeholderFont = UIFont.systemFontOfSize(14)

        
        var text:NSMutableAttributedString!
        if textView.attributedText == nil {
            text = NSMutableAttributedString()
        } else {
            text = NSMutableAttributedString(attributedString: textView.attributedText)
        }
     let image = UIImage(named:"")
      image = image.resizedImageByWidth(UInt(self.width-32))
        let attachmentString = NSAttributedString.attachmentStringWithContent(image, contentMode: .Center, attachmentSize: image.size, alignToFont: parser.defualtFont, alignment: .Center)
        text.insertAttributedString(attachmentString, atIndex: selectedRange.location)
        text.insertAttributedString(NSAttributedString(string: "\n"), atIndex: selectedRange.location + attachmentString.length)
        selectedRange.location = selectedRange.location + attachmentString.length + 1
        textView.attributedText = text

**Comment by ibireme** [comment]
暂时没看出什么问题。。猜测有下面几种可能：

1. attachment 里会用 RunDelegate 来重新设置文字的 ascent、descent，这个可能会被错误的扩散到别的字符上。这可以在设置 attributedText、并经过 parser 解析后，打印下实际显示的 attributedText 来看看是否有错误。

2. 看看是否有修改 font、line space 等属性，这个也可以按上面这样打印来看看。

3. attachment 宽度应该小于文本控件的宽度，不然在某些情况下会导致 CoreText 排版结果有问题。

**Comment by ljlin1520** [comment]
@ibireme  谢谢了，是我在TextParser 设置了字体的原因。
