### ISSUE TITLE
如何优雅的添加多个textparse

### ISSUE THREAD

**Issue by seedotlee** [ibireme/YYText#12]
目前好像只能拥有一个textparse
这样的话就需要将许多不同的解析内容全部写到一起，比如：一个textview需要解析自定义emoji也需要解析`@xxx`
能不能自己写了一个`@xxx`解析然和与原来的YYTextSimpleEmoticonParser进行合并使用呢？

**Comment by ibireme** [comment]
YYTextParser 只是一个协议，你可以自己实现一个类来封装多个 sub parser，类似这样：

    @interface YYTextParserGroup : NSObject<YYTextParser>
    @property NSArray *parsers;
    @end

    @implementation YYTextParserGroup
    - (BOOL)parseText:(NSMutableAttributedString *)text selectedRange:(NSRangePointer)selectedRange {
        BOOL changed = NO;
        for (id<YYTextParser>parser in _parsers) {
            if ([parser parseText:text selectedRange:selectedRange]) {
                changed = YES;
            }
        }
        return changed;
    }
    @end

**Comment by xueliangwd** [comment]
YYLabel在tableviewCell设置textparser，cell复用后，纯文字也会被设置为带格式显示，是不是我用的不对。自定义parser如下：
@implementation YYTextRichParser

-(BOOL)parseText:(NSMutableAttributedString *)text selectedRange:(NSRangePointer)selectedRange{
    if (!_detector||!text.string.length) {
        return NO;
    }
    
    NSArray *matches = [_detector matchesInString:text.string options:NSMatchingReportProgress range:NSMakeRange(0, text.string.length)];
    if(!matches.count) return NO;
    for (NSUInteger i = 0, max = matches.count; i < max; i++) {
        NSTextCheckingResult *one = matches[i];
        NSRange oneRange = one.range;
        if (oneRange.length == 0) continue;
        
        [text yy_setUnderlineStyle:NSUnderlineStyleSingle range:oneRange];
        [text yy_setTextHighlightRange:oneRange
                                color:TextHighlightColor
                      backgroundColor:TextBackgroundColor
                            tapAction:^(UIView *containerView, NSAttributedString *text, NSRange range, CGRect rect){
                                NSLog(@"高亮区点击事件 ");
                                //高亮区点击事件 注意 i 顺序和GMTextLabelLinkType 对应
                                
                            }];
    }
    return YES;

}
