### ISSUE TITLE
YYLabel 设置lineBreakMode

### ISSUE THREAD

**Issue by jcxc** [ibireme/YYText#120]
设置后 感觉没有UILabel的效果，比如说设置成NSLineBreakByTruncatingTail类型时，abc....这样。

求解

**Comment by ibireme** [comment]
<img width="551" alt="2016-01-13 6 26 51" src="https://cloud.githubusercontent.com/assets/839283/12291613/47f443ca-ba23-11e5-8ff6-fdb635ea4dce.png">
<img width="272" alt="2016-01-13 6 27 03" src="https://cloud.githubusercontent.com/assets/839283/12291614/4a5e0ab0-ba23-11e5-8818-8a3463018751.png">

没问题啊？

**Comment by jcxc** [comment]
![Uploading 73167FD1-B9AE-48D9-A6B3-B3A212226BFB.png…]()
![Uploading 73167FD1-B9AE-48D9-A6B3-B3A212226BFB.png…]()

我是在textlayout里设置这个linebreak，最大行数为3，结果没一行都有 ......， 求解答

**Comment by jcxc** [comment]
NSMutableAttributedString *contentText = [[NSMutableAttributedString alloc] initWithString:model.postContent];
    contentText.font = k14Font;
    contentText.kern = @(2.5);
    contentText.color = [HXColor colorWithHexString:@"#5a5a5a"];
    contentText.lineBreakMode = NSLineBreakByTruncatingTail;
    YYTextContainer *contentContain = [YYTextContainer containerWithSize:CGSizeMake(UIScreenWidth-kLeftToEdgeGap*2, MAXFLOAT)];
    contentContain.maximumNumberOfRows = 3;
    _contentLayout = [YYTextLayout layoutWithContainer:contentContain text:contentText];


我在textlayout里设置的这个属性，结果没一行都有 ..... , 求解答

**Comment by jcxc** [comment]
每一行

**Comment by ibireme** [comment]
这是用 TextLayout 来设置属性的啊，那可能麻烦些，参考下 `[YYLabel setLineBreakMode]` 的方法：

    switch (lineBreakMode) {
        case NSLineBreakByWordWrapping:
        case NSLineBreakByCharWrapping:
        case NSLineBreakByClipping: {
            _innerContainer.truncationType = YYTextTruncationTypeNone;
            _innerText.yy_lineBreakMode = lineBreakMode;
        } break;
        case NSLineBreakByTruncatingHead:{
            _innerContainer.truncationType = YYTextTruncationTypeStart;
            _innerText.yy_lineBreakMode = NSLineBreakByWordWrapping;
        } break;
        case NSLineBreakByTruncatingTail:{
            _innerContainer.truncationType = YYTextTruncationTypeEnd;
            _innerText.yy_lineBreakMode = NSLineBreakByWordWrapping;
        } break;
        case NSLineBreakByTruncatingMiddle: {
            _innerContainer.truncationType = YYTextTruncationTypeMiddle;
            _innerText.yy_lineBreakMode = NSLineBreakByWordWrapping;
        } break;
        default: break;
    }

container 的 truncationType 设置为 YYTextTruncationTypeEnd，
text 的 lineBreakMode 设置为 NSLineBreakByWordWrapping 或 NSLineBreakByCharWrapping。

（另外，那个每行都有点点点是 CoreText 的排版结果，CoreText 会把文本按换行符分割，然后对每一行进行裁剪）

**Comment by jcxc** [comment]
哇o，棒棒哒，有时间得好好看看源码，谢谢～

**Comment by mountainpig** [comment]
YYLabel *label = [YYLabel new];
    label.size = CGSizeMake(260, 260);
    label.lineBreakMode = NSLineBreakByTruncatingTail;
    label.center = self.view.center;
    label.text = @"@孟门嘛 @123456789012345678901234";
    [self.view addSubview:label];
这个就有问题
