### ISSUE TITLE
关于yyTextView 和yyLabel 转换问题

### ISSUE THREAD

**Issue by DeepMissea** [ibireme/YYText#124]
首先谢谢你制作了这么优秀的库。

第一个问题是，我需要用textView 让用户输入，然后展示，看了很多issue，你都建议使用yylabel做展示，但是我把textView的layout复制给label，发现排版不对，显示不出来图片。请问他们两个的图文混排布局计算方式是一样的么？
还有一个问题是，怎么获取textView中的图片和表情呢？
最后一个问题是，我需要把数据传到后台，这样就只能拆分，然后读取的时候，我再手动转成attributeString，请问有什么其他的好的方式么？

**Comment by ibireme** [comment]
1. 排版最终都是 YYTextLayout 来渲染的。如果从 YYTextView 取出 textLayout，再赋值给 YYLabel，那应该是一样的，但是这需要 YYLabel  的 frame 和 TextView 的文本 frame 保持一致。 图片的话，如果是 UIImage，那应该是直接绘制出来的，但如果是 UIImageView 之类的视图，那就只能显示一份了。
2. 可以获取 attribuedText，然后用 enumerateAttribute 之类的方法遍历属性（YYTextAttachmentAttributeName），然后取出 YYTextAttachment。
3. 这可能需要你自己定义一个格式了。

**Comment by DeepMissea** [comment]
Thanks a lot.
