### ISSUE TITLE
iOS 7.0系统 YYLabel 画删除线必Crash

### ISSUE THREAD

**Issue by jxaufang168** [ibireme/YYText#126]
iOS 7.0系统 YYLabel 画删除线必Crash
YYLabel
NSAttributedString+YYText
- (void)yy_setTextStrikethrough:(YYTextDecoration *)textStrikethrough range:(NSRange)range;

**Comment by ibireme** [comment]
能提供一些更详细的信息吗？比如崩溃log，或者崩溃时的代码行？

**Comment by jxaufang168** [comment]
7.1.2 (11D257) （iphone 5s）

YYTextContainerView
- (void)drawRect:(CGRect)rect {
...
102行    [_layout drawInContext:UIGraphicsGetCurrentContext() size:self.bounds.size point:point view:self layer:self.layer debug:_debugOption cancel:nil];
}

YYTextLayout
- (void)drawInContext:(CGContextRef)context
                 size:(CGSize)size
                point:(CGPoint)point
                 view:(UIView *)view
                layer:(CALayer *)layer
                debug:(YYTextDebugOption *)debug
                cancel:(BOOL (^)(void))cancel{
...
 if (self.needDrawUnderline && context) {
            if (cancel && cancel()) return;
 3261行      YYTextDrawDecoration(self, context, size, point, YYTextDecorationTypeUnderline, cancel);
        }
}

YYTextLayout
static void YYTextDrawLineStyle(CGContextRef context, CGFloat length, CGFloat lineWidth, YYTextLineStyle style, CGPoint position, CGColorRef color, BOOL isVertical) {
...
 if (styleBase == YYTextLineStyleSingle) {
                CGContextMoveToPoint(context, x1, y);
                CGContextAddLineToPoint(context, x2, y);
        2945行  CGContextStrokePath(context);
            } 
}

7.1.2 (11D257)  (iphone 4s)

不会crash，但是删除线显示不出来

![Uploading 1.png…]()

**Comment by jxaufang168** [comment]
不小心点到close了。。。

**Comment by ibireme** [comment]
稍后我找台老机子测一下。。

**Comment by ibireme** [comment]
这是 CoreText 的 Bug！！

我找了台 iOS7 的真机，测试时发现这样的问题：CoreText 排版后的 CTRunRef 里面取出来的属性，本应该是 CGColor 的属性，有部分被 CoreText 转换成了 UIColor。这个问题在其他版本的系统中都不会出现。。

我提了一个 workaround：https://github.com/ibireme/YYText/commit/c4002c2699f25d88ed9fd07c8b06d7c1520b62ec
