### ISSUE TITLE
设置verticalForm=YES以后，RubyAnnotation无法显示

### ISSUE THREAD

**Issue by realcarlos** [ibireme/YYText#127]
是什么原因呢？

**Comment by ibireme** [comment]
目前竖排版不支持 RubyAnnotation。

RubyAnnotation 是要用 CTFrame、CTLine 或者 CTRun 来绘制的，但是竖排版下目前是用 CGGlyph 绘制每个字形，RubyAnnotation 就绘制不出来了。

目前 RubyAnnotation 是直接用 CoreText 实现的，如果要竖排版也支持 RubyAnnotation 的话，那就得避开 CoreText 的实现，自己计算和绘制，相当麻烦。。
