### ISSUE TITLE
Asynchronous layout

### ISSUE THREAD

**Issue by menhui222** [ibireme/YYText#128]

**Comment by menhui222** [comment]
let  a1 = NSMutableAttributedString()
                    let titleLabel = UILabel(frame: CGRectMake(0, 0, kScreenWidth, 40))
                    titleLabel.text = "解析区"
                    titleLabel.textColor = UIColor.grayColor()
                    let titleAttributeString = NSMutableAttributedString.yy_attachmentStringWithContent(titleLabel, contentMode: .Center, attachmentSize: titleLabel.size, alignToFont: AttachMentFontSize, alignment: .Center)
                    a1.appendAttributedString(titleAttributeString)
                    //answer
                    
                    for an in question.paperQuestion.Q.answer{
                        a1.appendAttributedString(wk_attributeString(an,imageFinder: question.contentImageFinder()))
                        a1.appendAttributedString(NSAttributedString(string:"\n"))
                        
                    }
                    
                    //analyze
                    a1.appendAttributedString(wk_attributeString(question.paperQuestion.Q.analyze,imageFinder: question.contentImageFinder()))
                    //video
                    if question.paperQuestion.Q.video != "" {
                        let videoBtn = UIButton()
                        videoBtn.addTapGesture(tapNumber: 1, action: { (tapGestureRecognizer) -> () in
                            let view = UIApplication.sharedApplication().keyWindow
                            view?.currentViewController()
                            let filePath = question.paperQuestion.Q.video
                            let playerController = MPMoviePlayerViewController(contentURL:NSURL(string: filePath))
                            view?.currentViewController()!.presentViewController(playerController, animated: true, completion: nil)
                        })
                        
                        videoBtn.frame = CGRectMake(0,0,50,50)
                        let headAttributeString = NSMutableAttributedString.yy_attachmentStringWithContent(videoBtn, contentMode: .Center, attachmentSize: videoBtn.size, alignToFont: AttachMentFontSize, alignment: .Center)
                        a1.appendAttributedString(headAttributeString)
                    }
                    
                    yy_answerLabel.attributedText = a1
                    yy_answerLabel.numberOfLines = 0
                    let size = CGSizeMake(CellWidth,10000)
                    let layout = YYTextLayout(containerSize: size, text:a1)
                    
                    
                    dispatch_async(dispatch_get_main_queue(), { () -> Void in
                        yy_answerLabel.frame = CGRectMake(20, 5, layout.textBoundingSize.width, layout.textBoundingSize.height)
                        yy_answerLabel.textLayout = layout
                        question.yy_answerLabel = yy_answerLabel
                       self.tableView()?.reloadData()
                    })

**Comment by menhui222** [comment]
我在 里面加了2个控件 为什么 2个控件出来比较慢  是不是在异步的问题 控件是不是在在分线程上进行 加载了？

**Comment by ibireme** [comment]
默认 UILabel、YYLabel 都是同步显示的，渲染逻辑都是在主线程的。如果有卡顿，那可能需要用 Instruments 检测一下哪些方法占用了 CPU 资源。

**Comment by menhui222** [comment]
YYLabel  出来挺快的 就我上面加的2个控件出来慢    而且图文混编那部分都出现了   2个控件没出来 我以为 分线程是不能刷新ui的 我以为是分线程appendAttributedString的原因

**Comment by ibireme** [comment]
上面这段代码是在 background queue 执行的？那可能有些问题。
注意一下，所有 UIKit 控件，包括 UIButton、CALayer 等东西，都只能在主线程设置和执行。如果代码没问题，但还是有卡顿，那真得拿 Instruments 检查下了。
