### ISSUE TITLE
关于YYLabel的行高和自动换行问题

### ISSUE THREAD

**Issue by VVJason** [ibireme/YYText#129]
这是Demo里面的案例，为什么第一行好像还是可以继续显示一个或者多个字符的，但是却换行了，如果是YYLabel怎么计算内容的高度啊，系统的sizeWithAttributes算的是正常的label内容范围，，，方便解答一下吗。。

![8e7eac28f1753c8e4ca938b90a4981f2](https://cloud.githubusercontent.com/assets/14148888/12381762/78a0b566-bdcb-11e5-8619-633f5bf09dd4.png)
![4a8667112edf790502006d99935ec162](https://cloud.githubusercontent.com/assets/14148888/12381770/a0dc57ce-bdcb-11e5-9e88-485a5b7472dd.png)

**Comment by ibireme** [comment]
这个不太清楚。。换行是由 CoreText 负责的，YYLabel 应该没有做什么处理。你可以试试调整一下 lineBreakMode、kern 之类的属性看看。

文本宽高计算可以看一下 readme 里的介绍：https://github.com/ibireme/YYText#文本布局计算
