### ISSUE TITLE
[!] Unable to find a specification for `YYText`

### ISSUE THREAD

**Issue by Rick630** [ibireme/YYText#13]
YYKit能搜到，为什么呢？

cocoapods version: 0.39.0

**Comment by LiuSky** [comment]
pod setup

**Comment by Rick630** [comment]
@LiuSky 无效

**Comment by ibireme** [comment]
$ pod search YYText
	
	-> YYText (0.9.4)
	   Powerful text framework for iOS to display and edit rich text.
	   pod 'YYText', '~> 0.9.4'
	   - Homepage: https://github.com/ibireme/YYText
	   - Source:   https://github.com/ibireme/YYText.git
	   - Versions: 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0 [master repo]

看一下你的 pod 配置

**Comment by Rick630** [comment]
@ibireme 能搜到了，谢谢回复

**Comment by wudabei** [comment]
我也不行？ pod search YYText  显示  [!] Unable to find a pod with name matching `YYText'

**Comment by ibireme** [comment]
更新一下 pod 列表：

    pod update --verbose

**Comment by wudabei** [comment]
pod repo remove master  
pod setup 后再pod install 就可以了。
