### ISSUE TITLE
[YYLabel] Tap and long press action on none-highlight part of the label?

### ISSUE THREAD

**Issue by skyline75489** [ibireme/YYText#130]
I need YYLabel to respond to tap and long press action on the **none**-highlight part of the label, like what WeChat did(long press comment to show delete menu).

I've implemented it in [my fork](https://github.com/skyline75489/YYText).

**Comment by ibireme** [comment]
You may add UIGestureRecognizer on label to receive touch event.

**Comment by skyline75489** [comment]
I was worried that adding `UIGestureRecognizer` might causing conflicts with YYLabel's internal touch handling code.

**Comment by ibireme** [comment]
You may set `gesture.cancelsTouchesInView = NO` to avoid the conflicts.

**Comment by skyline75489** [comment]
Yeah...things are a little more complicated here. Setting `gesture.cancelsTouchesInView = NO` allows touches to move to YYLabel, however, it does not prevent the gesture recognizer itself from responding.

For example, let's say I add both `highlightAction` and `UITapGestureRecognizer` and set `gesture.cancelsTouchesInView = NO`. When I tap the highlight part, not only the highlightAction is triggered, the gesture handler is also triggered.

**Comment by ibireme** [comment]
Can you provide some code to reproduce the problem?

**Comment by skyline75489** [comment]
As I said before, suppose we need a Wechat-like comment:

```objecitive-c
- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = [UIColor whiteColor];
    YYLabel *label = [[YYLabel alloc] initWithFrame:CGRectMake(100, 100, 200, 20)];

    NSMutableAttributedString *attrText = [[NSMutableAttributedString alloc] initWithString:@"小明回复了小红：你好"];

    [attrText yy_setTextHighlightRange:NSMakeRange(0, 2) color:[UIColor grayColor] backgroundColor:[UIColor whiteColor] tapAction:^(UIView *containerView, NSAttributedString *text, NSRange range, CGRect rect) {
        NSLog(@"Tapped 小明");
    }];

    [attrText yy_setTextHighlightRange:NSMakeRange(5, 2) color:[UIColor grayColor] backgroundColor:[UIColor whiteColor] tapAction:^(UIView *containerView, NSAttributedString *text, NSRange range, CGRect rect) {
        NSLog(@"Tapped 小红");
    }];

    [label setAttributedText:attrText];
    [self.view addSubview:label];
}
```

Now everything works. However, if we need to handle tap on the none-highlight part of the label, as you said, we can use UITapGestureRecognizer:

```objective-c
UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(handleTap:)];

[label addGestureRecognizer:tap];
```

And handle it:

```objective-c
- (void)handleTap:(UIGestureRecognizer *)tap {
    NSLog(@"Tapped Label");
}
```

This will prevent the original highlight part from responding. All the output will be:

     Tapped Label


If we added this:

```objective-c
 tap.cancelsTouchesInView = NO;
```

A single tap on highlight part will trigger *two* handler:

```objective-c
Tapped 小红
Tapped Label
```

**Comment by ibireme** [comment]
I understand. I will try to add more callback later.

**Comment by skyline75489** [comment]
I've tried to implement this in my [fork](https://github.com/skyline75489/YYText) but it may not be ideal since I've only read a small part of the source. 

Besides, [TTTAttributedLabel](https://github.com/TTTAttributedLabel/TTTAttributedLabel) also has the same problems. I feel that this might be a common issue for most text layout solutions. It would be really nice if YYText solves this.

**Comment by ibireme** [comment]
Added: https://github.com/ibireme/YYText/commit/947db8fa1eb1ffe92e538bfca76e3aca93401cb3
