### ISSUE TITLE
YYLabel中的文本能不能设置对齐方式啊

### ISSUE THREAD

**Issue by loumzy** [ibireme/YYText#131]
### YYLabel中的文本能不能设置对齐方式啊

First  | Second
------------ | -------------
left 1 |                     right 1
left 2 | right2 right2 right2

如上四块文本属于同一个YYLabel中，能不能让right 1 右对齐

**Comment by ibireme** [comment]
都拆开，每块儿都用一个 Label 显示，然后再调解每个 Label 的文本对齐。

**Comment by loumzy** [comment]
谢谢，底层绘制由coretext去处理的，不容易去设置绘制字体的位置是吧

**Comment by ibireme** [comment]
配合 CoreText 也能实现每段文本的偏移，但这需要调用者额外来写逻辑了。上面这种表格的需求在这里几乎无法封装到 Label 这种控件内。。
