### ISSUE TITLE
居中对齐

### ISSUE THREAD

**Issue by CXRoronoa** [ibireme/YYText#133]
.textAlignment = NSTextAlignmentCenter;不起作用 效果还是居左 
[[YYLabel alloc] init]替换成[[UILabel alloc] init]就可以居中了

**Comment by ibireme** [comment]
如果是用 AttributedString 来显示的话，也设置一下这个值吧：

    text.yy_alignment = NSTextAlignmentCenter;
    label.textAlignment = NSTextAlignmentCenter;

**Comment by CXRoronoa** [comment]
解决了 谢谢

**Comment by Jacky-LinPeng** [comment]
图文的时候  文本不能垂直居中呀

**Comment by CYBoys** [comment]
垂直居中不能这样做。
