### ISSUE TITLE
YYText的markdown解析问题

### ISSUE THREAD

**Issue by misaka14** [ibireme/YYText#134]
你好。
请问YYText的`markdown`解析，会保留 `###`、`-------------`标记，是不是没有开关可以取消掉？

**Comment by ibireme** [comment]
没有。。
这个 markdown 解析，只是很简单的加上了一些文本高亮和效果，性能和功能都很弱。

如果想要一个足够强大的 markdown 解析，推荐试试这些项目：
 https://github.com/NimbusKit/markdown
 https://github.com/dreamwieber/AttributedMarkdown
 https://github.com/indragiek/CocoaMarkdown
 
或者用 lex/yacc 之类的自己生成 parser。
