### ISSUE TITLE
请教YY大神一个问题

### ISSUE THREAD

**Issue by lexiaoyao20** [ibireme/YYText#135]
想向大神请教下UITextView的一个问题，Google没找到答案，只好跑过来想你请教了。。

我有类似下面的四行文字：
1轻仓操作，顺势而为！
2亏损不是亏在技术上，而是亏在心态上！
3研究市场情绪和人心的部分要高于研究数据和模型！
4身体状态不佳，头脑不清醒，情绪不稳定时，远离盘面，做单就会亏损，凡人都有情绪效应！

我的目标是只显示两行，多余的文字在末尾显示 ...
代码如下：
```
    self.textView.textContainer.maximumNumberOfLines = 2;
    self.textView.textContainer.lineBreakMode = NSLineBreakByTruncatingTail;
```  
但是第2行末尾没有显示... ，想问下这是换行符引起的还是苹果的BUG？ 有没有解决方案？

**Comment by ibireme** [comment]
不知道是什么问题，但这更适合用 UILabel 显示～

**Comment by lexiaoyao20** [comment]
谢谢大神回答。
我的情况比较特殊，还需要用到*exclusionPaths*，用来实现 展开/收起功能，所以只能用UITextView

**Comment by csc-EricWu** [comment]
@lexiaoyao20 大神如何实现展开/收起功能？上个demo 看看？
