### ISSUE TITLE
YYLabel是不是不支持UIimage网络图片加载

### ISSUE THREAD

**Issue by xiaowoniu2012** [ibireme/YYText#136]
YYLabel 是不是不支持UIimage网络图片加载

**Comment by lexiaoyao20** [comment]
支持的，你可以参考YYKit 里面 新浪微博 的那个Demo

**Comment by ibireme** [comment]
可以用 UIImageView 创建 Attachment，然后用各种 WebImage 库来加载网络图片。

除此以外，也可以参考这里：https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/WBStatusLayout.m#L70-L93
