### ISSUE TITLE
YYLabel没法与UILabel一样，在多行模式下文本顶到最上？

### ISSUE THREAD

**Issue by Ryan-Lee** [ibireme/YYText#137]
我在做YYLabel的高度自适应时，总是遇到YYLabel的内容与上下边缘有边距，而且随着attributedText.length越来越大上下边距也越来越大，这导致我在UI布局时跟设计图总是有出入，没法完整的对齐周围的控件，但是当我把控件换成UILabel时，就没有这个问题了。PS：我是用- (CGRect)boundingRectWithSize:(CGSize)size options:(NSStringDrawingOptions)options context:(NSStringDrawingContext *)context；来做高度计算的。
下面是控件为YYLabel的代码
![image](https://cloud.githubusercontent.com/assets/4626985/12479910/4b92f4b6-c079-11e5-8ba9-1593bebe4e33.png)
下面是效果图
![image](https://cloud.githubusercontent.com/assets/4626985/12479931/7b8a164a-c079-11e5-994a-5a0d188b156b.png)

当我上面截图的代码中YYLabel改成UILabel后的效果图如下
![image](https://cloud.githubusercontent.com/assets/4626985/12480028/492a0b5a-c07a-11e5-8ab3-bb1ea349ea11.png)

注意上下边缘是没有边距的，由于这串字符串不是很大，所以两个效果图的差异不是非常明显，但是如果字符串很长的是非常明显，我现在想要YYLabel的文本跟UILabel的文本一样，顶到最上面，有什么办法做到吗？还有这个差异到底是什么原因来的？

**Comment by ibireme** [comment]
UIKit 和 CoreText 的接口是两套东西，不能混用。YYText 是基于 CoreText 的，这里应该用 YYText 封装的文本宽高计算方法：https://github.com/ibireme/YYText#文本布局计算 。

之所以这里有差异，是因为 UILabel 在排版时，会对行间距等排版结果进行微调，导致计算结果和 YYLabel 对不上。
