### ISSUE TITLE
如何提前计算附带 Attachements 的文本高度呢？

### ISSUE THREAD

**Issue by hilen** [ibireme/YYText#139]
Hi，YY 你好：
        请问，如 Demo 中的图片，dribble 和汽车机器人的富文本显示，使用 YYText 如何在绘制之前提前计算好高度呢？

![image](https://cloud.githubusercontent.com/assets/2245840/12501899/b83a19bc-c0fd-11e5-911f-08c5f8dcfce1.png)

**Comment by ibireme** [comment]
YYTextAttachment 本身是有 size 之类的属性的，设置好这些就行了。
文本整体宽高的计算可以看这里：https://github.com/ibireme/YYText#文本布局计算

**Comment by hilen** [comment]
这个看到了，如果不设置文字行距，ascent 和 descent 等参数，文本显示和 UILabel 确不一样。
我看微博 demo 中的 `WBStatusLayout.m` 里对这些字段有说明。
那这些参数针对不同字体有默认的值吗？

![image](https://cloud.githubusercontent.com/assets/2245840/12503296/0a4349ee-c10e-11e5-8178-80d0e7edd570.png)

**Comment by ibireme** [comment]
UILabel 底层用的是 TextKit，TextKit 底层是 CoreText，它对输出结果有微调。
YYLabel 底层用的是 CoreText，排版结果用的是 CoreText 默认输出，至于如何微调是调用者来实现的，并没有默认参数。

**Comment by hilen** [comment]
好的，了解了。
多谢 100:

**Comment by hilen** [comment]
遇见一个问题，使用 `YYTextContainer` 的 `linePositionModifier` 对象后， 设置了字体的 paddingTop, paddingBottom, font 后，纯文字高度计算没有问题。 但是如果附带了 大图片后就不对了， 拿到计算的高度 `textBoundingSize` 设置 YYLabel 的 size 或者使用 YYLabel 的 `sizeToFit`方法后都是图下这种效果， 哪里使用不当吗？

![image](https://cloud.githubusercontent.com/assets/2245840/12504842/673145a8-c11c-11e5-987b-0cfd35174472.png)

**Comment by ibireme** [comment]
图片的 size 大于行高，那么如果要正确显示图片，那一行文本肯定也要有更大的行高啊，那就不能写死行高了啊。。上面这段代码，已经能访问每一个 line.position 了，如何修改需要看你的需求了。

另外， YYTextLinePositionModifier  这个，不应该只用在计算文本高度上，也要设置到 label 上才能起作用。

**Comment by hilen** [comment]
哦，是需要对 `YYTextLine` 的 attachment 进行处理啊。 我还是把表情的 size 用文字的 size 好了。 感谢回答 :+1:
