### ISSUE TITLE
Swift: include of non-modular header inside framework module"YYText.YYText"

### ISSUE THREAD

**Issue by hilen** [ibireme/YYText#140]
在使用CocoaPods 加载 YYText 报这个错 `include of non-modular header inside framework module"YYText.YYText"`，截图如下
![image](https://cloud.githubusercontent.com/assets/2245840/12551110/1d6878ea-c3a3-11e5-97b1-15100266050a.png)

工程是 Swift ，Bridging-Header.h 是这么引入的
```
#import <YYImage/YYImage.h>
#import <YYText/YYText.h>
``` 

podfile:
```
platform:ios,'8.0'
use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target 'demo' do
    pod 'YYImage'
    pod 'YYText'
end
```

我还引入了一些其他的库，不知道是不是冲突问题。这是 CocoaPods 的问题么？

**Comment by ibireme** [comment]
我觉得，要不然就是有冲突，要不然就是缓存问题。。。

**Comment by hilen** [comment]
`Pods 文件夹，derived data, cocoapods cache` 几乎都清理了，好像还是不行

详细 podfile：
```
source 'https://github.com/CocoaPods/Specs.git'

platform:ios,'8.0'
use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target 'demo' do
    #Swift
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Kingfisher'
    pod 'KeychainAccess', '~> 2.3.1'
    pod 'UIColor_Hex_Swift', '~> 1.5'
    pod 'Timepiece'
    pod 'ReachabilitySwift'
    pod 'RxSwift', '~> 2.0.0-beta'
    pod 'RxCocoa', '~> 2.0.0-beta'
    pod 'RxBlocking', '~> 2.0.0-beta'
    pod 'Dollar'
    pod 'Cent'
    pod 'ObjectMapper', '~> 1.0'
    pod 'XCGLogger'
    pod 'Swift_cURLCommand'
    pod 'SnapKit'
    pod 'BSImagePicker', '~> 2.1'

    #Objective-C
    pod 'FLEX', '~> 2.0'
    pod 'SVPullToRefresh', :git => 'https://github.com/hilen/SVPullToRefresh.git', :commit => '5a753b4d3d817c512a5c7f54822029361df72b0f'
    pod 'SocketRocket'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ActionSheetPicker-3.0'
    pod 'TPKeyboardAvoiding'
    pod 'YYImage'
    pod 'YYText'
end
```
这些库哪个能冲突呢？

**Comment by ibireme** [comment]
看样子没冲突。。
我搜索了一下相关错误，看样子像是旧版 CocoaPods 的问题：https://github.com/CocoaPods/CocoaPods/issues/4420

明天我再仔细看一下。

**Comment by hilen** [comment]
我觉得可能也是 CocoaPods 的问题，因为在用RxSwift 的时候也出现过类似的问题…😂

**Comment by ibireme** [comment]
试试用 `gem update cocoapod` 更新一下 CocoaPods 吧。

**Comment by hilen** [comment]
@ibireme 依然不可以，我是不是得把 CocoaPods 卸载重新安装啊？😂

**Comment by ibireme** [comment]
那。。参考 CocoaPods 那个 Issues 里面的，这样引入呢：

#if __has_include(<RealmMapView/RealmMapView-BridgingHeader.h>)
@import RBQFetchedResultsController;
#else
#import <RBQFetchedResultsController/RBQFetchRequest.h>
#endif

**Comment by hilen** [comment]
这个也试过...不知道引入姿势是不是错误的，还是无法编译。
![image](https://cloud.githubusercontent.com/assets/2245840/12572038/142bd7de-c422-11e5-88ff-ba7dfd21084e.png)

**Comment by ibireme** [comment]
我自己也测试了下，`#import <YYText/YYText.h>` 是没问题的。。其他的我也不清楚了。。

试一下 `pod --version` 看看当前指定的是哪个 CocoaPods 版本吧。

**Comment by hilen** [comment]
我之前在电脑上安装过一个 CocoaPods 的官方 App，我不知道会不会和这个有关系。我卸载重新安装 CocoaPods  试试吧。

**Comment by hilen** [comment]
我把 cocoaPods App  删除了，terminal 版本重新安装了一遍。 现在的 `pod --version` 是 0.39.0  ，依然不可以。T.T

**Comment by ibireme** [comment]
╮(￣▽￣")╭ (摊手)

**Comment by hilen** [comment]
(T＿T)/~~ （伤心）

**Comment by hilen** [comment]
我大概发现问题出在哪里了，我的工程内使用了多个  Configuration, 不同的 Configuration 对应不同的 Scheme，在 `Other Swift Flags` 里我添加了`-D Debug`等参数来区分 Scheme，然后又在 Edit Scheme 里的把这些配置都改了。下图所示：
![image](https://cloud.githubusercontent.com/assets/2245840/12577317/909722e2-c454-11e5-8e4f-7aed8ce8d021.png)

之后我就选择了这个修改后的 Scheme 进行 Build，然后就会报错。 但是如果我选择默认的 Scheme 进行 Build 就没有问题。 (T＿T)/~~

**Comment by hilen** [comment]
@ibireme 我好像有点线索了，会不会跟我在 Build Settings -> Header Search Paths 添加了 ${SRCROOT} 有关系呢？
![image](https://cloud.githubusercontent.com/assets/2245840/12638051/06ad17c6-c5d5-11e5-96bd-8e0893142c67.png)

**Comment by ibireme** [comment]
这一行，会让头文件搜索路径扩展到项目中的每个子目录中去，很容易引起头文件搜索冲突。

**Comment by hilen** [comment]
😂 是啊，所以各种头文件冲突。去掉就好了
