### ISSUE TITLE
List support?

### ISSUE THREAD

**Issue by frankai** [ibireme/YYText#141]
Hello!

Any chance to support ordered and unordered lists?

Thanks!

**Comment by ibireme** [comment]
You mean markdown? The markdown parser is simple, slow and weak, it can only add some highlight color on text.

You may parse the text yourself, and add some attachment to display ordered and unordered lists.

**Comment by frankai** [comment]
I mean like the usual list and tables found in text editors like TextEdit. Any clue? I suppose that NSAttributedString has tables and list support but the code to view/edit/modify them in YYText is not there...

**Comment by ibireme** [comment]
It only supports the attributes listed in readme: https://github.com/ibireme/YYText#text-attributes 
Unfortunately, NSAttributedString (or CoreText) does not support table or list layout.
