### ISSUE TITLE
[YYTextLayout] Potentially wrong result due to direct float comparison

### ISSUE THREAD

**Issue by skyline75489** [ibireme/YYText#142]
https://github.com/ibireme/YYText/blob/master/YYText%2FComponent%2FYYTextLayout.m#L388

This comparison could potentially produce wrong result:

```objective-c
if (8.3 <= systemVersionFloat && systemVersionFloat < 9) {
    needFixJoinedEmojiBug = YES;
}
```

**Comment by ibireme** [comment]
What does "wrong result" mean?

**Comment by skyline75489** [comment]
The float value of `systemVersionFloat` could be something like `8.2999999999998` or `9.00000000000012`

**Comment by ibireme** [comment]
When the bits of floating point number is the same, it can be compared directly. 
There may be some potential problems, but I have tested it before to make sure there's no error.

**Comment by skyline75489** [comment]
Yes, float number can be compared directly. But the `<=` estimation will produce wrong result if the `systemVersionFloat` is actually `8.2999999999998 `. I just encountered an error like this [here](https://github.com/NYTimes/NYTPhotoViewer/issues/133). So it might be a little more unreliable than you think.

**Comment by ibireme** [comment]
I'v tested in armv7 and arm64:

    CGFloat v1 = @"8.3".floatValue;
    CGFloat v2 = @"8.3.1".floatValue;
    
    BOOL b1 = 8.3 <= v1; // YES
    BOOL b2 = 8.3 <= v2; // YES

It may get error result when compare `0.9` (for example), but 8.3 is OK.

**Comment by skyline75489** [comment]
Most of the time it should work. Still, I wouldn't really rely on this. I think comparison with `FLT_EPSILON` would be more reliable than this.

**Comment by ibireme** [comment]
If you want to get the `accurate` result, you should use `DBL_EPSILON` instead of `FLT_EPSILON` for CGFloat in arm64, but there are still some potential problems, see:
http://www.cygnus-software.com/papers/comparingfloats/comparingfloats.htm

**Comment by skyline75489** [comment]
Comparison is a little bit trivial. For convenience I would use those macros:

```objective-c
#define SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(v)  ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] != NSOrderedAscending)
```

**Comment by ibireme** [comment]
It seems simple and effective~ 
I'll replace it soon.

**Comment by ibireme** [comment]
Fixed: The default float number type in C language is `double`, so we can use `double` to compare the **system version** directly.

    double v1 = @"8.1.2".doubleValue;
    double v2 = 8.1;

    printf("%.32f\n%.32f\n%s\n",v1, v2, (v1 == 8.1 ? "true" : "false"));
    
    // console:
    8.09999999999999964472863211994991
    8.09999999999999964472863211994991
    true
