### ISSUE TITLE
手动下载YYtext

### ISSUE THREAD

**Issue by baiyidjp** [ibireme/YYText#143]
Undefined symbols for architecture x86_64:
  "_crc32", referenced from:
      _yy_png_copy_frame_data_at_index in YYImageCoder.o
      -[YYImageEncoder _encodeAPNG] in YYImageCoder.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

我引入了YYImage

**Comment by ibireme** [comment]
这是引入 YYImage 时，没有链接必要的库（libz）。
你可以再照着这个列表检查一下：https://github.com/ibireme/YYImage#手动安装

**Comment by baiyidjp** [comment]
OK  的确是
