### ISSUE TITLE
如何设定换行模式

### ISSUE THREAD

**Issue by qylibohao** [ibireme/YYText#144]
![tmp2a60b198](https://cloud.githubusercontent.com/assets/5283516/12574648/db176fb6-c440-11e5-9942-de9f032d6ac2.png)
输入表情之后的换行有问题，请问如何设定换行呢？

**Comment by ibireme** [comment]
lineBreakMode 默认是 NSLineBreakByWordWrapping，即按单词换行，这也是 UILabel、UITextView 的默认表现。

设置为 NSLineBreakByCharWrapping 就可以避免单词换行了，但这对英文文本的显示非常不友好。

**Comment by qylibohao** [comment]
textview最好有个属性可以设定一下吧，我找了一下没找到

**Comment by ibireme** [comment]
YYTextView 是必须要换行的，所以不能对外暴露 lineBreakMode 属性。UITextView 也是一样的。

如果非要设置 lineBreakMode，那可以设置到 attributedText 上，但只能用 NSLineBreakByWordWrapping、NSLineBreakByCharWrapping 这两个属性，否则会出现问题。
