### ISSUE TITLE
YYlabel 使用您demo里的表情后 中文乱码的问题

### ISSUE THREAD

**Issue by liu3619376** [ibireme/YYText#145]
![7868a33e-80c8-4f8b-b40d-3afe28e1b839](https://cloud.githubusercontent.com/assets/4251633/12602937/9becb7bc-c4e8-11e5-8d03-e7ad655f1929.png)
有些 又没问题
![57be0132-705f-44f7-92da-3368bc689c18](https://cloud.githubusercontent.com/assets/4251633/12602951/bc676c9e-c4e8-11e5-90fb-f6075ce338b5.png)
请问 这个是怎么回事？

**Comment by liu3619376** [comment]
去掉textParser 就能正常显示中文了

**Comment by ibireme** [comment]
textParser 是怎么使用的？

**Comment by liu3619376** [comment]
已经解决了 ignoreCommonProperties = false 然后 用您最新的 YYla'bel 就解决问题了 和那个setText 有方法有关 之前有人提过那个问题
还有就是大神 fixedLineHeight 这个值小于20之后 带表情的 字符串就无法显示了 应该是你说的 高度有关，但是这个设置大了的话 行间距太大 很难看界面
