### ISSUE TITLE
怎样调整网址换行的问题

### ISSUE THREAD

**Issue by qiaoxiyang** [ibireme/YYText#148]
我在制作内容包含网址时`YYLabel`每次遇到`http://`时就会换行，请问该怎么解决

**Comment by ibireme** [comment]
用 UILabel 或 UITextField 也会换行啊。。

这是英文文本换行规则，你可以设置 lineBreakMode 为 NSLineBreakByCharWrapping 来强制按字符换行，但这对英文文本的显示很不友好。

**Comment by qiaoxiyang** [comment]
由于我用到了`YYLabel`中的`textLayout`导致`YYLabel`中的一些属性不能用了，所以设置`YYLabel`中的`lineBreakMode = NSLineBreakByCharWrapping`是没有作用的，请问在`YYTextLayout`中如何设置能达到我想要的效果(使遇到http://不换行)呢？

**Comment by qiaoxiyang** [comment]
谢谢ibireme的指点，我找到了解决的方法，正如我上面所说的如果用了`YYTextLayout`的话，会导致`lineBreakMode = NSLineBreakByCharWrapping`不起作用，如果用到`YYTextLayout`，会有用到`NSMutableAttributedString`和`NSAttributedString`，这样就可以用到`attributedStr.yy_lineBreakMode = NSLineBreakByCharWrapping`了，就可以解决网址换行的问题了。再次感谢博主，正在研究CoreText的用法，在研究过程中碰到了点击相应文字跳转的问题，不知道如何将点击在`View`层上的点如何转化为文本对应的`NSRange`上，我想通过YYLabel我会学习到很多！感谢博主分享～
