### ISSUE TITLE
demo里的表情键盘 使用问题

### ISSUE THREAD

**Issue by LiweiDong** [ibireme/YYText#149]
用了demo里的表情键盘 
但是当页面里有UIActionSheet show 之后，表情键盘就无法切换和显示了。

**Comment by ibireme** [comment]
可以看一下 UIResponder.inputView 相关的文档，了解一下自定义键盘的用法。这里可以尝试在 show 和 hide 后调用 reloadInputViews 重新加载键盘，或者用 becomeFirstResponder、canResignFirstResponder 来控制键盘显示与隐藏。
