### ISSUE TITLE
YYText sizeThatFits 异常

### ISSUE THREAD

**Issue by thundernet8** [ibireme/YYText#15]
使用原生 UITextView重写 layoutSubviews方法时调用sizeThatFits获取内容高度以适配 cell，改用了 YYText 后获取的高度始终为0

**Comment by ibireme** [comment]
已添加 sizeThatFits 支持，但是这个方法目前来说性能不算太好。。。

**Comment by thundernet8** [comment]
那 YYText 提供的方法中哪个是替代sizeThatFits的呢，谢谢

**Comment by ibireme** [comment]
见这一页面中间的那个 [comment](https://github.com/ibireme/YYText/commit/47b42988fa00d94a27189b8c0ce31385dc252df4)
