### ISSUE TITLE
添加表情文字后导致一行显示不完全

### ISSUE THREAD

**Issue by SwordZJ** [ibireme/YYText#151]
在demo中仅仅修改文字，如下：
![image](https://cloud.githubusercontent.com/assets/14093546/12776282/a0305da4-ca8f-11e5-87b9-04650d74d64e.png)
运行后的结果如图：
![snip20160203_4](https://cloud.githubusercontent.com/assets/14093546/12776656/d8fa6d7a-ca92-11e5-9c09-2417c31fb048.png)

**Comment by ibireme** [comment]
我这里测试了一下，无法复现。。

上面那段代码和截图匹配不上（比如说`刷卡饭上看到`这段的属性在后面应该还有调整），还希望能把调整后的代码直接贴上来吧～

另外，可以试试打开右上角那个调试开关看看具体的排版结果。

**Comment by SwordZJ** [comment]
为了防止干扰 viewDidLoad只留如下代码
    NSMutableAttributedString *text = [NSMutableAttributedString new];
    
    {
        NSMutableAttributedString *one = [[NSMutableAttributedString alloc] initWithString:@"刷饭卡上看到是就是大数据菊花😄5555大劫案屌丝男打开的☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️爱我我http://www.baidu.com经典诵读快睡觉🈚️🈷️数据库导师.刷饭卡上😄😄看到是就是大数据菊花😄5555大劫案屌丝男打开的☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️爱我我http://www.baidu.com经典诵读快睡觉🈚️🈷️数据库导师刷饭卡上看到是就是大数据菊花😄5555大劫案屌丝男打开的☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️爱我我http://www.baidu.com经典诵读快睡觉🈚️🈷️数据库导师刷饭卡上看到是就是大数据菊花😄5555大劫案屌丝男打开的☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️☺️爱我我http://www.baidu.com经典诵读快睡觉🈚️🈷️数据库导师"];
        one.yy_font = [UIFont boldSystemFontOfSize:12];
        one.yy_color = [UIColor blackColor];
        YYTextShadow *shadow = [YYTextShadow new];
        shadow.color = [UIColor colorWithWhite:0.000 alpha:0.490];
        shadow.offset = CGSizeMake(0, 1);
        shadow.radius = 5;
        one.yy_textShadow = shadow;
        [text appendAttributedString:one];
        [text appendAttributedString:[self padding]];
    }
    
    YYLabel *label = [YYLabel new];
    label.attributedText = text;
    label.width = self.view.width;
    label.height = self.view.height - (kiOS7Later ? 64 : 44);
    label.top = (kiOS7Later ? 64 : 0);
    label.textAlignment = NSTextAlignmentCenter;
    label.textVerticalAlignment = YYTextVerticalAlignmentCenter;
    label.numberOfLines = 0;
    label.backgroundColor = [UIColor colorWithWhite:0.933 alpha:1.000];
    [self.view addSubview:label];
运行结果：
![image](https://cloud.githubusercontent.com/assets/14093546/12779639/fcba5822-caa3-11e5-871a-aac55ca2b874.png)

**Comment by SwordZJ** [comment]
附上排版图
![image](https://cloud.githubusercontent.com/assets/14093546/12779671/391b6ebe-caa4-11e5-85ff-2d7765e506ff.png)

**Comment by ibireme** [comment]
这应该是 CoreText 的一个 bug：在某些情况下（比如此处是连续 Emoji 并且前后都紧跟中文字符）绘制某几个特定的 Emoji，并且 Emoji 字号小于 25.2667 (即379/15) 时，Emoji 图像后面会多出一个很窄的空白，这个空白会影响 CoreText 本身的排版。

之前我也遇到过这个问题 （[见此处注释](https://github.com/ibireme/YYText/blob/master/YYText/Component/YYTextLayout.m#L1249-L1252)），但由于这是 CoreText 内部的 bug，我也没办法解决。目前对于这种特殊的情况有这样几个 workaround：

1. 把字符串中的 Emoji 前后都加上零宽空格 @"\u200B" 来避免这种问题。 
2. 为 label 增加内边距：`label.textContainerInset = UIEdgeInsetsMake(0, 10, 0, 10);`
