### ISSUE TITLE
YYLabel的链接在行尾时（未跨行）获取rect不正确

### ISSUE THREAD

**Issue by hh-in-zhuzhou** [ibireme/YYText#152]
YYLabel的链接的rect获取仍然有bug:：链接的这个rect的获取，仍然存在问题。比如一个2个字的短链接，在屏幕的最右边，没有跨行，获取的rect，应该是个小rect，但是获取的rect大小竟然是跨行的那种大rect。

设备：iPhone 6s
出问题的链接的range:
range NSRange location=23, length=2

出问题的链接获取到的rect: (实际并未跨行，宽度应该大约50左右，只有2个字，这个获取的结果有错误)
rect CGRect (origin = (x = 0, y = 9.8134765625), size = (width = 343, height = 45.283523437500001))

链接所在的containerView:
(lldb) po containerView
YYLabel: 0x136a3db20; frame = (16 0; 343 292); text = '1、桂枝汤 5味 桂枝三两(去皮)，芍药三两，甘草...'; opaque = NO; layer = YYTextAsyncLayer: 0x136a3ddc0

链接的text:
@"1、桂枝汤 5味 桂枝三两(去皮)，芍药三两，甘草二两，炙，生姜三两(切)，大枣十二枚(擘)。\n\t上五味，以水七升，微火煮取三升，去滓，适寒温，服一升。服已须臾，啜热稀粥一升余，以助药力，温覆令一时许，遍身漿漿，微似有汗者益佳，不可令如水流漓，病必不除。若一服汗出病差，停后服，不必尽剂；若不汗，更服依前法；又不汗，后服小促其间，半日许，令三服尽。若病重者，一日一夜服，周时观之。服一剂尽，病证犹在者，更作服。若汗不出，乃服至二三剂。禁生冷、粘滑、肉面、五辛、酒酪、臭恶等物。 "

出问题的NSAttributedString的描述：
1{
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
NSColor = "UIDeviceRGBColorSpace 0 0 1 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}、{
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}桂枝汤{
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
CTUnderlineColor = " (kCGColorSpaceDeviceGray)";
NSColor = "UIDeviceRGBColorSpace 0 0 1 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
NSStrokeWidth = "-2";
NSUnderline = 1;
NSUnderlineColor = "UIDeviceWhiteColorSpace 0 1";
YYTextHighlight = "";
} 5味{
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
NSColor = "UIDeviceRGBColorSpace 1 0 0 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
} {
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}桂枝{
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
CTUnderlineColor = " (kCGColorSpaceDeviceGray)";
NSColor = "UIDeviceRGBColorSpace 0.3 0 1 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
NSUnderline = 1;
NSUnderlineColor = "UIDeviceWhiteColorSpace 0 1";
YYTextHighlight = "";
}三两(去皮){
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
NSColor = "UIDeviceRGBColorSpace 0 0.5 0 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 13.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}，{
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}芍药{
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
CTUnderlineColor = " (kCGColorSpaceDeviceGray)";
NSColor = "UIDeviceRGBColorSpace 0.3 0 1 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
NSUnderline = 1;
NSUnderlineColor = "UIDeviceWhiteColorSpace 0 1";
YYTextHighlight = "";
}三两{
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
NSColor = "UIDeviceRGBColorSpace 0 0.5 0 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 13.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}，{
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}甘草{
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
CTUnderlineColor = " (kCGColorSpaceDeviceGray)";
NSColor = "UIDeviceRGBColorSpace 0.3 0 1 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
NSUnderline = 1;
NSUnderlineColor = "UIDeviceWhiteColorSpace 0 1";
YYTextHighlight = "";
}二两，炙{
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
NSColor = "UIDeviceRGBColorSpace 0 0.5 0 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 13.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}，{
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}生姜{
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
CTUnderlineColor = " (kCGColorSpaceDeviceGray)";
NSColor = "UIDeviceRGBColorSpace 0.3 0 1 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
NSUnderline = 1;
NSUnderlineColor = "UIDeviceWhiteColorSpace 0 1";
YYTextHighlight = "";
}三两(切){
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
NSColor = "UIDeviceRGBColorSpace 0 0.5 0 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 13.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}，{
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}大枣{
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
CTUnderlineColor = " (kCGColorSpaceDeviceGray)";
NSColor = "UIDeviceRGBColorSpace 0.3 0 1 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
NSUnderline = 1;
NSUnderlineColor = "UIDeviceWhiteColorSpace 0 1";
YYTextHighlight = "";
}十二枚(擘){
CTForegroundColor = " (kCGColorSpaceDeviceRGB)";
NSColor = "UIDeviceRGBColorSpace 0 0.5 0 1";
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 13.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}。
上五味，以水七升，微火煮取三升，去滓，适寒温，服一升。服已须臾，啜热稀粥一升余，以助药力，温覆令一时许，遍身漿漿，微似有汗者益佳，不可令如水流漓，病必不除。若一服汗出病差，停后服，不必尽剂；若不汗，更服依前法；又不汗，后服小促其间，半日许，令三服尽。若病重者，一日一夜服，周时观之。服一剂尽，病证犹在者，更作服。若汗不出，乃服至二三剂。禁生冷、粘滑、肉面、五辛、酒酪、臭恶等物。 {
NSFont = " font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 17.00pt";
NSParagraphStyle = "Alignment 4, LineSpacing 4, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n 28L,\n 56L,\n 84L,\n 112L,\n 140L,\n 168L,\n 196L,\n 224L,\n 252L,\n 280L,\n 308L,\n 336L\n), DefaultTabInterval 0, Blocks (\n), Lists (\n), BaseWritingDirection -1, HyphenationFactor 0, TighteningForTruncation NO, HeaderLevel 0";
}

**Comment by ibireme** [comment]
Fixed... https://github.com/ibireme/YYText/commit/3bb85d5ae9e3e97ce73a14dc36de02eed23bd0a8
刚才那个问题怎么关闭了。。

**Comment by hh-in-zhuzhou** [comment]
我看您没回复，还以为您没看到。。。不好意思，谢谢啊！感谢您的付出，给我们带来了极大的便利。

**Comment by hh-in-zhuzhou** [comment]
确实解决了，太感谢了！
