### ISSUE TITLE
不知道这是不是YYLabel的bug，更改字体刷新后，行距会增大，然而行距参数没变

### ISSUE THREAD

**Issue by hh-in-zhuzhou** [ibireme/YYText#153]
是这样的，刚启动程序时，无论tableView reloadData多少次，都不会有问题。但是当我动态的增大YYLabel的字体后，再刷新tableView ，行距就明显增大了。然后再动态的把YYLabel的字体调整回初始值后，行距也回不到初始的那个行距，无论在代码里哪个地方设置行距都没用。

这是我动态调整字体的代码：在一个界面中调整font后，其他界面获取这个font ，然后重新渲染。
虽然这个lineSpacing的大小我写死为4，在font变动后，行距明显的增大了。。。
    NSMutableAttributedString *res = [[NSMutableAttributedString alloc] initWithString:@“。。。”];
    UIFont *font = [HH2SearchConfig sharedConfig].font;
    res.yy_font = font;
    res.yy_lineSpacing = 4;

经过观察，我手动调整行距参数是有效的，但是把字体动态调大后，再调回来后，行距比之前的要大（参数一样），我感到很困扰，不知道这是不是bug。

**Comment by hh-in-zhuzhou** [comment]
请看，我只是动态的调整了字体后，又调整回去后，你看这行距就变了。
![img_0695](https://cloud.githubusercontent.com/assets/6437400/12813732/dcfd5026-cb74-11e5-997f-ba61c19c591e.PNG)
![img_0696](https://cloud.githubusercontent.com/assets/6437400/12813733/de7138e6-cb74-11e5-8d32-e94232ac29cb.PNG)
![img_0697](https://cloud.githubusercontent.com/assets/6437400/12813734/df56846e-cb74-11e5-89fe-cf8ef8b69c9d.PNG)

**Comment by ibireme** [comment]
字体与行距是无关的。

lineSpacing 这个属性，实际是对应到内部的 NSParagraphStyle 上的，你可以打印一下看看这个参数的值。

**Comment by hh-in-zhuzhou** [comment]
好的，我再看看。我奇怪的是，我改字体大小，影响行距。我保证我的代码没有改行距。行距还是写死的。其中的机理我不是很明白。谢谢了。
