### ISSUE TITLE
YYText有没有推荐的持久化方案？

### ISSUE THREAD

**Issue by realcarlos** [ibireme/YYText#155]
有时编辑好以后还是希望能够存储起来，有没有比较好的办法呢？

**Comment by ibireme** [comment]
如果只需要在 iOS 设备本地保存，那可以直接用 `YYTextArchiver` 和 `YYTextUnarchiver` 来序列化 NSAttributedString 或 YYTextLayout。

如果需要跨平台传输，那可能就需要一套自定义的富文本格式了（比如 markdown、HTML）。
