### ISSUE TITLE
CTFramesetterCreateWithAttributedString崩溃

### ISSUE THREAD

**Issue by tianglin** [ibireme/YYText#156]
博主，最近经常遇到一个问题，就是碰到一些特殊字符的时候很容易崩溃，比如字符串是：
：@“有木有喜欢唱歌，喜欢古风的汉纸，而且不污的ԅ(¯﹃¯ԅ)”
如下图，必崩
![acaa032d-fbb2-486c-9926-f9a945e2fa93](https://cloud.githubusercontent.com/assets/1657594/13045245/328179be-d40d-11e5-83fc-8981a6f0229f.png)

是在YYTextLayout.m里面的+ (YYTextLayout *)layoutWithContainer:(YYTextContainer *)container text:(NSAttributedString *)text range:(NSRange)range; 这个方法

有什么办法解决这个问题吗？

**Comment by ibireme** [comment]
这不是崩溃。
CoreText 内部会抛出异常，并且内部也会进行捕获，所以如果 Xcode 在 `All Exceptions` 下了断点时，这里会停下来，但仍然能继续下去，不会影响运行。

**Comment by tianglin** [comment]
多谢lz
