### ISSUE TITLE
ios7 yytext 会出现崩溃 先面试崩溃信息

### ISSUE THREAD

**Issue by lyt1117** [ibireme/YYText#157]
![2016-02-16 10 42 42](https://cloud.githubusercontent.com/assets/15885890/13065710/1043d6a2-d49a-11e5-988c-bfd96b61e8a0.png)

IOS7.0.4,IOS7.0.6, IOS7.1都会出现上述情况  其他版本暂未发现问题  使用的yytext版本号是:YYText (0.9.19)

**Comment by ibireme** [comment]
已知问题：https://github.com/ibireme/YYText/issues/126

这是 iOS 7 上 CoreText 本身的 bug，YYText 已经做了兼容处理 (Master https://github.com/ibireme/YYText/commit/c4002c2699f25d88ed9fd07c8b06d7c1520b62ec )，但还未同步到 CocoaPods 里，稍后版本号更新时会同步的。你也可以先替换一下这个文件临时修复下。
