### ISSUE TITLE
当设置 YYLabel 属性 ignoreCommonProperties ＝ true 时，无法使用 textParser 属性

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYText#160]
我开启了 YYLabel 的 ignoreCommonProperties 属性，结果就是把 textParser 属性也忽略了，无法解析表情，另外也没在唯一可用的 textLayout 属性里找到有关设置 textParser 的地方，所以请问作者在开启了 ignoreCommonProperties 的情况下怎么使用解析？另一个看了源码才解惑的地方也说一下，就是 textParser 属性必须放在 text/attributeText 或者 textLayout 属性之后才有效，希望在 README 中顺带提醒一下。谢谢。

**Comment by ibireme** [comment]
`ignoreCommonProperties` 设置为 YES 后，会忽略除了 `textLayout` 之外的所有属性，这个在注释上也有标注和使用 Tip：https://github.com/ibireme/YYText/blob/master/YYText/YYLabel.h#L268-L295

如果还要用 textParser，那只能手动去调用一下了：

    NSMutableAttributedString *text = ...
    [label.textParser parseText:text selectedRange:NULL];

**Comment by KittenYang** [comment]
你好，你也能没有理解我的意思。我并不是说 ignoreCommonProperties 会忽略除 textLayout 之外所有属性这个需要注释，我是说如果没有开启 ignoreCommonProperties 的时候设置 textParser 这个属性需要放在  text/attributeText 后面（或者放在 textLayout 后面）这个需要注释一下。

**Comment by KittenYang** [comment]
@ibireme 实在没招了。请问高亮点击延迟怎么解决？需要按稍长时间才会高亮（但是 tapAction 却是立刻响应，想不通），拜托了。

**Comment by ibireme** [comment]
1.上面那个设置先后顺序的问题，能提供下代码吗？我这里复现不了：

    YYLabel *textView = [YYLabel new];
    textView.numberOfLines = 0;
    
    // 先设置 parser
    textView.textParser = parser;
    textView.text = text;

    // 或者先设置 text
    textView.text = text;
    textView.textParser = parser;
    
    // 都是正常的


2.高亮变色有延迟那个，Label 是不是放在 ScrollView/TableView 上了？如果是的话，可以设置一下：

    scrollView.delaysContentTouches = NO;
    scrollView.canCancelContentTouches = YES;

或者参考 [这里](https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/YYTableView.m#L19-L30) 去掉 TableView 的触摸延迟。

如果视图本身有添加 GestureRecognizer，那也可以检查下是否会阻碍视图本身的 Touch 事件。

**Comment by KittenYang** [comment]
```objc
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT,0)) { () -> Void in
            //...
            let textLayout = YYTextLayout(container: self.textContainer, text: text)
            dispatch_async(dispatch_get_main_queue(), { () -> Void in
                self.label.textLayout = textLayout
                self.label.textParser = emotionParser
                // 以上两者顺利倒置则失效
            })
        }
```

**Comment by KittenYang** [comment]
@ibireme 高亮延迟解决了，需要同时开启 delaysContentTouches 和关闭 wrapView 的 gesture 。感谢。

**Comment by ibireme** [comment]
哦，YYLabel 的排版流程是这样的：

    +------------------+
    |NSAttributedString|
    +--------+---------+
             |
             | YYTextParser
             v
    +--------+---------+
    |NSAttributedString|
    +--------+---------+
             |
             | YYTextContainer
             v
    +--------+---------+
    |   YYTextLayout   |
    +------------------+

YYLabel 最终只需要 YYTextLayout 就能够显示了，其他的属性（比如 text/font/attributedText/parser）都是对这个过程的封装。

1. 先设置 textLayout，这时 text/font/attributedText 等属性都会被重置；之后再设置 textParser，会导致 label 内部重新走了一遍上面的流程，重新又生成了一份 textLayout，这样看似 parser 起效了。
2. 先设置 emotionParser，会导致 label 内部先执行了一遍上面的流程；再设置 textLayout 时，label 就会绕开上面的流程，直接使用这个 textLayout 了，这样看似 parser 失效了。

所以说，textParser 这个东西，只是相当于一个很简单的辅助功能，并且只配合 text/attributedText 来使用的，[注释](https://github.com/ibireme/YYText/blob/master/YYText/YYLabel.h#L128-L142)里也有提到，但可能不方便理解吧。这块儿之后可能再增加些文档多做一些解释和说明。

**Comment by KittenYang** [comment]
@ibireme 嗯嗯，明白了。感谢如此详细和耐心的解释！

**Comment by willbetter** [comment]
上面的流程虽然很清楚，但有个问题还是没回答：
不使用textParser，只使用textLayout，如何做到表情符解析 ？

**Comment by KittenYang** [comment]
@willbetter 不用 textParser，自己做解析然后替换。

**Comment by willbetter** [comment]
@KittenYang 感谢回复，能不能说的详细些？我现在既用了layout，也用了textParser，直接把表情符NSDictionary 传给textParser就可以自动解析表情符。自己做解析该怎么处理？能这么方便嘛？是重写YYParse里的方法还是该怎么做？

**Comment by KittenYang** [comment]
正则匹配出形如[笑哈哈]，去维护的 plist 里面找到 [笑哈哈] 对应到表情图片，然后把图片 replace 掉 [笑哈哈]。
