### ISSUE TITLE
YYTextLayout中的attachmentSize能否推迟赋值？

### ISSUE THREAD

**Issue by Finb** [ibireme/YYText#161]
非常感谢你开源的这么好用的库！！
我在使用中碰到一个问题，查阅了 Issues 和阅读了部分源码后自己暂时没找到解决办法。

问题描述：

有一个ImageView 被添加到YYTextLayout ，设置了个默认的attachmentSize
然后这个ImageView显示时，会去异步获取图片，当获取完后 会设置自身的 size，
这时我想更新这个ImageView 在YYLabel中的尺寸时，却没找到合适的能赋值的方法

请问有没有类似 setNeedsLayout 的方法？能更新YYTextLayout 中的 attachmentd 尺寸 和重新计算布局得到新的textBoundingRect

**Comment by ibireme** [comment]
参考 https://github.com/ibireme/YYText/issues/154

attachment 肯定要在排版前，有一个明确的 size，所以不能延迟赋值。attachment 尺寸变了的话，只能重新走一遍计算布局、设置到 label 这样的流程了。

**Comment by Finb** [comment]
@ibireme 谢谢！
