### ISSUE TITLE
yy_setTextHighlightRange 中的UserInfo 怎么在tapAction中调用呢？

### ISSUE THREAD

**Issue by Finb** [ibireme/YYText#162]
我有一个 类似 a标签的 点击事件，
显示的是 普通的文字，但是点击时 需要跳转到URL，（一段文本可能有大量的链接）

我可以将URL放在UserInfo中，然后在tapAction中调用吗？

我发现tapAction的参数并没有UserInfo的引用。
这里是否有其他的方法呢？

**Comment by ibireme** [comment]
highlight.tapAction = ^(UIView *containerView, NSAttributedString *text, NSRange range, CGRect rect) {
        YYTextHighlight *highlight = [text attribute:YYTextAttachmentAttributeName atIndex:range.location effectiveRange:NULL];
        NSDictionary *userInfo = highlight.userInfo;
    };

**Comment by Finb** [comment]
@ibireme 非常感谢帮助！
忘记了这个好办法 - -。


另外如果调用的是 yy_setTextHighlightRange 方法，
增加的attributeName 应该是 `YYTextHighlightAttributeName`

```OBJC
highlight.tapAction = ^(UIView *containerView, NSAttributedString *text, NSRange range, CGRect rect) {
    YYTextHighlight *highlight = [text attribute:YYTextHighlightAttributeName atIndex:range.location effectiveRange:NULL];
    NSDictionary *userInfo = highlight.userInfo;
};
```
