### ISSUE TITLE
如何使不同字号居中对齐而不是基于 baseline 对齐?

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYText#164]
如图：
![image_1455867998 069174](https://cloud.githubusercontent.com/assets/5517281/13169427/5548cd4c-d720-11e5-9f88-2abd8d484c4d.jpg)

**Comment by ibireme** [comment]
这要用到一些 CoreText 的属性了，比较麻烦：

    // 创建一个示意字符串，设置一下字体
    NSMutableAttributedString *text = [[NSMutableAttributedString alloc] initWithString:@"MMMMHHHHMMMM"];
    UIFont *normalFont = [UIFont systemFontOfSize:30];
    UIFont *smallFont = [UIFont systemFontOfSize:16];
    NSRange normalRange = [text yy_rangeOfAll];
    NSRange smallRange = [text.string rangeOfString:@"HHHH"];
    [text yy_setFont:normalFont range:normalRange];
    [text yy_setFont:smallFont range:smallRange];
    
    // 调整某段文本的 baseline 对齐
    CTFontRef ctNormalFont = CTFontCreateWithName((__bridge CFTypeRef)normalFont.fontName, normalFont.pointSize, NULL);
    NSDictionary *referenceInfo = @{(id)kCTBaselineReferenceFont : (__bridge id)ctNormalFont};
    [text addAttribute:(id)kCTBaselineReferenceInfoAttributeName value:referenceInfo range:smallRange];
    [text addAttribute:(id)kCTBaselineClassAttributeName value:(id)kCTBaselineClassIdeographicCentered range:smallRange];
    CFRelease(ctNormalFont);
    // 这段属性也可以用在整个文本中来全局调整

**Comment by KittenYang** [comment]
嗯，了解了，感谢！

**Comment by KittenYang** [comment]
@ibireme 貌似上面的代码对于简单的 string 没有问题，但是我解决不了我的情况。请问您指的「如果用到了 Attachment 或者 RunDelegate，那可能需要手动调整一下了」是什么意思？

**Comment by ibireme** [comment]
CTRunDelegateRef 会覆盖文本字体本身的 ascent、descent、width，让其不受字体和其他排版因素的影响，所以用了 CTRunDelegateRef (或者 YYTextRunDelegate)，那就需要手动把 descent 这个值调大一些。这种方式相比上面的 baseline 调整来说，更灵活也更麻烦。

YYTextAttachment 也是配合 CTRunDelegateRef 起作用的，所以如果用了 Attachment，那也得手动调整一下其对应的 descent。另外，如果 Attachment 是用 [NSAttributedString yy_attachmentStringWithContent:...] 这个封装方法创建的，那就可以直接用 alignToFont (传入需要对齐的大号字体) 和 alignment (传入 YYTextVerticalAlignmentCenter) 来进行对齐。

**Comment by ibireme** [comment]
除了 baseline 属性、RunDelegate 属性外，对于纯文本的位置微调，也可以试试 YYTextGlyphTransform 这个自定义的属性：

    [text yy_setTextGlyphTransform:CGAffineTransformMakeTranslation(0, -3.0) range:range];

如果上面提到的这些东西都还不行，那你可以把这个 NSAttributedString 打印一下，贴上来看看。

**Comment by KittenYang** [comment]
时隔一年多，竟然用 `replaceText.yy_setBaselineOffset(NSNumber(floatLiteral: 2.0), range: replaceText.yy_rangeOfAll())` 这么简单的一行代码把这个问题解决了，记录一下。

**Comment by xhjcs** [comment]
@KittenYang replaceText.yy_setBaselineOffset(NSNumber(floatLiteral: 2.0), range: replaceText.yy_rangeOfAll()) 在ios10之前这个好像无效
