### ISSUE TITLE
Calculate text height use YYTextLayout question

### ISSUE THREAD

**Issue by meilbn** [ibireme/YYText#165]
首先感谢一下作者！

根据 README 里的代码，计算文字的高度，但是有点小问题，计算出来的高度总是小于 YYTextContainerView 和 YYTextSelectionView 的高度(在 Reveal 中看到的)，导致有时候最后一行或者几行被切掉了。代码如下：

```
NSMutableAttributedString *attributedString;
    if (isHTML) {
        attributedString = [[NSMutableAttributedString alloc] initWithData:[text dataUsingEncoding:NSUnicodeStringEncoding]
                                                                     options:@{ NSDocumentTypeDocumentAttribute : NSHTMLTextDocumentType }
                                                          documentAttributes:nil
                                                                       error:nil];
    } else {
        attributedString = [[NSMutableAttributedString alloc] initWithString:text];
    }
    
    attributedString.yy_font = _contentTextView.font;
    attributedString.yy_color = _contentTextView.textColor;
    attributedString.yy_lineSpacing = 8;
    attributedString.yy_lineBreakMode = NSLineBreakByWordWrapping;
    
    _contentTextView.attributedText = attributedString;
    
    CGSize size = CGSizeMake(SCREEN_WIDTH - 12, CGFLOAT_MAX);
    YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:size text:attributedString];
    DDLogDebug(@"layout.textBoundingRect = %@, layout.textBoundingSize = %@, layout.container.size = %@",
               NSStringFromCGRect(layout.textBoundingRect),
               NSStringFromCGSize(layout.textBoundingSize),
               NSStringFromCGSize(layout.container.size));
    _contentTextViewHeightConstraint.equalTo(@(layout.textBoundingSize.height));
```

``_contentTextView`` 为 ``YYTextView``，当文本中有 HTML 标签的时候，比如 ``<br>``，则 isHTML 为 YES，当文本中不包含 HTML 标签，但是包含回车(\r)或者换行符(\n)的时候，则为 NO，比如下面的文本：

```
二十岁的某一天／和你牵手走到天桥边／你兜里只有五块钱／我们吃了一碗牛肉面\r\n\r\n你说什么爱情都会变／你说你现在也没有钱／你说谢谢我陪你这些天／你说以后不要再被别人骗\r\n\r\n三十岁的某一天／我和他路过这条街／我说想吃碗牛肉面／他说他身上没零钱\r\n\r\n我已经想不起你的脸／我也没有你的照片／时间它杀死了所有的从前／我们也没必要再去怀念／你说什么爱情都会变／你说你现在也没有钱／你说谢谢我陪你这些天／你说以后不要再被别人骗\r\n\r\n八十岁的某一天／我能否再想起你的脸
```

计算出来的rect、size、container size 为：

```
layout.textBoundingRect = {{0, -0.27999999999999936}, {300, 547.89499999999998}},
layout.textBoundingSize = {300, 548},
layout.container.size = {308, 1048576}
```

但是像上面说的，实际上 YYTextContainerView 和 YYTextSelectionView 的高度为 560。

请问有什么解决办法吗？

**Comment by ibireme** [comment]
CoreText 排版时，会忽略最后一行的换行符。TextView 在最后一行是换行符时，需要把光标挪到新的一行去，所以内部是额外为文本再添加了一个换行符号：https://github.com/ibireme/YYText/blob/master/YYText/YYTextView.m#L245 。

所以这里计算 TextView 文本大小时，可以再文本结尾添加一个 "\r" 再计算

**Comment by meilbn** [comment]
@ibireme 谢谢回复
我试了一下，实例化 attributedString 的时候，如果是 HTML 的，则在 text 后面添加了 ``<br>``，不是则添加 ``\r``，不知道这样对不对，不过实际显示的高度差却比不添加还要大一点，应该是大了一行的高度吧。
( ∙̆ .̯ ∙̆ )

**Comment by ibireme** [comment]
直接在 NSAttributedString 结尾添加 `\r` 就好，不要去修改 HTML，也不用用考虑其他状态。这样就能和 TextView [内部的实现](
https://github.com/ibireme/YYText/blob/master/YYText/YYTextView.m#L245)保持一致了。

**Comment by meilbn** [comment]
搜噶，我试了下，代码如下：

```
[attributedString yy_appendString:@"\r\r"];
```

我试过你说的添加一个 ``\r``，但是高度差还在，底部文字稍微显示多了一点，所以我又添加了一个，高度差变得更大了，但是文字显示出来的，没有被切掉。
(..•˘_˘•..)

**Comment by ibireme** [comment]
可能是计算时，没有考虑 textParser、linePositionModifier 等东西？
还有问题，那就直接这样做吧：先调整好 YYTextView 的宽高（比如定宽的话，高度就设置个任意的值），然后直接取 textView.textLayout.textBoundingSize。

**Comment by meilbn** [comment]
感谢！╭(●｀∀´●)╯╰(●’◡’●)╮
直接取 ``textView.textLayout.textBoundingSize``，高度对了！这样都不用 YYTextLayout 来计算高度了。。。也不用添加结尾的 ``\r``。。。
(●´∀｀●)

**Comment by GPF253904828** [comment]
[attributedString yy_appendString:@"\r\r"];
 加入了这个会出现换行，高度远远高于应有的高度
