### ISSUE TITLE
你好，我在做显示表情时，需要获取光标位置出现问题

### ISSUE THREAD

**Issue by Migo24K** [ibireme/YYText#166]
我输入文本框的文本是:[微笑],[大笑]
此时在页面上显示出来是两个笑脸，我光标定位到这两个表情中间，
我使用YYTextView.selectedRange获取到的位置是1
此时我需要做表情插入，我希望把表情插入到4那个位置（即逗号前面）
应该怎么做呢，我获取到的位置不对，插入后到页面上就乱了

**Comment by ibireme** [comment]
如果想要在当前光标处插入文本，那可以直接调用 [textView insertText:@"xxx"]，如果需要对某块儿文本进行插入和处理，那可以用 [textView replaceRange:range withText:@"xxx"] 来做。

文本的光标位置查询，最好用 textView.attributedText 来做。

**Comment by Migo24K** [comment]
谢谢您的建议，我使用这种方式也解决了这个问题
      NSInteger  lastCurPosition=txtInput.selectedRange.location;
       NSLog(@"选中的表情:%@",_emojyText);
        NSMutableAttributedString *temp=txtInput.attributedText.mutableCopy;
        [temp insertAttributedString:[[NSAttributedString alloc]initWithString:_emojyText] atIndex:lastCurPosition];
        txtInput.attributedText=temp;
        //输入一次表情，更新一次最后位置，防止位置错乱
        lastCurPosition++;
