### ISSUE TITLE
如何获取YYTextView中输入文字的总高度。

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#167]

**Comment by ibireme** [comment]
textView.textLayout.textBoundingSize

**Comment by offbye** [comment]
是的

**Comment by wy19901227** [comment]
恩，我也这样用的，这是打印的结果，每次粘贴一行文字

![a7421b01-5c35-47e8-8749-ce5f0d7cbd8b](https://cloud.githubusercontent.com/assets/8086633/13310775/f96e09da-dbc3-11e5-8754-60c6852eca2e.png)

**Comment by wy19901227** [comment]
开始是对的 每次加18  后来怎么不对了，，，，

**Comment by wy19901227** [comment]
原来和textView.textContainerInset还有关系。
