### ISSUE TITLE
请问如何依次获取YYTextView中输入的文字和图片

### ISSUE THREAD

**Issue by mayazhe** [ibireme/YYText#168]
想要实现一个textview编辑器，就是从上到下依次 图片-->文字-->图片-->文字-->  这样的效果。
textview中添加图片可以通过[NSMutableAttributedString yy_attachmentStringWithContent:imageView ......] 实现。

但是如何依次获取添加到_textView中的图片和文字呢，因为要将图片上传服务器，但貌似没有找到相关方法

**Comment by mayazhe** [comment]
目前想到的方法只有依次遍历，不知道有什么更好的方法没有？

`[_textView.attributedText enumerateAttributesInRange:NSMakeRange(0, _textView.attributedText.length) options:NSAttributedStringEnumerationLongestEffectiveRangeNotRequired usingBlock:^(NSDictionary<NSString *,id> * _Nonnull attrs, NSRange range, BOOL * _Nonnull stop) {
        NSDictionary *dic = attrs;
        NSString *str = [_textView.text substringWithRange:range];
        
        if (str && ![str isEqualToString:YYTextAttachmentToken]) {
            // 此处是文字
            NSLog(@"+++ %@",str);
        }
        
        if (dic[YYTextAttachmentAttributeName]) {
            // 此处是图片
            YYTextAttachment *attachment = dic[YYTextAttachmentAttributeName];
            NSLog(@"=== %@",attachment);
        }
    }];`

**Comment by ibireme** [comment]
也许可以试试访问 `textView.textLayout.attachments` 和 `textView.textLayout.attachmentRanges` 属性看看。

**Comment by mayazhe** [comment]
@ibireme 谢谢，我试一下

**Comment by fuhailong** [comment]
怎么取出啊  求解
textLayout?.attachmentRanges 看 range，如果不是连着的 就自己算字符串的 range?
再textLayout?.attachments?.first?.content 取出 image ?
有没有更好的法子
