### ISSUE TITLE
How to interact with the custom `UIView` attachment?

### ISSUE THREAD

**Issue by shivanraptor** [ibireme/YYText#17]
Thanks for this great library! In the README example, I found the following codes:

    // UIView attachment
    UISwitch *switcher = [UISwitch new];
    [switcher sizeToFit];
    attachment = [NSMutableAttributedString yy_attachmentStringWithContent:switcher contentMode:UIViewContentModeBottom attachmentSize:switcher.frame.size alignToFont:font alignment:YYTextVerticalAlignmentCenter];
    [text appendAttributedString: attachment];

However, the `UISwitch` is not selectable. How to enable selection of the `UISwitch` (or other element like `UITextField`)?

**Comment by ibireme** [comment]
Make sure you create the UISwitch in main thread, then make a reference to this UISwitch in your class.

See this file for example:
https://github.com/ibireme/YYText/blob/master/Demo/YYTextDemo/YYTextAttachmentExample.m
