### ISSUE TITLE
在竖版排版下，使用自定义字体时，出现闪退

### ISSUE THREAD

**Issue by JPluto** [ibireme/YYText#170]
你好，在使用YYLabel时，使用了一个自定义的ttf字体，并且设置为竖版排版，文字颜色为红色，运行后出现了崩溃，挂在了YYTextDrawRun中的CGContextShowGlyphsAtPositions位置；如果设置为纯白或者黑色，不会出现崩溃，但是文字没有绘制出来；是否有碰到过这种问题？或者说有没有什么思路。

对了，只有在iOS7上出现目前测试

**Comment by ibireme** [comment]
Readme 最底下提到了这个问题，但之前我只注意到文字没有绘制出来。。

我猜是 CoreText 或者上面这个方法内部的问题，因为同样的代码和逻辑，在 iOS6/8/9 上都没问题，水平排版时也没问题。这个稍后我会再找个 iOS7 设备来看一下。

**Comment by JPluto** [comment]
好的，感谢。
我这边使用自定义字体的方式很简单：找一个中文字体，项目配置里头添加“Fonts provided by application”项并往里头注册该字体使用，使用时YYLabel文字颜色用redColor，就出现了crash；用whiteColor或者blackColor时不会导致crash，但是没有绘制出来；

**Comment by ibireme** [comment]
Fixed: https://github.com/ibireme/YYText/commit/922592d6c47ded0cfda1bc87800bc65591f8a086

**Comment by shukaka** [comment]
ios 10真机上竖排使用自定义字体还是崩溃
