### ISSUE TITLE
YYLabel in tableview cell

### ISSUE THREAD

**Issue by skipness** [ibireme/YYText#171]
I have added a yylabel in a custom talbeviewcell which use to show attributed string(actually content from web and I parse it to attributed string) and I set the following constraint on it
![untitled](https://cloud.githubusercontent.com/assets/8035517/13323396/3bb52bb6-dc14-11e5-8504-968ab52d6598.jpg)

However the cell height doesn't change base on the content and all cells keep the default height. Did I set the constraint in a wrong way?

**Comment by ibireme** [comment]
You may try the latest code in `Master` branch (and set the `preferredMaxLayoutWidth` property).

**Comment by skipness** [comment]
Problem solved after using the latest code.
thank you!
