### ISSUE TITLE
YYTextView插入图片后，会自动全选

### ISSUE THREAD

**Issue by cctvzxxz1** [ibireme/YYText#172]
在使用YYTextView动态添加图片时，在当弹出键盘的情况下，添加图片，会出现YYTextView中的内容被全选的情况，这个我在YYTextView中也没有找到相关属性可以关掉，请问要如何关闭这个效果呢，谢谢

**Comment by ibireme** [comment]
如果要是直接更新整个 attributedText，可能会导致选中范围的改变。这可以重新设置一下 textView.selectedRange 来修改选中区域（比如插入图片前先记一下这个值，插入图片后在设置回来）。

**Comment by cctvzxxz1** [comment]
多谢，问题解决了，插入图片后，重新设置下selectedRange，设置选中区域为图片的下一个位置
