### ISSUE TITLE
YYTextView不支持IQKeyboard的工具条吗?

### ISSUE THREAD

**Issue by redohat** [ibireme/YYText#173]
您好,最近用了您的YYTextView,也用了IQK.
但是发现好像IQKeybordManager的工具条在YYTextView成为第一响应者的时候不会出现.

**Comment by ibireme** [comment]
看了一下 IQKeyboardManager，它在[这段代码中](https://github.com/hackiftekhar/IQKeyboardManager/blob/master/IQKeyBoardManager%2FIQKeyboardManager.m#L189-L196)只监听了 UITextField 和 UITextView 的通知，比如UITextViewTextDidChangeNotification，而 YYTextView 不能和 UITextView 冲突，所以这里是用的自定义通知，比如 YYTextViewTextDidChangeNotification。

另外，它在代码中，也指定了 UITextView 和 UITextField 的类名，所以这里用不了。
