### ISSUE TITLE
YYText获取高度问题

### ISSUE THREAD

**Issue by Migo24K** [ibireme/YYText#174]
您好，我在处理消息列表时有两处需要计算高度，消息列表中包含表情
1.给UITableViewCell先添加一个静态方法，在这里返回cell的高度
2.给UITableViewCell添加一个setData方法，在此方法中再计算一次高度，此处重新设置YYLabel的frame或约束
现在遇到些问题:

### 这是我初始化YYLabel的代码

    //评论
    YYLabel * lblComment = [YYLabel new];
    [lblComment setTextColor:color_333333];
    [lblComment setFont:fitFont_13];
    [lblComment setNumberOfLines:0];
    [self.contentView addSubview:lblComment];
    
    //表情映射
    YYTextSimpleEmoticonParser *parser = [YYTextSimpleEmoticonParser new];
    parser.emoticonMapper = [MemoryData sharedInstance].emojiDict;
    
    //行高
    YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
    modifier.fixedLineHeight = lineHeight;

    [lblComment setTextParser:parser];
    [lblComment setLinePositionModifier:modifier];

### 这里是我静态方法中的代码

        NSMutableAttributedString *attrString=.....;        
        //行高
        YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
        modifier.fixedLineHeight = lineHeight;
        
        // Create text container
        YYTextContainer *container = [YYTextContainer new];
        container.size = CGSizeMake(contentWidth, CGFLOAT_MAX);
        container.maximumNumberOfRows = 0;
        container.linePositionModifier=modifier;
        
        //创建layout
        YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:attrString];
        // 获取文本显示位置和大小
        //####此处算出的高度较小，然后整个cell返回高度就不对了######
        contentHeight =layout.textBoundingSize.height;

### 这里是重新设置约束

        NSMutableAttributedString *attrString=.....;        
        [lblComment setAttributedText:attrString];
        
        //行高
        YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
        modifier.fixedLineHeight = lineHeight;
        
        // Create text container
        YYTextContainer *container = [YYTextContainer new];
        container.size = CGSizeMake(contentWidth, CGFLOAT_MAX);
        container.maximumNumberOfRows = 0;
        
        //创建layout
       //####此处用的是YYLabel.attributedText参与高度运算的，这里高度应该是对的######
        YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:lblComment.attributedText];
        // 获取文本显示位置和大小
        contentHeight =layout.textBoundingSize.height;
        
        [lblComment updateConstraints:^(MASConstraintMaker *make) {
            make.height.equalTo(contentHeight);
        }];

不知道大神可明白我的意思，我上面算的高度永远都是不对的，由于才开始使用YYText，不知道使用方法是否正确，也实在找不着资料，花了很多时间了，还是搞不定，老板要发飙了，求大神指点迷津

**Comment by ibireme** [comment]
简单点的方法（需要先更新到 Master 分之的最新代码，还未发布到 CocoaPods）：

    label.preferredMaxLayoutWidth = 220;
    CGSize size = label.intrinsicContentSize;
    
复杂点的方法：

    NSMutableAttributedString *text = label.attributedText;
    [label.textParser parseText:text selectedRange:NULL];

    YYTextContainer *container = [YYTextContainer new];
    container.size = CGSizeMake(220, CGFLOAT_MAX);
    container.linePositionModifier = label.linePositionModifier;
    container.insets = label.textContainerInset;
    container.maximumNumberOfRows = label.numberOfLines;
    
    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:text];
    CGSize size = layout.textBoundingSize;

**Comment by Migo24K** [comment]
还是不对，静态方法中算出来比setData方法高度小21    
T.T

**Comment by Migo24K** [comment]
大神，第一种方法，size算出来都是0
第二种方法算出来和我之前一样 T.T
还有其他可能性吗？我有可能哪里属性没设置或者是其他情况？

**Comment by ibireme** [comment]
先把 label 所有属性都设置好，然后：

    NSAttributedString *text = [label valueForKey:@"_innerText"];
    YYTextContainer *container = [label valueForKey:@"_innerContainer"];
    container.size = CGSizeMake(200, CGFLOAT_MAX);
    CGSize size = [YYTextLayout layoutWithContainer:container text:text].textBoundingSize;
    
    // 或者
    CGSize size = [label sizeThatFits:CGSizeMake(200, CGFLOAT_MAX)];

    // 这两个计算方法，结果应该一样。

如果这还不对，那就需要检查下其他的布局逻辑了。

**Comment by Migo24K** [comment]
这两个方法返回值是一样的

**Comment by ibireme** [comment]
还有问题？高度是大了还是小了？界面显示和期望是什么样子？

仔细调试一下，打印一下 label 中的各个属性是否正确，打印一下 size 计算过程中每个返回值是否正确，开启一下 Debug 模式，看看界面布局的样式：

    YYTextDebugOption *debugOptions = [YYTextDebugOption new];
    debugOptions.baselineColor = [UIColor redColor];
    debugOptions.CTFrameBorderColor = [UIColor redColor];
    debugOptions.CTLineFillColor = [UIColor colorWithRed:0.000 green:0.463 blue:1.000 alpha:0.180];
    debugOptions.CGGlyphBorderColor = [UIColor colorWithRed:1.000 green:0.524 blue:0.000 alpha:0.200];
    [YYTextDebugOption setSharedDebugOption:debugOptions];

我觉得是 Label 的属性或大小在某个地方又被修改过了。

**Comment by Migo24K** [comment]
我创建label和计算高度地方用的临时label，是出自于同一个方法的，属性应该是一致的
如我第一步所述：我在静态方法中算出来的高度偏小，所以整个cell高度不对，界面显示和期望值，不知道您是否方便加下我QQ或者其他，我给您截图，我在这里卡了好几天了，怎么算都不对

**Comment by ibireme** [comment]
没必要那样做啊。。又容易出错又浪费 CPU 资源。。

可以看一下这块儿的逻辑：https://github.com/ibireme/YYText#异步排版和渲染

    YYLabel *label = [YYLabel new];
    label.displaysAsynchronously = YES; //开启异步绘制
    label.ignoreCommonProperties = YES; //忽略除了 textLayout 之外的其他属性
    // 之后，label 就只用设置 textLayout 属性就好。


    // 创建文本：
    NSMutableAttributedString *text = ...;
    [textParser parseText:text selectedRange:NULL];  //解析表情

    YYTextContainer *container = [YYTextContainer new];
    container.size = CGSizeMake(220, CGFLOAT_MAX);
    container.linePositionModifier = ...
    container.insets = ...
    ...

    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:text];
    CGSize size = layout.textBoundingSize;
    
    label.textLayout = layout;

**Comment by Migo24K** [comment]
对了，有个情况忘了跟您说，如果我数据是单行的，算出来高度就正确，如果是多行的，高度就不对，还有其他可能性吗？

**Comment by ibireme** [comment]
label 本身的宽度设置、insets，和计算时的给的宽度限制、insets 不一样，会有上面这种问题。

**Comment by Migo24K** [comment]
我有个问题想问下您，为了消除疑惑与验证计算高度代码的正确性，我现在写了段测试代码，您看下为啥上面这段计算出来的aSize和下面这段计算出来的bSize高度不一样？代码量已经很少了,aSize计算出来高度是35，bSize计算出来是39，这很有可能就是我上面那堆问题的根源所在
NSString *message=@"我是一个测试表情:[微笑][困]我是一个测试表情:[微笑][困]我是一个测试表情:[微笑][困]";
    
    //表情映射
    YYTextSimpleEmoticonParser *parser = [YYTextSimpleEmoticonParser new];
    parser.emoticonMapper = [MemoryData sharedInstance].emojiDict;
    
    //行高
    YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
    modifier.fixedLineHeight = fitFont_15_height;
//
    //测试表情label
    YYLabel *lbl=[YYLabel new];
    [lbl setFont:fitFont_15];
    [lbl setTextColor:color_ff0000];
    [lbl setTextAlignment:NSTextAlignmentCenter];
    [lbl setNumberOfLines:0];
    [lbl setTextParser:parser];
    [lbl setLinePositionModifier:modifier];
    [self.view addSubview:lbl];
    lbl.textContainerInset=UIEdgeInsetsMake(0, 0, 0, 0);
    
    
    NSMutableAttributedString *aText = [[NSMutableAttributedString alloc]initWithString:message];
    YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:CGSizeMake(ScreenSize.width, 500) text:aText];
    // 获取文本显示位置和大小
    CGSize aSize=layout.textBoundingSize;
    
    
    NSMutableAttributedString *bText = aText;
    YYTextContainer *container = [YYTextContainer new];
    container.size = CGSizeMake(ScreenSize.width, 500);
    container.linePositionModifier = lbl.linePositionModifier;
    container.insets = lbl.textContainerInset;
    container.maximumNumberOfRows = lbl.numberOfLines;
    
    YYTextLayout *bLayout = [YYTextLayout layoutWithContainer:container text:bText];
    CGSize bSize = bLayout.textBoundingSize;

**Comment by hw20101101** [comment]
‘’‘
    
    NSMutableDictionary *mapper = [NSMutableDictionary new];
    mapper[@"[生气]"] = [self imageWithName:@"angry"];
    mapper[@"[篮球]"] = [self imageWithName:@"basketball"];
 
    YYTextSimpleEmoticonParser *parser = [YYTextSimpleEmoticonParser new];
    parser.emoticonMapper = mapper;
    
    YYTextLinePositionSimpleModifier *mod = [YYTextLinePositionSimpleModifier new];
    mod.fixedLineHeight = 22;
    
    YYLabel *label = [[YYLabel alloc] init];
    label.text = @"Hahahah[生气], it\'s emoticons:[篮球]:arrow::cry::wink: You can input \":\" + \"smile\" + \":\" to display smile emoticon, or you can copy and paste these emoticons";
    label.font = [UIFont systemFontOfSize:15];
    label.textParser = parser;
    label.size = self.view.size;
    label.numberOfLines = 0;
    label.linePositionModifier = mod;
    [self.view addSubview:label];
 
	//我是这样设置label的宽高的，不知对你是否有用
    CGSize size = label.textLayout.textBoundingSize;
 
    [label makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(@(66));
        make.left.equalTo(@(2));
        make.width.equalTo(@(size.width));
        make.height.equalTo(@(size.height));
    }];

’‘’‘

**Comment by SwordZJ** [comment]
说一下我计算带富文本的文字高度计算方法
- (CGFloat)heightForAttributeText:(NSAttributedString *)attributeText maxWidth:(CGFloat)maxWidth{
    YYTextContainer *container = [YYTextContainer new];
    container.size = CGSizeMake(maxWidth, CGFLOAT_MAX);
    container.maximumNumberOfRows = 0;
    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:attributeText];
    return layout.textBoundingSize.height;
}

**Comment by SwordZJ** [comment]
```objc
- (CGFloat)heightForAttributeText:(NSAttributedString *)attributeText maxWidth:(CGFloat)maxWidth{
    YYTextContainer *container = [YYTextContainer new];
    container.size = CGSizeMake(maxWidth, CGFLOAT_MAX);
    container.maximumNumberOfRows = 0;
    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:attributeText];
    return layout.textBoundingSize.height;
}
```

**Comment by SwordZJ** [comment]
我发现最终通过layout计算出来的尺寸比较准确 所以在封装后使用此方法计算带富文本文字的YYLabel
