### ISSUE TITLE
关于lineBreakMode属性设置后的重置问题

### ISSUE THREAD

**Issue by SwordZJ** [ibireme/YYText#176]
你好 在设置完label的换行模式为NSLineBreakByCharWrapping后  再调用setAttributeText方法后，换行模式自动重置为NSLineBreakByWordWrapping  
另外，我想重新YYLabel的lineBreakMode的setter方法强制在设置完后再重置回来，发现继承YYLabel的类无法调用下划线成员变量 请问这种情况如何解决

**Comment by ibireme** [comment]
NSAttributedString 本身就带有 lineBreakMode 属性，可以通过 text.yy_lineBreakMode 访问，默认是 NSLineBreakByWordWrapping。所以设置了 attributedText 后，label 的 lineBreakMode 也会被重置。
