### ISSUE TITLE
不设置YYLable的高度，只显示一行

### ISSUE THREAD

**Issue by wzi90921** [ibireme/YYText#178]
[self.byReplyLabel updateConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.replyView).offset(SYRealValue(2*padding));
        make.left.equalTo(self.replyView).offset(SYRealValue(2*padding));
        make.right.equalTo(self.replyView).offset(SYRealValue(-padding));
    }];
使用masonry，内容是不固定的。
用pod上面最新版本可以显示出来，但只是显示一行。。
只有设置了高度后，就能完整显示。。
目前无法算出文字的高度，由于显示内容宽度受其他节目元素影响，很难算出显示内容的宽度

**Comment by ibireme** [comment]
设置一下 label.preferredMaxLayoutWidth 试试，如果还不行，取一下 label.intrinsicContentSize。

**Comment by wzi90921** [comment]
非常感谢大神的指点。。。
    [self.byReplyLabel setPreferredMaxLayoutWidth:self.byReplyLabel.frame.size.width];
我用这个解决了。。。。
是不是在您的项目中，可以直接解决这个问题呢。。。

**Comment by ibireme** [comment]
能解决就好
