### ISSUE TITLE
Some document can't display in YYTextView

### ISSUE THREAD

**Issue by oulvhai** [ibireme/YYText#18]
测试下来，一些文档没办法显示。比如以下这个文档。
[Markdown 語法官方說明繁體中文版.txt](https://github.com/ibireme/YYText/files/35332/Markdown.txt)

**Comment by ibireme** [comment]
额，你是说内置的那个 Markdown Parser 吗？那个我在注释里写了一下：

    YYTextSimpleMarkdownParser
    It'a very simple markdown parser, you can use this parser to highlight some 
    small piece of markdown text.
   
    This markdown parser use regular expression to parse text, slow and weak.
    If you want to write a better parser, try these projests:
    https://github.com/NimbusKit/markdown
    https://github.com/dreamwieber/AttributedMarkdown
    https://github.com/indragiek/CocoaMarkdown
 
    Or you can use lex/yacc to generate your custom parser.

**Comment by oulvhai** [comment]
非也，我用 YYTextSimpleEmoticonParser 也一样。

**Comment by ibireme** [comment]
能贴下你的代码片段吗？

**Comment by oulvhai** [comment]
其实即使不设置 Parser 也是不能显示的。

**Comment by oulvhai** [comment]
```
YYTextView *textView = [YYTextView new];
    textView.text = @"Hahahah:smile:, it\'s emoticons::cool::arrow::cry::wink:\n\nYou can input \":\" + \"smile\" + \":\" to display smile emoticon, or you can copy and paste these emoticons.\n";
    NSStringEncoding encode;
    NSURL *url = [NSURL fileURLWithPath:@"/Users/oulvhai/Documents/MWeb/External Mode Docs/iOS Demo/Markdown 語法官方說明繁體中文版.txt"];
    
    NSString *textMarkdown = [[NSString alloc] initWithContentsOfURL:url usedEncoding:&encode error:nil];
    NSLog(@"TT:%@",textMarkdown);
    textView.text = textMarkdown;
    
    textView.font = [UIFont systemFontOfSize:17];
    //textView.textParser = parser;
    textView.size = self.view.size;
    textView.textContainerInset = UIEdgeInsetsMake(10, 10, 10, 10);
    textView.delegate = self;
```

**Comment by ibireme** [comment]
目前测试发现，在模拟器中，当文本内部视图高度大于 8192 时，渲染有问题，真机目前测试OK，请换真机跑一下看看？

**Comment by oulvhai** [comment]
真机的确没问题，超讚！
然后如 <https://github.com/ibireme/YYText/issues/16> 所说，如果想用 YYTextView 做长文档编辑器，暂时还是不可行。
目前只能用回 UITextView 先了 😀。
