### ISSUE TITLE
action重复调用

### ISSUE THREAD

**Issue by sulizhan** [ibireme/YYText#180]
实现了YYLabel的textTapAction 同时实现了内容highlight的tapAction 然后点击高亮的时候会同时触发两个事件。 想实现像微信那样 点击名字和点击内容区分开来。

**Comment by ibireme** [comment]
label.textTapAction = ^(UIView *containerView, NSAttributedString *text, NSRange range, CGRect rect) {
        if (range.location == NSNotFound) {
            /// 点击了非文本区域
        } else if ([text attribute:YYTextHighlightAttributeName atIndex:range.location]) {
            /// 点击了高亮文本
        } else {
            /// 点击了普通文本
        }
    };
