### ISSUE TITLE
YYTextView相关问题

### ISSUE THREAD

**Issue by mayazhe** [ibireme/YYText#181]
Hi，YY大神:
如图，TextView的内容区域和图片宽度始终是一致的。图片右侧蓝色线条是光标，现在的情况是插入图片后虽然当前行内容已满但光标默认在图片右侧，输入文字才换行。能不能实现插入图片后如果当前行内容已满则光标自动下移到下一行，而不是输入"\n"来换行

============================分割线============================

![img_0806 1](https://cloud.githubusercontent.com/assets/10356817/13430529/5fb06892-e000-11e5-9195-52f51e58c40f.PNG)

**Comment by ibireme** [comment]
这个。。由于目前光标是处于那一行的结尾，如果不输入点东西的话，是触发不了换行的。就算 iOS 自带的备忘录也是这个逻辑。。

**Comment by mayazhe** [comment]
首先感谢您这么晚了还回复，真是太给力了！
顺便问个问题，那个图片能不能做到禁止点击，只能点击文字区域？

**Comment by mayazhe** [comment]
感谢您这么晚了还回复，多谢！
