### ISSUE TITLE
YYLabel显示自定义emoji有问题

### ISSUE THREAD

**Issue by medisean** [ibireme/YYText#182]
YYLabel显示自定义emoji有问题，在只显示一行的情况下，YYLabel最右边不会出现省略号

**Comment by ibireme** [comment]
<img width="291" alt="2016-03-02 10 29 43" src="https://cloud.githubusercontent.com/assets/839283/13448937/c77d3b88-e061-11e5-95b6-6e9e77b0646d.png">
这是 Demo，稍微改了一下，应该是没问题的啊。。

你能贴一下你的代码片段嘛？

**Comment by ibireme** [comment]
没有更多信息，也不能复现，关闭问题。
