### ISSUE TITLE
你好，YYTextEmoticonExample这个演示类里，能不能不用YYTextView获取表情、文字混排的高度？

### ISSUE THREAD

**Issue by lx19990999** [ibireme/YYText#187]
> https://github.com/ibireme/YYText#文本布局计算

这里的计算方法和_textView.textLayout.textBoundingSize.height的结果不一致啊。
是不是只能写个静态类用YYTextView来解析后返回高度？
感谢回复。

**Comment by ibireme** [comment]
如果有 textParser，那计算宽高之前，需要你手动调用一下 textParser，把文本先解析一遍再计算。

    NSMutableAttributedString *text = ...
    [label.textParser parseText:text selectedRange:NULL];

**Comment by tuimaochang** [comment]
你好，我把YYTextEmoticonExample这个演示类右上角的事件稍加修改成如下代码，其中变量parser为
viewDidLoad里的。
控制台输出的2个值还是不一致……感谢回复。
`- (void)edit:(UIBarButtonItem *)item {
    NSLog(@"%f,%f",_textView.textLayout.textBoundingSize.height,_textView.textLayout.textBoundingSize.width);
    
    NSMutableAttributedString *text = [[NSMutableAttributedString alloc] initWithString:_textView.text];
    [parser parseText:text selectedRange:NULL];
    CGSize size = CGSizeMake(_textView.textLayout.textBoundingSize.width, CGFLOAT_MAX);
    YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:size text:text];
    NSLog(@"%f",layout.textBoundingSize.height);
    
    if (_textView.isFirstResponder) {
        [_textView resignFirstResponder];
    } else {
        [_textView becomeFirstResponder];
    }
}`

**Comment by lx19990999** [comment]
你好，我把YYTextEmoticonExample这个演示类右上角的事件稍加修改成如下代码，其中变量parser为
viewDidLoad里的。
控制台输出的2个值还是不一致，不知道问题出在哪里，能帮我分析下吗？感谢回复。

`NSLog(@"%f,%f",_textView.textLayout.textBoundingSize.height,_textView.textLayout.textBoundingSize.width);
    
    NSMutableAttributedString *text = [[NSMutableAttributedString alloc] initWithString:_textView.text];
    [parser parseText:text selectedRange:NULL];
    CGSize size = CGSizeMake(_textView.textLayout.textBoundingSize.width, CGFLOAT_MAX);
    YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:size text:text];
    NSLog(@"%f",layout.textBoundingSize.height);
    
    if (_textView.isFirstResponder) {
        [_textView resignFirstResponder];
    } else {
        [_textView becomeFirstResponder];
    }`
