### ISSUE TITLE
在TableViewCell中添加 YYAnimatedImageView 上下滚动时，有时图标会不显示

### ISSUE THREAD

**Issue by toss156** [ibireme/YYText#19]
添加的代码如下：

        YYImage *image = [YYImage imageNamed:imageName];
        YYAnimatedImageView *imageView = [[YYAnimatedImageView alloc] initWithImage:image];
        
        UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(5, 2, 38, 16)];
        label.text = text;
        label.font = [UIFont systemFontOfSize:12];
        label.textColor = color;
        [imageView addSubview:label];
        
        NSMutableAttributedString *imgText = [NSMutableAttributedString yy_attachmentStringWithContent:imageView contentMode:UIViewContentModeCenter attachmentSize:size alignToFont:[UIFont systemFontOfSize:12] alignment:YYTextVerticalAlignmentBottom];
        
        [_attrText appendAttributedString:imgText];

**Comment by ibireme** [comment]
首先确保那个 imageView 能在一般视图上能显示，如果显示不了则可能是文件名、图片有问题。

之后确认 ImageView 、Label 是在主线程创建和操作的。

**Comment by toss156** [comment]
感觉应该是与 Cell 的重用机制有关，不显示的图标，通过cell的上下滑动，重新出现以后可以显示。

**Comment by toss156** [comment]
直接在YYTextDemo，测试也会发生这样的问题，快速上下滑动，有几率出现，如果 attachment 是 UIImage没有问题，只有UIView 的时候会出现，问题应该是出在newAsyncDisplayTask， task.willDisplay task.display task.didDisplay 里面，麻烦帮忙看一下
![image](https://cloud.githubusercontent.com/assets/3478955/11206070/9575d932-8d47-11e5-8983-c973d50efde7.png)

**Comment by ibireme** [comment]
感谢提出问题，已复现并修复。
更新一下代码或者 pod 再试一下看看～

**Comment by toss156** [comment]
测试过了，目前没有重现了。Thanks！
