### ISSUE TITLE
一个体验问题。

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#190]
用YYlabel来写cell，reloadData的时候，会明显的闪烁，这个体验不是很好，我自己处理一下就是，model赋值的时候，如果是同一个model，也就是同一个cell的话，就不赋值了。但是这样的话，有的时候model回跟新，所以解决的不是很好，不知道你这边能优化下吗>

**Comment by ibireme** [comment]
See: https://github.com/ibireme/YYText/issues/103
