### ISSUE TITLE
使用TextParser时，每次都需要调用yy_removeAttributesInRange后重新匹配文字，导致设置好的样式都消失了

### ISSUE THREAD

**Issue by Huanhoo** [ibireme/YYText#192]
需求是“#”中间的文字变色，所以用了TextParser。然后发现如果每次不调用yy_removeAttributesInRange的话，会出现文字颜色错乱的情况，但是调用的话，提前设好的样式都消失了。于是我把之前设好的样式都提前存起来，remove之后再添上，但是发现font这类属性在取得时候有时会变成默认的17号字体，依然导致样式丢失。所以请问有没有完美的解决方案？

**Comment by ibireme** [comment]
yy_removeAttributesInRange 实际上也是调用了 NSMutableAttributedString 的方法，把所有属性都移除掉。如果只需要重置颜色，那应该只移除颜色的属性。

这里面只涉及 NSMutableAttributedString 的处理，YYText 不涉及这块儿。

**Comment by Huanhoo** [comment]
好 谢谢 明白了 我就移除颜色就好了

**Comment by Huanhoo** [comment]
另外再问一下，我用YYTextView的时候，使用yy_removeAttributesInRange后再输入自己通过TextParser匹配的表情时，之前输入过的表情就变成乱码了 这是为什么呢？乱码是\U0000fffc，是固定的

**Comment by ibireme** [comment]
表情是通过 Attachment 和 RunDelegate 两个属性实现的，如果移除了属性那当然就显示不出表情了。

**Comment by Huanhoo** [comment]
恩 但是是原始的字符串里边的表情文本变成了乱码，难道移除属性还会改变原始文本的内容吗？

**Comment by ibireme** [comment]
这个"乱码"实际上是一个固定值，即 NSAttachmentCharacter，苹果的注释是 `Specifies a character that denotes an attachment.`

这是用于表情占位用的，但如果没有配合表情属性（Attachment/RunDelegate）使用，那它本身是没什么用的。

**Comment by Huanhoo** [comment]
👍多谢大神
