### ISSUE TITLE
图文混排编辑求解

### ISSUE THREAD

**Issue by leibaozai** [ibireme/YYText#193]
1. 
![1](https://cloud.githubusercontent.com/assets/12133314/13565343/803334b2-e48a-11e5-8737-6d28a1b84a5e.png)
默认内容为空，当输入一定文字时再添加图片，结果显示为
![2](https://cloud.githubusercontent.com/assets/12133314/13565436/fffd8bb6-e48a-11e5-87d5-54ca1128c58f.png)
打印self.context内容为，也是有文本和图片的，不知道是什么原因？虚心求教
![3](https://cloud.githubusercontent.com/assets/12133314/13565476/42d5a432-e48b-11e5-9d1a-2d0870ab90ed.png)

**Comment by ibireme** [comment]
textView.attributedText = xxx 这样设置时，textView 内部会认为是把全部文本都替换，所以这时会尽量保持原有的光标位置不变。这可以在外部再设置一下 selectedRange 改变光标位置。

**Comment by leibaozai** [comment]
还是没解决，可能我的方法不对。还有一次性添加多张图片会有重叠效果，可以微博私信你详聊吗？万分感谢。

**Comment by ibireme** [comment]
那可能是你从图片创建 Attachment 时大小或者 contentMode 没有设置对。

    [NSMutableAttributedString yy_attachmentStringWithContent:image 
        contentMode:UIViewContentModeCenter 
        attachmentSize:image.size 
        alignToFont:font 
        alignment:YYTextVerticalAlignmentCenter];

**Comment by leibaozai** [comment]
之前是你说的那个问题，已解决，非常感谢！但是现在又出现一个新问题，如图：
![1](https://cloud.githubusercontent.com/assets/12133314/13591058/318cfe60-e520-11e5-8a8e-a7fa7de08523.png)

**Comment by ibireme** [comment]
处理 textView 的富文本时，直接用 textView.attributedText.mutableCopy 来做。

**Comment by leibaozai** [comment]
不是很懂，是在哪个地方使用了

**Comment by leibaozai** [comment]
我就是用的YYTextView，默认 textView.attributedText为空。输入一段文字，插入图片；输入一段文字，插入图片。并且我做好了插入图片换行，就是不知道怎么去设置 textView.attributedText，每次赋值，你说是textView 内部会认为是把全部文本都替换，我移动光标到最后。再次添加图片会把之前输入文本也加进去。使用的这个方法有问题
 NSMutableAttributedString *attStr = [[NSMutableAttributedString alloc] initWithString:[NSString stringWithFormat:@"%@\n",self.yyTextView.text]];
那怎么去除每次添加图片前存在的文字了？？？

**Comment by ibireme** [comment]
`.text` 是纯文本，不包含图片等富文本内容。如果要操作富文本，那应该是只访问 `.attributedText` 属性。

    NSMutableAttributedString *text = textView.attributedText.mutableCopy;
    [text appendAttributedString:imageAttachment];
    textView.attributedText = text;
    textView.selectedRange = xxx

**Comment by leibaozai** [comment]
谢谢解答。

**Comment by leibaozai** [comment]
谢谢解答。
按照你说的解决了之前的问题，但是添加图片到最后，再次输入文本，字体变回默认大小，打印结果还是为设置的20pt。当再次添加图片是，又变回设置的20pt。是按照你的demo里的YYTextEditExample仿照做的。o(╯□╰)o orz
![1](https://cloud.githubusercontent.com/assets/12133314/13602405/703e3e34-e571-11e5-8c91-63c8856e11a4.png)
![2](https://cloud.githubusercontent.com/assets/12133314/13602410/75493758-e571-11e5-97e3-56c5b99c39cd.png)

**Comment by ibireme** [comment]
attachment 创建时是没有 font 的，当 TextView 内部 NSMutableAttributedString 附加纯文本时，NSMutableAttributedString 自己会把附加文本左侧的文本属性带过来。UITextView、YYTextView、其他富文本编辑器比如 MS Word 都是这个逻辑。

如果你希望设置字体，那可以在 attachment 上也加上属性、或者在 appendAttributeString 后全部设置一遍。

**Comment by leibaozai** [comment]
我在换行那里再次设置了字体，解决了问题，非常感谢热心解答。

**Comment by leibaozai** [comment]
不知道为什么现在每次加载UIImageView会留白，要过10几秒才会出现图片。但是我直接加载UIImage就是秒出现。我有回到主线程刷新UI，不知打是不是你说的异步排版和渲染的问题。但是在YYTextView没有YYLable的displaysAsynchronously属性，我该怎么办了？

**Comment by ibireme** [comment]
YYTextView 的操作全部都是在主线程进行的，没有异步排版等模式。

UIImage 是直接绘制成图片的，所以肯定能显示。UIImageView 是视图，如果你在非主线层操作了它，那会出现各种问题。

**Comment by leibaozai** [comment]
恩，非常感谢。（づ￣3￣）づ╭❤～，爱你，么么哒！我要给你生猴子，可惜我是男的。
