### ISSUE TITLE
YYLabel怎么识别内容中的链接呢

### ISSUE THREAD

**Issue by hackjie** [ibireme/YYText#194]
你好，现在我用YYLabel实现长按复制 和 点击链接效果，我想问的是YYLabel有自动识别url并返回所在位置，还是说需要手动正则识别，谢谢

**Comment by hackjie** [comment]
解决了，谢谢

**Comment by fengyunjue** [comment]
请问你是怎么解决的,能说下吗?

**Comment by hackjie** [comment]
in fact, apple had helped us to solve, use NSDataDetector class

**Comment by hackjie** [comment]
NSDataDetector

2016-03-17 17:49 GMT+08:00 fengyunjue <notifications@github.com>:
