### ISSUE TITLE
YYLable 支持在xib中设置属性后，直接动态在IB中更新吗？

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#197]
比如设置了text，text就直接在IB中绘制出来。

**Comment by wy19901227** [comment]
![image](https://cloud.githubusercontent.com/assets/8086633/13624304/c0716dc4-e5e7-11e5-84ab-4d273afbe7ef.png)

**Comment by wy19901227** [comment]
![image](https://cloud.githubusercontent.com/assets/8086633/13624387/86baecda-e5e8-11e5-9595-89a5777b27db.png)

**Comment by wy19901227** [comment]
![image](https://cloud.githubusercontent.com/assets/8086633/13624395/951fe5be-e5e8-11e5-9db6-2111cda989d1.png)

**Comment by ibireme** [comment]
<img width="573" alt="snapshot" src="https://cloud.githubusercontent.com/assets/839283/13625003/38209ef2-e5ee-11e5-9f2b-f5109c17f195.png">

YYText 最新版（1.0.1）开始支持 Interface Builder。

**Comment by wy19901227** [comment]
我这个不是最新版吗？还是你没发布？

发自我的 iPhone

**Comment by ibireme** [comment]
你可以检查一下你本地的版本号。

**Comment by wy19901227** [comment]
是1.01呢，支持在xcode设置属性，但是就是不行

发自我的 iPhone

**Comment by ibireme** [comment]
清空一下 Xcode 缓存，如果还报错，可以看一下错误日志。

**Comment by wy19901227** [comment]
清空过了，错误信息请看上边的图片

发自我的 iPhone

**Comment by ibireme** [comment]
如果本地代码是 YYText 1.0.1，那就不是 YYText 的错误了。

你应该先搜一下上面的错误信息，这可能是 CocoaPods 或者 Xcode 的问题：
http://stackoverflow.com/questions/28391112/interface-builder-failed-to-load-designables-from-path-null
http://stackoverflow.com/questions/28204108/ib-designables-failed-to-update-auto-layout-status-failed-to-load-designables

**Comment by wy19901227** [comment]
嗯，tks.我的xcode是7.2

发自我的 iPhone

**Comment by wy19901227** [comment]
你的yykit也是通过pod还是直接拖进去的呢？

发自我的 iPhone

**Comment by ibireme** [comment]
我都测试过，没有问题。

**Comment by wy19901227** [comment]
pod中需要写use_frameworke吗

发自我的 iPhone

**Comment by wy19901227** [comment]
这样吧  ，你可以发个demo给我吧，我看下我这里能显示不，发我邮箱吧。936788507@qq.com.
谢谢你了。

**Comment by ibireme** [comment]
这里面的 YYTextDemo 就可以，打开后直接创建一个 UIViewController with xib 就没问题。

**Comment by wy19901227** [comment]
我重新建了个工程，podYYKit，用xib，YYLabel是可以在ib中绘制的，但是我在我项目中pod就是不行呢。。。。。。为什么呢。。。

**Comment by wy19901227** [comment]
直接拖进去的话  也不行。。

**Comment by wy19901227** [comment]
可以把你直接拖进去  可以的 demo发我吗

**Comment by wy19901227** [comment]
我在你的YYText demo中是可以的，在我项目中是不ok得，，。。。。所以麻烦 你在一个项目中拖入，看能遇到和我一样的问题吗？

**Comment by CantChat** [comment]
层主你也太懒了吧，遇到问题伸手党可不行，请人帮忙也不带这样的。。。
同遇到这个问题，在podfile的platform下一行添加了use_framework!，再pod update一下，就ok了！
之后输入text或者placeholder，直接就可以看到效果
