### ISSUE TITLE
YYTextView现在支持autolayout了吗?

### ISSUE THREAD

**Issue by xialisuper** [ibireme/YYText#198]
我使用Masonry布局,使用系统的UITextView可以正常显示,如果使用YYTextView高度就是0.
是不是不支持? 还是需要用YYTextLayout计算一次高度?

**Comment by ibireme** [comment]
你的 UITextView 是怎么配合 Masonry 用的？

**Comment by xialisuper** [comment]
我把UITextView放在cell里,上下左右间距都是0. 给UITextView设置text内容和字体,文字显示cell高度,没有什么问题.
把UITextView幻化成YYTextView就不显示文字. 高度是0.

**Comment by xialisuper** [comment]
//正文
    [_contentTextView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(_textView.mas_top).offset(titleMargin);
        make.left.equalTo(_textView.mas_left).offset(titleMargin);
        make.right.equalTo(_textView.mas_right).offset(-titleMargin);
        make.bottom.equalTo(_textView.mas_bottom).offset(-titleMargin);
        self.textViewHeight = make.height.with.priorityHigh();
    }];

 //正文
    NSMutableAttributedString *contentString = [[NSMutableAttributedString alloc] initWithString:replyModel.content];
    //字体大小
    [contentString addAttribute:NSFontAttributeName value:[UIFont systemFontOfSize:timeLabelFont] range:NSMakeRange(0, replyModel.content.length)];
    //文字高度
    CGSize size = CGSizeMake(XLQscreenWidth - 2 * titleMargin, CGFLOAT_MAX);
    YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:size text:contentString];
    self.textViewHeight.offset = layout.textBoundingSize.height;
    self.contentTextView.attributedText = contentString;


刚刚补充了高度的优先级,在赋值之后计算了高度赋值给高度约束的offset 这样就没事儿了.不知道是不是这样使用.暂时没有发现什么问题.
