### ISSUE TITLE
YYTextView设置的属性，在输入文字时会被清除

### ISSUE THREAD

**Issue by matthewyan** [ibireme/YYText#20]
调试时发现：

- (void)setMarkedText:(NSString *)markedText selectedRange:(NSRange)selectedRange {
    [self _updateIfNeeded];
    [self _endTouchTracking];
    [self _hideMenu];
    
    if (!NSEqualRanges(_lastTypeRange, _selectedTextRange.asRange)) {
        [self _saveToUndoStack];
        [self _resetRedoStack];
    }
    
    BOOL needApplyHolderAttribute = NO;
    if (_innerText.length > 0) {
        [self _updateAttributesHolder];  // 这儿，会将设置的属性重置为前面文字的属性
    } else {
        needApplyHolderAttribute = YES;
    }

这样会导致手动设置的属性被重置，不知道是不是故意这样设计的？

**Comment by ibireme** [comment]
确实和头文件注释实现得不一样，但修改属性是在 _updateOuterProperties 里实现的，已经修改好了。

**Comment by matthewyan** [comment]
开始没有描述清楚，具体问题是这样的：

外部使用的时候，设置了typingAttributes，期望输入文字的时候可以应用这些Attribute。
而使用系统的中文输入法输入，触发了-(void)setMarkedText:(NSString *)markedText selectedRange:(NSRange)selectedRange这个函数，其中_updateAttributesHolder会把typingAttributesHolder重置为前一个字符的属性。
这样外部设置的typingAttributes就被覆盖了。

![25932356-6c99-4a3d-9160-da45bc617f4e](https://cloud.githubusercontent.com/assets/8739896/11260520/0915c932-8ea7-11e5-88d3-7909f1a3f649.png)

**Comment by ibireme** [comment]
明白了，我试着改一下。

**Comment by ibireme** [comment]
已修改，请更新代码或 pod 再试试～

**Comment by matthewyan** [comment]
thanks, 验证ok
