### ISSUE TITLE
YYTextView支持富文本编辑吗

### ISSUE THREAD

**Issue by lexiaoyao20** [ibireme/YYText#200]
如题，YYTextView可以支持类似于新浪微博的头条文章那样的富文本编辑吗，比如大小标题，无序列表，引用 这些功能

**Comment by ibireme** [comment]
YYTextView 支持 NSAttributedString 富文本显示与编辑，可用属性见 Readme。至于如何操作 NSAttributedString 这个需要开发者自己实现。 

另外，微博头条的编辑，是由多个 TextView 组合实现的，这用 UITextView 或 YYTextView 都能实现。

**Comment by lexiaoyao20** [comment]
我抓包了下新浪微博头条文章，它那边是转成的html标签传到服务端的。比如，
```
{"title":"得意","content":"<h1>啊啊啊啊</h1>\n<h2>擦</h2>\n<p>\n<font color=\"#507daf\"><a href=\"http://www.baidu.com\">咋</a></font>\n</p>\n<blockquote>\n<font color=\"#939393\">黑</font>\n</blockquote>\n<ul><li>\n<font color=\"#333333\">mom</font>\n</li>\n<li>\n<font color=\"#333333\">now</font>\n</li>\n","cover":"883ab0aagw1f1qpvcm58jj20vf0hs0ss","summary":"额咯哦哦"}
```
不过我在这里找到了一个解决方案： https://github.com/nnhubbard/ZSSRichTextEditor
如果用UITextView或者YYTextView实现估计会比较麻烦

**Comment by ibireme** [comment]
单独一个 TextView 或者 ZSSRichTextEditor 是实现不了微博头条那样的效果的。

**Comment by lexiaoyao20** [comment]
嗯，我知道，
标题是一个TextView，
正文又是另外一个TextView，
导语也是一个TextView，
标题简单，主要是正文那里处理很复杂

**Comment by ibireme** [comment]
如果需要处理 HTML，我很推荐先用 ZSSRichTextEditor 试试。

**Comment by lexiaoyao20** [comment]
嗯，我明天试一下。 多谢大神解答~
