### ISSUE TITLE
用YYTextView做类似于发微博页面的问题

### ISSUE THREAD

**Issue by DaZuo** [ibireme/YYText#201]
我在textView上面添加了一个collectionView来承载图片，在编辑的时候修改了textView的contentSize，但是当contentSize的高大于整个textView的高且输入文字的光标的那一行要是没有字符输入的话，这个collectionView在屏幕下面，滚动不上来，当输入空格或者其他字符时则可以。求帮忙解决，谢谢

**Comment by ibireme** [comment]
你是说 [textView addSubView:collectionView] 这样的吗？

textView 继承自 scrollView，在内部文本有变动时，scrollView.contentSize 会自动改变，这个不应该在外部调整。。

**Comment by DaZuo** [comment]
```
- (void)textViewDidChange:(YYTextView *)textView {
    if (textView.textLayout.lines.count >= 4) {
        CGFloat maxY = CGRectGetMaxY(textView.textLayout.textBoundingRect) + 10;
        self.picturesCollectionView.top = MAX(maxY, 100);
    } else {
        self.picturesCollectionView.top = 100;
    }
}
```
我做了类似于这样的操作，当文字一多时，这个collectionView就在屏幕下面就出不来了。

**Comment by ibireme** [comment]
那当然了。。UIScrollView 本身就是这个逻辑啊。。改一下 textView.textContainerInset 呗。。

**Comment by DaZuo** [comment]
好的，谢谢了
