### ISSUE TITLE
使用 YYTextLayout 异步排版时如何设置文本垂直居中？

### ISSUE THREAD

**Issue by PrideChung** [ibireme/YYText#203]
我按照文档里面的方式在后台线程生成`YYTextLayout`对象，然后在主线程里面把这个对象直接赋值给`YYLabel`。由于调大了lineHeightMultiple参数，可以很明显地看见文字在垂直方向上是靠底部排列的，即时设置了`YYLabel`的`textVerticalAligment`属性为`center`也无效。`YYTextContainer`里面也找不到可以调整垂直对齐的参数。

**Comment by ibireme** [comment]
可以试试调整下 container insets。

**Comment by PrideChung** [comment]
我可以用lineSpacing达到类似的效果，只是没有直接一点的做法吗？

**Comment by ibireme** [comment]
![lineheightmultiple](https://cloud.githubusercontent.com/assets/839283/13669951/db49106e-e701-11e5-8b3f-1ee142540d12.png)
这是 lineheightmultiple，注意，第一行上面是额外多出来了一些空白。这些空白会被 layout 计算在内的。

![linespacing](https://cloud.githubusercontent.com/assets/839283/13669952/dc45de02-e701-11e5-826d-35b91b921667.png)
这是 linespacing，第一行上面没有空白。

正常情况下，vertical aligment 属性已经提供了一个足够精确的对齐点，如果还要再微调，那可以调节 container insets。

**Comment by PrideChung** [comment]
拜读了一下源码，发现YYLabel控制垂直居中是通过调整`YYTextLayout`的`[drawLayout drawInContext:context size:size point:point view:nil layer:nil debug:debug cancel:isCancelled];` 里面`point`的位置来实现的，怪不得没有生效，因为我的`YYLabel`的大小是紧贴它的`YYTextLayout`的`textBoundingSize`的。我的问题是，当调大了lineHeightMultiple之后，发现行高虽然变高了，但是文本绘制的位置还是紧贴在绘制区域的下方，导致文字的上方出现了大量空白。似乎`YYTextLinePositionModifier`也没法实现我想要的效果。

**Comment by ibireme** [comment]
![lineheightmultiple](https://cloud.githubusercontent.com/assets/839283/13693039/b65fdda2-e781-11e5-9245-abcf3f2dd63d.png)
lineHeightMultiple 本身会调整每行文本的`行高`属性，而行高是会在文本排版时计算进去的，效果见上面那张图。默认情况下，`行高` 属性是把文字包含起来的最小高度，而 `lineHeightMultiple` 会额外增加这个高度。这是调用者本身的意图，如果我把上面这个空白除去来计算，那会破坏调用者的意图。

如果你非要在 top、mid、bottom 这三种对齐方式上进行微调，那你可以用 container insets 为文本额外增加你指定的边缘留白。

![linespacing](https://cloud.githubusercontent.com/assets/839283/13693041/bde39014-e781-11e5-909c-19b1bf0a58a5.png)
lineSpacing 是调整的`行间距`，这个空白本身是无关文本内容的，这不会影响视觉效果。

**Comment by PrideChung** [comment]
多谢解答。在生成`YYTextLayout`时调整`YYTextContainer`的`contentInsets`应该可以就可以达到我的目的了。
