### ISSUE TITLE
用YYText加载动态表情，有时候会加载不出来

### ISSUE THREAD

**Issue by zhouzizi** [ibireme/YYText#204]
![image](https://cloud.githubusercontent.com/assets/9103749/13666329/efbabcc0-e6eb-11e5-9609-31a487f0625f.png)
在tableview中，有时候显示有时候不显示
![image](https://cloud.githubusercontent.com/assets/9103749/13666470/a6cb7918-e6ec-11e5-9091-fcba4b3f0374.png)
![image](https://cloud.githubusercontent.com/assets/9103749/13666480/b6e3997a-e6ec-11e5-9500-9bfbca3e6db9.png)

**Comment by ibireme** [comment]
YYText 版本、系统版本、相关代码和调用线程？

**Comment by zhouzizi** [comment]
好像是我没在主线程调用引起的

**Comment by zhouzizi** [comment]
我改成主线程还是会不显示。系统版本10.11.1 (15B42)，xcode版本Version 7.3 beta (7D111g)，YYText版本不知道怎么查看。。代码调用的地方是在tableviewcell中，直接对YYLabel的attributedText赋值

**Comment by ibireme** [comment]
如果是 CocoaPods 安装的，那看一下 Podfile.lock 文件里的版本号；如果是手动安装的，那更新代码到最新看看。

如果最新代码还有问题，那开启一下 Debug 看看：

    YYTextDebugOption *debugOptions = [YYTextDebugOption new];
    debugOptions.baselineColor = [UIColor redColor];
    debugOptions.CTFrameBorderColor = [UIColor redColor];
    debugOptions.CTLineFillColor = [UIColor colorWithRed:0.000 green:0.463 blue:1.000 alpha:0.180];
    debugOptions.CGGlyphBorderColor = [UIColor colorWithRed:1.000 green:0.524 blue:0.000 alpha:0.200];
    [YYTextDebugOption setSharedDebugOption:debugOptions];

另外，确认一下所有的与 UIView 相关的操作（比如 UIImageView 的创建和修改、Attachment 的赋值等）都是在主线程进行的。

**Comment by zhouzizi** [comment]
是的，确认过后，YYText也是最新的，但还是会出现
![ebfcecaca78ef73386bb6c4a0e931e45](https://cloud.githubusercontent.com/assets/9103749/13721711/60159b42-e869-11e5-86e5-add347b0d45e.png)

![0c592d143a43aaf152912ebc2826614f](https://cloud.githubusercontent.com/assets/9103749/13721713/670bd452-e869-11e5-99e8-502de7659445.png)

**Comment by ibireme** [comment]
贴一下使用 YYLabel 相关的代码和复现过程吧。。

**Comment by zhouzizi** [comment]
![image](https://cloud.githubusercontent.com/assets/9103749/13721943/64ce855c-e870-11e5-94a7-4b9167f7130b.png)
![image](https://cloud.githubusercontent.com/assets/9103749/13721945/6cfe064e-e870-11e5-925c-3770b4c9839c.png)
![image](https://cloud.githubusercontent.com/assets/9103749/13721949/7f358b98-e870-11e5-8e1f-0e1aa781f035.png)

**Comment by ibireme** [comment]
呃。。我想问 YYLabel 的使用代码和问题的复现过程。。
比如说  YYLabel 是如何创建、如何设置属性的，问题是如何复现的。。
另外，那个 UIImageEmoticon 是什么东西。。

**Comment by zhouzizi** [comment]
YYLabel是在Xib中创建的。
![image](https://cloud.githubusercontent.com/assets/9103749/13722200/43bbf57c-e878-11e5-82a5-f68969b84b42.png)

赋值属性设置都是在主线程中
![image](https://cloud.githubusercontent.com/assets/9103749/13722230/554a92de-e879-11e5-9b6d-9783fe19a6f7.png)

**Comment by ibireme** [comment]
1. YYLabel 是如何创建的，它的属性是什么，是否启用了异步绘制。
2. YYLabel 是如何使用的，比如说 Cell 被复用时，是否有多余或者重复的赋值过程。
3. UIImageEmoticon 是什么，返回了什么样的对象。

如果没有开启异步绘制，并且逻辑都是在主线程使用的，那就是 Cell 复用的过程或其它地方的逻辑有问题。

**Comment by ibireme** [comment]
如果有新进展可以 Reopen 来继续讨论。

**Comment by zhouzhongguang** [comment]
兄弟，请问你的问题解决了吗
我也遇到了同样的问题，想请教一下

**Comment by zhouzhongguang** [comment]
@zhouzizi 
兄弟，你的问题解决了吗
我也遇到了同样的问题，想请教下
