### ISSUE TITLE
求助：图文混编的时候，能单独给图片绑定事件吗

### ISSUE THREAD

**Issue by heqichang** [ibireme/YYText#205]
图片想单独点击进入图片浏览模式

**Comment by ibireme** [comment]
可以给那个位置的 NSAttribuedString 添加一个 YYTextHighlight 属性；
也可以把图片换成 UIImageView，并在上面天假 gesture。

**Comment by heqichang** [comment]
赞！回复的真速度，用 highlight 的 tapaction 解决了
