### ISSUE TITLE
YYText能控制图片大小吗？

### ISSUE THREAD

**Issue by bamaocc** [ibireme/YYText#207]
怎样控制自定义表情的大小？[NSMutableAttributedString yy_attachmentStringWithContent:image contentMode:UIViewContentModeCenter attachmentSize:CGSizeMake(5, 20) alignToFont:[UIFont systemFontOfSize:14] alignment:YYTextVerticalAlignmentCenter];设置attachmentSize貌似只能控制高度

**Comment by ibireme** [comment]
改一下 contentMode
