### ISSUE TITLE
textview中的placeholder只要包含数字、字母、或者符号都显示不出来

### ISSUE THREAD

**Issue by SawyerEve** [ibireme/YYText#209]
![03141](https://cloud.githubusercontent.com/assets/13621650/13734873/80b77968-e9dd-11e5-8e7e-3c8c561c41f7.png)

**Comment by SawyerEve** [comment]
![03142](https://cloud.githubusercontent.com/assets/13621650/13734879/966da3ea-e9dd-11e5-81b2-4832a12b2263.png)

**Comment by ibireme** [comment]
当 placeholder 文本的排版高度大于 TextView 的高度时，这一行会显示不出来。。（中文字体的高度要小于英文字体，所以你这里刚刚好能显示中文而显示不了英文／数字）。

调整一下 TextView 的高度，或者设置一下 textInsets 看看。

**Comment by SawyerEve** [comment]
升高两个像素后确实可以了，感谢指正~
