### ISSUE TITLE
怎么给 YYLabel  追加一个下标？？

### ISSUE THREAD

**Issue by FengDeng** [ibireme/YYText#21]

**Comment by ibireme** [comment]
目前 YYText 还不支持上下标。
一个临时的解决方案是，通过 YYTextGlyphTransform 属性，为对应上下标字符添加形变和位移。
另一个临时的解决方案是，把上下标写成一个 Label，然后当作 Attachment 添加到字符串中。

**Comment by FengDeng** [comment]
谢了哈  我用了系统的直接返回属性字符串 已经解决了。你这个YYText很好用。
