### ISSUE TITLE
异步排版中关于网络加载图片的问题

### ISSUE THREAD

**Issue by lishuanghenu** [ibireme/YYText#210]
您好,我想问下关于异步加载时 图文混排是怎么实现的呢

**Comment by ibireme** [comment]
和一般使用没有区别。
只是注意下，创建和修改 UIView 相关的操作保证在主线程就行。

**Comment by lishuanghenu** [comment]
谢谢你这么快回复我啊 我可能没说清楚 我说的意思是图片是异步加载的 而且我要在图片上添加手势 uiimageview的创建肯定要在主线程 但是textlayout的创建要在子线程 我怎么样去找到图片的位置呢 而且还有一个问题是textlayout相关的 我发现我同一段代码 两个相同的yylabel子类产生的textlayout高度是不一样的

**Comment by lishuanghenu** [comment]
哦哦哦 第二个问题我找到原因了 麻烦了 第一个还在思考中

**Comment by ibireme** [comment]
如果是静态图片，那可以直接用  UIImage 来创建 Attachment。点击事件添加一个 textHighlight。
如果是动态图片，或者网络图片，可以参考下这块儿的代码：https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/WBStatusLayout.m#L67-L93

**Comment by lishuanghenu** [comment]
恩恩 我仔细看看 谢谢你啦
