### ISSUE TITLE
-[UIApplication _runWithMainScene:transitionContext:completion:]崩溃问题

### ISSUE THREAD

**Issue by yybutcher** [ibireme/YYText#211]
在设定 RootViewController时，如果RootViewController上面有一个 YYTextView，则程序崩溃。

1. 新建一个工程
2. cocoapod YYKit
3. 在 Main.storyboard中的 ViewController类对应的试图中 拖入一个 UIVew，Class设置成 YYTextView
4. 运行程序

环境： iOS9 Xcode Version 7.2.1 (7C1002)

**Comment by yybutcher** [comment]
我看到你之前解决了问题，但是我使用cocoapod 安装YYKit后(1.0.1)，YYTextEffectWindow这个文件并未更改！

**Comment by ibireme** [comment]
还没更新到 CocoaPods。

**Comment by ibireme** [comment]
今晚更新。先关闭问题。
