### ISSUE TITLE
Attributed string doesn't use YYLabel font as default value

### ISSUE THREAD

**Issue by vox-humana** [ibireme/YYText#212]
1. Set YYLabel font value.
2. Set attributed string value (without NSFontAttributeName property and empty yy_font).
3. Font value from YYLabel doesn't apply to result text.

UILabel use its own font value in this case.
Changing order of 1 and 2 points fix the problem.

**Comment by ibireme** [comment]
Set a new value to `attributedText` property also replaces the value of the `text`, `font`, `textColor`,
 `textAlignment` and other properties in label.

See: https://github.com/ibireme/YYText/blob/master/YYText/YYLabel.h#L104-L112

**Comment by vox-humana** [comment]
Yes, if these values from `attributedText` are not nil, everything works fine. But what if user wants to set default value to `font`, `textColor` or `textAlignment`? Main problem is difference between `YYLabel` and `UILabel` behaviours. I'm not sure, whether is a real problem or kind of side effect.

**Comment by ibireme** [comment]
NSMutableAttributedString *text = [[NSMutableAttributedString alloc] initWithString:@"123"];
    
    YYLabel *l1 = [YYLabel new];
    UILabel *l2 = [UILabel new];
    
    l1.font = [UIFont systemFontOfSize:30];
    l2.font = [UIFont systemFontOfSize:30];
    
    l1.attributedText = text;
    l2.attributedText = text;
    
    l1.attributedText.yy_font; // -> nil
    l2.attributedText.yy_font; // -> nil
    
    l1.font; // -> Helvetica 17
    l2.font; // -> Helvetica 100

So `UILabel`'s content is not same as the `label.attributedText`, and I think it's not a good beheaver...
