### ISSUE TITLE
YYTextUtilities.h中计算表情的YYTextEmojiGetDescentWithFontSize方法，是根据什么来计算的呢？

### ISSUE THREAD

**Issue by DeepMissea** [ibireme/YYText#218]
比如
static inline CGFloat YYTextEmojiGetDescentWithFontSize(CGFloat fontSize) {
    if (fontSize < 16) {
        return 0.390625 * fontSize;
    } else if (16 <= fontSize && fontSize <= 24) {
        return 0.15625 * fontSize + 3.75;
    } else {
        return 0.3125 * fontSize;
    }
    return 0;
}

这里面的小数是怎么算出来的？看到这一脸懵逼。。忘告知。。

**Comment by ibireme** [comment]
这是 `AppleColorEmoji` 的属性。
一般字体，ascent、descent 和字号是呈线性关系的，但 `AppleColorEmoji` 的这几个值和字号之间的关系就比较奇怪了。这里的数字是我创建不同字号的 `AppleColorEmoji` 字体，然后计算和字号的函数关系得到的。

**Comment by DeepMissea** [comment]
噢，就是说字号小于16时的线性关系是balabala，字号在16到24之间的是balabala，字号大于24的又是balabalabala。那也就是说你是把字号从1到至少是30以后的字号全列出来，然后计算他们的比例，得到的数据？我理解的对么？

**Comment by ibireme** [comment]
是的。

**Comment by DeepMissea** [comment]
谢谢
