### ISSUE TITLE
为什么同样的字体普通文字和系统emoji算出来高度不一样

### ISSUE THREAD

**Issue by ufosky** [ibireme/YYText#219]
我通过YYTextLayout计算文字布局，但是当文字里面只有emoji的时候上下有一些空白，不普通文字要高，导致整个排版不是很美观

**Comment by ufosky** [comment]
我尝试通过实现YYTextLinePositionModifier来改变，但是这样计算出来宽高后，到显示的时候重新计算布局，发现此时通过得到的size用coretext计算显示不了那么多行文字，这个回调方法得到的lines比之前计算布局时少了
```
- (void)modifyLines:(NSArray *)lines fromText:(NSAttributedString *)text inContainer:(YYTextContainer *)container
```

**Comment by ibireme** [comment]
Emoji 的 ascent、descent 确实是比一般字体要大。

用 YYTextLinePositionModifier 的时候，如果用 label.textLayout 来设置，那是没问题的。如果是用 label.attributedText 设置，那还需要额外设置一下 label.linePositionModifier。
