### ISSUE TITLE
YYText复制粘贴，联想输入的问题

### ISSUE THREAD

**Issue by tianyig** [ibireme/YYText#220]
这个库很好用，感谢作者。提几个使用时遇到的问题。
1.复制粘贴问题。
现象描述：从系统空间拷贝一段文字，不能粘贴到YYTextView上。
调试源代码发现YYTextView里面paste函数实现是从UIPasteboard取出p.yy_AttributedString,这个应该是没有考虑到从系统控件拷贝粘贴到YYTextView的问题。我目前修改的办法是取p.yy_AttributedString，如果为空，取p.string。
2.联想输入的问题。
现象描述：输入联想英文时如果先输入一个N，从联想板上选择Now，光标会跳到No字母的后面，而不是Now的后面。
经过调试源代码应该是- (YYTextRange *)_correctedTextRange:(YYTextRange *)range；判断时没有考虑到联想输入。
3.三方输入法联想输入的问题。
现象描述：使用搜狗输入法英文输入状态下输入NK,从联想板上选择NKOTB，输入nkNKOTB。期望NKOTB。这个使用系统输入控件无问题。
调试发现系统输入法联想调用了KeyBoardImpl AutoCorrect方法，这个又调用了YYTextView的replaceRange:withText。但是使用搜狗输入法联想时调用的insertText。

**Comment by ibireme** [comment]
1. 复制粘贴是没问题的，我在各个系统版本的真机和模拟器测试过。代码中，如果富文本没取到，那会用纯文本代替的：https://github.com/ibireme/YYText/blob/master/YYText/YYTextView.m#L2990-L2995

2. 系统键盘的联想是没问题的，这个我也在各个系统版本的真机和模拟器测试过。

3. 搜狗和百度输入法的英文联想是已知问题，具体讨论见这个 Issues 最底部的回答：https://github.com/ibireme/YYText/issues/89 。
