### ISSUE TITLE
InputView失效

### ISSUE THREAD

**Issue by BaeCheung** [ibireme/YYText#221]
在iOS8及以上的设备，弹一个UIActionSheet后再去修改textView的inputView，无论怎么reloadInputViews都无效。但是把UIActionSheet改成UIAlertController，是能够刷新的。。

**Comment by ibireme** [comment]
`If set the value while first responder, it will not take effect until 'reloadInputViews' is called.`

实际上 `inputView` 这个属性是由系统提供支持的，如果当前视图不是 firstResponder，那就不起作用了。UIActionSheet 有可能会修改 keyWindow 或是 firstResponder。

**Comment by BaeCheung** [comment]
@ibireme 但是即使我执行becomeFirstResponder后再进行reloadInputViews一样是无效的；替换成UITextView后一切正常，并不受UIActionSheet的影响

**Comment by ibireme** [comment]
看看 becomeFirstResponder 是否返回了 YES，textView.isFirstResponder 是否是 YES。

另外，`inputView` 这个属性的逻辑并不是 YYTextView 负责的，如果这个表现有什么问题，我这边也是无法控制的。。。
