### ISSUE TITLE
YYTextView怎么设置输入问题的行间距

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#222]

**Comment by ibireme** [comment]
和 UITextView 一样。
修改 attributed text 或者 typing attributes.

**Comment by wy19901227** [comment]
具体代码呢？UITextView也支持设置字体行间距吗？

发自我的 iPhone

**Comment by ibireme** [comment]
这个。。网上一搜一大堆啊。。"UITextView 行间距"

**Comment by wy19901227** [comment]
要在代理里打一个字设置一下吗？我以为有个什么属性直接搞定呢。。

发自我的 iPhone

**Comment by ibireme** [comment]
所以说可以直接设置一下 `typingAttributes` 那个属性啊，里面加上个 paragraph style。

**Comment by wy19901227** [comment]
keyw是什么

发自我的 iPhone

**Comment by wy19901227** [comment]
NSMutableParagraphStyle *paragraphStyle = [[NSMutableParagraphStyle alloc] init];
    paragraphStyle.lineSpacing = 10;// 字体的行间距
    
    NSDictionary *attributes = @{
                                 NSFontAttributeName:[UIFont systemFontOfSize:14],
                                 NSParagraphStyleAttributeName:paragraphStyle
                                 };

    _textView.typingAttributes=attributes;
 OK，供大家参考。
