### ISSUE TITLE
ImageView 点击放大后无法点击返回

### ISSUE THREAD

**Issue by tangqi92** [ibireme/YYText#224]
ibireme 你好，

我在使用 YYTextView 时，给图片添加了 UITapGestureRecognizer 点击事件，当我点击放大后，再次点击希望缩回原图时，出现了如图情况，暂时不知道是什么原因导致的。（翻看了历史 Issues 没有发现和我情况相似的），不知道是不是自己写错了...

![simulator screen shot mar 16 2016 9 39 52 pm](https://cloud.githubusercontent.com/assets/10348598/13814528/91884e80-ebc1-11e5-83ba-59486593700b.png)

**Comment by ibireme** [comment]
查一下，放大后，点击事件是否穿透到了 UITextView 上。如果UITextView 上有点击事件，那就会弹出键盘了。

另外，弹出后，可以调用 textView.editable = NO 来临时禁用编辑。

**Comment by tangqi92** [comment]
你好，

是穿透了，然后，我在图片放大后 调用 textView.editable = NO 来临时禁用编辑，但仍然没用。

下面是我自定义点击放大缩小的 ImageView 相关代码，请你看下是否有问题。（iOS 新人还请谅解）

**Comment by tangqi92** [comment]
//
//  QTClickImageView.m
//  Voice2Note
//
//  Created by Tang Qi on 3/16/16.
//  Copyright © 2016 jinxing. All rights reserved.
//

#import "NoteEditViewController.h"
#import "QTClickImageView.h"
#import "YYTextView.h"

#define SCREEN_WIDTH [UIScreen mainScreen].bounds.size.width
#define SCREEN_HEIGHT [UIScreen mainScreen].bounds.size.height
static float kDuration = 0.3;

@interface QTClickImageView () <UIGestureRecognizerDelegate, UIScrollViewDelegate> {
    // 用于按屏幕比例缩放图像
    UIView *containerView;
    // 用于保存缩放的图像
    UIView *snapShotView;
    // 利用 ScrollView 的缩放功能来缩放图像
    UIScrollView *containerScrollView;
    // 保存放大前原始图像在 Window 上的坐标
    CGRect originImageRect;
    // 设置动画时间
    CGFloat duration;
}

@end

@implementation QTClickImageView

/**
 *  StoryBoard 中初始化
 */

- (instancetype)initWithCoder:(NSCoder *)aDecoder {
    self = [super initWithCoder:aDecoder];
    if (self) {
        // 允许交互
        self.userInteractionEnabled = YES;
        // 为 UIImageView 添加点击手势
        UITapGestureRecognizer *tapGesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(tapImage:)];
        tapGesture.numberOfTapsRequired = 1;
        tapGesture.delegate = self;
        [self addGestureRecognizer:tapGesture];
        // 初始化时间
        duration = kDuration;
    }
    return self;
}

- (instancetype)initWithFrame:(CGRect)frame {
    self = [super initWithFrame:frame];
    if (self) {
        self.userInteractionEnabled = YES;
        // 为 UIImageView 添加点击手势
        UITapGestureRecognizer *tapGesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(tapImage:)];
        tapGesture.numberOfTapsRequired = 1;
        tapGesture.delegate = self;
        [self addGestureRecognizer:tapGesture];
        // 初始化时间
        duration = kDuration;
    }
    return self;
}

- (instancetype)initWithImage:(UIImage *)image {
    self = [super initWithImage:image];
    if (self) {
        self.userInteractionEnabled = YES;
        // 为 UIImageView 添加点击手势
        UITapGestureRecognizer *tapGesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(tapImage:)];
        tapGesture.numberOfTapsRequired = 1;
        tapGesture.delegate = self;
        [self addGestureRecognizer:tapGesture];
        // 初始化时间
        duration = kDuration;
    }
    return self;
}

- (void)tapImage:(UITapGestureRecognizer *)sender {

    [self showImage:(UIImageView *) sender.view];
}

- (void)showImage:(UIImageView *)originImageView {
    
    UIWindow *window = [UIApplication sharedApplication].keyWindow;

    // 获取当前显示的 image
    UIImage *image = originImageView.image;
    // 将 imageview 的坐标转换到屏幕上的坐标位置
    originImageRect = [originImageView convertRect:originImageView.bounds toView:window];

    // 添加容器 containerScrollView
    containerScrollView = [[UIScrollView alloc] initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT)];
    containerScrollView.delegate = self;
    // 设置最大伸缩比例
    containerScrollView.maximumZoomScale = 3.0;
    // 添加容器 containerView, 用于缩放
    // 若图像的大小比例不是屏幕的大小，若直接缩放图像，缩放的时候会有位移偏差
    containerView = [UIView new];
    containerView.frame = containerScrollView.frame;
    containerView.backgroundColor = [UIColor colorWithRed:0 green:0 blue:0 alpha:0];
    // 用于缩放的方法
    snapShotView = [self snapshotViewAfterScreenUpdates:NO];
    snapShotView.frame = originImageRect;
    // 加载到屏幕上
    [containerView addSubview:snapShotView];
    [containerScrollView addSubview:containerView];
    [window addSubview:containerScrollView];
    // 添加全局手势，点击缩小回原位
    self.alpha = 0;

    // 移动到屏幕中央
    CGFloat rate = SCREEN_WIDTH / image.size.width;
    CGRect finalRect = CGRectMake(1, (SCREEN_HEIGHT - image.size.height * rate) / 2, SCREEN_WIDTH, image.size.height * rate);
    // 动画显示
    [UIWindow animateWithDuration:duration delay:0 usingSpringWithDamping:0.7 initialSpringVelocity:0 options:UIViewAnimationOptionCurveEaseInOut animations:^{
        snapShotView.frame = finalRect;
        containerScrollView.backgroundColor = [UIColor colorWithRed:0 green:0 blue:0 alpha:1.0];
    }
        completion:^(BOOL finished) {
            // 隐藏状态栏
            [UIApplication.sharedApplication setStatusBarHidden:true withAnimation:UIStatusBarAnimationSlide];
            YYTextView *yy = (YYTextView *) [self superview];
            if (yy) {
                yy.editable = NO;
                UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(hideImage:)];
                tap.numberOfTapsRequired = 1;
                tap.delegate = self;
                [containerScrollView addGestureRecognizer:tap];
            }

        }];
}

- (void)hideImage:(UITapGestureRecognizer *)tap {
    [UIApplication.sharedApplication setStatusBarHidden:false withAnimation:UIStatusBarAnimationNone];
    [UIView animateWithDuration:duration delay:0 usingSpringWithDamping:0.7 initialSpringVelocity:0 options:UIViewAnimationOptionCurveEaseInOut animations:^{
        // 缩放到原始大小时，必须同时缩放到原始的倍率，否则放大的情况位置偏移
        containerScrollView.zoomScale = 1.0f;
        snapShotView.frame = originImageRect;
        containerScrollView.backgroundColor = [UIColor colorWithRed:0 green:0 blue:0 alpha:0];
    }
        completion:^(BOOL finished) {
            self.alpha = 1;
            [containerScrollView removeFromSuperview];
            YYTextView *yy = (YYTextView *) [self superview];
            if (yy) {
                yy.editable = YES;
            }
        }];
}

- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch {
    if ([touch.view isKindOfClass:[UIImageView class]]) {
        return YES;
    } else {
        return NO;
    }
}

#pragma mark - UIScrollView Delegate
- (UIView *)viewForZoomingInScrollView:(UIScrollView *)scrollView {
    // 缩放容器 containerView
    return containerView;
}

@end

**Comment by ibireme** [comment]
[self showImage:(UIImageView *) sender.view];

如果用这个方法，把 imageView 添加到 UITextView 上，那可能出问题。

    UIWindow *window = [UIApplication sharedApplication].keyWindow;

如果用这个方法，取到的 keyWindow 可能是 YYTextView 自带的 Window。

**Comment by tangqi92** [comment]
感谢回复。

所以，像我这种需求，该如何解决呢？（我插入一张图片，然后希望能点击放大查看，再次点击缩回）

还请指点下，谢

**Comment by ibireme** [comment]
一般展示时，可以单独创建一个 UIViewController 来展示，或者添加到 App 本身的 Window。

**Comment by ibireme** [comment]
一般 App 本身的 Window 是 [UIApplication sharedApplication].windows[0]; 当然如果你在 AppDeleaget 里有明确的引用那更好。

**Comment by tangqi92** [comment]
OK~懂了 

十分感谢你的回复！

**Comment by tangqi92** [comment]
感谢！

```objective-c
UIWindow *window = [UIApplication sharedApplication].keyWindow;
```

问题就出在这里，改用 [UIApplication sharedApplication].windows[0];  便可以了！
