### ISSUE TITLE
调起键盘之后uiwindow覆盖UITextEffectsWindow 

### ISSUE THREAD

**Issue by qylibohao** [ibireme/YYText#225]
我用yykit做发帖控件，发完贴自后uiwindow覆盖了UITextEffectsWindow，导致退出发帖后屏幕覆盖一层view无法点击我的控件了。请问下如何设置不要覆盖

**Comment by ibireme** [comment]
YYText 中，只用到了一个自定义的 UIWindow（YYTextEffectWindow），并且是不处理触摸事件的：
https://github.com/ibireme/YYText/blob/master/YYText/Component/YYTextEffectWindow.m#L37

你可以检查下你在使用 UIWindow 时是否存在问题（比如获取 App Window 时错误的取到了最上方的 Window）。

**Comment by qylibohao** [comment]
恩，知道了，我添加的空间调用 [uiapplication shareapplication].keywindow 函数，导致添加到yytexteffectwindow上面去了，
