### ISSUE TITLE
请教一下有详细的文档资料吗

### ISSUE THREAD

**Issue by am1993421** [ibireme/YYText#226]

**Comment by am1993421** [comment]
如果一段text里面有很多不一样的表情 我在不确定有哪些表情的情况下 如何展示这段文字呢？
YYTextSimpleEmoticonParser *parser = [YYTextSimpleEmoticonParser new];
NSMutableDictionary *mapper = [NSMutableDictionary new];
mapper[@":smile:"] = [UIImage imageNamed:@"smile.png"];
mapper[@":cool:"] = [UIImage imageNamed:@"cool.png"];
mapper[@":cry:"] = [UIImage imageNamed:@"cry.png"];
mapper[@":wink:"] = [UIImage imageNamed:@"wink.png"];
parser.emoticonMapper = mapper;
看到你这里是这样写的 有没有其他的方法呢？

**Comment by ibireme** [comment]
完整文档：http://cocoadocs.org/docsets/YYText/

表情这块儿，其实可以完全不用 parser，手动解析并创建 NSAttributedString 就行。

**Comment by am1993421** [comment]
额....请问这一块有示例的代码吗？不太知道该怎样做。谢谢

**Comment by ibireme** [comment]
Readme 里有：https://github.com/ibireme/YYText#图文混排

YYTextSimpleEmotionParser 本身的实现代码就很简单，可以做参考。另外可以参考下这个：https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/WBStatusLayout.m#L707-L717
