### ISSUE TITLE
crash in iOS7.1 because of YYTextRubyAnnotation

### ISSUE THREAD

**Issue by Testman231** [ibireme/YYText#227]
Dyld Error Message:
  Symbol not found: _CTRubyAnnotationCreate

**Comment by ibireme** [comment]
- (nullable CTRubyAnnotationRef)CTRubyAnnotation CF_RETURNS_RETAINED NS_AVAILABLE_IOS(8_0);

It's available since iOS 8.0.

**Comment by Nomeqc** [comment]
不是说支持到7.0嘛..

**Comment by ibireme** [comment]
YYText 最低支持到 6.0，但是这个属性是从 8.0 开始支持的。

就像 NSLayoutConstraint 是从 6.0 开始支持的，但它的 `active` 是从 8.0 开始支持的。

**Comment by fangborui** [comment]
所以怎么解决这个问题呢 iOS7的设备跑起来会直接crash

**Comment by ibireme** [comment]
和一般做老版本兼容一样。。根据版本号判断就行。

**Comment by fangborui** [comment]
关键是我没有用到它 在开机的的dylb线程里就挂了

**Comment by ibireme** [comment]
是不是代码版本太旧？还是安装方式不对？
我在 iPad iOS 7.2 上未复现。。

**Comment by zhongjiezhe** [comment]
dyld`dyld_fatal_error:
dyld: Symbol not found: _CTRubyAnnotationCreate
接上面问题系统版本是是7.1.1,开机的时候直接挂
<img width="339" alt="crash" src="https://cloud.githubusercontent.com/assets/12046916/15204204/7c61dcc6-183d-11e6-815b-ed9aa1a384bf.png">

**Comment by ibireme** [comment]
Google 一下 `dyld`dyld_fatal_error: dyld: Symbol not found:` 会遇到很多类似的问题，不限于具体的函数，可以参考下。

这里 http://stackoverflow.com/questions/24043532/dyld-symbol-not-found-nsurlauthenticationmethodclientcertificate-when-trying 有一些方案可以试试，基本上是调整一下库的引用顺序。

**Comment by zhongjiezhe** [comment]
@ibireme 非常感谢,通过库的option的选项问题解决了
