### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by medisean** [ibireme/YYText#229]
如图，上面是系统17号字体，下面是YYLabel17号字体，下面明显更粗

![simulator screen shot 2016 3 18 2 32 29](https://cloud.githubusercontent.com/assets/6093631/13870130/9d9a56cc-ed16-11e5-8f71-02a116fbd191.png)
![simulator screen shot 2016 3 18 2 32 31](https://cloud.githubusercontent.com/assets/6093631/13870131/9d9bd768-ed16-11e5-86e7-69ed0a43f285.png)

**Comment by ibireme** [comment]
我测试了 CoreText/CoreGraphic 里所有与渲染模式、字体相关的 API，但都不能完全对应上 UILabel 的效果，似乎 UILabel 调用了一些私有方法对字体渲染模式进行了微调。

**Comment by ibireme** [comment]
Fixed.
今天又仔细调试了一下，是我的错。。在绘制文本时，我设置了一下 Shadow offset 为 zero 希望避免外界对 context 的阴影设置影响到内部，但这会带入一个与文字重合的很轻的默认阴影。
