### ISSUE TITLE
BUG: YYTextView选择时的几个问题

### ISSUE THREAD

**Issue by adad184** [ibireme/YYText#23]
https://vimeo.com/146200609

视频中有两个问题

1. 选择的时候 弹出的位置有问题
2. 先选择一部分 然后再移动到其他地方  弹出的还是"剪切"菜单  而不是"选择"

**Comment by ibireme** [comment]
啊，之前就发现了，只是没时间改。

稍后会看一下的～

**Comment by ibireme** [comment]
fixed
