### ISSUE TITLE
键盘问题

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#230]
不知您用过IQKeyboardManager没，对于键盘的处理我看了您的keyboardManager，但是还是要自己处理键盘弹起时的frame问题，IQ就自动帮处理完了，但是IQ只对apple提供的textView，field做了处理，并不能处理像您这样继承view自定义的textView，（太崇拜了），所以我和IQ的作者沟通了下，扩展下IQ对类似YYTextView的识别，开了一个issue，https://github.com/hackiftekhar/IQKeyboardManager/issues/455
希望你可以看下。

**Comment by ibireme** [comment]
呃。。这个我也没有什么太好的办法。。

**Comment by ibireme** [comment]
看到 IQ 的作者提供了额外的自定义通知的接口。。Thanks～
