### ISSUE TITLE
富文本插入图片后,再输入文字, 文字就会变的很小,怎么解决?

### ISSUE THREAD

**Issue by zhangshuaijiayanni** [ibireme/YYText#231]
当我使用YYTextView实现富文本编辑的时候, 开始直接输入文字的时候,文字大小是正常的, 但是当我插入图片后,再输入文字,  文字就变的很小?  这是为什么,该怎么解决?
![Uploading 4F7191DA-48DE-41C7-9774-FF6A9E73100D.png…]()

**Comment by ibireme** [comment]
图没传上来。

插入图片时的 Attachment 本身也需要设置字体，不然默认是 12 号字。

**Comment by zhangshuaijiayanni** [comment]
恩, 问题解决了.  插入图片时的 Attachment设置字体就解决了

**Comment by johntaiii** [comment]
<img width="840" alt="lantern lantern at 4 06 58" src="https://cloud.githubusercontent.com/assets/2558009/14201376/12d77b0a-f824-11e5-947f-0a54f1566112.png">

请问字体是这么设置的吗？@zhangshuaijiayanni

**Comment by ibireme** [comment]
alignToFont 只是用来进行对齐的。
这行后面应该再加一个 `self.attachmentAttrStr.yy_font = xxx;`

**Comment by johntaiii** [comment]
感谢。
