### ISSUE TITLE
label点击事件

### ISSUE THREAD

**Issue by 597579501** [ibireme/YYText#233]
label.highlightTapAction = ^(UIView *containerView, NSAttributedString *text, NSRange range, CGRect rect) {
    NSLog(@"tap text range:...");
};
之前都是吧事件加到NSMutableAttributedString。
但是发现如果字体小不好点所以想加到整个label上。但是直接加到label。我进去看了代码
_state.trackingTouch给过滤了。并不清楚这个是干什么。请问使用这个需要设置其他的什么的属性吗？
不能单纯的直接用吗

**Comment by ibireme** [comment]
`highlightTapAction` 和 `highlight.tapAction` 逻辑是一样的，只是如果有  `highlight.tapAction` 则忽略对应的 `highlightTapAction`。

**Comment by 597579501** [comment]
@ibireme 我不知道是我描述有问题还是。我直接贴代码吧。
![image](https://cloud.githubusercontent.com/assets/6228678/13909288/f82053b8-ef4a-11e5-9fdd-2e3bda9b927c.png)

怎么都没有相应

**Comment by ibireme** [comment]
你这块儿是纯文本，而 highlightTapAction 只能处理 highlight 标记的文本。
试试 `textTapAction` 这个回调。

**Comment by 597579501** [comment]
@ibireme tapAction.貌似YYLabel。没有textTapAction这个回调。还是我用的方式不对

**Comment by ibireme** [comment]
可能你的版本太旧了。。更新到最新的版本（1.0以上）看看。
