### ISSUE TITLE
在TextView中，使用TextParser给某段匹配的文字变色后，再输入其他文字时，字色没有恢复成原始字色

### ISSUE THREAD

**Issue by Huanhoo** [ibireme/YYText#234]
我TextView的文字颜色是黑色，用TextParser给警号中间的文字变成蓝色；然后我用insertText 给TextView加了一个带警号的文字，然后文字变成了蓝色，但是再输入文字时，文字的颜色也是蓝色，怎么解决呢？

**Comment by ibireme** [comment]
NSMutableAttributedString 有这样的特性：当在某处插入纯文本时，这段纯文本会被附加上它附近一个字符（一般是左侧的字符）的属性。这个逻辑和在 MS Word、Pages 里输入文本是一样的。

上面这种情况，应该在 parser 里重新调整颜色，或者在输入文本时调整一下新输入文本的属性。

**Comment by Huanhoo** [comment]
对 我每次在parser里都是先把文字置成默认颜色 然后执行下面变色的block 但是也不行啊；而且是在输入拼音的过程中，textview里边的拼音区域就是蓝色了……

**Comment by Huanhoo** [comment]
而且变色之后再输入英文是正常的 中文就不行了 中文的话会先输入拼音 在输拼音的时候textView文字还没真正改变 但是等真正改变之后 也还是蓝色的 所以感觉很奇怪

**Comment by ibireme** [comment]
可以试试设置一下 `typingAttributes`。

**Comment by Huanhoo** [comment]
试了下 也不行……算了 我在插入的文本后边加了个空格 就解决了……先暂时这样吧 谢谢大神啊；顺便问一下 大神有没有做过给MPMoviePlayerController播放的请求加个header头 这样的事呢？这个能实现吗？

**Comment by tanny2015** [comment]
设置typingAttributes之后，在同时添加了highLight 和 NSLink的一串NSMutableAttributedString中，如果随后已经添加了一个空格（与前方的link字符串绑定），然后键入其他字符串，新键入的文字样式确实是typingAttributes，但是在随后点击那个链接的时候，发现高亮的同时包括了后来新键入的那些文字。   试试看这个能否重现？

**Comment by ibireme** [comment]
那个就不了解了
