### ISSUE TITLE
相邻的高亮会连在一起

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYText#235]
如下图所示：正则分别匹配出了话题和 @ ,但是当点击的时候发现高亮连在了一起，而触发的高亮事件取决于谁更晚正则处理。比如先对全文进行 @ 正则匹配，再进行话题正则匹配，那么点击这个连在一起的高亮事件将会出发话题对应的高亮事件。反之亦然。但是我发现您提供的 feed list demo 中对于相邻的高亮并不会产生相连的情况。折腾他如果，特来请教原因。
![img_6865](https://cloud.githubusercontent.com/assets/5517281/13914782/9e617c80-ef8b-11e5-88fc-0477e10f664a.PNG)

**Comment by ibireme** [comment]
NSAttributedString 会合并 key 和 value 都相同的属性片段。

这块儿，可以分别设置两段的 highlight；或者先设置全部，再设置第二段时先清空目标范围的 highlight。l另外，每次 highlight 属性都要重新 new 出来，这样保证不会被 NSAttributedString 自动合并。

如果还有问题，可以打印一下 NSAttributedString 看看。

**Comment by KittenYang** [comment]
@ibireme  恩，重新 new 一个 highlight 问题解决。
