### ISSUE TITLE
YYTextView innerContainer问题。

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#236]
YYTextLayout* layout=[YYTextLayout layoutWithContainer:innerContainer text:self.attributedText];

我用这个方法算出的layout 发现比实际的要小，请问是为什么？
YYTextLayout* layout=[YYTextLayout layoutWithContainerSize:CGSizeMake(kScreenWidth-80-40, MAXFLOAT) text:self.attributedText];
我用这个算的才刚刚好。

**Comment by ibireme** [comment]
innerContainer 是怎么生成的？
container 应该尽可能的大，来保证文本都能容纳得下。
