### ISSUE TITLE
YYTextLaout问题

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#237]
当我设置文本为@“。。。。。。。\n”，后边有个换行f的话，计算出的高度是不带最后的换行f的。当我用YYTextView的时候，文本末尾有个换行f，计算出来的高度会少一行，然后textView就可以滑动了。。。

**Comment by ibireme** [comment]
YYTextView 为了显示最后一行换行后的光标，做了特殊处理：
https://github.com/ibireme/YYText/blob/master/YYText/YYTextView.m#L245-L246

**Comment by wy19901227** [comment]
额，那我还是把文本的最后一个换行f给去掉 处理吧。
