### ISSUE TITLE
有没有可能实现高亮部分自动换行避免截断

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYText#238]
![image](https://cloud.githubusercontent.com/assets/5517281/13940288/08bc20fe-f017-11e5-8930-c49b8e8e1813.jpeg)
如图所示，有没有可能实现高亮部分自动换行避免截断。例如图中的网页链接这个 tag，能否在绘制的时候提前判断以避免截断？

**Comment by ibireme** [comment]
有个很勉强的 workaround：https://github.com/ibireme/YYText/issues/62

另外，可以在 container.insets 里设置一下左右留白，让高亮的圆角部分不至于被截断。

**Comment by KittenYang** [comment]
@ibireme Solved my problem,many thanks!
