### ISSUE TITLE
连续创建三个yylabel， textAlignment 0 跟 1 都变成居中了

### ISSUE THREAD

**Issue by hydyy** [ibireme/YYText#239]
for (int i=0; i<3; i++) {
        YYLabel *label1 = [YYLabel new];
        label1.text = @(i).stringValue;
        label1.textAlignment = i;
        label1.backgroundColor = [[UIColor blackColor] colorWithAlphaComponent:.5];
        label1.frame = CGRectMake(0, i*50, 100, 30);
        [self.view addSubview:label1];
    }

**Comment by ibireme** [comment]
检查一下，后面的代码是否设置过 textLayout。

**Comment by hydyy** [comment]
就只有for循环这些代码


原始邮件
发件人:Yaoyuannotifications@github.com
收件人:ibireme/YYTextYYText@noreply.github.com
抄送:Adamhouyaodong@qq.com
发送时间:2016年3月22日(周二) 13:48
主题:Re: [YYText] 连续创建三个yylabel， textAlignment 0 跟 1 都变成居中了 (#239)


检查一下，后面的代码是否设置过 textLayout。

**Comment by ibireme** [comment]
测试了一下，很奇怪的问题。。如果单独一个 Label，或者全部设置为一种 alignment 都是没问题的。。

可能是内部处理 alignment 默认值时的问题。。

**Comment by hydyy** [comment]
求修复呀， 这个会排期很久么？ 如果要很久我就要看看怎么处理啦。

**Comment by ibireme** [comment]
今天或明天改好吧。

**Comment by hydyy** [comment]
期待期待！

**Comment by ibireme** [comment]
Fixed

**Comment by hydyy** [comment]
awesome！！！！


为什么呢？


原始邮件
发件人:Yaoyuannotifications@github.com
收件人:ibireme/YYTextYYText@noreply.github.com
抄送:Adamhouyaodong@qq.com
发送时间:2016年3月22日(周二) 16:24
主题:Re: [YYText] 连续创建三个yylabel， textAlignment 0 跟 1 都变成居中了 (#239)


Fixed

**Comment by ibireme** [comment]
[NSParagraphStyle defaultParagraphStyle].alignment 默认是 NSLeftTextAlignment 的。。
