### ISSUE TITLE
iOS7上，设置了下划线属性之后，就取消不掉了

### ISSUE THREAD

**Issue by matthewyan** [ibireme/YYText#24]
在iOS7上，输入文字时设置了下划线属性，则无法将其去掉了

**Comment by ibireme** [comment]
能再多描述些吗？比如提供一些代码片段？

**Comment by matthewyan** [comment]
我对demo进行了一点修改，把第三个开关作为了下划线属性设置的开关
![image](https://cloud.githubusercontent.com/assets/8739896/11296387/c6115c62-8fac-11e5-9eab-d769a36c72cf.png)

我先打开该属性进行文字的下划线输入文字，然后再关闭下划线属性，但在iOS7上发现下划线就会一直存在：

![image](https://cloud.githubusercontent.com/assets/8739896/11296547/b771137c-8fad-11e5-9bc0-1deaf08314f5.png)

不知道这次描述清楚没。。

**Comment by ibireme** [comment]
<img width="316" alt="snapshot" src="https://cloud.githubusercontent.com/assets/839283/11297205/d73267d4-8fb1-11e5-9278-be575afa3c91.png">

目前没发现问题啊。。

**Comment by matthewyan** [comment]
额，是在iOS7上么

**Comment by ibireme** [comment]
换用 AttributedText.yy_textUnderline 或 YYTextUnderlineAttributeName 属性来设置下划线试试，不要用 UIKit 或 CoreText 的下划线属性。
