### ISSUE TITLE
点击链接高亮  NSLink  YYTextHighlight

### ISSUE THREAD

**Issue by tanny2015** [ibireme/YYText#241]
设置typingAttributes之后，在添加了YYTextHighlight 和 NSLink的一串NSMutableAttributedString中，如果随后已经添加了一个空格（与前方的link字符串绑定），然后键入其他字符串，新键入的文字样式确实是typingAttributes，但是在随后点击那个链接的时候，发现高亮的同时包括了后来新键入的那些文字。 试试看这个能否重现？

辛苦了，非常感谢。

**Comment by ibireme** [comment]
NSMutableAttributedString 有这样的特性：当在某处插入纯文本时，这段纯文本会被附加上它附近一个字符（一般是左侧的字符）的属性。这个逻辑和在 MS Word、Pages 里输入文本是一样的。

看样子，你可以试试清空一下新键入文字的 highlight 属性。

**Comment by tanny2015** [comment]
清空一下新键入文字的 highlight 属性   能否提供一点思路呢，非常感谢。
我的YYTextView里边有插入图片（textAttachment）和插入链接的功能（NSLink）
现在在链接部分后续插入文字有点儿异样。

**Comment by tanny2015** [comment]
以下是尝试过清理后续文字随前边链接格式的一个方法：
//1.在attributedString的前后方随一个无格式的回车字符，让后方输入的文字自动沿用这个无格式的回车字符
[attrString insertAttributedString:[[NSAttributedString alloc] initWithString:@"\n"] atIndex:0];
[attrString appendAttributedString:[[NSAttributedString alloc] initWithString:@"\n"]];
//2.在前后添加了无格式的attributedString设置绑定，防止新键入的位置位于这串字符串的中间位置
[attrString setTextBinding:[YYTextBinding bindingWithDeleteConfirm:NO] range:attrString.rangeOfAll];
//3.该解决方法在点击链接的时候，高亮位置（原来的attrString设置了NSLink和YYTextHighlight）仍然是包括新输入的文字。

谢谢

**Comment by tanny2015** [comment]
以上那个方法我遍历了一下添加了两个回车键之后的新字符串，发现最后一个回车键确实只带了一个YYTextBinding的字符串属性，请问这个属性也会导致前方字符串的其他格式自动沿用了？

**Comment by tanny2015** [comment]
如将链接前后加上空格的方法，如果对这个新字符串整体添加YYTextHighlight【该链接点击需要action响应】，则后续所有文字都会沿用之前的字符串格式。但是如果只对未添加空格字符的原字符串设置YYTextHighlight，然后将空格和原字符串设置YYTextBinding，此时原来字符串（设置了YYTextHighlight）无法被选中，响应事件无法启用

**Comment by ibireme** [comment]
这些逻辑都是 NSMutableAttributedString 的。。如果有问题可以打印一下 attributedText 看看对应字符串的属性是否正确。

**Comment by tanny2015** [comment]
恩  之前所指的attributedString就是NSMutableAttributedString。@" "+ mutableAttributedString + @" " (三者拼接后设置binding)---为了让这个整体具备点击调用链接action的功能(highlight.tapAction).
打印出来最前方的空格和最后方的空格的attributes都是
YYTextBinding = "<YYTextBinding: 0x12e628c90>";
YYTextHighlight = "<YYTextHighlight: 0x12e603c40>";


而随后插入的其他文字，都沿用了这最后一个空格中的YYTextHighlight，他们的attributes为
YYTextHighlight = "<YYTextHighlight: 0x12e603c40>";

**Comment by ibireme** [comment]
如果不需要，就把属性移除啊。。
另外，你也可以写一个 YYTextParser 的实现来手动调整每段文字的属性。。

**Comment by tanny2015** [comment]
使用YYLabel作为attachment嵌入后解决这个问题
谢谢~
