### ISSUE TITLE
这样的图文混排，YYLabel 应该怎么弄呢

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#242]
![image](https://cloud.githubusercontent.com/assets/8086633/13975295/a2f07008-f0ee-11e5-8b8e-0d83bf28c758.png)

**Comment by ibireme** [comment]
label. exclusionPaths = ...; // 这能让对应区域留出空白。

然后在 label 对应位置上添加一个 UIImageView 或 CASharpLayer 用来显示这个图片。

**Comment by wy19901227** [comment]
额，等于和apple的textKit是一样的用法是吧，棒啊
