### ISSUE TITLE
用YYText写的timeLine，tableview为什么不能调用didselectedrowatindex

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#244]
是因为cell上被UIControl 覆盖了吗？

**Comment by ibireme** [comment]
YYLabel 之类的控件会可能会拦截触摸事件。

**Comment by wy19901227** [comment]
那可以设置下让他往上传递吗？

发自我的 iPhone

**Comment by ibireme** [comment]
这是 UIView 的默认行为啊。。。
你可以试着调节一下 Gesture 和 UIView 的触摸逻辑。

**Comment by wy19901227** [comment]
你写的推特，cell并没有写点击事件，为什么也不能调didselectrow，

发自我的 iPhone

**Comment by ibireme** [comment]
你可以看下那个 Cell 的代码。。
我里面拦了个其它视图。https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/YYControl.m

**Comment by wy19901227** [comment]
那我应该怎么弄才可以调用，还是说另外这个点击事件？

发自我的 iPhone

**Comment by ibireme** [comment]
如果你不需要 Label 内的链接触摸事件，那可以把 label 的触摸禁用；否则就像上面这样自己添加控件来拦截。

**Comment by wy19901227** [comment]
yylabel内的点击，你不是已经做了拦截处理吗？我点击不是富文本的时候应该把事件传递到父试图，但是我点击正常文本的时候，cell会有点击效果，颜色变暗，但是就是没调用didselectrow这个代理，我应该怎么弄让事件传递出去


发自我的 iPhone

**Comment by wy19901227** [comment]
![image](https://cloud.githubusercontent.com/assets/8086633/14005776/96cfe4c6-f1a1-11e5-9c8f-404938187e76.png)

**Comment by wy19901227** [comment]
我在YYControl里将触摸事件传递出去，cell被点击的代理是会被调用，我看YYLabel，也有讲事件传递出去，这里为什么没有呢？ 还是说有其他的好的处理方式？

**Comment by ibireme** [comment]
好吧，我特地改了一下 Demo 中的[这个](https://github.com/ibireme/YYText/blob/master/Demo/YYTextDemo/YYTextAsyncExample.m)视图，didSelectRowAtIndexPath 是能调用到的。你可以检查下其它地方的问题看看。

**Comment by wy19901227** [comment]
![image](https://cloud.githubusercontent.com/assets/8086633/14006732/5d0c16ba-f1ab-11e5-8da2-adeeed1c738b.png)

**Comment by wy19901227** [comment]
您的YYlabel在处理触摸的时候，当没有当点击普通文本的时候，会调用父类的touchesBegan，然后就把事件传递出去了，但是您在写TimeLine的时候，cell上覆盖了一层UIControl，所以点击cell的时候，UIControl在处理的touchesbegan的时候，并没有做传递事件的操作，所以不cell不能调didSelectRowAtIndexPath，我在UIControl的touchesBegan里增加了super touchesBegan 才可以调，。。。。
