### ISSUE TITLE
YYTextAttachment 插入图片 点击选中的问题

### ISSUE THREAD

**Issue by tanny2015** [ibireme/YYText#246]
项目中允许用户插入图片 -- 通过YYTextAttachment 设置到 YYTextView 的NSMutableAttributedString中。此处的YYTextAttachment是个UIImage,规则是每张图片都应该单独占据一行。
 
因此当用户插入一张图片后，就追加一个attributedString，随后在这个attributedString的前后插入一个"\n"换行符，再使用setTextBinding，把这个"\n" + attributedString + "\n" 的新字符串绑定起来。  发现单点击这个图片的时候，在attributedString和与其绑定的最后一个"\n"之间的位置居然可以被选中并且光标移动到了那个位置。  
这种情况下，如果在这个位置退格对图片做删除操作（比如误操作）,会导致报错停止。

@ibireme  辛苦看下能否重现这个问题？  不知是否可以通过什么方式解决。
谢谢~

**Comment by tanny2015** [comment]
如何在YYTextAttachment（image）上下各绑定一个空行呢？

**Comment by ibireme** [comment]
建议在创建 Attachment 时，把宽度调节为和 TextView 一样，这样就能保证每行最多一张图片了。

TextBinding 和换行符绑定这个我没测试过，但换行和光标判断的关系很大，可能会有冲突。

**Comment by tanny2015** [comment]
恩 是已经调整到textView宽度的情况下出现的。

**Comment by ibireme** [comment]
我的意思是说，调整到 textView 的宽度时，输入新文本就会自动新启一行了，就能够满足你的规则了。然后。。别再用 TextBinding 绑定换行符了。。那样确实容易出错。。

**Comment by TonyGJJ** [comment]
我现在遇到了一个问题。输入文字后再插入图片，默认进入选中状态。
![1544757870577](https://user-images.githubusercontent.com/4088735/49981434-dd6cc000-ff92-11e8-819b-1c8841b1bd32.jpg)
