### ISSUE TITLE
关于基本UILable的用法

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#25]
我的cell并不是需要大量富文本，所以我就直接用YYLbel的基本用法，只是让它异步绘制。代码如下
 _requir=[YYLabel new];
_requir.displaysAsynchronously=YES;
 _requir.frame=CGRectMake(110, 35, 120, 14);
        _requir.backgroundColor=[UIColor redColor];
        [self.contentView addSubview:_requir];
        _requir.font=kSystemFont(14);
        
        _stock=[[YYLabel alloc]init];
        _stock.displaysAsynchronously=YES;
        _stock.backgroundColor=[UIColor redColor];
        _stock.frame=CGRectMake(110, 60, 120, 14);
        [self.contentView addSubview:_stock];
        _stock.font=kSystemFont(14);

然后我在setModel的方法里
 _requir.text=[NSString stringWithFormat:@"兑换条件：%@",model.convertCondition];
    _stock.text=[NSString stringWithFormat:@"剩余：%d份",(int)model.residueNumber];

但是结果却是
![img_0252](https://cloud.githubusercontent.com/assets/8086633/11291641/84747930-8f7d-11e5-86bd-dfa15a6e985e.PNG)

只有把_stock的高加3也就是17才能显示出来。这是什么情况，我有点摸不着头脑。希望表达清楚了，望解答。

**Comment by ibireme** [comment]
第一行文本是纯中文，行高可能和字号一样，第二行有用到英文字体，行高就大于字号了。

目前 YYLabel 在高度比第一行文字还小时无法显示，这是个已知问题，在 readme 里有提到
