### ISSUE TITLE
NSMutableAttributedString

### ISSUE THREAD

**Issue by 597579501** [ibireme/YYText#250]
NSMutableAttributedString添加图片和文本的时候。有没有设置这2个单位之间的间距的。我都是用空格的。。。UI给的px单位。。。。

**Comment by ibireme** [comment]
如果用 textAttachment，那可以直接传入明确的宽度和高度。如果是用空格占位符，那可以添加一个 runDelegate 来指定宽高。

**Comment by 597579501** [comment]
![image](https://cloud.githubusercontent.com/assets/6228678/14069640/2b98e640-f4cf-11e5-9824-40f415015e96.png)


如图。这一行文字是YYLabel加NSMutableAttributedString实现。想问下有没有办法后面的文字能加在最后图片里面。如下图
![image](https://cloud.githubusercontent.com/assets/6228678/14069589/9a7b0dd2-f4ce-11e5-9694-3282a3e727de.png)

**Comment by ibireme** [comment]
可以把 白色星星和 `8` 这个数字连起来，然后加一个紫色的 textBorder 背景。
也可以把这个东西拼成一个 UIView 来当作 attachment 显示。

**Comment by 597579501** [comment]
@ibireme 
![image](https://cloud.githubusercontent.com/assets/6228678/14076659/63d8536e-f516-11e5-8aa7-395eb188be95.png)
我按你说的第一种方式做了。有个问题就是。他整个为文本了。就会以前面的文本底部对齐。我希望是后面的月亮和文字以前面的图片剧中对齐。另外。
    YYTextBorder *textBorder = [YYTextBorder borderWithFillColor:UIColorHexAlpha(0xDC143C, 1) cornerRadius:3];
这个textBorder.insets很难控制啊。

**Comment by ibireme** [comment]
那就把前面的图片向文本对齐试试。

**Comment by 597579501** [comment]
@ibireme 不知道哪个地方使用的不对。文本和图是剧中的。如果再加个图就乱了。就根本不剧中了。。。。

![image](https://cloud.githubusercontent.com/assets/6228678/14077621/ed8c602e-f51f-11e5-93a8-2345e0e66f38.png)


另外        image = [UIImage imageWithCGImage:image.CGImage scale:2 orientation:UIImageOrientationUp];
这句话的意思我知道。但是这样做的意义我有点不太明白用意何为。
还请YY大神给条明路

**Comment by ibireme** [comment]
那个 `8` 和前面的文字字体大小不一样，这就没法和前面的文字对齐。另外，创建 attachment 时，alignment 用 center。
