### ISSUE TITLE
YYText textLongPressAction问题

### ISSUE THREAD

**Issue by CoderDKBai** [ibireme/YYText#251]
YY大神，你好：
我在使用YYLabel的时候，给YYLabel实现了长按功能，即textLongPressAction；未实现单击功能；YYLabel是添加在tableViewCell上的，当我单击YYLabel的时候，好像拦截了事件，导致单击cell不调用tableview的didselectedRow代理方法？

请问如何解决？
查看YYText Demo好像没有类似的例子.

我同时实现了YYLabel的单击和长按，可是当我长按时，首先调用长按block，完了之后又会调用单击block。

                    titleLabel.textLongPressAction = ^(UIView *containerView, NSAttributedString *text, NSRange range, CGRect rect) {
                        
                        weakSelf.longPressAction = YES;
                        [weakSelf showMenuController:containerView rect:rect];
                    };
                   titleLabel.textTapAction = ^(UIView *containerView, NSAttributedString *text, NSRange range, CGRect rect) {
                        
                        if (!weakSelf.longPressAction) {
                            [weakSelf pushClubDynamicDetailedControllerWithDynamicId:model.dynamicId dynamicType:model.type activityUrl:model.url];
                        } else {
                            weakSelf.longPressAction = NO;
                        }
                    };

有没有方法实现：当我长按时，不调用单击的block？或者改如何设置？请教！

我是按照上面方法实现的长按的时候不调用单击block，请问有没有别的属性可以直接设置的？

**Comment by ibireme** [comment]
看这两个方法的注释，这两个方法会捕获在整个 Label 上的触摸事件。

如果你仅需要处理高亮链接的事件，那可以用 `highlightTapAction` 和 `highlightLongPressAction` 这两个方法。另外，也可以手动添加 gesture，然后去 label.textLayout 查询点击的文本位置。

**Comment by CoderDKBai** [comment]
可不可以像系统手势那样，当长按手势侦测失败时，才触发单击手势？


        UITapGestureRecognizer *singleTap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(handleSingleTap:)];
        UITapGestureRecognizer *doubleTap = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(handleDoubleTap:)];
        //  如果双击手势确定侦测失败才会触发单击，可以解决手势冲突
        [singleTap requireGestureRecognizerToFail:doubleTap];

**Comment by ibireme** [comment]
内部并不是 gesture，那两个回调也是很简单的逻辑，并没有考虑太多情况。。
你可以直接在上面添加 gesture 来监视事件，来实现更完善的手势操作。

**Comment by CoderDKBai** [comment]
谢谢！
