### ISSUE TITLE
系统自带的文字复制全选功能怎么隐藏不了

### ISSUE THREAD

**Issue by zhangshuaijiayanni** [ibireme/YYText#252]
/* 选中文字后是否能够呼出菜单 */
- (BOOL)canBecomeFirstResponder {
    return YES;
}
// 用来关闭菜单中所有系统的菜单项，如copy, select, select all等。
- (BOOL)canPerformAction:(SEL)action withSender:(id)sender {

    if (action == @selector(paste:) ||
        action == @selector(cut:) ||
        action == @selector(copy:) ||
        action == @selector(select:) ||
        action == @selector(selectAll:) ||
        action == @selector(delete:) ||
        action == @selector(makeTextWritingDirectionLeftToRight:) ||
        action == @selector(makeTextWritingDirectionRightToLeft:) ||
        action == @selector(toggleBoldface:) ||
        action == @selector(toggleItalics:) ||
        action == @selector(toggleUnderline:) ||
        action == @selector(increaseSize:) ||
        action == @selector(decreaseSize:)
        ) {
        return NO;
    }
    
    if (action == @selector(changeToTaskSelection)){
        
        return YES;
    }
    else if(action == @selector(selectText)){
        
        return YES;
    }
    else if(action == @selector(selectAllSelection)){
        
        return YES;
    }

    // 事实上一个return NO就可以将系统的所有菜单项全部关闭了
    return [super canPerformAction:action withSender:sender];;
}

- (void)loadView {
    [super loadView];
    
    // 自定义text view选中文字后的菜单
    UIMenuItem *selectItem = [[UIMenuItem alloc] initWithTitle:@"复制" action:@selector(selectText)];
    UIMenuItem *selectAllItem = [[UIMenuItem alloc] initWithTitle:@"全选" action:@selector(selectAllSelection)];
    UIMenuItem *changeToTaskItem = [[UIMenuItem alloc] initWithTitle:@"转任务" action:@selector(changeToTaskSelection)];
    
    // 获得菜单
    UIMenuController *menu = [UIMenuController sharedMenuController];
    menu.menuItems = @[selectItem, selectAllItem, changeToTaskItem];
    [menu setMenuVisible:YES animated:YES];
}

我这样写的, 想将系统自带的  复制 全选 定义  隐藏, 但是隐藏不了, 为什么?该怎么做?

**Comment by ibireme** [comment]
改一下 menu.menuItems

**Comment by zhangshuaijiayanni** [comment]
menu.menuItems?  什么意思?   怎么改

**Comment by ibireme** [comment]
你这是在修改 YYTextView 的源码，还是说这是你自己的 Controller？不论怎么写，这些代码应该是针对同一个控件来做的。

canPerformAction 返回 NO，menu.menuItems 设置为自定义的字段。如果还有问题，那仔细看一下 UIMenuController 的文档。

**Comment by zhangshuaijiayanni** [comment]
自己的controller上集成的YYTextView.
 将canPerformAction 无论返回 NO或者YES，menu.menuItems 设置为自定义的字段,  自己自定义的字段添加上了, 但是不能隐藏系统自带的选择 全选 定义 三个字段

**Comment by ibireme** [comment]
如果你希望改 YYTextView 中菜单的逻辑，那只能直接去修改 YYTextView.m 的源码，或者子类化来重写那些方法。

菜单逻辑是由 firstResponder 控制的。
