### ISSUE TITLE
YYText上添加子控件时,当文字内容高于整个屏幕时,添加到底部的子控件被遮挡了

### ISSUE THREAD

**Issue by zhangshuaijiayanni** [ibireme/YYText#253]
YYText上添加子控件时  使用这个方法 [self.textView addSubview:self.imageView];  
 当文字内容高于整个屏幕时,添加到底部的子控件被遮挡了, 只能显示到文字的最后 ,不能显示最后添加的子控件?

图片一直添加不上, 不知道为什么

**Comment by ibireme** [comment]
YYTextView 是 UIScrollView 的子类，它的 contentSize 会自动根据文字改变。

**Comment by zhangshuaijiayanni** [comment]
当文字内容高于屏幕时, textView可以滑动之后, 在使用 [self.textView addSubview:self.imageView]方法添加一个子控件在最后位置, textView的高度只是根据文字改变了, 但是没有根据这个子控件改变, 导致添加的这个子控件被遮挡了

**Comment by ibireme** [comment]
是的，UIScrollView 不会根据子视图改变 contentSize。
