### ISSUE TITLE
求助:当NSAttributedString中含有emoji表情时,高度计算错误,是我代码写的不对吗?

### ISSUE THREAD

**Issue by fengyunjue** [ibireme/YYText#255]
UIFont *font = [UIFont systemFontOfSize:19];
    
    YYLabel *label = [YYLabel new];
    label.backgroundColor = [UIColor grayColor];
    [[NSMutableAttributedString alloc]initWithString:@"😁🤗😟😫😁🤗😟😫😁😟😫😁😟🌿🏐🐬🌳"];
    string.font = font;
    YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
    modifier.fixedLineHeight = font.lineHeight;
    YYTextContainer *container = [YYTextContainer new];
    container.size = [UIScreen mainScreen].bounds.size;
    container.linePositionModifier = modifier;
    YYTextLayout *textLayout = [YYTextLayout layoutWithContainer:container text:string];
    label.textLayout = textLayout;
    label.frame = CGRectMake(0, 64, textLayout.textBoundingSize.width, textLayout.textBoundingSize.height);
    [self.view addSubview:label];
![qq20160329-1 2x](https://cloud.githubusercontent.com/assets/6801297/14112920/4b1fde62-f603-11e5-987c-8b3f81cdf2c3.png)

**Comment by ibireme** [comment]
测试了一下这段代码，问题比较微妙。。这个地方用到了 YYLinePositionSimpleModifie，而这个会在内部 CoreText 排版后对每行文本进行微调，这样就会导致最终计算结果和 CoreText 排版结果不一致（此处是文本高度小于 CoreText 排版高度）。如果拿着这样计算出来的宽高做限制，再计算一次，那就会出现不同了。

当重新设置 label.frame 时，内部会尝试对文本进行重新排版计算，而这时用的最大宽高限制是从 frame 获取的，这就会造成重新排版后的结果和之前的结果不一样。

解决办法的话，可以交换一下这两行，把 setTextLayout 放在最后：

    label.textLayout = textLayout;
    label.frame = CGRectMake(0, 64, textLayout.textBoundingSize.width, textLayout.textBoundingSize.height);

或者设置一下 label.ignoreCommonProperties = YES 让 label 仅渲染 textLayout 的内容而忽略其他属性。

**Comment by tianglin** [comment]
测试交换位置可以，多谢lz
