### ISSUE TITLE
求助：iOS7下YYLabel使用中文冒号（：）后，一个表情（\u263a\ufe0f）显示不正常了

### ISSUE THREAD

**Issue by xiabob** [ibireme/YYText#256]
**iOS7.1.2**下
没加冒号代码：
![snip20160330_1](https://cloud.githubusercontent.com/assets/9293442/14130077/c3733058-f662-11e5-8403-82772cdc2aa4.png)

![img_0198](https://cloud.githubusercontent.com/assets/9293442/14130065/8db45ba4-f662-11e5-8abe-d7dd68f11380.PNG)
加了冒号：
![snip20160330_2](https://cloud.githubusercontent.com/assets/9293442/14130103/f080dfb4-f662-11e5-9f82-fd215ba7f0b3.png)
![img_0199](https://cloud.githubusercontent.com/assets/9293442/14130108/fdef0bbc-f662-11e5-8310-f41cfecb92ca.PNG)

**Comment by ibireme** [comment]
这是 CoreText 的问题，我无法修复。。

**Comment by xiabob** [comment]
之前就觉得是系统自身的问题，换了几个基于CoreText的第三方库，都出现这个问题

**Comment by wy19901227** [comment]
UILabel是没问题的

发自我的 iPhone

**Comment by ibireme** [comment]
谁知道 UILabel 做了多少额外处理或者私有 API。。
CoreText 的 bug 一坨一坨的。。我已经尽量做了很多 workaround 来避免 bug。。
