### ISSUE TITLE
超大GIF图片占用内存过多后crash。

### ISSUE THREAD

**Issue by Finb** [ibireme/YYText#258]
大大你好，非常感谢你开源这个库。

我在使用中碰到个问题，想请教下看看有没有解决办法

我有一个位置会显示gif图片，当图片超大时，内存会占用非常大，真机可占满内存导致crash。
模拟器的内存占用会达到2G(峰值)，之后会回落到400MB，然后释放UIImage缓存后 回退到正常水平

我的用法是 
有个cell里有一个YYLabel 
```Objc
self.commentLabel = YYLabel();
self.commentLabel!.numberOfLines = 0;
self.commentLabel!.displaysAsynchronously = true
self.contentPanel?.addSubview(self.commentLabel!);
```

然后给这个YYLabel赋值
```objc
//image 是UIImageView 的子类对象，在显示在window上时，会去加载远程图片并显示
NSMutableAttributedString.yy_attachmentStringWithContent(image, contentMode: .ScaleAspectFit , attachmentSize: CGSizeMake(80, 80), alignToFont: v2ScaleFont(14), alignment: .Bottom)
```

```Objc
//image 加载远程图片代码
override func willMoveToSuperview(newSuperview: UIView?) {
    ...
    self.kf_setImageWithURL(URL ...)
    ...
}
```

测试图片
http://ww2.sinaimg.cn/large/9093b87dgw1f2ewpedx0ig20m80godrx.jpg

我想请教一下
有没有什么办法能禁用掉超大GIF的加载，只加载它第一帧，把它当成一个静态图像

**Comment by ibireme** [comment]
Kingfisher (或者 SDWebImage) 会把 GIF 的每帧都取出来放入内存数组来显示，所以这种内存过大的问题很难避免。

**Comment by Finb** [comment]
感谢你的回复。
也就是说这个问题得在请求数据那块避免，
YYLabel 不需要额外设置
或没必要对YYText框架做修改对吧

**Comment by skyline75489** [comment]
https://github.com/kaishin/Gifu 这个项目提供了一个思路，能够最小化内存占用。

**Comment by Finb** [comment]
@skyline75489 咱这里的crash实际上是由于 Kingfisher 对GIF图片逐帧解码然后扔到内存里，如果GIF超大的话，内存完全扛不住 😄~~ 

喵神说有空会增加个option来优化这些。
