### ISSUE TITLE
YYText竖排时怎样垂直居中（只有一列）

### ISSUE THREAD

**Issue by chx632996066** [ibireme/YYText#26]
像这yang样
![95539af8-69db-4e2b-897f-d84c8d42a9aa](https://cloud.githubusercontent.com/assets/4217642/11294100/9f81d2ae-8f9b-11e5-81cd-112df68c3006.png)

**Comment by ibireme** [comment]
竖排时，让它在左右居中，可以用 label.textVerticalAlignment = YYTextVerticalAlignmentBottom;

CoreText 在用 kCTFrameProgressionRightToLeft 进行竖排版时，不支持 TextAlignment 属性。。所以上下居中目前还做不到。。

**Comment by chx632996066** [comment]
@ibireme 你好
1.我加了textVerticalAlignment = YYTextVerticalAlignmentBottom;这句还是无法左右居中。你确定是可以的吗？

2. 还有单列的情况下，能不能像正常label那样超出显示范围了就显示一部分内容，然后末尾显示“...”
我设置了lineBreakMode = NSLineBreakByTruncatingTail;但是变成整个label只显示“...”，没有其它内容了。

**Comment by ibireme** [comment]
能贴出你的代码片段来看一下吗？

**Comment by chx632996066** [comment]
_label_targetName.verticalForm = YES;
_label_targetName.numberOfLines = 1;
_label_targetName.textVerticalAlignment = YYTextVerticalAlignmentBottom;
_label_targetName.lineBreakMode = NSLineBreakByTruncatingTail;
_label_targetName.font = CustomFontWithSize(14);

**Comment by ibireme** [comment]
1. 写错了。。用 YYTextVerticalAlignmentCenter。。
2. 确实是有 bug。。目前暂时定为是 CTLineCreateTruncatedLine() 的问题，目前可能没计划对这块儿进行修改，原因件和上面类似。。

稍后如果有空闲，我会重写竖排版底层的这块儿东西，用自定义的变换代替 CoreText 的竖排版，那样应该能避开不少 CoreText 竖排版的坑。。

**Comment by chx632996066** [comment]
YYTextVerticalAlignmentCenter 也试过了，也是没起作用

**Comment by ibireme** [comment]
这个请更新一下代码看看

**Comment by zy30651** [comment]
你好，我在使用你的YYText框架练习的时候，当我模仿YYTextDemo里边的YYTextAttachmentExample，有qq几个动画，他们使用的是YYImage，每次我引用YYImage，就报错。找不到什么问题，没有重复的YYImageCoder，这文件也没有被链接2次。把YYImage删除后又添加还是不行。

Undefined symbols for architecture x86_64:
  "_crc32", referenced from:
      _yy_png_copy_frame_data_at_index in YYImageCoder.o
      -[YYImageEncoder _encodeAPNG] in YYImageCoder.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
