### ISSUE TITLE
ios7下使用iOS8新版emoji,应用假死

### ISSUE THREAD

**Issue by FutureChen** [ibireme/YYText#260]
ios 8以后新增的emoji， 在 7的系统下运行，使用YYText会导致应用进入假死状态。
如果使用UILabel 则不影响

**Comment by FutureChen** [comment]
经过验证，带中文冒号的会渲染失败 再添加点击事件，就导致奔溃
  @"123123：😄🌶️喔喔喔喔喔喔";

**Comment by wy19901227** [comment]
贴下原因，或者给作者一个demo

发自我的 iPhone

**Comment by ibireme** [comment]
找了个 iOS7 的 iPad 测试了一下，这应该是 iOS7 下 CoreText 的 Bug。。
App 会卡死在 CoreText 内部的死循环，这个我也没办法，CoreText 的 Bug 太多了。。这只能在上层通过修改文字来避免了。
<img width="324" alt="2016-04-02 1 07 38" src="https://cloud.githubusercontent.com/assets/839283/14224574/f3cce1f4-f8d3-11e5-84e0-d7ded7700a2b.png">

**Comment by FutureChen** [comment]
恩 我搞了个破坏，给ios 7手机发了个推送，结果系统死机了。。呵呵哒
