### ISSUE TITLE
iOS7下YYtextView插入YYImage Crash

### ISSUE THREAD

**Issue by mayazhe** [ibireme/YYText#261]
YYtextView插入YYImage 崩溃，目前只在iOS7发现有此问题

我的代码，运行到最后一句崩溃：
```
YYImage *image = [[YYImage alloc] initWithCGImage:[[asset defaultRepresentation] fullScreenImage]];
DGCloseImageView *imageView = [[DGCloseImageView alloc] initWithImage:image];
imageView.url = ast.url;
imageView.delegate = self;
                
CGFloat width = kScreenWidth - 8*2;
CGFloat height = image.size.height * width / image.size.width;
CGSize size = CGSizeMake(width, height);
                
NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithContent:imageView contentMode:UIViewContentModeScaleAspectFill attachmentSize:size alignToFont:KFont alignment:YYTextVerticalAlignmentCenter];
                
attachText.yy_font = KFont;
attachText.yy_minimumLineHeight = 30;
[attachText yy_insertString:@"\n" atIndex:0];
[attachText yy_appendString:@"\n"];
                
NSRange range = _textView.selectedRange;
NSMutableAttributedString *attr = [[NSMutableAttributedString alloc] initWithAttributedString:_textView.attributedText];
[attr insertAttributedString:attachText atIndex:range.location];
_textView.attributedText = attr;
```

崩溃在 YYTextEffectWindow.m 文件如下代码：
```
CGPoint center = [dot yy_convertPoint:CGPointMake(CGRectGetWidth(dot.frame) / 2, CGRectGetHeight(dot.frame) / 2) toViewOrWindow:self];
dot.mirror.center = center;
```

应该是计算出来的frame有问题：
center = (x = NaN, y = NaN)

![aaa](https://cloud.githubusercontent.com/assets/10356817/14208559/a8588ce0-f852-11e5-9b6a-f3774ba12c2d.jpg)

**Comment by mayazhe** [comment]
`[weakSelf.assetsLibrary assetForURL:ast.url resultBlock:^(ALAsset *asset) {
                
                YYImage *image = [[YYImage alloc] initWithCGImage:[[asset defaultRepresentation] fullScreenImage]];
                DGCloseImageView *imageView = [[DGCloseImageView alloc] initWithImage:image];
                imageView.url = ast.url;
                imageView.delegate = self;
                
                CGFloat width = kScreenWidth - 8*2;
                CGFloat height = image.size.height * width / image.size.width;
                CGSize size = CGSizeMake(width, height);
                
                NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithContent:imageView contentMode:UIViewContentModeScaleAspectFill attachmentSize:size alignToFont:KFont alignment:YYTextVerticalAlignmentCenter];
                
                attachText.yy_font = KFont;
                attachText.yy_minimumLineHeight = 30;
                [attachText yy_insertString:@"\n" atIndex:0];
                [attachText yy_appendString:@"\n"];
                
                NSRange range = _textView.selectedRange;
                NSMutableAttributedString *attr = [[NSMutableAttributedString alloc] initWithAttributedString:_textView.attributedText];
                [attr insertAttributedString:attachText atIndex:range.location];
                _textView.attributedText = attr;
                
                NSRange endRange = NSMakeRange(range.location + attachText.length, 0);
                _textView.selectedRange = endRange;
                [_textView scrollRangeToVisible:endRange];
                
            } failureBlock:^(NSError *error) {
                
            }];`

**Comment by ibireme** [comment]
Fixed.
