### ISSUE TITLE
YYTextView 会响应键盘通知自动调整 inset

### ISSUE THREAD

**Issue by heqichang** [ibireme/YYText#263]
Hi,

我测试 YYTextView 会响应键盘通知自动调整 inset。我可以停用这个功能吗？没有发现方法怎么停用。因为我在键盘上面还有一层 ToolView ，ToolView 是在键盘升起的时候才会出现，然后 ToolView 就会遮盖住部分 YYTextView。

<img width="316" alt="454ecb2a-31aa-40d4-b0fd-1900e7872209" src="https://cloud.githubusercontent.com/assets/717699/14276814/e32252ea-fb52-11e5-9e69-c66583be1626.png">

**Comment by ibireme** [comment]
可以设置一下 textView. extraAccessoryViewHeight。

**Comment by heqichang** [comment]
@ibireme
cool, 回答真迅速。搞定了。看到原来你预留了 AccessoryView 来做这事的
