### ISSUE TITLE
手势高亮问题

### ISSUE THREAD

**Issue by FutureChen** [ibireme/YYText#264]
提个优化意见
只设置长按手势的block,  单击的时候也会触发高亮的动画效果

**Comment by ibireme** [comment]
现在就是这样啊。。

**Comment by FutureChen** [comment]
我的意思应该是不需要的吧，比如我只想要长按复制的功能， 然而多了莫名的单击效果。
比如微信的朋友圈， 单击是没有效果的，长按才有全选高亮。

所以，tabAction设置nil的时候，应该不需要高亮效果~~

**Comment by ibireme** [comment]
这个交互的考虑是这样的：

以朋友圈的效果来说，整个 Label 具有一个高亮效果，当长按后，Label.highlighted 被设置为 YES，然后当用户点击了菜单、或者滑动整个 table view 后，highlighted 被设为 NO。

但换到 YYLabel 这里就不行了，文本中，highlight 的范围可能有多个，并不能用一个属性来控制；还有，如果长按后将 highlight 变为高亮，那如何取消还是得由外部开发者来控制，这里的对外的接口就会变得非常复杂而且不易用。如果有这种需求，我建议开发者可以直接在外部针对整个 label 添加一个 gesture，然后通过修改 label 的背景颜色实现。

另外，在 `只设置长按手势的block, 单击的时候` 这种情况下，如果触摸时没有效果，那用户就得不到反馈了。如果开发者确实不需要效果，那不用给文本添加 highlight 属性就可以了。

**Comment by FutureChen** [comment]
好的，受教，谢谢建议
