### ISSUE TITLE
请教下，如何保存含有YYTextAttachment的NSAttributedString？

### ISSUE THREAD

**Issue by johntaiii** [ibireme/YYText#267]
如题，谢谢。

**Comment by ibireme** [comment]
YYTextAttachment 可能可能会包含 UIView 或 CALayer，所以这里没办法做序列化的支持。。这个可以保存更上一层的原始数据。

**Comment by johntaiii** [comment]
对，我的YYTextAttachment对象确实包含了UIImageView，你是说保存UIImage吗？

**Comment by ibireme** [comment]
一般，应该是拿一些纯文本加上一些元数据生成的 NSAttributedString，这样的话，可以保存这些纯文本和元数据。

另外，可以试试用 YYTextArchiver 来直接序列化 NSAttributedString，但如果里面有不支持序列化的对象（比如 tapBlock、CALayer 等东西），那可能会失败。

**Comment by johntaiii** [comment]
好的， 我试试，谢谢。
