### ISSUE TITLE
AutoLayout的问题

### ISSUE THREAD

**Issue by lexiaoyao20** [ibireme/YYText#269]
```
//label 初始化代码
_titleLabel = [YYLabel new];
    _titleLabel.numberOfLines = 2;
    _titleLabel.font = [UIFont systemFontOfSize:17];
    _titleLabel.textColor = [themeMgr colorForKey:@"TextColor"];
    _titleLabel.lineBreakMode = NSLineBreakByTruncatingTail;
    _titleLabel.displaysAsynchronously = YES;
    _titleLabel.ignoreCommonProperties = NO;
    _titleLabel.fadeOnAsynchronouslyDisplay = NO;
    _titleLabel.fadeOnHighlight = NO;
    _titleLabel.textVerticalAlignment = YYTextVerticalAlignmentTop;
    [self.containerView addSubview:_titleLabel];

//使用Masonry进行自动布局
[self.titleLabel mas_makeConstraints:^(MASConstraintMaker *make){
        make.top.left.right.equalTo(self.containerView);
    }];
```
我设置了numberOfLines=2，使用了自动布局，但是只显示了一行，不知道是哪里出问题了，麻烦YY大神帮我看下

我使用的YYText的版本是 - YYKit (1.0.3)
![示例图](https://cloud.githubusercontent.com/assets/3021017/14340193/c223565a-fcb7-11e5-9549-4aef7b24ae56.png)

**Comment by ibireme** [comment]
设置一下 preferredMaxLayoutWidth 看看。

**Comment by lexiaoyao20** [comment]
设置了 preferredMaxLayoutWidth 可以解决问题
不过我试了UILabel，不用设置preferredMaxLayoutWidth也能显示两行，这个能不能改进下？

**Comment by ibireme** [comment]
目前没有什么好的办法。。如果你有好办法希望能帮忙改进一下这块儿。
（另外，UILabel 在某些情况下不设置这个属性也会有问题。。）

**Comment by LawrenceHan** [comment]
别偷懒。。。直接用YYTextLayout算出高宽，然后赋值就可以了。。。

**Comment by wy19901227** [comment]
这不是偷懒，人家用自动布局呢，高度自然不用算，但是这个布局的宽度你必须要设置，ios7以后uilabel不用设置，估计是apple在布局的时候，自己算的

发自我的 iPhone

**Comment by LawrenceHan** [comment]
如果只是普通label，不要用YYLabel。YYLabel是为了复杂需求和性能设计的。

**Comment by starFelix** [comment]
监听frame变化，同步设置preferredMaxLayoutWidth

**Comment by kharmabum** [comment]
Can some explain in English how to approach this problem? I'd really appreciate it! cc @ibireme @wy19901227 🙇

**Comment by kharmabum** [comment]
Well. I think I figured it out. By setting `preferredMaxLayoutWidth` to the max available width of the label, autolayout appears to be working correctly. @ibireme, thanks for such an incredibly powerful library.
