### ISSUE TITLE
关于placeholder的问题

### ISSUE THREAD

**Issue by wangyanlong** [ibireme/YYText#271]
<img width="375" alt="69c23a15-446b-438e-b58d-8448aa6b1027" src="https://cloud.githubusercontent.com/assets/5455698/14344378/ce062566-fcd9-11e5-87e7-7eae7c401130.png">
请问为什么placeholder上面会空出一行呢,怎么处理这个问题,怎么让他到第一行开始显示

**Comment by ibireme** [comment]
看看是否设置了 textContainerInset 或者 exclusionPaths。
另外，也可以打开调试模式看看具体排版是什么样的：

    YYTextDebugOption *debugOptions = [YYTextDebugOption new];
    debugOptions.baselineColor = [UIColor redColor];
    debugOptions.CTFrameBorderColor = [UIColor redColor];
    debugOptions.CTLineFillColor = [UIColor colorWithRed:0.000 green:0.463 blue:1.000 alpha:0.180];
    debugOptions.CGGlyphBorderColor = [UIColor colorWithRed:1.000 green:0.524 blue:0.000 alpha:0.200];
    [YYTextDebugOption setSharedDebugOption:debugOptions];

**Comment by wangyanlong** [comment]
我并没有设置textContainerInset 或者 exclusionPaths 
我按照您的方法调试了一下,发现是CTFrameBorderColor的问题
如图
<img width="367" alt="c70ae16c-2dcf-43f3-a296-48e34c9b6712" src="https://cloud.githubusercontent.com/assets/5455698/14345952/59c7327c-fce2-11e5-8e89-760dc9d719c3.png">

**Comment by wangyanlong** [comment]
我的代码,在我的项目里就是这样,但是如果我单独创建一个工程,就没事...奇怪了...
    self.textView = [YYTextView new];
    self.textView.textParser = parser;
    self.textView.placeholderText = @"我是placeholderText";
    self.textView.delegate = self;
    self.textView.backgroundColor = [UIColor whiteColor];
    self.view.backgroundColor = [UIColor grayColor];
    
    [self.view addSubview:self.textView];
    
    [self.textView mas_makeConstraints:^(MASConstraintMaker *make) {
        
        make.top.mas_equalTo(ws.view.mas_top).offset(20);
        make.left.mas_equalTo(ws.view.mas_left).offset(10);
        make.height.mas_equalTo(100);
        make.right.mas_equalTo(ws.view.mas_right).offset(-10);
        
    }];

**Comment by ibireme** [comment]
那这个就不太清楚了。。

**Comment by wangyanlong** [comment]
好的,感谢

**Comment by huayangyu** [comment]
@wangyanlong 我遇到的时候是和navigationBar的transclunt有关，我改成NO，就显示正常了
