### ISSUE TITLE
yy_font 字体 与系统字体有区别

### ISSUE THREAD

**Issue by xingyong723** [ibireme/YYText#272]
将yy_font设置成 [UIFont systemFontOfSize:14]   赋值给YYlabel
 
为啥YYlabel的字体，和系统UILabel的字体不一样？

**Comment by ibireme** [comment]
具体有什么不一样的，能详细说明一下吗？

**Comment by yuyedaidao** [comment]
![6c8ae073-5f74-4ac9-9cdc-7fb14f422103](https://cloud.githubusercontent.com/assets/6354958/14662380/1a88ec12-06e8-11e6-9b2c-8388f6267297.png)

**Comment by ibireme** [comment]
更新到当前最新版本。

**Comment by yuyedaidao** [comment]
已解决，多谢
