### ISSUE TITLE
YYLabel的 IB_DESIGNABLE 好像有问题。 

### ISSUE THREAD

**Issue by developforapple** [ibireme/YYText#274]
在xib中拖进去一个View，修改类名为 YYLabel。 然后就会报错

error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)
error: IB Designables: Failed to render instance of YYLabel: Failed to load designables from path (null)

Xcode 7.3下出现的

**Comment by ibireme** [comment]
对于 Xcode Designable 的问题，照我的经验：

1. 清空缓存
2. 不行的话重启 Xcode
3. 还不行重启系统
4. [摊手] 手写代码来做吧，或者干脆换个其他的库试试看。。

**Comment by wy19901227** [comment]
yy哥，是那个podfile需要加个use_framworks!，然后就可以了，但是加了这个东西其他得库可能出问题，我的就是，我处理办法就是禁止IB_DESIGNALE

发自我的 iPhone

**Comment by developforapple** [comment]
目前只能不用cocoapods咯，搜索了下 好像是Xcode的BUG，很久了的BUG

**Comment by wy19901227** [comment]
可以啊，不是说了加个命令吗

发自我的 iPhone

**Comment by WangGuibin** [comment]
是的 我也遇到了, 这个问题其实很简单 直接导进去用就是了,不要用pod , 经常要更新的话,那还是用其他的库吧 /机智
