### ISSUE TITLE
请教下YYTextArchiver

### ISSUE THREAD

**Issue by v2panda** [ibireme/YYText#276]
由于需要在 iOS 设备本地保存，用 YYTextArchiver 和 YYTextUnarchiver 来序列化 NSAttributedString，

Unarchiver后AttributedString的数据变化导致YYTextView显示不了图片。

如下，使用yy_archiveToData前的AttributedString
   ```
 CTForegroundColor = "<CGColor 0x7fa3a2d081d0> [<CGColorSpace 0x7fa3a2f24380> (kCGColorSpaceDeviceGray)] ( 0.333333 1 )";
    CTRunDelegate = "<CTRunDelegate 0x7fa3a2d2b200 [0x105da6a40]>";
    NSColor = "UIDeviceWhiteColorSpace 0.333333 1";
    YYTextAttachment = "<YYTextAttachment: 0x7fa3a2d268c0>";
    YYTextBackgroundBorder = "<YYTextBorder: 0x7fa3a2d2f330>";
    YYTextHighlight = "<YYTextHighlight: 0x7fa3a2d23b70>";
```
和yy_unarchiveFromData后的AttributedString
```
CTForegroundColor = "<CGColor 0x7fa3a2ec4450> [<CGColorSpace 0x7fa3a2f24380> (kCGColorSpaceDeviceGray)] ( 0.333333 1 )";
    CTRunDelegate = "<CTRunDelegate 0x7fa3a2ec41d0 [0x105da6a40]>";
    NSColor = "UIDeviceWhiteColorSpace 0.333333 1";
    YYTextAttachment = "<YYTextAttachment: 0x7fa3a5046990>";
    YYTextBackgroundBorder = "<YYTextBorder: 0x7fa3a5044650>";
    YYTextHighlight = "<YYTextHighlight: 0x7fa3a5023570>";
```

以上的几个属性在unarchive后都发生变化，造成图片不能显示。

有没有比较好的解决办法呢？谢谢！

**Comment by ibireme** [comment]
光看上面打印的内容，看不出来"属性发生变化"。。

你可以检查下 YYTextAttachment.content 内容是否有变化。另外，如果这里面有 UIView/CALayer 等元素，那需要检查下 archive/unarchive 是否在主线程进行。

**Comment by v2panda** [comment]
具体的说是
1.AttributedString里有image 
2.archive/unarchive操作是在主线程执行的
3.下面unarchive后的YYTextAttachment.content为空

目前我是把archive之前的AttributedString里的image取出来，存到数组里，然后再往unarchive后的AttributedString里添加
折腾了一回....

**Comment by ibireme** [comment]
如果图片是用 [UIImage imageNamed:] 创建的，那这个 Image 是无法 archive 的，这是 UIImage 本身的设计。

**Comment by v2panda** [comment]
学到了，谢谢！

**Comment by tounaobun** [comment]
> 如果图片是用 [UIImage imageNamed:] 创建的，那这个 Image 是无法 archive 的，这是 UIImage 本身的设计。

果然，用[UIImage contentsOfFile:]就可以archive了。
