### ISSUE TITLE
crash on 8.1.1

### ISSUE THREAD

**Issue by kinglezhuang** [ibireme/YYText#277]
When we long press on YYTextView, it will crash on 8.1.1 or 8.0.1
- (CGFloat)_updateMagnifier:(YYTextMagnifier *)mag {
    UIApplication *app = YYTextSharedApplication();
    if (!app) return 0;
    
    UIView *hostView = mag.hostView;
    UIWindow *hostWindow = [hostView isKindOfClass:[UIWindow class]] ? (id)hostView : hostView.window;
    if (!hostView || !hostWindow) return 0;
    CGPoint captureCenter = [self yy_convertPoint:mag.hostCaptureCenter fromViewOrWindow:hostView];
    captureCenter = [self _correctedCaptureCenter:captureCenter];
    CGRect captureRect = {.size = mag.snapshotSize};
    captureRect.origin.x = captureCenter.x - captureRect.size.width / 2;
    captureRect.origin.y = captureCenter.y - captureRect.size.height / 2;
    
    CGAffineTransform trans = YYTextCGAffineTransformGetFromViews(hostView, self);
    CGFloat rotation = YYTextCGAffineTransformGetRotation(trans);
    
    if (mag.captureDisabled) {
        if (!mag.snapshot || mag.snapshot.size.width > 1) {
            static UIImage *placeholder;
            static dispatch_once_t onceToken;
            dispatch_once(&onceToken, ^{
                CGRect rect = mag.bounds;
                rect.origin = CGPointZero;
                UIGraphicsBeginImageContextWithOptions(rect.size, NO, 0);
                CGContextRef context = UIGraphicsGetCurrentContext();
                [[UIColor colorWithWhite:1 alpha:0.8] set];
                CGContextFillRect(context, rect);
                placeholder = UIGraphicsGetImageFromCurrentImageContext();
                UIGraphicsEndImageContext();
            });
            mag.captureFadeAnimation = YES;
            mag.snapshot = placeholder;
            mag.captureFadeAnimation = NO;
        }
        return rotation;
    }
    
    UIGraphicsBeginImageContextWithOptions(captureRect.size, NO, 0);
    CGContextRef context = UIGraphicsGetCurrentContext();
    if (!context) return rotation;
    
    CGPoint tp = CGPointMake(captureRect.size.width / 2, captureRect.size.height / 2);
    tp = CGPointApplyAffineTransform(tp, CGAffineTransformMakeRotation(rotation));
    CGContextRotateCTM(context, -rotation);
    CGContextTranslateCTM(context, tp.x - captureCenter.x, tp.y - captureCenter.y);
    
    NSMutableArray *windows = app.windows.mutableCopy;
    UIWindow *keyWindow = app.keyWindow;
    if (![windows containsObject:keyWindow]) [windows addObject:keyWindow];
    [windows sortUsingComparator:^NSComparisonResult(UIWindow *w1, UIWindow *w2) {
        if (w1.windowLevel < w2.windowLevel) return NSOrderedAscending;
        else if (w1.windowLevel > w2.windowLevel) return NSOrderedDescending;
        return NSOrderedSame;
    }];
    UIScreen *mainScreen = [UIScreen mainScreen];
    for (UIWindow *window in windows) {
        if (window.hidden || window.alpha <= 0.01) continue;
        if (window.screen != mainScreen) continue;
        if ([window isKindOfClass:self.class]) break; //don't capture window above self
        CGContextSaveGState(context);
        CGContextConcatCTM(context, YYTextCGAffineTransformGetFromViews(window, self));
[[crash on this line]]        [window.layer renderInContext:context]; //render
        //[window drawViewHierarchyInRect:window.bounds afterScreenUpdates:NO]; //slower when capture whole window
        CGContextRestoreGState(context);
    }
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    if (mag.snapshot.size.width == 1) {
        mag.captureFadeAnimation = YES;
    }
    mag.snapshot = image;
    mag.captureFadeAnimation = NO;
    return rotation;
}

**Comment by kinglezhuang** [comment]
[[crash on this line]] [window.layer renderInContext:context]; //render

**Comment by kinglezhuang** [comment]
captureRect is Zero, need to check it first

**Comment by kinglezhuang** [comment]
can not support spellCheckingType

**Comment by kinglezhuang** [comment]
can not support autocorrectionType

**Comment by ibireme** [comment]
1. The crash could not reproduce, but I will do more check later.
2. It doesn't support spellCheckingType or autocorrectionType.

**Comment by kinglezhuang** [comment]
How to support  spellCheckingType or autocorrectionType, There many bugs for that, can you tell me how to fix it.

**Comment by kinglezhuang** [comment]
小伙，你这个很多bug，我用您的东西做项目，搞大了

**Comment by kinglezhuang** [comment]
光标也会跳来跳去
重现步骤：
开启autocapital 模式，　输入几个字符用手把光标定位到大写字母前再输入，我点发送按钮清输入框，光标没了

**Comment by kinglezhuang** [comment]
你在不在软件园，我去找你玩大了

**Comment by ibireme** [comment]
1. 如果要实现 spellCheckingType 和 autocorrectionType 的话，需要用 UITextChecker 等工具去在每次文本发生变化时检查全部文本、然后为错误文本等添加红点下划线，并添加手势监听点击事件，还要处理点击后的逻辑、弹出菜单、单词替换、记忆等逻辑，工程量非常大。

2. 目前已知的 bug，只有处理输入法英文联想时，光标会定位不准的问题，其他上面的描述都暂时无法复现。这可能与内部通知 inputDelegate 的顺序有关，但由于这个没有文档，只能去调试系统组件来猜测用法。这个项目目前只是个人的开源项目，我并没有时间和精力来处理难以复现的问题。如果你能复现和解决问题，欢迎提 PR 来一起改进。
