### ISSUE TITLE
YYLabel 中文Italic支持问题

### ISSUE THREAD

**Issue by kinglezhuang** [ibireme/YYText#279]
不支持中文Italic

**Comment by ibireme** [comment]
Italic 本身是由字体支持的，iOS 中的中文字体并不包含 Italic，所以实际上 iOS 是不支持中文 Italic 的。

YYText 支持用 TextGlyphTransform 来进行字体变形：

    [text yy_setTextGlyphTransform:YYTextCGAffineTransformMakeSkew(-0.3, 0) range:NSMakeRange(0, text.length)];

这样可以模拟 Italic，看上去可能差别不大，但算不上真正的 Italic。
