### ISSUE TITLE
UIStatusBarStyle does not become LightContents

### ISSUE THREAD

**Issue by jstarfruits** [ibireme/YYText#28]
UIStatusBarStyle does not become LightContents after the YYTextEffectWindow.sharedWindow is created.
Do you have a workaround?

**Comment by ibireme** [comment]
I have tested it in my demo:
Set `View controller-based status bar appearance` to NO in your app's info.plist, and use [UIApplication sharedApplication].statusBarStyle to control the status bar style.

**Comment by jstarfruits** [comment]
I will use that workaround now, but I think it will be better to be able to use preferedStatusBarStyle in the future, because it will help prevent future bugs.

**Comment by seedotlee** [comment]
+1 
In iOS 9 [UIApplication sharedApplication].statusBarStyle was deprecated.

**Comment by ibireme** [comment]
It seems to be a bug of UIWindow and UIViewController. See this question: http://stackoverflow.com/questions/19617122/uistatusbarstyle-changes-after-dispaying-a-uiwindow-over-uistatusbar

I tried some solutions. It seems that I should create all my custom UIWindow in `application:didFinishLaunchingWithOptions` method to avoid this problem...

**Comment by ibireme** [comment]
Fixed

**Comment by seedotlee** [comment]
cool

**Comment by jstarfruits** [comment]
cool!

**Comment by swsdyg** [comment]
@ibireme 你好，能说一下你解决状态栏变黑的方法吗，我没有使用您的这个库，但我现在也遇到了同样的问题，希望能不吝赐教，谢谢
