### ISSUE TITLE
YYLabel的显示问题

### ISSUE THREAD

**Issue by Hanwp** [ibireme/YYText#280]
![Uploading QQ20160414-0@2x.png…]()
我设置了@用户和链接等属性，然后导致 “打发”后面空了好多。为什么不会换行显示呢。

**Comment by ibireme** [comment]
空格是不会触发换行的，这个可以拿系统的备忘录试试看。

**Comment by Hanwp** [comment]
图片一致上床失败，我在描述一下吧。就是
呵呵呵 @这段文字如果在这一行显示不下的话，就直接换行了。导致呵呵呵后面空了好多。
怎么解决。

**Comment by ibireme** [comment]
根据你的需求调整 lineBreakMode

**Comment by Hanwp** [comment]
YYLabel *label = [YYLabel new];
    label.textVerticalAlignment = YYTextVerticalAlignmentTop;
    label.displaysAsynchronously = YES;
    label.ignoreCommonProperties = YES;
    label.fadeOnAsynchronouslyDisplay = NO;
    label.fadeOnHighlight = NO;
    __weak YYLabel *weakLabel = label;
    label.highlightTapAction = ^(UIView *containerView, NSAttributedString *text, NSRange range, CGRect rect) {
        
        YYTextHighlight *highlight = [weakLabel.textLayout.text yy_attribute:YYTextHighlightAttributeName atIndex:range.location];
        NSDictionary *info = highlight.userInfo;
        
        NSLog(@"info = %@", info);
    };

    
    label.lineBreakMode = NSLineBreakByClipping;
    label.font = [UIFont systemFontOfSize:14];
    label.backgroundColor = [UIColor lightGrayColor];
    label.frame = CGRectMake(20, 100, layout.textBoundingSize.width, layout.textBoundingSize.height);
    label.textLayout = layout;
    [self.view addSubview:label];

**Comment by Hanwp** [comment]
调整了，没有效果
```
    NSAttributedString *text = [self pipeiAt:@"法[便便]1212131312312312312312312313131131313131#zhoujielun#师 #112233# www.baidu.com[偷笑]打发@helffdfdfdfdfdffdfdffffflo 哈[亲亲]哈http://www.baidu.com哈@nimen 哈哈@jj 哈哈[再见]哈[吓]哈"];
    CGSize size = CGSizeMake(200, CGFLOAT_MAX);
    YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:size text:text];
```

**Comment by Hanwp** [comment]
法[便便]
1212131312312312312312312313131131313131

显示效果就是这样。表情后面空了好多

**Comment by Hanwp** [comment]
lineBreakMode 换哪个都不行，请帮我看下是怎么回事，是我代码写的有问题吗

**Comment by ibireme** [comment]
没有图片的话，还是不清楚是什么问题

**Comment by Hanwp** [comment]
![yylabel](https://cloud.githubusercontent.com/assets/10218623/14549149/e919ef6a-02ef-11e6-8cb2-7c285ab29942.png)

**Comment by Hanwp** [comment]
终于把图片搞上去了，还请作者好好看下，多谢！

**Comment by ibireme** [comment]
如果用 textLayout 的话，lineBreakMode 应该直接加到 attributedString 上：text.yy_lineBreakMode = NSLineBreakByCharWrapping;

另外，可以开启 Debug 模式来看看空白地方是什么排版结果。

    YYTextDebugOption *debugOptions = [YYTextDebugOption new];
    debugOptions.baselineColor = [UIColor redColor];
    debugOptions.CTFrameBorderColor = [UIColor redColor];
    debugOptions.CTLineFillColor = [UIColor colorWithRed:0.000 green:0.463 blue:1.000 alpha:0.180];
    debugOptions.CGGlyphBorderColor = [UIColor colorWithRed:1.000 green:0.524 blue:0.000 alpha:0.200];
    [YYTextDebugOption setSharedDebugOption:debugOptions];

注意一下是空格、换行符还是其他东西。

**Comment by Hanwp** [comment]
ok,解决了。多谢。
