### ISSUE TITLE
部分文本不能正常显示

### ISSUE THREAD

**Issue by Rick630** [ibireme/YYText#281]
你好，我在工程里面使用YYText进行图文混排，遇到一个比较奇怪的情况，
部分情况正常赋值时文字不能正常显示（在模拟器上必现，真机调试上偶现），大概效果如

正常情况

![](https://github.com/Rick630/yytextDemo/raw/master/Screen%20Shot%202016-04-16%20at%206.15.47%20PM.png)

不正常显示

![](https://github.com/Rick630/yytextDemo/raw/master/Screen%20Shot%202016-04-16%20at%206.16.43%20PM.png)

方便的话麻烦移步demo
https://github.com/Rick630/yytextDemo

不知道是什么原因，希望能帮忙看下，谢谢

**Comment by ibireme** [comment]
请在真机上测试。

**Comment by Rick630** [comment]
@ibireme 真机上也出现过这种情况，可是几率比较少

**Comment by ibireme** [comment]
这么说，YYLabel 是通过创建一个 bitmap 来绘制文本的。

模拟器上，受限于 GPU 的 texture 大小（可能是模拟器的 bug），bitmap 宽高是不能超过 4096 的。
真机上不会受到这个限制，但仍然会受限于空闲内存大小。

**Comment by Rick630** [comment]
@ibireme 感谢回答，的确是attributeString中包含太多图片，导致高度太大的原因
