### ISSUE TITLE
subclass yytextattachment

### ISSUE THREAD

**Issue by skipness** [ibireme/YYText#283]
I am trying to implement the following sample code in swift version but I got some problems. Is it possible to do it in swift? 
[https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/WBStatusLayout.m#L67-L93](url)
![untitled](https://cloud.githubusercontent.com/assets/8035517/14593875/8a81e672-0562-11e6-8a56-2772d1e0ae61.jpg)

**Comment by ibireme** [comment]
I don't know, but I think it's a question about Swift language, not about this library.
