### ISSUE TITLE
设置斜体变换的时候绘制有点问题

### ISSUE THREAD

**Issue by semazengyi** [ibireme/YYText#284]
如果前一个attributedString是斜体的，后一个不是，会出现接下去几个字符位置错位
![1](https://cloud.githubusercontent.com/assets/3383471/14598026/e9b9deb8-0582-11e6-85a9-eeaa3b7aca10.png)
如图，最后一个a是接着输入的，但是位置确漂移了

设置斜体的代码
```
NSNumber *textGlyphTransform = self.sheetStyle[@"italic"];
    if (textGlyphTransform) {
        text.textGlyphTransform = CGAffineTransformMakeSkew(textGlyphTransform.floatValue, 0);
    }
    else
    {
        text.textGlyphTransform = CGAffineTransformMakeSkew(0, 0);
    }

```

**Comment by ibireme** [comment]
建议先开启 Debug 模式看一下页面中的排版结果：

    YYTextDebugOption *debugOptions = [YYTextDebugOption new];
    debugOptions.baselineColor = [UIColor redColor];
    debugOptions.CTFrameBorderColor = [UIColor redColor];
    debugOptions.CTLineFillColor = [UIColor colorWithRed:0.000 green:0.463 blue:1.000 alpha:0.180];
    debugOptions.CGGlyphBorderColor = [UIColor colorWithRed:1.000 green:0.524 blue:0.000 alpha:0.200];
    [YYTextDebugOption setSharedDebugOption:debugOptions];

**Comment by semazengyi** [comment]
debug的结果
![12](https://cloud.githubusercontent.com/assets/3383471/14670786/226f3dee-0721-11e6-97dc-d157e90e5925.png)
挺多情况会出现这样的情况，大多出现在attributed属性不同的情况下。我在看看

**Comment by ibireme** [comment]
<img width="317" alt="2016-04-20 6 02 14" src="https://cloud.githubusercontent.com/assets/839283/14670978/11d77f40-0722-11e6-8755-ed2a2066ff82.png">

复现不了。。
建议看看 attributedText 中的 textGlyphTransform 是否有其它位移。

**Comment by semazengyi** [comment]
我有个百分百复现的步骤，首先写一串文字，然后选择从头开始的一部分，使选择的这部分变换斜体，后面的部分就漂移了

**Comment by ibireme** [comment]
但是我并没有你的代码啊。。又不能帮你调试。。
所以说，贴一下你的代码或者给一个能复现问题的 Demo（上面贴出的那段设置斜体的代码并不能复现问题，而且我也不清楚`self.sheetStyle[@"italic"]` 的上下文是什么）。或者你自己打印一下 textView 中  attributedText 中的 textGlyphTransform，看看是否有不对的位移。

从上面的截图看着，像是用了 CGAffineTransformMakeTranslation 之类的位移设置。

**Comment by semazengyi** [comment]
我来提供一个demo

**Comment by semazengyi** [comment]
我直接在你Demo中的`YYTextEditExample`这个类里面改了，也一样重现。
替换 _verticalSwitch 事件处理block
```
  [_verticalSwitch addBlockForControlEvents:UIControlEventValueChanged block:^(UISwitch *switcher) {
        CGAffineTransform transform = CGAffineTransformIdentity;
        transform.c = -0.3;
        transform.b = 0;
        NSMutableAttributedString *text = [[NSMutableAttributedString alloc]initWithAttributedString:textView.attributedText];
        [text yy_setTextGlyphTransform:transform range:textView.selectedRange];
        textView.attributedText = text;
    }];
```

选择一段文字，然后点_verticalSwitch结果是
![321](https://cloud.githubusercontent.com/assets/3383471/14672879/2dba3bd4-072d-11e6-9f52-89aa1a7e0e8e.png)

**Comment by ibireme** [comment]
<img width="487" alt="2016-04-20 9 53 31" src="https://cloud.githubusercontent.com/assets/839283/14677006/57d01528-0742-11e6-8bee-7b2c7f3a2c6f.png">

仍然不能复现。。

**Comment by ibireme** [comment]
能够重现，稍后会调试一下来看看是什么问题。

**Comment by semazengyi** [comment]
好的，辛苦了

**Comment by ibireme** [comment]
Fixed: https://github.com/ibireme/YYText/releases/tag/1.0.5
