### ISSUE TITLE
点击事件不被触发

### ISSUE THREAD

**Issue by wfkbyni** [ibireme/YYText#286]
// 1. 创建一个属性文本
            NSMutableAttributedString *text = [[NSMutableAttributedString alloc] initWithString:@"Some Text, blabla..."];

            // 2. 为文本设置属性
            text.yy_font = [UIFont boldSystemFontOfSize:30];
            text.yy_color = [UIColor blueColor];
            [text yy_setColor:[UIColor redColor] range:NSMakeRange(0, 4)];
            text.yy_lineSpacing = 10;

            // 3. 赋值到 YYLabel 或 YYTextView
            YYLabel *label = [YYLabel new];
            label.frame = CGRectMake(20, 2, self.moreView.frame.size.width - 40, 36);
            label.attributedText = text;
            [self.moreView addSubview:label];

            [text yy_setTextHighlightRange:NSMakeRange(0, text.length) color:[UIColor redColor] backgroundColor:[UIColor greenColor] tapAction:^(UIView * _Nonnull containerView, NSAttributedString * _Nonnull text, NSRange range, CGRect rect) {

            }];

text的tapAction不会被触发！！！！

**Comment by ibireme** [comment]
为什么要加这么多叹号。。。。

可以检查下 Label 或 TextView 的触摸事件是否被禁用了、是否有其它手势（尤其是 TapGesture）阻碍了触摸流程。

**Comment by yishuiliunian** [comment]
在UIScrollView中使用YYLabel，触摸时间很容易走到

- (void)touchesCancelled:(NSSet *)touches withEvent:(UIEvent *)event {
    [self _endTouch];
    if (!_state.swallowTouch) [super touchesCancelled:touches withEvent:event];
}

而非预期的- (void)touchesEnded:(NSSet *)touches withEvent:(UIEvent *)event  去触发tapAction，为何这样？

**Comment by ibireme** [comment]
注意 UIScrollView 的 delaysContentTouches 和 canCancelContentTouches 这两个属性。

**Comment by yishuiliunian** [comment]
这两个属性，调整之后，对上述问题，没有影响。

**Comment by ibireme** [comment]
YYLabel  是继承自 UIView，然后重写了 UIResponder 的 `touchesBegan` `touchesMoved` `touchesEnded` 和 `touchesCancelled` 这四个方法来监听触摸事件的，这里没有做其他多余的处理。

UIScrollView 自带一个 PanGesture，而这个 Gesture 会优先拦截触摸事件，并在识别到 Pan 动作时取消掉其他触摸流程，这时 YYLabel 就会走到 `touchesCancelled` 去了。如果设置一下 UIScrollView 的属性，delaysContentTouches = YES, canCancelContentTouches = NO 这样就不会进入`touchesCancelled` 了，但这会产生一些副作用（手指落到 Label 后不动，0.5 秒后再滑动就没效果了）。

如果你测试这两个属性不起作用，看看整个视图层级中是否还有其他 Gesture 或触摸拦截操作（比如 TableView/Cell 由苹果内嵌的一些自定义 Gesture 也会有影响）。
