### ISSUE TITLE
YYLabel回车问题

### ISSUE THREAD

**Issue by kinglezhuang** [ibireme/YYText#287]
我把一个字符串包含回车符\n传入YYlabel，　接下来取出来的self.attributedText.string　或者self.text回车都变成unicode，　我在swift下就变成\u{e2}页不是\n

**Comment by ibireme** [comment]
YYLabel 内部并没有对字符串进行其它处理。。仅仅有 copy 或 转换成 NSAttributedString 这样的操作。

至于打印出来的结果，是由 NSString 和 NSAttributedString 控制的。
