### ISSUE TITLE
使用YYTextView会截获window上得点击事件

### ISSUE THREAD

**Issue by zhangshuaijiayanni** [ibireme/YYText#288]
控制器自带的View用YYTextView替代, 当使用window进行弹窗, YYTextView会截获window上得button点击事件, 造成YYTextView变成第一响应者, 而无法进行window上button的点击事件

**Comment by GIKIios** [comment]
遇到了同样的问题YYTextEffectWindow 会变成keywindow 导致当前弹层不可操作

**Comment by ibireme** [comment]
更新到最新版试试：
https://github.com/ibireme/YYText/releases/tag/1.0.5
