### ISSUE TITLE
能否只改变高亮文本的颜色

### ISSUE THREAD

**Issue by jasonzb** [ibireme/YYText#289]
能否只改变高亮文本的颜色？

**Comment by ibireme** [comment]
https://github.com/ibireme/YYText#文本高亮

    YYTextHighlight *highlight = [YYTextHighlight new];
    [highlight setColor:[UIColor whiteColor]];

**Comment by jasonzb** [comment]
谢谢，我试过了，这样只改变了点击后的颜色，我找到了其他方法
[attributedText yy_setTextHighlight:highlight range:range];
