### ISSUE TITLE
类YYTextLayout中的YYTextDrawBorder方法崩溃

### ISSUE THREAD

**Issue by tianglin** [ibireme/YYText#290]
![2016-04-25 10 55 46](https://cloud.githubusercontent.com/assets/1657594/14772756/4d996fce-0ad4-11e6-9cfe-11a6472fa8bd.png)

![2016-04-25 10 57 52](https://cloud.githubusercontent.com/assets/1657594/14772783/99ab9608-0ad4-11e6-9dd5-adee9661fada.png)

![2016-04-25 11 00 10](https://cloud.githubusercontent.com/assets/1657594/14772807/ec33d3d6-0ad4-11e6-89c3-f63449955de3.png)

博主您好，我用了YYLabel，显示一段苹果自带的emoji，并且加了单击和长按事件，单击是没问题，长按的时候出现如上图的崩溃。而且我发现，用+ (YYTextLayout *)layoutWithContainerSize:(CGSize)size text:(NSAttributedString *)text;这个方法去计算这个这段emoji的高度不准确，导致label后面显示3个点号；

我手动把那个方法计算的高度再多加一些，就会显示全，长按也不会崩溃了。

**Comment by ibireme** [comment]
更新到最新版试试：https://github.com/ibireme/YYText/releases/tag/1.0.5

另外，上面那块儿，计算出 layout 后，可以直接赋值给 label 来显示了 `self.messageLabel.textLayout = layout`

崩溃的问题我再多添加一些校验。

**Comment by tianglin** [comment]
抱歉博主，昨天已经解决了，忘记close。感谢博主
