### ISSUE TITLE
YYLabel  lineBreakMode  不起作用

### ISSUE THREAD

**Issue by enrecul** [ibireme/YYText#293]
已设置displaysAsynchronously = NO。

调整YYLable的lineBreakMode，不起作用。感觉一直是NSLineBreakByWordWrapping模式。

**Comment by ibireme** [comment]
注意看下注释：
设置了 `attributedText` 后，attributedText 的属性会替换 label 中对应的 property (例如 lineBreakMode)，
设置了 `textLayout` 后，textLayout 的属性会替换 label 中对应的 property (也包括 lineBreakMode)。

**Comment by enrecul** [comment]
"设置了 attributedText 后，attributedText 的属性会替换 label 中对应的 property"

**Comment by enrecul** [comment]
谢谢，是我没有理解对。

**Comment by wishsoul** [comment]
依然不起作用
`[resultAttrString setYy_lineBreakMode:NSLineBreakByTruncatingMiddle];`
