### ISSUE TITLE
Demo有bug

### ISSUE THREAD

**Issue by 108FZ** [ibireme/YYText#296]
YYTextBindingExample中,当光标靠近正则表达式的文字再离开的时候,文字颜色就变成蓝色.重现方法:打开Demo,按一下delete键,再按一下空格,然后输入文字,就变成蓝色的了

**Comment by ibireme** [comment]
https://github.com/ibireme/YYText/issues/11

**Comment by 108FZ** [comment]
不好意思,没看懂怎么解决...

**Comment by ibireme** [comment]
不影响功能演示，所以不打算改了啊😷

**Comment by 108FZ** [comment]
那有没有办法解决这个bug呢
