### ISSUE TITLE
网络图片加载显示的问题请教（希望博主写个简单demo）

### ISSUE THREAD

**Issue by Jacky-LinPeng** [ibireme/YYText#297]
我看了别人好像也有问过 但是 你都是给他们看了一个新浪微博的一个源码  那段好长的代码 我看蒙圈了  能不能写一个更简单易懂的例子在demo里面呀  希望你有时间帮助我们  因为我觉得应该有很多人跟我有一样的需求

**Comment by ibireme** [comment]
具体是什么样的需求？

**Comment by lihj** [comment]
估计就是YYLabel加载网络图片了

**Comment by Denghuajie** [comment]
@"对不对<img src="网络图片url" />对嘞"，请问类似这样的字符串，拿到后如何在label或textView中加载出有图片的富文本

**Comment by Denghuajie** [comment]
中间是带有标签的网络图片的url

**Comment by ibireme** [comment]
如果数据量小、或者 UI 性能不太敏感，直接全放到主线程去创建就好，然后图片用 UIImageView 作为 Attachment，之后就可以用 WebImage 之类的组件来设置网络图片了。

如果一定需要放到后台线程创建，那可以子类化 Attachment 来判断线程，就像这样：https://github.com/ibireme/YYKit/blob/master/Demo/YYKitDemo/WBStatusLayout.m#L70-L93
