### ISSUE TITLE
YYTextView 用于显示在tableView的cell里面，添加的约束，快速滚动的时候改变约束yytextview的显示会错乱

### ISSUE THREAD

**Issue by nizenyang** [ibireme/YYText#299]
如题，具体情况是 添加约束，显示的是图文混排，快速滚动tableview的时候，修改left 和 right 的约束，速度很快的时候，显示会错乱，应该显示靠左边的显示变成靠右边显示，我是用于聊天界面的设计

**Comment by ibireme** [comment]
left 和 right 约束具体是指什么？如果单纯只是 constraints 的话，应该与 YYLabel 内部的逻辑没关系。

**Comment by wy19901227** [comment]
写个简单重现问题的demo上来看看。

**Comment by nizenyang** [comment]
暂时先关闭这个问题吧，去年出现的问题，后面没用，现在用的时候暂时没出现
