### ISSUE TITLE
如何实现文字颠倒混排？

### ISSUE THREAD

**Issue by SeanChense** [ibireme/YYText#30]
![](http://ww3.sinaimg.cn/large/006c3h06gw1eya2h81lq2j30kg0aoq4z.jpg)

请问能实现这样的效果吗？

**Comment by ibireme** [comment]
不支持。。但是可以用稍微复杂些的方法绘制出来：

    
    YYTextLayout *layout = nil;
    CGSize size = CGSizeMake(100, 100);
    UIGraphicsBeginImageContext(size);
    CGContextRef ctx = UIGraphicsGetCurrentContext();
    
    // 水平
    layout = [YYTextLayout layoutWithContainerSize:size text:line1];
    layout.textBoundingSize; //可以获得这一行的宽高
    [layout drawInContext:ctx size:size point:CGPointMake(20, 10) view:nil layer:nil debug:nil cancel:nil];
    
    // 竖直
    CGContextSaveGState(ctx);
    CGContextRotateCTM(ctx, YYDegreesToRadians(90));
    layout = [YYTextLayout layoutWithContainerSize:size text:line2];
    [layout drawInContext:ctx size:size point:CGPointMake(60, 55) view:nil layer:nil debug:nil cancel:nil];
    CGContextRestoreGState(ctx);
    
    CGImageRef imageRef = CGBitmapContextCreateImage(ctx);
    UIImage *image = [UIImage imageWithCGImage:imageRef scale:2 orientation:UIImageOrientationUp];
    CFRelease(imageRef);
    UIGraphicsEndImageContext();
    
    UIImageView *imageView = [[UIImageView alloc] initWithImage:image];

**Comment by SeanChense** [comment]
- (void)viewDidLoad {
    [super viewDidLoad];
    YYTextLayout *layout = nil;
    CGSize size = CGSizeMake(100, 100);
    UIGraphicsBeginImageContext(size);
    CGContextRef ctx = UIGraphicsGetCurrentContext();
    
    // 水平
    layout = [YYTextLayout layoutWithContainerSize:size text:[[NSAttributedString alloc] initWithString:@"line1"]];
    //    layout.textBoundingSize; //可以获得这一行的宽高
    [layout drawInContext:ctx size:size point:CGPointMake(20, 10) view:nil layer:nil debug:nil cancel:nil];
    
    // 竖直
    CGContextSaveGState(ctx);
    CGContextRotateCTM(ctx, YYDegreesToRadians(90));
    layout = [YYTextLayout layoutWithContainerSize:size text:[[NSAttributedString alloc] initWithString:@"line2"]];
    [layout drawInContext:ctx size:size point:CGPointMake(60, 55) view:nil layer:nil debug:nil cancel:nil];
    CGContextRestoreGState(ctx);
    
    CGImageRef imageRef = CGBitmapContextCreateImage(ctx);
    UIImage *image = [UIImage imageWithCGImage:imageRef scale:2 orientation:UIImageOrientationUp];
    CFRelease(imageRef);
    UIGraphicsEndImageContext();
    
    _imageView = [[UIImageView alloc] initWithImage:image];
    [self.view addSubview:_imageView];
    _imageView.frame = self.view.frame;
    self.view.backgroundColor = [UIColor whiteColor];
    }


感谢您的回答。可惜我得出的效果似乎不太好。
![](http://ww3.sinaimg.cn/large/006c3h06gw1eya4eyh8p8j31kk124avb.jpg)

**Comment by ibireme** [comment]
额，我只是大概举个例子。。
实际用起来需要调整画布的大小、Scale、每行文本的字体颜色等属性。。

**Comment by SeanChense** [comment]
@ibireme 哦，知道啦，谢谢你啦。
