### ISSUE TITLE
NSAttributedString使用你们的图文混排之后，系统的计算宽高失败，见代码

### ISSUE THREAD

**Issue by nizenyang** [ibireme/YYText#300]
![f6fc33fc-28b6-4803-b3bd-8605243390dc](https://cloud.githubusercontent.com/assets/8390188/14907903/8c60824e-0e01-11e6-888f-071aac9c9189.png)
![46c5f6e0-55af-436a-8ed2-4d9d723d80bb](https://cloud.githubusercontent.com/assets/8390188/14907923/c3a9d20a-0e01-11e6-94c4-6e55a6253817.png)
![9c333855-098b-4b91-8a45-e982c423e0ac](https://cloud.githubusercontent.com/assets/8390188/14907935/eb2831b4-0e01-11e6-8f67-ed0983c323cb.png)

**Comment by ibireme** [comment]
YYText 里面，没有和系统方法产生冲突的代码。下面那个方法，调用时传入的 width 和 height 宽高不都是 0 吗？“系统的计算宽高失败”是什么意思。。

**Comment by nizenyang** [comment]
忘记说了，那个第三张图是return之后的CGRect的size不是传进去的，附图：
![729b49e1-6606-4a72-9fac-96eee64d26d4](https://cloud.githubusercontent.com/assets/8390188/14908554/3976e2e4-0e0b-11e6-9aec-427785a83a12.png)

**Comment by ibireme** [comment]
检查一下 boundingRectWithSize:options:context 的每个传入参数、 attrStr 中是否有不能用于 UIKit 的属性。

另外，YYText 是基于 CoreText 的，而这个函数是用于 UIKit (UILabel/UITextView) 的，所以计算结果是不准确的。
