### ISSUE TITLE
IQKeyboardManager的shouldResignOnTouchOutside在YYTextView的下不起作用

### ISSUE THREAD

**Issue by abellee** [ibireme/YYText#301]
用系统的都很正常 点击空白位置就能隐藏键盘，但用YYTextView就不行 为何

**Comment by ibireme** [comment]
原因：https://github.com/ibireme/YYText/issues/173
解决办法：https://github.com/ibireme/YYText/issues/230

**Comment by abellee** [comment]
监听是可以了 但是每次点YYTextView 键盘都会重新弹一下，貌似becomeFirstResponder里的self.isFirstResponder不为true
