### ISSUE TITLE
点击事件的问题

### ISSUE THREAD

**Issue by nizenyang** [ibireme/YYText#302]
- (void)textView:(YYTextView *)textView didTapHighlight:(YYTextHighlight *)highlight inRange:(NSRange)characterRange rect:(CGRect)rect；

我在tableview里面加了一个点击手势， 这个方法（添加在cell里面的textview）就无法回调，但是那个tap又无法去除，有别的用途，我该如何处理呢？

`self.textMsg.dataDetectorTypes = UIDataDetectorTypePhoneNumber | UIDataDetectorTypeLink;`
我使用了这个之后，我发现你的回调方法只能给出点击的范围，当然我自己可以去取出，但是不能做到像系统方法那样自动识别并跳转的功能，我是否需要自己去再去作进一步处理，，比如检测到一个链接www.baidu.com   可以自动跳转呢？类似系统那种

**Comment by nizenyang** [comment]
我也试了下使用系统的textView的他们就不会冲突，并且可以成功跳转

**Comment by ibireme** [comment]
YYTextView 是重写了 UIResponder 的那4个 touch 方法，并没有用 GestureRecognizer。你可以试着调节一下 GestureRecognizer 的 `cancelsTouchesInView` `delaysTouchesBegan` `delaysTouchesEnded` 属性。

关于 dataDetectorTypes 的效果，UITextView 会自动处理跳转，但是很难手动控制；我希望这个地方的后续事件能够手动控制，所以没有添加多余的处理。

**Comment by nizenyang** [comment]
设置了`cancelsTouchesInView `这个属性为NO之后可以响应了
关于自动跳转这个问题的话，也是正如你所说的，自己后续控制了下，所以可以实现差不多的效果，thank  you
