### ISSUE TITLE
使用文本解析时计算文本高度的问题

### ISSUE THREAD

**Issue by glaciertears** [ibireme/YYText#303]
我参考您的demo，使用YYLabel的textParser属性来解析表情，但是我的label的frame是单独写的，能获取的只有普通的文本内容，这时候应该怎么去计算文本的高度呢？

**Comment by glaciertears** [comment]
对了，这是一个聊天模块

**Comment by ibireme** [comment]
先手动调用 TextParser 的那个唯一的方法，把字符串解析好再计算。

**Comment by glaciertears** [comment]
- (BOOL)parseText:(nullable NSMutableAttributedString *)text selectedRange:(nullable NSRangePointer)selectedRange;
调用这个方法？
我的文本内容是NSString类型的

**Comment by glaciertears** [comment]
`NSMutableAttributedString *attributedString = [[NSMutableAttributedString alloc] initWithString:message.content];
        [SharedSetting.textParser parseText:attributedString selectedRange:nil];
        YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:CGSizeMake(kScreenWidth - kIconLength * 2 - 10.0f * 5 - 6.5f + 8, MAXFLOAT) text:attributedString];
        CGFloat contentHeight = layout.textBoundingSize.height;
        CGFloat contentWidth = layout.textBoundingSize.width;`
我这样写的，算出来的宽度是不对的。

**Comment by glaciertears** [comment]
插入的代码有点混乱，见谅呀

**Comment by ibireme** [comment]
YYLabel 的排版流程是这样的：

    +------------------+
    |NSAttributedString|
    +--------+---------+
             |
             | YYTextParser
             v
    +--------+---------+
    |NSAttributedString|
    +--------+---------+
             |
             | YYTextContainer
             v
    +--------+---------+
    |   YYTextLayout   |
    +------------------+

YYLabel 最终只需要 YYTextLayout 就能够显示了，其他的属性（比如 text/font/attributedText/parser）都是对这个过程的封装。你可以参考这个流程来看看你的代码的问题。

**Comment by glaciertears** [comment]
按照您的思路，昨天仔细看了看梳理了一下，最终也得到结果了，我再继续看一看，谢谢您的帮助。
