### ISSUE TITLE
使用的YYTextView图文混排时长按图片出现的放大镜怎么取消

### ISSUE THREAD

**Issue by zhangshuaijiayanni** [ibireme/YYText#304]
使用的YYTextView图文混排时长按图片时,会出现放大镜效果, 松开手指,放大镜不会自动消失,怎么解决?或者怎么取消放大镜效果

**Comment by ibireme** [comment]
正常情况下放大镜会自动消失的，不清楚你的项目中出现了什么问题。

如果实在解决不了，可以调用这个方法隐藏放大镜：

    [[YYTextEffectWindow sharedWindow].subviews makeObjectsPerformSelector:@selector(removeFromSuperview)];
