### ISSUE TITLE
YYLabel attributed text default linespacing is not Zero

### ISSUE THREAD

**Issue by tobatha** [ibireme/YYText#305]
Hi there, 
when i assign an attributed string to YYLabel.attributedText, and set *.yy_lineSpacing = 0, but there is still a default line spacing between lines, how can i get rid of it, or making it REALLY zero spacing between lines, thanks!

**Comment by ibireme** [comment]
The `spacing between lines` is not `line spacing property`, it's the ascent and descent value in font.

You may try the `maximumLineHeight` property, or you can set a `linePositionModifier` property for the label.
