### ISSUE TITLE
can not find the YYTextView on [UIResponder currentFirstResponder]?

### ISSUE THREAD

**Issue by pamredrum** [ibireme/YYText#307]
the [UIResponder currentFirstResponder] returns the YYTextView's superview.

**Comment by ibireme** [comment]
What is `currentFirstResponder`? I can't find this API in UIResponder's header file.

**Comment by pamredrum** [comment]
sorry, it's code from internet
`static __weak id currentFirstResponder;

@implementation UIResponder (FirstResponder)
+ (id)currentFirstResponder {
    currentFirstResponder = nil;
    [[UIApplication sharedApplication] sendAction:@selector(findFirstResponder:) to:nil from:nil forEvent:nil];
    return currentFirstResponder;
}

- (void)findFirstResponder:(id)sender {
    currentFirstResponder = self;
}
@end`

**Comment by ibireme** [comment]
In UIKit, there’s no public way to detect the first responder.

Apple has a workaround in ResearchKit and you may try it:  https://github.com/ResearchKit/ResearchKit/blob/1.0.0/ResearchKit/Common/UIApplication%2BResearchKit.h

But this method was deleted in master branch, maybe it's not good.
