### ISSUE TITLE
行距问题疑问

### ISSUE THREAD

**Issue by allenforrest** [ibireme/YYText#31]
YYText 非常棒，我已经扔掉了 TTTAttributedLabel :D
有个疑问，在文字段落时，行距有时候并没有保持一致，原因不明，见截图：
![img_7582](https://cloud.githubusercontent.com/assets/2303990/11356212/7b0fb488-9296-11e5-91b1-12bbeed5234f.PNG)

这是一段很均匀的纯文本（无 emoji 和 Attachment，也没有任何 highlight 和 binding）
仔细看一下会发现，倒数第六行的行距和其他行不同（「。第二，科创版推出...」这一行）

具体原因不明，代码片段：
```
- (YYLabel *)textLabel
{
   if (!textLabel) {
       self.textLabel = [[YYLabel alloc] initWithFrame:CGRectZero];
       self.textLabel.userInteractionEnabled = YES;
       self.textLabel.font = [UIFont systemFontOfSize:kEspressoDescriptionTextFontSize];
       self.textLabel.textColor = [UIColor darkGrayColor];
       self.textLabel.lineBreakMode = NSLineBreakByCharWrapping;
       self.textLabel.textVerticalAlignment = YYTextVerticalAlignmentCenter;
       self.textLabel.numberOfLines = 0;
       self.textLabel.displaysAsynchronously = YES;
       [bubbleView addSubview:self.textLabel];
    }
    return textLabel;
}
```

```
- (YYTextLayout *)textLayoutForMessageContent:(NSString *)content font:(UIFont *)font textWidth:(CGFloat)maxWidth {
    NSMutableAttributedString *text = [[NSMutableAttributedString alloc] initWithString:content];
    text.yy_font = font;
    text.yy_color = [UIColor darkGrayColor];
    text.yy_lineSpacing = kTextLineSpacing;
    text.yy_lineBreakMode = NSLineBreakByCharWrapping;
    
    // 解析超链接
    [text enumerateTextParser:AKCTextMessageCheckingTypeURL];
    
    // 解析电话号码
    [text enumerateTextParser:AKCTextMessageCheckingTypePhoneNum];
    
    // 解析邮箱地址
    [text enumerateTextParser:AKCTextMessageCheckingTypeEmail];
    
    // 解析表情
    [text enumerateTextParser:AKCTextMessageCheckingTypeFace];
    
    YYTextContainer *container = [YYTextContainer new];
    container.size = CGSizeMake(maxWidth, CGFLOAT_MAX);
    
    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:text];
    
    return layout;
}
```

```
    YYTextLayout *layout = [self textLayoutForMessageContent:msgModel.message_content font:[UIFont systemFontOfSize:16.f] textWidth:maxTextWidth];
    
    width = layout.textBoundingSize.width;
    height = layout.textBoundingSize.height;

    self.textLabel.frame = CGRectMake(kLeftBubbleTextLeftInset,
                                            kBubbleTextTopInset,
                                            width,
                                            height);
    self.textLabel.textLayout = layout;
```

**Comment by LiuSky** [comment]
你这个还好。我有时候显示不全。比如最后一行可能不显示了，但是列表滚动下，又显示出来。

**Comment by ibireme** [comment]
请先更新一下 YYText 代码到目前的最新版以解决上面这个问题。

固定行高可以看 readme 里面的这段代码：[文本行位置调整](https://github.com/ibireme/YYText#文本行位置调整)。另外，设置 Label 的宽高时，最好用 floor 之类的函数向上取整一下。

**Comment by allenforrest** [comment]
多谢。

我已经更新到0.9.9。

我理解固定行高是为了解决文字、emoji 等混排时高度差异问题，但我上面这个例子，完全是纯文字的，应该不需要固定行高把？

参考 readme 中增加下列代码：
```
       YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
       modifier.fixedLineHeight = 24;
       self.textLabel.linePositionModifier = modifier;
```
感觉没有太大差别。

BTW：相比 TTTAttributedLabel，YYText 还有一个小问题，在文字和 emoji 混排的时候，文字和 emoji 其实是相同的字体，但是 emoji 的行高要比文字略高一些，导致了行距的差异不同。

如图：
![img_7583](https://cloud.githubusercontent.com/assets/2303990/11357385/c8ff62d2-92a1-11e5-96d4-4d5686b593e0.PNG)

但同样的做法，TTT 中就能看到文字和 emoji 完全同高，各行行距均匀。

**Comment by ibireme** [comment]
在外部设置字体时是同一个字体，比如 Helvetica，但是排版渲染时会根据实际内容进行 Fallback：需要显示中文时，字体会 Fallback 到 PingHei SC，需要显示 Emoji 时，会回退到 AppleColorEmoji。虽然字号一样，但 Ascent、Descent 都是不一样的，这就会造成每行高度不一样，所以可能需要手动额外修改。

如果你需要查看每行的精确位置，可以调用下面的代码来调试，测量一下 baseline 的间距。

    YYTextDebugOption *op = [YYTextDebugOption new];
    op.baselineColor = [UIColor redColor];
    op.CTLineFillColor = [UIColor colorWithRed:0.000 green:0.484 blue:1.000 alpha:0.165];
    [YYTextDebugOption setSharedDebugOption:op];

TTTAttributedLabel 在排版时，针对的是具有相同属性的一个 String，所以会进行特殊处理，当用 AttributedString 的时候，TTTAttributedLabel 会出现明显的文本行位置错误。YYText 是针对 AttributedString 进行处理的，需要满足更多、更复杂的一些情况，所以并没有对这种情况进行特殊处理。

**Comment by allenforrest** [comment]
理解了，OK，我开调试看一下。

**Comment by ibireme** [comment]
对了，看到你的代码，你是直接用 YYTextLayout 和 YYTextcontainer 来排版的，修改文本行位置的代码应该放在那里：

    YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
    modifier.fixedLineHeight = 24;
    
    YYTextContainer *container = [YYTextContainer new];
    container.size = CGSizeMake(maxWidth, CGFLOAT_MAX);
    container.linePositionModifier = modifier;

**Comment by allenforrest** [comment]
对对对，我也发现了这个问题。
改了一下，固定行高效果出来了。
但是有一点小问题的是，感觉 vertical alignment 方式变成 bottom 的感觉，似乎比不加固定行高的时候位置偏低一些。

**Comment by ibireme** [comment]
你可以参考 YYTextLinePositionSimpleModifier 实现一个自己的 LinePositionModifier，自己来按需求修改文本行的位置，这样比较简单，而且更灵活。

**Comment by allenforrest** [comment]
```
@implementation YYTextLinePositionSimpleModifier
- (void)modifyLines:(NSArray *)lines fromText:(NSAttributedString *)text inContainer:(YYTextContainer *)container {
    if (container.verticalForm) {
        for (NSUInteger i = 0, max = lines.count; i < max; i++) {
            YYTextLine *line = lines[i];
            CGPoint pos = line.position;
            pos.x = container.size.width - container.insets.right - line.row * _fixedLineHeight - _fixedLineHeight * 0.9;
            line.position = pos;
        }
    } else {
        for (NSUInteger i = 0, max = lines.count; i < max; i++) {
            YYTextLine *line = lines[i];
            CGPoint pos = line.position;
            
            pos.y = line.row * _fixedLineHeight + _fixedLineHeight * 0.9 + container.insets.top;
            line.position = pos;
        }
    }
}
```

这里面的 ``+ _fixedLineHeight * 0.9`` 是什么含义？

**Comment by ibireme** [comment]
假定字体的 ascent 是 0.9 倍的字号，这个主要是调整文本距离顶部的高度。
这个比较简单所以给了个通用一些的值，并没有再对外进行封装。

**Comment by allenforrest** [comment]
OK，我重写一个 LinePositionModifier 吧，我这里场景复杂一些：
1、纯文本的行高
2、纯文本+emoji 的行高
3、纯文本+emoji+highlight 的行高
4、以上+表情图（attachment）的行高
需要针对这几种情况自适应的调整 line ，我试试看。

**Comment by zwy2937** [comment]
请问这个模糊背景是用的什么第三方库弄的吗。是实时的吗

**Comment by allenforrest** [comment]
是一张静态背景图，做动态也可以，其实就是Gaussian Blur。

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On 周三, 12月 2, 2015 at 21:39, zwy2937 <notifications@github.com> wrote:
请问这个模糊背景是用的什么第三方库弄的吗。是实时的吗

—
Reply to this email directly or view it on GitHub
[https://github.com/ibireme/YYText/issues/31#issuecomment-161292215] .[https://github.com/notifications/beacon/ACMn9uHDxrFZrXPYSWRhDbbHuLRDqg0gks5pLuwTgaJpZM4GoDii.gif]

**Comment by VVJason** [comment]
为什么设置了fixedLineHeight还是这样呢。。。右边为什么会有间隙。。

```
YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
    modifier.fixedLineHeight = 20.5;
```

![simulator screen shot 2016 1 16 5 20 53](https://cloud.githubusercontent.com/assets/14148888/12371670/dc21ac28-bc75-11e5-90bd-a821ecf4b515.png)

**Comment by tianglin** [comment]
请问楼主解决了行高的问题吗？我也遇到了同样的问题。重写LinePositionModifier也没效果，可否参考下，谢谢

**Comment by zliuqing** [comment]
@LiuSky 你所述的问题，最后一行不显示，滚动后最后一行又出现了的问题解决了吗？详细可看我在YYText提了的issue，不知道是不是一个问题？

**Comment by LiuSky** [comment]
@zliuqing  解决了。挺久的了。

**Comment by hackjie** [comment]
使用了YYTextLinePositionSimpleModifier的话yy_lineSpacing好像没有效果了
