### ISSUE TITLE
YYLabel有实现长按复制的功能么？

### ISSUE THREAD

**Issue by Jacky-LinPeng** [ibireme/YYText#310]
YYLabel有实现长按复制的功能么？

**Comment by baiyyyf** [comment]
设置一下textLongPressAction就行了，就是会同时触发textTapAction，不知道怎么办

**Comment by ibireme** [comment]
简单加个 textLongPressAction 或者 Gesture 就行。

**Comment by bluesmilery** [comment]
给label加了gesture后，富文本的tap action失效，是有这么个情况吗？

**Comment by Sofreda** [comment]
自己在yylabe基础上再封装一个类
