### ISSUE TITLE
不能设置系统的Thin字体？

### ISSUE THREAD

**Issue by chx632996066** [ibireme/YYText#311]
设置了[UIFont systemFontOfSize:16 weight:UIFontWeightThin]但是无效

**Comment by ibireme** [comment]
字体是由 CoreText 绘制的，所以这完全依赖系统。
试试如果 UILabel 支持，那就应该能支持。

**Comment by chx632996066** [comment]
UILabel 是可以显示Thin字体的，但YYLabel显示不了

**Comment by chx632996066** [comment]
更正下，不是完全没效果，的确比默认的细点，但是没有UILabel的细....
![6842aca0-291e-4b6a-8c61-7762e16a16cb](https://cloud.githubusercontent.com/assets/4217642/15237139/ff8ef1a4-18fd-11e6-9847-6c3af93de1e3.png)
![7ea126e3-d6bb-4df5-b4c1-79d70bb9bc95](https://cloud.githubusercontent.com/assets/4217642/15237188/2de31d50-18fe-11e6-8357-270c170ea342.png)

**Comment by chx632996066** [comment]
噢，发现区别了，UILabel是在storyboard选的thin，如果在代码写[UIFont systemFontOfSize:FONTSIZE_NORMAL weight:UIFontWeightThin]，就和YYLabel显示的粗细一样了。

但是另外一个问题来了，怎样才可以让Label的文字像storyboard设置的那样细？（好像不是YYLabel的issue了，如果ibireme知道的话，麻烦告知一下，谢谢）

**Comment by ibireme** [comment]
试试 UIFontWeightUltraLight 或者其他手动值。

**Comment by chx632996066** [comment]
试过了，还是没有那么细，还好这个界面本来就是通过storyboard做的，我直接让YYLabel的font等于上面那个UILabel的font就可以了。
再次感谢你的开源库！
