### ISSUE TITLE
把一个 YYLabel 的 textlayout.text 和 textlayout.textBoundingSize 赋值给 YYTextView，显示有误。

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYText#315]
需求：让一个已经正确显示的 YYLabel 拥有Select All、Copy、Define 等功能。
思路：使用 YYTextView。
障碍：YYTextView 的 textLayout 属性是只读的，无法直接把 YYLabel 的 textLayout 赋值给 YYTextView 。
解决：分别把 YYLabel.textLayout 的 text, textBoundingSize 赋值给 YYTextView 的 attributedText,size。欲间接从 YYTextLabel “克隆” 出一个相同显示效果的 YYTextView 。
结果：YYTextView size 总是偏小。
> 正确显示的YYLabel:
![fullsizerender 3](https://cloud.githubusercontent.com/assets/5517281/15191010/434b997a-17e5-11e6-8d87-abdca7442664.jpg)

> "克隆"出的 YYTextView:
![fullsizerender](https://cloud.githubusercontent.com/assets/5517281/15190837/911ff2a0-17e4-11e6-93b4-d52f12f09286.jpg)

(以上不是个例，而是普遍现象)

望解答，感谢！

**Comment by ibireme** [comment]
YYTextLayout 是由 container 和 text 两个数据生成的，所以如果要挪出去的话，container 的属性也需要考虑。

YYTextView 默认的 container 会有一个 insets 用于留白，所以这里把 YYTextView.textContainerInset 设置为 0 应该就正常了。

**Comment by KittenYang** [comment]
恩，顺利解决✅
