### ISSUE TITLE
设置YYTextview的行高后怎么计算文字的高度

### ISSUE THREAD

**Issue by zhangshuaijiayanni** [ibireme/YYText#316]
用下面的方法设置textView的行高
YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
modifier.fixedLineHeight = 24;
_textView.linePositionModifier = modifier;

计算textView中得图片和文字的高度时使用下面的方法,这时候会出现问题,当不设置固定行高的时候用下面的方法计算的图文混排的高度就没有问题, 该怎么解决
#pragma mark - 计算富文本的高度
- (CGFloat)getAttributedStringHeightWithString:(NSAttributedString *)string  WidthValue:(CGFloat)width
{
    CGFloat total_height = 0;
    CTFramesetterRef framesetter = CTFramesetterCreateWithAttributedString((CFAttributedStringRef)string);    //string 为要计算高度的NSAttributedString
    CGRect drawingRect = CGRectMake(0, 0, width, 1000000000000000);  //这里的高要设置足够大
    CGMutablePathRef path = CGPathCreateMutable();
    CGPathAddRect(path, NULL, drawingRect);
    CTFrameRef textFrame = CTFramesetterCreateFrame(framesetter,CFRangeMake(0,0), path, NULL);
    CGPathRelease(path);
    CFRelease(framesetter);
    NSArray *linesArray = (NSArray *) CTFrameGetLines(textFrame);
    CGPoint origins[[linesArray count]];
    CTFrameGetLineOrigins(textFrame, CFRangeMake(0, 0), origins);
    int line_y = (int) origins[[linesArray count] -1].y;  //最后一行line的原点y坐标
    CGFloat ascent;
    CGFloat descent;
    CGFloat leading;
    CTLineRef line = (__bridge CTLineRef) [linesArray objectAtIndex:[linesArray count]-1];
    CTLineGetTypographicBounds(line, &ascent, &descent, &leading);
    total_height = 1000000000000000 - line_y + (int) descent +1;    //+1为了纠正descent转换成int小数点后舍去的值
    CFRelease(textFrame);
    return total_height;
}

**Comment by ibireme** [comment]
当未设置 YYTextLinePositionModifier 时，内部会直接用 CoreText 的排版结果来绘制，所以上面这种计算是可以的。但设置了 YYTextLinePositionSimpleModifier 后，内部会把每行的位置进行调整，上面代码就不行了。

这个可以用 YYTextLayout 来计算，使用方法 Readme 里应该有。
