### ISSUE TITLE
YYTextView  shouldInteractWithURL:(nonnull NSURL *)URL inRange:(NSRange)characterRange

### ISSUE THREAD

**Issue by NSaylor** [ibireme/YYText#318]
在使用中，发现对比系统原生的代理方法中 少了上面这个。对于超链这部分，是建议使用和Demo里一样的可点击文本属性进行处理么？

**Comment by ibireme** [comment]
有 shouldTapHighlight 和 shouldLongPressHighlight 两个方法，可以试一下。

**Comment by NSaylor** [comment]
感谢你的回复，另外一个问题。我现在有个页面整体有手势实现页面退出和跳转（用的是一个第三方），在YYTextview 进行文本选择时即复制功能，手势穿透了。也就是说文本在选择时，页面也在跟着移动。对比原生textview 没有这个问题。

**Comment by ibireme** [comment]
YYTextView 的触摸事件的检测方式和 UITextView 是不一样的。这里是重写了 UIResponder 的那四个 touch 方法，可以从这方面来看一下如何调整代码。
