### ISSUE TITLE
YYTextLayout 获取文本宽度 始终为0

### ISSUE THREAD

**Issue by hackjie** [ibireme/YYText#319]
+ (CGFloat)calculateAttributeStringWidthWithAttributeString:(NSMutableAttributedString *)string fixHeight:(CGFloat)height
{
    CGSize size = CGSizeMake(CGFLOAT_MAX, height);
    YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:size text:string];
    return layout.textBoundingSize.width;
}
@ibireme 返回的宽度始终为0，求解答 谢谢！！！

**Comment by ibireme** [comment]
如果传入的 height 连一行文本都容纳不下，那就会排版失败，返回0。

**Comment by hackjie** [comment]
谢谢！你没回答我之前我采用intrinsicContentSize计算，然后更新约束做的

**Comment by lzcdgit** [comment]
所以如果lable不支持换行的话。我给一个很大的高（超过lable高的2倍以上），也可以算出来宽度吧？
