### ISSUE TITLE
YYSelectionGrabber 的两个 bug

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYText#320]
### 1.全选时，上方 Grabber 的 dot 消失：

![fullsizerender 4](https://cloud.githubusercontent.com/assets/5517281/15267024/a3328128-19e8-11e6-9e23-ef5e232c44a9.jpg)

### 2.若下方 Grabber 在文本最后一行时，且 textView 又加在一个 scrollview 上，滑动 scrollview 时 dot 依然加在 window 上：

![fullsizerender 5](https://cloud.githubusercontent.com/assets/5517281/15267025/a3350bf0-19e8-11e6-9eaa-b27eacf95e64.jpg)

**Comment by ibireme** [comment]
这个地方确实有些问题：

UITextView(UIScrollView) 在文本过长时能上下滑动，所以需要设置 textView.clipsToBounds = YES 来把超过边界的内容裁剪掉，这时那个选择器就会显示不全。

我本意是希望参考 UIKit 的实现方法，把裁剪掉的内容放到单独的 TextEffectWindow 里。但是这里没有什么好的办法能实时监控当前试图在屏幕上绝对位置的变化，所以这里更新有时会不及时（比如父视图位置有了变化），而且有时点的位置也会计算不准。

对于上面这种情况（文本都显示出来了，不需要上下滑动），可以试着设置一下 textView.clipsToBounds = NO。对于选择器更新不及时的问题，可以在外面 scroll 时强制调用一下 textView 的 scrollViewDidEndDecelerating: 方法。

**Comment by KittenYang** [comment]
Fixed!
Thanks!
