### ISSUE TITLE
我使用的是NSMutableAttributedString怎么触发点击事件

### ISSUE THREAD

**Issue by smallqiang** [ibireme/YYText#322]
+ (NSMutableAttributedString *)yy_attachmentStringWithContent:(nullable id)content
                                                  contentMode:(UIViewContentMode)contentMode
                                               attachmentSize:(CGSize)attachmentSize
                                                  alignToFont:(UIFont *)font
                                                    alignment:(YYTextVerticalAlignment)alignment;
用了这个方法在YYTextView上显示图片，但怎么让图片触发点击事件呢？

**Comment by ibireme** [comment]
静态的 UIImage 的话，可以这样：https://github.com/ibireme/YYText#文本高亮
动态图或者 UIImageView 的话，可以直接在 View 上面添加 Gesture。
