### ISSUE TITLE
8.4.1在reloadInputViews的时候crash

### ISSUE THREAD

**Issue by decemberLi** [ibireme/YYText#324]
![image](https://cloud.githubusercontent.com/assets/13531628/15319169/2057dcfa-1c5c-11e6-810d-acba3eae0aa6.png)

**Comment by ibireme** [comment]
注意看一下 inputView 不应该有父视图。

**Comment by decemberLi** [comment]
嗯。谢谢回答。崩溃的地方找了。是其他类添加了UIKeyboardWillChangeFrameNotification,而在dealloc的时候没有remove掉。修改掉这个就ok了。
