### ISSUE TITLE
求助： YYLabel在显示emoji表情的时候有一部分表情不能正常显示，而且表情的高度不一致，如下图

### ISSUE THREAD

**Issue by gongjiehong** [ibireme/YYText#325]
![img_1138](https://cloud.githubusercontent.com/assets/3861150/15349153/446a15a2-1d03-11e6-9be9-8a828d3cf724.jpg)
![img_1139](https://cloud.githubusercontent.com/assets/3861150/15349155/44df6cf8-1d03-11e6-9d2e-56259b62dd0f.jpg)

**Comment by ibireme** [comment]
可以把这段文字贴上来看一下。

或者把这段文字 copy 到微信朋友圈看看，如果也有问题，那可能是 CoreText 排版的问题。

**Comment by gongjiehong** [comment]
感谢作者回复

原因已找到，这里是因为在设置字体计算长度的时候，直接使用了swift String characters.count作为字符长度设置range了，实际上NSAttributedString(string: string).length  !=  string.characters.count，造成正文的字体不一致，表情显示乱码的地方是因为一个emoji有了两种字体，所以就错乱了

我也来回复一下，避免有人跟我趟同样的坑，哈哈

**Comment by WorthyZhang** [comment]
@gongjiehong  我也遇到emoji显示乱码的问题，能详细说一下怎么解决掉吗？我只设置了一种字体，还是乱码。

**Comment by DSPerson** [comment]
swift 使用 nickStr.utf16.count 计算长度
