### ISSUE TITLE
YYLabel显示符号的时候，会显示异常

### ISSUE THREAD

**Issue by zwy2937** [ibireme/YYText#326]
就是当前面文字是带有空格的时候，后面文字是符号的时候，YYLabel显示会在前面空格处换行了。。。

**Comment by zwy2937** [comment]
![img_2416](https://cloud.githubusercontent.com/assets/12247200/15383921/4c3067f2-1dc9-11e6-91ba-b2041b20a39b.PNG)
如图下发那个。。。。。。。。显示的这样

**Comment by zwy2937** [comment]
@ibireme

**Comment by zwy2937** [comment]
另外咨询一下如何更高效的异步排版，在一秒内渲染100个textlayout时候会比较吃力，而且为其设置Font更是吃性能。。。请问如果解决~

**Comment by ibireme** [comment]
换行这个是 CoreText 自动完成的，一般当 lineBreakMode 设置为 word wrap 时就系统会尝试尽量保持英文单词的连贯性。如果你不介意英文单词的折断，剋一把 lineBreakMode 设置为 char wrap。

性能问题，可以参考 Readme 和 Demo 中的做法，几乎所有操作都是可以挪到后台线程去的，可以保证主线程不卡顿，
