### ISSUE TITLE
当scrollview嵌套YYText时menu的显示会因为手势传递出现问题

### ISSUE THREAD

**Issue by sky15179** [ibireme/YYText#327]
是不是在dot update的时候加一个通知,让父容器去做menu展示的逻辑能更好的解决这个问题呢

**Comment by ibireme** [comment]
看看这个问题有帮助没？https://github.com/ibireme/YYText/issues/320

**Comment by sky15179** [comment]
scroll容器包裹textview还是的需求还是挺常见的,开启手势共享后.textview选中滑动都有问题了,我暂时用aspect在放大镜出现消失的时候加了个通知出来,用来区分做手势处理,对textview进入手势处理的时候暴露一些接口能更好的为容器做逻辑处理怎样啊

**Comment by SiTianyu** [comment]
嗯，确实有这样的问题。不知道还有什么好的思路？
