### ISSUE TITLE
YYTextView可以添加剩余字数统计吗

### ISSUE THREAD

**Issue by EZElkins** [ibireme/YYText#33]
添加两个字段,设置字数限制和是否显示剩余字数

**Comment by ibireme** [comment]
这个需求并不算通用。。。

字数限制是按 unicode 字符数统计还是按字节数统计？按字节数统计的话，用什么编码呢？是按照富文本的属性统计还是按转换后的纯文本映射进行统计呢？剩余字数的格式是怎样的呢？样式和位置呢？什么时候显示呢？如果要实现的话，配置太过复杂并且还不一定能满足具体需求。

你可以在 delegate 里接收回调或者子类化 TextView 来实现想要的功能。
