### ISSUE TITLE
请问一下，关于view的大小改变之后，会遮盖文字如何解决？

### ISSUE THREAD

**Issue by Lishaoshuai** [ibireme/YYText#333]
使用字符串拼接一个button后，如果改变button中的文字长度并sizetofit，button的长度还是按照原来的长度计算，导致遮挡文字，请问该如何重新计算button的长度？  

NSMutableAttributedString *text = [NSMutableAttributedString new];
    UIFont *font = [UIFont systemFontOfSize:16];
    
    {
        NSString *title = @"This is UIView attachment: ";
        [text appendAttributedString:[[NSAttributedString alloc] initWithString:title attributes:nil]];
        
//        UISwitch *switcher = [UISwitch new];
//        [switcher sizeToFit];
        UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
        [button setTitle:@"你好" forState:UIControlStateNormal];
        button.backgroundColor = [UIColor redColor];
        [button sizeToFit];
        [button addTarget:self action:@selector(hehe:) forControlEvents:UIControlEventTouchUpInside];
        
        NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithContent:button contentMode:UIViewContentModeCenter attachmentSize:button.size alignToFont:font alignment:YYTextVerticalAlignmentCenter];
        [text appendAttributedString:attachText];
        [text appendAttributedString:[[NSAttributedString alloc] initWithString:@"\n" attributes:nil]];
    }

**Comment by ibireme** [comment]
重新进行一次布局。
例如用了 label.attributedText，那可以先把 attributedText 取出来暂存，然后清空 label.attributedText，再设置回去。
