### ISSUE TITLE
iOS 8.4 itouch5 使用中文九宫格输入文字或符号时会发生崩溃。

### ISSUE THREAD

**Issue by Shanesun** [ibireme/YYText#335]
![2016-05-25 5 35 38](https://cloud.githubusercontent.com/assets/12092728/15535750/40b8fcfe-22a1-11e6-90a7-24dd18a739f3.png)
iOS 8.4 itouch5 使用中文九宫格输入文字或符号时会发生崩溃。暂时只在iOS8.4系统中文九宫格输入法中发现。
_innerText String为空，_selectedTextRange.end.offset >0 。
发生崩溃：NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds

谢谢~

**Comment by ibireme** [comment]
<img width="373" alt="2016-05-25 11 47 45" src="https://cloud.githubusercontent.com/assets/839283/15546606/1b65b514-22d3-11e6-87ff-e51715b01ebd.png">

手头没有 8.4 的真机，在模拟器下测试看看，但没找到九宫格输入法。。
