### ISSUE TITLE
YYLabel 纯汉字，纯因为字母，相同的TextBorder属性，出来的框高度不一样

### ISSUE THREAD

**Issue by yunhaiwu** [ibireme/YYText#340]
纯汉字，纯因为字母，相同的TextBorder属性，出来的框高度不一样

NSMutableAttributedString *text = [[NSMutableAttributedString alloc] init];
{
        NSMutableAttributedString *one = [[NSMutableAttributedString alloc] initWithString:@"文本一"];
        one.yy_font = [UIFont boldSystemFontOfSize:10];
        one.yy_color = [UIColor redColor];
        YYTextBorder *border = [YYTextBorder new];
        border.cornerRadius = 50;
        border.insets = UIEdgeInsetsMake(0, -10, 0, -10);
        border.strokeWidth = 0.5;
        border.strokeColor = one.yy_color;
        border.lineStyle = YYTextLineStyleSingle;
        one.yy_textBackgroundBorder = border;
        [text appendAttributedString:one];
        [text appendAttributedString:[self padding]];
    }
{
        NSMutableAttributedString *one = [[NSMutableAttributedString alloc] initWithString:@"text"];
        one.yy_font = [UIFont boldSystemFontOfSize:10];
        one.yy_color = [UIColor redColor];
        YYTextBorder *border = [YYTextBorder new];
        border.cornerRadius = 50;
        border.insets = UIEdgeInsetsMake(0, -10, 0, -10);
        border.strokeWidth = 0.5;
        border.strokeColor = one.yy_color;
        border.lineStyle = YYTextLineStyleSingle;
        one.yy_textBackgroundBorder = border;
        [text appendAttributedString:one];
        [text appendAttributedString:[self padding]];
    }

![image](https://cloud.githubusercontent.com/assets/13548459/15615160/44328e0c-246f-11e6-80eb-fb7ca91c343b.png)

**Comment by ibireme** [comment]
中文、英文、数字的字体高度是不一致的（相同字号下 ascent+descent 是不一样的）。border 会按照最终排版高度（这里就是 font 高度）来进行绘制，保证能框住内部文字。举个例子，如果一串富文本，有很大的字体也有很小的字体，最终 border 会尝试以最大字体的高度来绘制。

如果你希望这里保持高度一致，一种做法是判断字体，调整 border 的 insets；另一种做法是直接嵌入 UIButton 或者类似的控件。

**Comment by yunhaiwu** [comment]
OK

**Comment by yunhaiwu** [comment]
非常感谢~，我用button
