### ISSUE TITLE
行间距问题

### ISSUE THREAD

**Issue by jcxc** [ibireme/YYText#347]
初始化YYTextView时，如何设置其linespacing？必须使用NSMutableAttributedString属性去设置嚒？

**Comment by ibireme** [comment]
是的。
TextView 的 font/color/alignment 等属性，都是对 NSAttributedString 的封装。NSAttributedString 支持的属性太多了，很多不常用的属性就没有封装。

**Comment by jcxc** [comment]
3Q,get
