### ISSUE TITLE
YYTextView选中问题

### ISSUE THREAD

**Issue by jcxc** [ibireme/YYText#348]
当一个YYTextView输入一定文字后，resign first 然后再becomeFirstResponder，输入的文字会全选，请问这是什么属性？

**Comment by ibireme** [comment]
textView.selectedRange

**Comment by jcxc** [comment]
我现在不要它全选噢。。。它现在自动全选。。

**Comment by jcxc** [comment]
现在在 - (void)textViewDidBeginEditing:(YYTextView *)textView 里设置  textView.selectedRange = NSMakeRange(0, 0); 
但是再次响应的时候，不全选了，可是光标在初始位置。。。。
