### ISSUE TITLE
YYTextView怎么设置单行输入 不许换行？

### ISSUE THREAD

**Issue by LiweiDong** [ibireme/YYText#35]
![7c46ae5b-6f59-47ac-a790-b556adfcad98](https://cloud.githubusercontent.com/assets/1669848/11415570/b78453ec-943f-11e5-8ba2-542147e45cd1.png)

![e216e9ea-85ef-475e-8ba5-df9111897b53](https://cloud.githubusercontent.com/assets/1669848/11415575/bf3ace18-943f-11e5-9417-9c926b8b7153.png)

怎么设置单行输入 和居中？

**Comment by ibireme** [comment]
垂直居中可以设置 textView.textVerticalAlignment = YYTextVerticalAlignmentCenter;
单行输入是 TextField 的特性，YYTextView 不支持。
