### ISSUE TITLE
TextView 搜狗输入法输入重复

### ISSUE THREAD

**Issue by ramoslin02** [ibireme/YYText#356]
不清楚为什么用第三方的输入法,会出现重复输入的问题。如果是英文的话，会有问题。比如输入how 英文，会变成howhow.测试最新版也是有问题的。
![img_2097](https://cloud.githubusercontent.com/assets/10205321/15735256/c60d7ce4-28c9-11e6-9129-82f82c5cf20a.PNG)

**Comment by ibireme** [comment]
已知问题：https://github.com/ibireme/YYText/issues/89
