### ISSUE TITLE
关于长度的问题

### ISSUE THREAD

**Issue by 597579501** [ibireme/YYText#357]
这个问题可能有点跑偏了。
但是毕竟里面有textfiled的东西。我觉得在这发问。也还OK

是这样的。输入框这些东西经常要涉及到长度的问题。如果纯数字和英文还好。
类似介绍这种。里面会有英文。和表情（emoji）还有汉子。我怎么严格来做呢。而且一直好奇为什么textfile不带这个东西。自己在回调里实现
我遇到比较蛋疼的问题就是如果通过长度回调截取。经常遇到还能输入一个字符。但是这时候高亮词选了一个字就会超出1个字符。或者选个表情（表情）算2个字符的。就会乱码

**Comment by ibireme** [comment]
你是说文本的 length 问题吗？这个就比较复杂了。。如果是文本还好说，但表情这东西相对来说就比较麻烦。苹果的表情是需要依赖字体和排版结果的，直接从 unichar 去判断容易出现误判的情况。

理论知识可以看看这篇文章：http://objccn.io/issue-9-1/  UITextField 之类的操作可以看看 UITextInput 这个协议。
