### ISSUE TITLE
YYTextView reloadInputViews无效的问题

### ISSUE THREAD

**Issue by romantic100** [ibireme/YYText#358]
在当前页面先调Actionsheet后再点击切换表情无效 #
![simulator screen shot 2016 6 4 12 19 58](https://cloud.githubusercontent.com/assets/3139857/15797580/1faa3c88-2a50-11e6-8cd8-7415e7d6def3.png)
![simulator screen shot 2016 6 4 12 21 01](https://cloud.githubusercontent.com/assets/3139857/15797579/1fa9f3ea-2a50-11e6-9c24-edcabb61f9ae.png)

**Comment by ibireme** [comment]
请在真机上测试看看。另外，可以试试在弹出系统选择之前 endEditing。

**Comment by romantic100** [comment]
设了endEditing 真机上也是这样

**Comment by ibireme** [comment]
我测试了一下：WBStatusComposeViewController.m

    } else if (button == _toolbarExtraButton) {
        UIAlertController *ctrl = [UIAlertController alertControllerWithTitle:@"Test" message:@"Hehe" preferredStyle:UIAlertControllerStyleActionSheet];
        __weak typeof(ctrl) _ctrl = ctrl;
        [ctrl addAction:[UIAlertAction actionWithTitle:@"Test" style:UIAlertActionStyleCancel handler:^(UIAlertAction * _Nonnull action) {
            [_ctrl dismissViewControllerAnimated:YES completion:nil];
        }]];
        [self presentViewController:ctrl animated:YES completion:nil];
    }

表现正常啊。。

**Comment by ibireme** [comment]
有后续跟进的话，可以 reopen。
