### ISSUE TITLE
YYText如果想把整个富文本导出发送给后台该怎么做

### ISSUE THREAD

**Issue by Thetiso** [ibireme/YYText#360]
仔细看了下textview,没能找到导出的方法。
ps：我的意思是指，富文本图文混编之后，是否有属性或者方法会生成一个包装好的结构(json或者text)，方便与服务器的交互。
准备把这个编辑器做成帖子发布的工具来用。

**Comment by ibireme** [comment]
目前没有，这个可能需要手动包装了。

**Comment by Thetiso** [comment]
@ibireme   了解了，等于需要按照输入的顺序自己写结构了。  那我还是简化下写个差不多微信朋友圈那种顶一下，后面有时间再研究研究
