### ISSUE TITLE
关于设置linePositionModifier奔溃问题

### ISSUE THREAD

**Issue by caiZhenAn** [ibireme/YYText#361]
作者你好，我在设置这个属性后，设置maximumNumberOfRows后奔溃。请问怎么解决？
代码如下
YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
YYTextContainer *container = [YYTextContainer new];
container.size = CGSizeMake(100, CGFLOAT_MAX);
container.maximumNumberOfRows=3
container.linePositionModifier = modifier;

YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:text];

**Comment by ibireme** [comment]
提供可复现代码片段，或者崩溃日志/调用栈。

**Comment by caiZhenAn** [comment]
YYKitDemo was compiled with optimization - stepping may behave oddly; variables may not be available.
2016-06-06 23:02:25.377 YYKitDemo[1021:425554] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 3 beyond bounds [0 .. 2]'
*** First throw call stack:
(0x182942db0 0x181fa7f80 0x182822dfc 0x10011f22c 0x10011e468 0x1001174e4 0x100116114 0x100115f8c 0x10015c630 0x10047da7c 0x10047da3c 0x10048cc9c 0x10048c364 0x1825a5470 0x1825a5020)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by caiZhenAn** [comment]
在最新的YYkit不会出现这个问题了

**Comment by ibireme** [comment]
那应该之前修复过。
