### ISSUE TITLE
使用YYText和AutoLayout结合，做类似微博页面的列表页，图片多了很卡。

### ISSUE THREAD

**Issue by hyhSuper** [ibireme/YYText#362]
每次刷新TableView的时候都会重新用YYText计算一次控件高度，所以滑动的时候很卡，请问怎么优化呢？需要做布局的缓存吗？

**Comment by ibireme** [comment]
不要用 YYTextView 改用 YYLabel 并开启异步绘制。不要用 AutoLayout，布局提前计算好。
