### ISSUE TITLE
YYTextContainer指定linePositionModifier后，YYLabel最后一行如果有emoji，最后一行有一定概率不显示

### ISSUE THREAD

**Issue by zliuqing** [ibireme/YYText#363]
YYTextContainer指定linePositionModifier属性来修正含有emoji的文字行高变高的问题，YYLabel的最后一行如果含有emoji表情，最后一行有一定概率不显示。我尝试把YYLabel.frame.size.height调高点，能解决部分问题。比如原来3行的YYLabel，最后一行带emoji的，最后一行能显示了，但如果是4行，5行又不行了。YYLabel的高度由YYTextLayout提供。
以下两种方法都存在这个问题，还请楼主指正：
1.以前的代码这样，去年年底今年年初使用YYText,版本号忘了：
YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
    modifier.fixedLineHeight = lineHeight;
    YYTextContainer *container = [YYTextContainer new];
    container.size = CGSizeMake(textWidth, CGFLOAT_MAX);
    container.linePositionModifier = modifier;（注释掉这行最后一行带emoji的可以显示，打开后偶尔能完全显示，不能的话，再走一遍cellForRow重新给YYLabel赋值YYTextLayout会出现,当然也有可能由出现变消失）
    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:text];
          .
          .
          .

2.或者现在这样使用YYKit 1.0.4版本：（YYTextLinePositionModifier同YYKitDemo中WeiBo 的WBTextLinePositionModifier）
YYTextLinePositionModifier *modifier = [YYTextLinePositionModifier new];
        modifier.font = font;
        modifier.paddingTop = kCellPaddingText;
        modifier.paddingBottom = kCellPaddingText;
        
        YYTextContainer *container = [YYTextContainer new];
        container.size = CGSizeMake(contentWidth, MAXFLOAT);
        container.linePositionModifier = modifier;（注释掉这行,最后一行可以显示，打开后偶尔能完全显示，不能的话，再走一遍cellForRow出现,也有可能由出现变消失）
        
        YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:text];
        CGFloat textHeight = [modifier heightForLineCount:layout.rowCount];
        contentLabel.top = 0;
        contentLabel.height = textHeight;
        contentLabel.textLayout = layout;

**Comment by zliuqing** [comment]
debug模式的附图一直传不上来，给作者发邮箱了

**Comment by ibireme** [comment]
大概有两种计算和设置方法：
1. 保证 YYTextContainer 的设置和 YYLabel 一致，然后计算出来后更新 frame 和 attrubutedText。
2. 设置 label.ignoreCommonProperties = YES，然后计算出来后，更新 frame 和 textLayout。

**Comment by zliuqing** [comment]
@ibireme 感谢作者及时回答，明天试试~

**Comment by zliuqing** [comment]
按方法2. 设置 label.ignoreCommonProperties = YES，然后更新 frame 和 textLayout后，暂时没有问题了，感谢作者！
