### ISSUE TITLE
Italic Font not work for Chinese

### ISSUE THREAD

**Issue by icoder20150719** [ibireme/YYText#369]
Italic Font not work for Chinese
![image](https://cloud.githubusercontent.com/assets/13404370/15998632/70de7eb0-3172-11e6-80cd-d07c01230afb.png)

**Comment by ibireme** [comment]
iOS 中的中文字体 (PingFang/Heiti) 本身是没有 Italic 的。。

**Comment by icoder20150719** [comment]
CGAffineTransform matrix = CGAffineTransformMake(1, 0, tanf(15 * (CGFloat)M_PI / 180), 1, 0, 0);
    UIFontDescriptor *desc = [UIFontDescriptor fontDescriptorWithName:@"Heiti SC Medium" matrix:matrix];
    [UIFont fontWithDescriptor:desc size:fontSize];
这个方法可行，但是[UIFont fontWithDescriptor:desc size:fontSize];这个方式第一次调用的时候会花费2-3s时间。有没有其他办法？

**Comment by icoder20150719** [comment]
采用这种字体（HelveticaNeue-Italic）可以避免

**Comment by ibireme** [comment]
也可以用 YYTextGlyphTransform 来做。
