### ISSUE TITLE
输入拼音的文本后还没有联想到然后随便输入一个逗号或者问号会崩溃如图

### ISSUE THREAD

**Issue by LiuSky** [ibireme/YYText#37]
![a39a404646eb211519925305b99e65ce](https://cloud.githubusercontent.com/assets/3087745/11432592/8f589f74-94ec-11e5-9533-35a157d6e303.png)
没有百分百复线

**Comment by ibireme** [comment]
能提供一下崩溃时的日志或者断点处的调用栈吗？

**Comment by LiuSky** [comment]
<img width="363" alt="2015-11-27 10 47 30" src="https://cloud.githubusercontent.com/assets/3087745/11433156/50ddfd2c-94f4-11e5-92e8-eda3e7c01d2b.png">

**Comment by ibireme** [comment]
这个调用栈没有打印出来啊。。

<img width="429" alt="a" src="https://cloud.githubusercontent.com/assets/839283/11433251/8ff1a422-94f5-11e5-9c51-5f7410e6dad1.png">
<img width="322" alt="b" src="https://cloud.githubusercontent.com/assets/839283/11433253/9409c508-94f5-11e5-8854-8f01eb3728ff.png">

请确保使用 Debug 模式，开启了 All Exceptions 断点，在 Crash 时 Xcode 左侧会停留在一个函数调用栈上，这能定位到崩溃的位置。

我刚刚测了一遍，还是没能复现。。

**Comment by LiuSky** [comment]
<img width="1048" alt="2015-11-27 11 18 51" src="https://cloud.githubusercontent.com/assets/3087745/11433516/f024452c-94f8-11e5-8151-fa6ccd577849.png">
我开了。我接错了。还有你按照我的方式来。输入jjjjjjjjjjjjjjjjjjj然后❓。

**Comment by ibireme** [comment]
好的，我跟进一下。

**Comment by ibireme** [comment]
请验证一下

**Comment by LiuSky** [comment]
好的。哈哈

发自我的 iPhone

**Comment by LiuSky** [comment]
解决.

**Comment by ibireme** [comment]
已更新。
