### ISSUE TITLE
YYLabel的highLight被点击后，dealloc走不到？是不是我的写法有问题？

### ISSUE THREAD

**Issue by sunnyryan** [ibireme/YYText#372]
highLight不点击的时候，label的dealloc是走到的，一旦被点击就走不到了？

   NSMutableAttributedString *text = [[NSMutableAttributedString alloc]initWithString:@"Test YYLabel"];
    [text yy_setTextHighlightRange:NSMakeRange(5, 7) color:[UIColor blueColor] backgroundColor:[UIColor lightGrayColor] userInfo:nil];
    
    YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:CGSizeMake(300, CGFLOAT_MAX) text:text];
    YYLabel *label = [[YYLabel alloc]initWithFrame:CGRectMake(10, 100, layout.textBoundingSize.width, layout.textBoundingSize.height)];
    label.backgroundColor = [UIColor whiteColor];
    label.textLayout = layout;
    
    [self.view addSubview:label];
    
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [label removeFromSuperview];
    });

**Comment by ibireme** [comment]
注意回调中是否有循环引用的问题。

**Comment by SunnyMxj** [comment]
@ibireme 一开始我也是这么认为的，所以甚至都没有写任何回调也是如此，后来发现，只要在屏幕上再触发任意一次touch就会释放了。。。

**Comment by SunnyMxj** [comment]
@ibireme 还有个问题请教下，触发highlightTapAction的时候，会提前先触发tapAction，有没有办法优先响应highlightTapAction？

**Comment by ibireme** [comment]
textTapAction、textLongPressAction 这两个回调，只要触摸完成，就会触发。
highlightTapAction、highlightLongPressAction 这两个回调，只有在高亮范围内才会触发。
这两组之间是并行的。

上面那个释放问题，在 Demo 中测试无法复现。。

**Comment by SunnyMxj** [comment]
@ibireme 1.释放问题，后来经测试在再次出发touch后，就会释放了，没问题了；2.自己封装了下yylabel，加了标志位，也满足了需求了。。 感谢
