### ISSUE TITLE
系统输入法联想问题

### ISSUE THREAD

**Issue by tianyig** [ibireme/YYText#374]
![untitled](https://cloud.githubusercontent.com/assets/4819240/16066691/1950a0a2-32e8-11e6-9a63-40cf0da8f03e.gif)

更新的最新的YYText，有以上问题。输入联想词语光标会进入到单词中间。模拟器和真机都有这个问题。

**Comment by ibireme** [comment]
合并至：https://github.com/ibireme/YYKit/issues/175
