### ISSUE TITLE
将LineBreakMode设置为NSLineBreakByTruncatingTail时显示错误

### ISSUE THREAD

**Issue by ethancheung1990** [ibireme/YYText#376]
YYLabel将 numberOfLine设置为1，
attributeText设置为 [icon图片][草稿]sdfasdfasdfasdf sdafadsf asldf asd" 代码如下
NSMutableString *text  = [NSMutableString new];
[text appendString:@"[草稿]"];
[text appendString:@"sdfasdfasdfasdf sdafadsf asldf asd"];
_cacheClientNameAttributeString = [[NSMutableAttributedString alloc] initWithString:text];
 [_cacheClientNameAttributeString yy_setFont:[UIFont systemFontOfSize:16.0f] range:NSMakeRange(0, text.length)];
 [_cacheClientNameAttributeString yy_setColor:[UIColor blackColor] range:NSMakeRange(0, text.length)];
 [_cacheClientNameAttributeString yy_setColor:[UIColor selectedOrangeColor] range:NSMakeRange(0, 4)];
UIImage *iconImage =  [UIImage imageNamed:@"tour_unplanned"];
NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithContent:iconImage contentMode:UIViewContentModeCenter attachmentSize:iconImage.size alignToFont:[UIFont systemFontOfSize:16.0f] alignment:YYTextVerticalAlignmentCenter];
 [_cacheClientNameAttributeString insertAttributedString:attachText atIndex:0];

label的宽度足够，但是被提前截断了
最后显示为了 [icon图片][草...
期望结果为 [icon图片][草稿]sdfasdfasdfasdf sdafads...

**Comment by ibireme** [comment]
合并至：https://github.com/ibireme/YYText/issues/339
