### ISSUE TITLE
当YYTextView的isFirstResponder为YES时，YYHighLight不起作用

### ISSUE THREAD

**Issue by goodbless** [ibireme/YYText#377]
有很多需求是想实现类似邮件的收件人输入框的那种效果，就是输入特定格式文本的时候，就自动把这一段文字加上一个Binding,从而成为一个整体。
现在有这样的需求，要求这个binding可以点击，在YYText实现文本可点击，我马上想到了用YYHighLight,但设置了后发现，当文本域还是焦点的时候，点击是无法触发highLight的。只有当文本域不是firstResponder时，点击highLight才有效果。
我看了代码，代码在处理点击的时候，加上了 !isFirstResponder 的判断条件，这就解释了上面的测试现象。

但这个需求是普遍存在的，现在的YYTextView有什么办法可以实现吗？

**Comment by ibireme** [comment]
点击会触发编辑，这个和 highlight 有冲突。这个可以看看系统的备忘录，也是同样的逻辑。

邮件输入那个比较复杂，YYTextView 实现不了那么好的效果。

**Comment by goodbless** [comment]
嗯，后来采用Attachment来实现了
