### ISSUE TITLE
YYlabel 事件和父视图手势冲突。

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#38]
给YYlabel做了点击事件，父view上加了一个tap手势，然后YYlabel的事件就不执行了。希望可以解决下这个手势冲突。

**Comment by hydyy** [comment]
确实 我也遇到了。

**Comment by ibireme** [comment]
配置一下： `gesture.cancelsTouchesInView`。

**Comment by wy19901227** [comment]
yes还是no 默认是yes

发自我的 iPhone

**Comment by ibireme** [comment]
NO

**Comment by LCcccccc** [comment]
@ibireme 我是在YYLabel上加了highlightTapAction，父view上加了一个tapGesture, cancelsTouchesInView设为NO后，再点击一下highlight文本时，会先触发父view的事件，再触发highlightTapAction，请问要怎样设置才能只触发highlightTapAction而不触发父view的事件呢？谢谢！

**Comment by zhangyuhan18** [comment]
@LCcccccc 你好，想请教一下这个问题解决了吗“父view上加了一个tapGesture, cancelsTouchesInView设为NO后，再点击一下highlight文本时，会先触发父view的事件，再触发highlightTapAction“

**Comment by liycoding** [comment]
#pragma mark - UIGestureRecognizerDelegate 请在需要有link事件的地方设置YYTextHighlight 否则不设置YYTextHighlight
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
{
    BOOL isCanRecognize = YES; //是否能被识别
    
    if ([touch.view isKindOfClass:[YYLabel class]]) {
        YYLabel *label = (YYLabel *)touch.view;
        NSAttributedString *attributedString = label.attributedText;
        NSUInteger index = attributedString.yy_rangeOfAll.location;
        YYTextHighlight *hl = [attributedString yy_attribute:YYTextHighlightAttributeName atIndex:index]; //获取当前文本上是否有点击事件
        isCanRecognize = hl ? NO : YES; //检查是否有有高亮对象
    }
    
    return isCanRecognize;
}

**Comment by icoder20150719** [comment]
@liy666 你的这个方法不行 需要改动一下
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
{
    BOOL isCanRecognize = YES; //是否能被识别
    
    if ([touch.view isKindOfClass:[YYLabel class]]) {
        YYLabel *label = (YYLabel *)touch.view;
        NSAttributedString *attributedString = label.attributedText;
         NSUInteger index = [label.textLayout textRangeAtPoint:[touch locationInView:label]].start.offset;
        YYTextHighlight *hl = [attributedString yy_attribute:YYTextHighlightAttributeName atIndex:index]; //获取当前文本上是否有点击事件
        isCanRecognize = hl ? NO : YES; //检查是否有有高亮对象
    }
    
    return isCanRecognize;
}
