### ISSUE TITLE
YYTextView 输入自定义表情

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYText#386]
YY 你好，在使用 YYTextView 的过程中需要实现输入表情的功能，于是很自然地如下实现：
```swift
extension YYTextView {
    func insertEmoji(emotion: UIImage) {
        let emotionAttText = NSMutableAttributedString.yy_attachmentStringWithEmojiImage(emotion, fontSize: 17.0)
        let originalAttributText = NSMutableAttributedString(attributedString: attributedText!)
        originalAttributText.appendAttributedString(emotionAttText!)
        self.attributedText = originalAttributText
    }
}
```

然后结果是：一旦输入表情，文本就会被自动选中，如下图:

![img_7372](https://cloud.githubusercontent.com/assets/5517281/16237584/b087f2a0-380f-11e6-9a64-5b0838d0ba3b.PNG)

然后，如果此时切换到标准键盘输入正常文字，会发现字体大小也变了，如下图：

![img_7373](https://cloud.githubusercontent.com/assets/5517281/16237585/b2e016f4-380f-11e6-8b01-6e2934401e41.PNG)

字体变小这个问题最后通过加了一句：

```swift
originalAttributText.yy_font = UIFont.WeiboStatusFont(17.0)
```
解决了。之所以还抛出来主要是自己对框架源码不熟悉，所以不知道有没有更简洁的办法，故来询问。

但是第一个自动选中的bug还是没有找到解决办法，期待回复。谢谢！

**Comment by ibireme** [comment]
纯文本的话，用 UITextInput 那些协议会比较合适。富文本的话，重新替换整个文本，确实会有这些麻烦。那个选择区域的，可能需要手动调整一下 selectedRange 了。

**Comment by KittenYang** [comment]
恩，加了个 parser 然后手动调整 selectedRange 解决了。
