### ISSUE TITLE
异步编排，表情不能正常转换

### ISSUE THREAD

**Issue by tysenlau** [ibireme/YYText#39]
异步编排模式下，表情无法转换吗？求教

抱歉，图片，上传不上来！

**Comment by ibireme** [comment]
请贴出你的代码片段

**Comment by tysenlau** [comment]
if(!self.label){
        YYTextSimpleEmoticonParser *parser = [YYTextSimpleEmoticonParser new];
        parser.emoticonMapper = [[FTGlobalSingleton sharedSingleton] getChatEmojis];
        self.label=[YYLabel new];
        self.label.textParser=parser;
        self.label.layer.borderWidth=1.0f;
        self.label.displaysAsynchronously = YES; //开启异步绘制
       //self.label.ignoreCommonProperties = YES; //忽略除了 textLayout 之外的其他属性
        [self addSubview:self.label];
    }

    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        NSMutableAttributedString *text = [[NSMutableAttributedString alloc] initWithString:@"您好啊[f024t] 哈哈"];
        text.yy_font = [UIFont systemFontOfSize:16.0f];

        // 创建文本容器
        YYTextContainer *container = [YYTextContainer new];
        container.size = CGSizeMake(100, CGFLOAT_MAX);
        container.maximumNumberOfRows = 0;

        // 生成排版结果
        YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:text];
        dispatch_async(dispatch_get_main_queue(), ^{// 创建文本容器
            self.label.size = layout.textBoundingSize;
            self.label.textLayout = layout;
        });
    });

**Comment by tysenlau** [comment]
![Uploading 1.png…]()

**Comment by ibireme** [comment]
1. 看到你只用了 textLayout 来显示文本，那推荐开启 self.label.ignoreCommonProperties = YES。
2. 你是手动生成 textLayout 的，那么 textParser 应该在生成 AttributedString 后手动调用：

    NSMutableAttributedString *text ＝ ... 创建并配置字符串与属性
    [textParser parseText:text selectedRange:NULL];

**Comment by tysenlau** [comment]
谢谢大神赐教，已解决，就是在当有表情或者其他非文本格式时 layout前调用作者给出的建议即可！
