### ISSUE TITLE
使用YYKit中的YYLabel，设置textTapAction，报错

### ISSUE THREAD

**Issue by huangxinyu1213** [ibireme/YYText#391]
提示没有这个方法，YYKit版本1.0.7

**Comment by huangxinyu1213** [comment]
demo地址：https://github.com/huangxinyu1213/YYLabelT

**Comment by ibireme** [comment]
<img width="305" alt="2016-06-29 10 47 29" src="https://cloud.githubusercontent.com/assets/839283/16456728/7dde3926-3e4b-11e6-8c3f-c6d4b2bb191e.png">

Demo 没问题啊，也能编译运行。

**Comment by huangxinyu1213** [comment]
为啥我一运行就崩了，提示找不到方法。。。
![aeaecfb8-5af6-4565-9146-4d6c4db4eca9](https://cloud.githubusercontent.com/assets/10813641/16474388/ef2f3708-3ea8-11e6-9d83-8ec7077fdb43.png)

**Comment by huangxinyu1213** [comment]
不好意思，我把Xcode的DerivedData清空就好了。
