### ISSUE TITLE
YY大神好,我想问下有没有属性可以实现让textView自增高

### ISSUE THREAD

**Issue by XHJiang** [ibireme/YYText#393]
thanks

**Comment by ibireme** [comment]
是说输入文本的时候，bounds 跟着文本变化吗，这个可以监听文本输入，然后取 textLayout.boundingSize 来设置。可能你需要做一下判断，没有文本时也要给个默认高度吧。

**Comment by XHJiang** [comment]
嗯嗯,好的,谢谢哈,
