### ISSUE TITLE
YYTextAsyncLayerGetDisplayQueue对if (cur < 0) cur = -cur;有疑问

### ISSUE THREAD

**Issue by chenxin0123** [ibireme/YYText#399]
if (cur < 0) cur = -cur;这句应该对值达到最大值溢出之后的处理吧。
int32_t i = INT32_MAX;
    printf("%d\n",i);
    i++;
    printf("%d\n",i);
    if (i<0) {
        i = -i;
        printf("%d\n",i);
    }
    printf("%d\n",i % queueCount);
上面这段代码打印结果：
2147483647
-2147483648
-2147483648
0
就是说当cur达到最大溢出后 即便执行cur = -cur;还是溢出值
最终返回的queues[(cur) % queueCount]; 只可能是queues[0] 或者queues[负数]然后crash

**Comment by ibireme** [comment]
确实是，该修改一下。

**Comment by ibireme** [comment]
Fixed: https://github.com/ibireme/YYText/commit/8330d7f1d12e9843ea380504915ad52636a99729
