### ISSUE TITLE
当文本含有表情时，YYTextLayout计算出来的高度是不正确的

### ISSUE THREAD

**Issue by tysenlau** [ibireme/YYText#40]
应该是把表情符号当做文本处理后进行高度计算了，
如文本：您haidf阿打发士大夫撒地方发的啥方[f024t]法发达范德萨法撒旦法地方
[f024t] 代表一个表情

    NSMutableAttributedString *text = [[NSMutableAttributedString alloc]initWithString:txt];
    text.yy_font=[UIFont systemFontOfSize:17.0f];
   
    YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
    modifier.fixedLineHeight = 22.0f;
    
    YYTextContainer *container = [YYTextContainer new];
    container.size =  CGSizeMake([[UIScreen mainScreen] bounds].size.width * 0.7f-50, CGFLOAT_MAX);
    container.linePositionModifier = modifier;
    
    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:text ];

实质显示只有3行，计算出来是4行。屏幕宽度320

**Comment by ibireme** [comment]
参考 #39 
确认一下布局结果和显示时的属性是否一致。

**Comment by tysenlau** [comment]
多谢大神，已解决

**Comment by LixinQian** [comment]
@tysenlau  如何解决的？
