### ISSUE TITLE
你好，使用YYTextLayout算高度出问题了

### ISSUE THREAD

**Issue by hackjie** [ibireme/YYText#400]
这是我算高的代码：
- (CGFloat)calculateAttributeStringHeightWithAttributeString:(NSMutableAttributedString *)string fixWidth:(CGFloat)width
  {
  CGSize size = CGSizeMake(width, CGFLOAT_MAX);
  YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:size text:string];
  CGFloat stringHeight = layout.textBoundingSize.height;
  return stringHeight;
  }

这是我Label的设置：
- (YYLabel *)improveResultLabel
  {
  if (!_improveResultLabel) {
      _improveResultLabel = [YYLabel new];
      _improveResultLabel.textAlignment = NSTextAlignmentLeft;
      _improveResultLabel.font = [UIFont systemFontOfSize:16];
      _improveResultLabel.textColor = [HBTThemeManager appCustomGrayFontColor];
      _improveResultLabel.lineBreakMode = NSLineBreakByWordWrapping;
      _improveResultLabel.numberOfLines = 0;
  }
  return _improveResultLabel;
  }

这是我算高的部分：
NSMutableAttributedString _improveAttributeText = [NSMutableAttributedString makeAttributeStringWithText:item.resultEval font:[UIFont systemFontOfSize:fontSize] color:[HBTThemeManager appCustomGrayFontColor]];
    improveAttributeText.yy_lineSpacing = lineSpacing;
    improveAttributeText.yy_maximumLineHeight = fontSize;
    improveAttributeText.yy_minimumLineHeight = fontSize;
    CGFloat improveHeight = [NSMutableAttributedString calculateAttributeStringHeightWithAttributeString:stateAttributeText fixWidth:(SCREEN_WIDTH \* 0.75 - 2_kViewLeadingAndTrailingOffset)];
![0671f109-4332-4636-9502-9baf518bf58c](https://cloud.githubusercontent.com/assets/9956115/16674946/7106a986-44ef-11e6-9f28-f14ef8bfae17.png)

现在计算的文字高度总是缺少一段，给定的宽度限制应该没问题

**Comment by ibireme** [comment]
看着这些没问题。那后面是怎么设置 label 的文字、调整 label 的大小的呢、

**Comment by hackjie** [comment]
奇怪的是我如果直接返回YYTextLayout就可以，但是直接返回height就不丢失
- (YYTextLayout *)calculateAttributeStringHeightWithFixWidth:(CGFloat)width
{
    CGSize size = CGSizeMake(width, CGFLOAT_MAX);
    YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:size text:self];
    return layout;
} 可以没问题

+ (CGFloat)calculateAttributeStringHeightWithAttributeString:(NSMutableAttributedString *)string fixWidth:(CGFloat)width
{
    CGSize size = CGSizeMake(width, CGFLOAT_MAX);
    YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:size text:string];
    CGFloat stringHeight = layout.textBoundingSize.height;
    return stringHeight;
} 不行会缺失，这两个方法我是定义在NSMutableAttributedString分类中的

**Comment by ibireme** [comment]
之后是怎么设置 label 的文字、调整 label 的大小的呢？那段代码可能能看出原因。

**Comment by hackjie** [comment]
我上面写了的：
NSMutableAttributedString improveAttributeText = [NSMutableAttributedString makeAttributeStringWithText:item.resultEval font:[UIFont systemFontOfSize:fontSize] color:[HBTThemeManager appCustomGrayFontColor]];
improveAttributeText.yy_lineSpacing = lineSpacing;
improveAttributeText.yy_maximumLineHeight = fontSize;
improveAttributeText.yy_minimumLineHeight = fontSize;
CGFloat improveHeight = [NSMutableAttributedString calculateAttributeStringHeightWithAttributeString:stateAttributeText fixWidth:(SCREEN_WIDTH * 0.75 - 2kViewLeadingAndTrailingOffset)];

**Comment by ibireme** [comment]
我的意思是，后面 label.frame、text、attributedText、textLayout 属性是怎么设置的，设置的顺序是什么样的。

我觉得如果直接设置 texyLayout 应该是没问题的。

**Comment by hackjie** [comment]
嗯嗯 直接设置textLayout可以解决问题

**Comment by 515783034** [comment]
灰常感谢....用系统方式算了半天行高,一直都算的不正确,后来发现原来是YYLabel显示的带行间距的attributeString和系统显示的间距不太一样,用YYTextLayout计算结果正常.

**Comment by hackjie** [comment]
@515783034 nice

**Comment by hackjie** [comment]
@515783034 haha

**Comment by 515783034** [comment]
@hackjie 哥们,我直接返回高度,算的也是有缺失,你返回layout的话是怎么获取文本实际高度的?因为我是代码计算cell的行高的,需要知道这个高度

**Comment by 515783034** [comment]
如果在PC端输入文字包含了\r\n,那么计算时的高度就会少1行.而且在某些情况下,单独的句号会另起一行,导致计算行高错误. @ibireme

**Comment by ibireme** [comment]
@515783034 你是用 YYTextView 还是 YYLabel 显示的？另外，lineBreakMode 设置的是什么？

**Comment by leirenbaobao** [comment]
@ibireme YYTextLayout 在使用layoutWithContainerSize方法计算size的时候  可以设置行数吗。试了下 设置好像没有效果。

**Comment by leirenbaobao** [comment]
自问自答:
YYTextContainer *container = [YYTextContainer containerWithSize:size];
        container.maximumNumberOfRows = self.numberOfLines;
        YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:totalAttributedString];
