### ISSUE TITLE
怎么可以根据网络图片的高度来重新渲染页面

### ISSUE THREAD

**Issue by smallqiang** [ibireme/YYText#401]
现在做的项目是使用bbcode的内容返回给客户端，但图片没有知道高度，我用的SDWebImage加载了图片后再获取图片的宽高来替换之前的内容，但我还没加载图片前先给了一个占位图，不知道要怎样才能找回之前的NSMutableAttributedString位置来替换。谢谢！

**Comment by smallqiang** [comment]
应该用哪种方式去渲染比较好，我现在是用YYTextView，然后把图片当作是YYTextAttachment来显示，但是这个需要固定的宽高，我现在是有一个占位图的宽高，然后当图片获取到后再更新图片的实际高度，但是我找不到之前占位图的位置，所以比较难处理。

**Comment by ibireme** [comment]
只要关联到 YYTextAttachment，就能找到对应的图片了啊，然后刷新整个 TextView。

**Comment by smallqiang** [comment]
现在我就是把UIImageView给到了YYTextAttachment的content，然后用SDWebImage去加载图片，当图片下载完后我要怎么去做呢？我改变了UIImageView的宽高，然后不知道要怎么刷新TextView了。

**Comment by ibireme** [comment]
简单些的方法，在图片下载 completion block 内，发一个通知，把 imageView 通过消息带出去。外面 textView 监听通知，遍历当前 textView.textLayout.attachments，找到 attachment.imageView 相同的那个，然后更新。

**Comment by smallqiang** [comment]
好的，谢谢指点，我试试。

**Comment by smallqiang** [comment]
imageView.image =image;
imageView.bounds = CGRectMake(0, 0, 330, 500);
YYTextAttachment *attach1 = (YYTextAttachment*)[_textView.textLayout.attachments firstObject];
attach1.content = imageView;

我尝试了这样，但是只是图片的宽高变了，图片浮在了文字上，不知道textView要怎样去刷新整个内容呢？

**Comment by ibireme** [comment]
attachmet 本身的 size 也要更新一下。

textView 可以重新清空和设置一下 attributedText。

**Comment by smallqiang** [comment]
attachmet只是一个Objct，怎样去更新它的size呢？然后textView也没有相关的reload方法。

**Comment by smallqiang** [comment]
attachmet只是一个Object，怎样去更新它的size呢？然后textView也没有相关的reload方法。

**Comment by ibireme** [comment]
哦。。是的，Attachment 是配合 RunDelegate 使用的。这样的话，那就重新创建一次，然后用 [replaceCharactersInRange:withAttributedString:] 来替换。

textView 更新的话，试试 
    NSAttributedString text = textView.attributedText;
    textView.attributedText = nil;
    textView.attributedText = textView.attributedText

**Comment by smallqiang** [comment]
但是之前的Attachment的range无法获取，因为替换之后range的初始位置和长度改变了，要怎样才能获取回之前Attachment的位置，然后替换新的。

**Comment by smallqiang** [comment]
因为我用了NSMutableAttributedString的yy_rangeOfAll也只是得到一个值为{0,1}，不是正确的位置，只是知道了长度，所以不知道怎么去替换原有的attachment。

**Comment by smallqiang** [comment]
解决了，原来textLayout里面有保存每个attachment的位置的。谢谢指导。
