### ISSUE TITLE
NSString的containsString是在iOS8以上的方法，在iOS7中会崩溃

### ISSUE THREAD

**Issue by zhmch0329** [ibireme/YYText#404]
YYLabel.m中的setFontName_:方法中使用了containsString:方法，在YYTextView中也同样使用了这个iOS8以上才提供的方法。建议使用([str rangeOfString:@"target"].length > 0)代替

**Comment by ibireme** [comment]
感谢指出问题。

目前只有在用 InterfaceBuilder 来手动填写 FontName 时才会遇到，再加上之前项目里为了兼容已经重写了 containsString 方法，所以一直没注意到把。

Fixed: https://github.com/ibireme/YYText/commit/eb6ab793a4a95ca2cd0ed337d8a227dca2fefa26
