### ISSUE TITLE
YYLabel显示不出的问题

### ISSUE THREAD

**Issue by yhcflyy** [ibireme/YYText#41]
我使用的Masonry布局，在ios8.4下遇到了如下问题
1.当要显示的字体较大时超过了要显示的范围，YYLabel什么都不显示
2.当添加了文本解析器后，必须减小字体，文字和表情才能显示出来
![image](https://cloud.githubusercontent.com/assets/5007022/11455712/55deabb4-96a7-11e5-962d-e16e3d7fd0d6.png)
没有使用表情解析时能够显示出来
![image](https://cloud.githubusercontent.com/assets/5007022/11455699/f669dbe0-96a6-11e5-8089-62f354593550.png)
使用了表情解析显示不出来
![image](https://cloud.githubusercontent.com/assets/5007022/11455704/3191ff9a-96a7-11e5-95d6-6e0e6862c52e.png)
当把字体缩小成13后就能显示了
![image](https://cloud.githubusercontent.com/assets/5007022/11455717/9196d1e0-96a7-11e5-8f02-e474e788f5b2.png)
3.YYLabel的textVerticalAlignment属性不起作用

**Comment by ibireme** [comment]
1. 2. 见 readme 结尾处的 已知问题：当 YYLabel 的高度小于第一行文本的内容高度时，文本不会显示。
3. textVerticalAlignment 的作用是，把排版后的内容，包括文本行的 ascent/descent，按照整体方向居上/中/下。表情和英文的 ascent、descent 大于中文，所以可能会产生不一致，但并不是不起作用。

上面的问题和 Masonry、系统版本无关。
