### ISSUE TITLE
YYTextView的placeholderFont 不支持苹方体

### ISSUE THREAD

**Issue by CoderMikeHe** [ibireme/YYText#422]
YYTextView的placeholderFont 不支持苹方体，一旦用了苹方体 ，就不显示placeholder了，用systemFontOfSize设置没问题。

**Comment by leibaozai** [comment]
你有没有做系统判断，在iOS9下好像是不显示苹方的。

**Comment by ibireme** [comment]
创建字体后，看看是否为 nil。

**Comment by gaochar** [comment]
`textView.placeholderFont = [UIFont fontWithName:@"PingFang-SC-Regular" size:17.0];`
