### ISSUE TITLE
Crash everytime a YYTextView was created in version 0.9.11

### ISSUE THREAD

**Issue by sleepEarlier** [ibireme/YYText#43]
Everytime a Creat a YYTextView and run, app would crash.Like the picture below:

<img width="712" alt="2015-11-29 3 45 15" src="https://cloud.githubusercontent.com/assets/10412018/11455949/abbd7a0c-96b0-11e5-9772-815ee3118fb0.png">
I only write 2 lines of code like below:
<img width="311" alt="2015-11-29 3 44 04" src="https://cloud.githubusercontent.com/assets/10412018/11455951/c149d500-96b0-11e5-9be0-9a8172346a66.png">

it that any obvious mistake i made, or any config should be add?

**Comment by ibireme** [comment]
A workaround: call `[YYTextEffectWindow sharedWindow].rootViewController = [UIViewController new];` once at your app startup.

Reference to issues #28, I'm looking for a better way to solve that problem.

**Comment by sleepEarlier** [comment]
Thank you! It workded!

**Comment by ibireme** [comment]
Fixed
