### ISSUE TITLE
使用YYLabel图文混排，固定行高时计算Label高度问题

### ISSUE THREAD

**Issue by zyi1992** [ibireme/YYText#430]
- (YYLabel *)contentLabel {
    if (!_contentLabel) {
        _contentLabel = [YYLabel new];
        _contentLabel.font = Font(16);
        _contentLabel.numberOfLines = 0;
        _contentLabel.textColor = [UIColor text2Color];
        _contentLabel.textVerticalAlignment = YYTextVerticalAlignmentBottom;
    }
    return _contentLabel;
}

- (YYTextLayout *)textLayout {
    if (!_textLayout) {
        YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new];
        modifier.fixedLineHeight = 25;
        YYTextContainer *container = [YYTextContainer new];
        container.size = CGSizeMake(SCREEN_WIDTH - 24, CGFLOAT_MAX);
        container.linePositionModifier = modifier;
        _textLayout = [YYTextLayout layoutWithContainer:container text:self.contentAttr];
    }
    return _textLayout;
}

上面是label的定义和layout的定义  图片是用yy_attachmentStringWithContent实现  宽度等于label的最大宽度SCREEN_WIDTH - 24  高度是算出来的  最后layout算出来的高度有些问题  
这里有几个问题
1.使用固定行高后  yy_attachmentStringWithContent 实现的图片高度会怎么算
2.YYTextLayout的textBoundingRect 的size和textBoundingSize差很多  这两者有什么区别 想要获取label的高度  应该使用那个参数
3.如何设置label的frame 就是设置label的位置 
self.contentLabel.textLayout = link.textLayout;
  self.contentLabel.frame = CGRectMake(12, 100, self.contentLabel.frame.size.width, self.contentLabel.frame.size.height);
上面是我现在的实现  希望能得到你的回复

**Comment by ibireme** [comment]
1. 如果用 textLayout 来显示，那可以设置 _contentLabel.ignoreCommonProperties = YES;
2. 固定高度后，每行文本的 baseline 位置会被固定，不受内容的影响。如果还要进行其他调整，那需要自己实现 linePositionModifier 协议来做了。
3. textBoundingRect 是原始数据，包括小数点和其他内容；textBoundingSize 是根据 textBoundingRect 计算得出的，用于 Label 宽高设置。

**Comment by zyi1992** [comment]
如果不设置固定行高 ，只显示文字的时候也会有个别行的间距高度不一样，这个问题有办法解决吗？但是使用固定行高之后图文混排的高度又总是算不准。

**Comment by ibireme** [comment]
不太清楚"高度计算不准"是什么情况。。
你可以自己实现 YYTextLinePositionModifier 来修改每行的位置，具体可以参考下 YYTextLinePositionSimpleModifier 的实现。
