### ISSUE TITLE
很严重的crash Bug  ，YYTextview使用attributedText赋值单个系统❤️ 表情，内存会暴增导致crash 

### ISSUE THREAD

**Issue by nizenyang** [ibireme/YYText#434]
赋值

`NSDictionary *dic = @{NSFontAttributeName:[UIFont systemFontOfSize:16],
NSForegroundColorAttributeName:[UIColor redColor]};
 NSMutableAttributedString *mutableAttStr = [[NSMutableAttributedString alloc] initWithString:@"❤️"];
 [mutableAttStr addAttributes:dic range:NSMakeRange(0, mutableAttStr.length)];`

`YYTextView *textView = [YYTextView new];
 textView.selectable = NO;
 textView.editable = NO;
 textView.highlightable = YES; 
textView.scrollEnabled = NO; 
textView.textContainerInset = UIEdgeInsetsMake(6, 0, 10, 0);
 textView.dataDetectorTypes = UIDataDetectorTypePhoneNumber | UIDataDetectorTypeLink; YYTextLinePositionSimpleModifier *modifier = [YYTextLinePositionSimpleModifier new]; modifier.fixedLineHeight = 20; 
textView.linePositionModifier = modifier;
 textView.attributedText = mutableAttStr;
 textView.size = self.view.size;
 textView.delegate = self; 
if (kiOS7Later) { 
textView.keyboardDismissMode = UIScrollViewKeyboardDismissModeInteractive; } else { textView.height -= 64; }
 textView.contentInset = UIEdgeInsetsMake(toolbar.bottom, 0, 0, 0); 
// textView.scrollIndicatorInsets = textView.contentInset; 
// textView.selectedRange = NSMakeRange(text.length, 0);
 [self.view insertSubview:textView belowSubview:toolbar];
 self.textView = textView;`

在你的demo里面的YYEditExample.m
里面测试，模拟器内存暴增至16g后崩溃

**Comment by nizenyang** [comment]
@ibireme @EuanChan @willbin @devjiangzhou @poboke

**Comment by devjiangzhou** [comment]
@nizenyang  找到问题了，是因为换行符的问题。

**Comment by ibireme** [comment]
<img width="927" alt="2016-08-05 4 27 05" src="https://cloud.githubusercontent.com/assets/839283/17430890/7a6c77e4-5b29-11e6-8193-882e90e7a646.png">

iOS8 和 9 的模拟器上都没复现，内存 32 MB。
能说下你的系统、模拟器型号等信息吗？

**Comment by devjiangzhou** [comment]
@ibireme  我在真机上复现了，我调试是由于换行符\r的问题。 我换成了 \r\n就好了

**Comment by nizenyang** [comment]
模拟器是iPhone 6s Plus  Xcode Version 7.3.1 (7D1014) 

![image](https://cloud.githubusercontent.com/assets/8390188/17431021/42f74892-5b2a-11e6-9455-f39d518d8a70.png)
![image](https://cloud.githubusercontent.com/assets/8390188/17431050/6f1b8348-5b2a-11e6-8a87-5e425dce33fd.png)
代码的图片见下
![image](https://cloud.githubusercontent.com/assets/8390188/17431059/78c1dd98-5b2a-11e6-8fec-83e3fbd6d967.png)

**Comment by nizenyang** [comment]
@devjiangzhou 你加了一个\n会不会导致文本换行呢？

**Comment by nizenyang** [comment]
@devjiangzhou 你确定吗，我想说一句就是NSDictionary *dic = @{NSFontAttributeName:[UIFont systemFontOfSize:16], NSForegroundColorAttributeName:[UIColor redColor]};
这行代码如果改成 NSDictionary *dic = @{ NSForegroundColorAttributeName:[UIColor redColor]};就不会崩溃，你可以试试，我怀疑是设置了字号的问题
@devjiangzhou @ibireme

**Comment by nizenyang** [comment]
@devjiangzhou 好像不是加一个\n就能解决，我加了，问题还是存在的

**Comment by devjiangzhou** [comment]
@nizenyang ibireme已经合并我的代码了 你可以去试试。  \r\n 是YYTextview内部加的

**Comment by nizenyang** [comment]
@devjiangzhou 我下载最新的代码可以试试么，然后我想说的是，我就是在你说的那个地方加的，是同一个地方加的，我看了你加的那个代码，好想真的不管用

**Comment by devjiangzhou** [comment]
@nizenyang  确实有问题
@ibireme   [text replaceCharactersInRange:NSMakeRange(text.length, 0) withString:@"\r"]; // add for nextline caret
不好意思 ibireme 刚才改的确实有问题，但我可以确定的是由于在这添加换行符导致内存暴涨，请问在为什么要在这加换行符呢？

**Comment by nizenyang** [comment]
@devjiangzhou 是啊，有问题的
@ibireme 你可以试试在内存暴增的时候，点击暂停可以看到会停在一个方法当中

**Comment by nizenyang** [comment]
@ibireme 
![image](https://cloud.githubusercontent.com/assets/8390188/17432365/6531d9b6-5b31-11e6-87e4-23117997f564.png)

**Comment by nizenyang** [comment]
@ibireme @devjiangzhou 哥们这个问题能解决吗？哎，我还等着这问题修复 好上线呢

**Comment by ibireme** [comment]
照着上面图里的代码敲了一遍终于复现了。
YYTextView 创建后，没有设置 frame，宽度为0，这时 CTFramesetterCreateFrame 本应该返回一个空的 CTFrame，但在处理这个特殊字符串时，CoreText 的这个方法陷入了内部死循环。这应该是 CoreText 的 Bug。

现在可以在创建 YYTextView 后随便设置一个 frame 来避免这种情况，稍后内部会处理一下来避免。

**Comment by nizenyang** [comment]
@ibireme 棒棒的，应该是的，在ios10里面这个bug就不存在，应该是苹果修复了这个bug，不过在ios9上就会出现这个问题，弱弱的问一句，啥时候修好啊，我还等着用呢，是在下一个版本里修复么，还是怎么说，我怎样可以在我的代码里修复这个bug，还是说要等你release一个版本？

**Comment by ibireme** [comment]
已修复到 Master 分支：https://github.com/ibireme/YYText/commit/944fedf816f7099f155a1d6d874c5cf3a168c201 下个 Release 会带上。

目前可以在创建 YYTextView 后随便设置一个 frame 来避免这种情况。

**Comment by hydyy** [comment]
我很早遇到过这个问题，终于修复了~！

**Comment by bitnpc** [comment]
实测
`if (container.size.width <= 0 || container.size.height <= 0) goto fail;`
这句话加了
创建 YYTextView 后随便设置一个 frame，并没有解决问题。
最后我在所有的text后面加了一个空格，就行了。
虽然办法有点low，但是总算解决问题了。
