### ISSUE TITLE
YYTextLayout 算高度时，文本中有空格的时候会出现问题

### ISSUE THREAD

**Issue by CheckRan** [ibireme/YYText#438]
![1fb433b1-2601-48b9-97dd-a85f7d7839df](https://cloud.githubusercontent.com/assets/14838025/17424249/ac25a0ba-5af4-11e6-9d94-01addc8d54bd.png)
系统SystemSize空格在中间和后面没有区别，通过textLayout 算出来的高度有差别，
![f962a307-0904-4dc2-b710-2d12b11053af](https://cloud.githubusercontent.com/assets/14838025/17424273/f1c318fa-5af4-11e6-9a72-6334859f5bc5.png)
在应用中就是这样，差别不大，但是可以体验出来

**Comment by CheckRan** [comment]
@ibireme

**Comment by ibireme** [comment]
系统计算的结果是用于 UILabel 这些控件的；YYTextLayout 是直接取 CoreText 的结果，并且只用于 YYLabel 这些控件的，所以可能有些差异吧。

**Comment by CheckRan** [comment]
@ibireme  根据 #31  的思路解决的，YYTextLinePositionModifier
表情、文本分别为不同的单独高度
