### ISSUE TITLE
YYLabel 包含图片会闪

### ISSUE THREAD

**Issue by LawrenceHan** [ibireme/YYText#445]
YYLabel开启同步

有一个问题，假如我同屏有5个cell (YYLabel)，其中第一个包含图片，
那么当我向下滑动显示第6个cell时，图片会在第6个cell出来的位置闪一下。考虑到cell复用问题，
我在 perpareForReuse 这个cell方法里 把YYLabel.layout设为nil，
或者直接把YYLabel.layer.contents设为nil都不行。

由于保密原因，我把视频直接发到你邮箱 ibireme@gmail.com @ibireme

**Comment by ibireme** [comment]
设置 label.fadeOnAsynchronouslyDisplay = NO 看看。

**Comment by LawrenceHan** [comment]
试过了，不行的@_@ @ibireme

**Comment by ibireme** [comment]
那在 prepareForReuse 里试试：

    [label.layer removeAnimationForKey:@"contents"];
    [CATransaction begin];
    label.textLayout = nil;
    label.layer.contents = nil;
    [CATransaction commit];

另外，如果图片是 UIView、CALayer 这样的对象，那试试直接移除 label 的所有 subView。

**Comment by LawrenceHan** [comment]
并不行啊，但是我用的是ios8 不知道有没有关系，ios9也有，但是很少出现。
@ibireme

**Comment by ibireme** [comment]
如果能提供一个简单的 Demo 或者可复现问题的代码片段，那可以再查查看。现在弄不清楚是什么原因。。

**Comment by LawrenceHan** [comment]
@ibireme 邮件发你 cell.m文件了，辛苦了。

**Comment by ibireme** [comment]
Cell.m 代码太多而且混有业务逻辑，我这里跑不起来也复现不了问题。。
看代码暂时没发现问题，我觉得可能是某处添加了什么动画影响到了内容。

**Comment by LawrenceHan** [comment]
@ibireme 那这样好不好，你告诉我应该看哪一部份原代码，我自己尝试修一下，修成功了我提个pr给你

**Comment by LawrenceHan** [comment]
@ibireme 已经解决了，还是cell复用的问题，我只复用了一种cell，然后根据YYTextLayout object来改变大小。现在我创建了四种不同的cell，对应图片，文字等。这样就没有冲突了。

**Comment by LawrenceHan** [comment]
另外我觉得textlayout可以再优化一下，YYLabel根据textlayout显示内容，但是为什么还是用layout里面的UIImageView来显示图片呢？可不可以直接生成一个layer来表示这个cell呢？MVVM里textlayout就相当于cell的view model啊。

**Comment by WangJianShi** [comment]
YYLabel设置了    self.displaysAsynchronously = YES; self.fadeOnAsynchronouslyDisplay = NO;//异步渲染动画； self.fadeOnHighlight = NO;//高亮渐变效果。刷新的cell重用的时候label文字会闪
