### ISSUE TITLE
求助：如何使用YYTextLayout计算最终显示的行数

### ISSUE THREAD

**Issue by songhailiang** [ibireme/YYText#447]
我用YYLabel显示一段内容，内容里会有表情，我现在的需求是默认显示5行，超过5行就显示“全文”，点击“全文”后显示“收起”，所以没法用Demo里的truncationToken，而且内容里可能会有\n这种换行符，我该怎么计算最终显示的行数呢？

**Comment by ibireme** [comment]
计算行数前，先不限制高度，生成 YYTextLayout 后可以直接取 YYTextLayout.rowCount。

**Comment by songhailiang** [comment]
非常感谢！之前没有注意到这个属性，很赞！

**Comment by csc-EricWu** [comment]
@songhailiang 能否看下最终实现代码，遇到同样问题了

**Comment by csc-EricWu** [comment]
![image](https://user-images.githubusercontent.com/13517061/42500397-c23f476c-8463-11e8-9b4d-c31d500c136c.png)
看了几天没人解答，自己解决了，希望后面人能用得上。
