### ISSUE TITLE
Found a weird performance of YYTextView when it's contentEdge was (0, 0, 0, 0)

### ISSUE THREAD

**Issue by sleepEarlier** [ibireme/YYText#45]
Simply creat a YYTextView:
```objective-C
    self.automaticallyAdjustsScrollViewInsets = NO;
    YYTextView *textView = [[YYTextView alloc]initWithFrame:CGRectMake(0, 20, self.view.width, 100)];
    textView.backgroundColor = [UIColor colorWithWhite:0.5 alpha:0.5];
    textView.text = @"This is test text";
    textView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0);
    [self.view addSubview:textView];
```
Run app and it looks like:
![Uploading 2.png…]()
![Uploading 2.png…]()

(Sorry failed to upload a screenShot, the text ("this is a test text")  can't be seen in textView, and after I type some word, still nothing can be seen including the cursor)

Then I change edgeInset.top to 0.5 and run agin,  YYTextView look normal, it also look fine when edgeInset.top was -0.5.
But when edgeInset.top was 0, seems everything just went wrong. 
I found you asways set the contentEdge to (64, 0 , 0 , 0) in the Demo, was the contentEdge's top just can't be 0? Or am I miss something?

**Comment by ibireme** [comment]
Fixed
