### ISSUE TITLE
YYLabel的超链接似乎能不能带个URL

### ISSUE THREAD

**Issue by syxiaqj** [ibireme/YYText#453]
之前显示自定义表情，我用了YYLabel，发现挺不错，但是现在要实现一个功能：比如点击“百度”两个字，需要跳转到百度。使用highlightTapAction，只能获取被点击的文字，无法获取连接？这个YYLabel能办到吗？

**Comment by ibireme** [comment]
可以把 URL 放到 YYTextHighlight.userInfo 里，也可以直接自定义一个 key 添加到 NSMutableAttributedString 上。

**Comment by syxiaqj** [comment]
ok，设置的时候可以，highlightTapAction的结构上并没有userInfo的信息，我需要如何读取？

**Comment by syxiaqj** [comment]
搞定了，我看NSAttributedString这个有个API能获取

**Comment by limuyang2** [comment]
能说明下是哪个api么？我半天没有找到userInfo的获取办法

**Comment by JRJian** [comment]
`YYLabel *yyLabel = (YYLabel *)containerView;YYTextHighlight *highligh = [yyLabel.textLayout.text attribute:YYTextHighlightAttributeName atIndex:range.location];
NSString *innerUrlString = highligh.userInfo[@"urlString"];`
