### ISSUE TITLE
图文混排支持图片的点击事件吗？

### ISSUE THREAD

**Issue by ZHDeveloper** [ibireme/YYText#454]
项目中有个需求是要点击图片的事件，我在图片的NSMutableAttributedString中设置 yy_setTextHighlightRange，点击没反应。

    UIImage *image = [UIImage imageNamed:@"ls_reds"];
    
    NSMutableAttributedString *attrImage = [NSMutableAttributedString yy_attachmentStringWithContent:image contentMode:UIViewContentModeCenter attachmentSize:image.size alignToFont:font alignment:YYTextVerticalAlignmentCenter];
    
    [attrText appendAttributedString:attrImage];
    
    [attrImage yy_setTextHighlightRange:NSMakeRange(0, attrImage.length) color:[UIColor whiteColor] backgroundColor:[UIColor whiteColor] tapAction:^(UIView * _Nonnull containerView, NSAttributedString * _Nonnull text, NSRange range, CGRect rect) {
        NSLog(@"-----");
    }];
    
    YYLabel *label = [YYLabel new];
    
    label.numberOfLines = 0;
    
    label.attributedText = attrText;
    label.textVerticalAlignment = YYTextVerticalAlignmentTop;

**Comment by ibireme** [comment]
yy_setTextHighlightRange 要放在 appendAttributedString 之前。
`-[NSMutableAttributedString appendAttributedString:]` 的时候，是把传入的字符串 copy 进去的。
