### ISSUE TITLE
在ios10出现兼容问题？

### ISSUE THREAD

**Issue by tunfo** [ibireme/YYText#459]
在ios10无论是单行还是多行，最后都会有...省略号。如果是多行的话最后一行会被吃掉。比如三行的文字，只显示2行，第三行没有了。

**Comment by ibireme** [comment]
同样的代码，是只在 iOS 10 上有问题，还是在其他版本也有问题？

**Comment by zhangxiaolian1991** [comment]
只在 iOS 10 上，其它版本都是好的

**Comment by wy19901227** [comment]
没ios10机子，关注中。。

**Comment by tunfo** [comment]
只在ios10上有问题（真机上跑的，模拟器还没下载）

**Comment by junbinchencn** [comment]
同样也出现了这个问题

**Comment by zhangxqq** [comment]
我的也是，如果把字体设置为9的默认字体，helvetica就正常了，否则就是少显示一行

**Comment by itdongbaojun** [comment]
同样遇到了该问题，今天刚刚设计的iOS10 GM版本

**Comment by itdongbaojun** [comment]
@ibireme 今天在适配iOS 10发现了同样的问题，应该是iOS10的字体变化导致的。

**Comment by ZengyiMa** [comment]
我没这个问题，检查下高度有没有给足试试，我今天试试GM 调整下高度就好啦

**Comment by itdongbaojun** [comment]
@ZengyiMa 高度怎么给？是通过YYText的方法动态计算出来的高度，难道是需要在计算出来的基础上额外增加一点高度吗？

**Comment by itdongbaojun** [comment]
现在目前的解决方式是，通过YYTextLayout计算完size后，需要在计算出来的height的基础上稍微调整高度大一些

**Comment by ibireme** [comment]
Fixed: https://github.com/ibireme/YYText/commit/01da2806f32656399bac517e60ff932dc542d168

**Comment by wy19901227** [comment]
👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻

发自我的 iPhone

**Comment by wy19901227** [comment]
啥时候更新pod？

发自我的 iPhone

**Comment by ibireme** [comment]
已更新

**Comment by SS0424** [comment]
中文和表情 多行 iOS 10 下还是会出现。。。。。

**Comment by SS0424** [comment]
作者您好请问表情多行时 在iOS 下会出现..... 计算的出来的size 比iOS9 上的宽高都要小一点
![wechatimg6](https://cloud.githubusercontent.com/assets/13725793/18873311/4b71d244-84f1-11e6-8672-bf15a87af3e2.jpeg)
