### ISSUE TITLE
你好，引用报错问题。

### ISSUE THREAD

**Issue by zy30651** [ibireme/YYText#46]
你好，我在使用你的YYText框架练习的时候，当我模仿YYTextDemo里边的YYTextAttachmentExample，有qq几个动画，他们使用的是YYImage，每次我引用YYImage，就报错。找不到什么问题，没有重复的YYImageCoder文件名，这文件也没有被链接2次。把YYImage删除后又添加还是不行。Other Linker Flags下边什么都没有。另外这种报错每次遇到都很麻烦，不知道您怎么解决的呢？我只知道看看有没文件名重复，build Phases有没有链接重复，别的都不确定
日志：
Undefined symbols for architecture x86_64:
"_crc32", referenced from:
_yy_png_copy_frame_data_at_index in YYImageCoder.o
-[YYImageEncoder _encodeAPNG] in YYImageCoder.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ibireme** [comment]
不知道你是通过哪种方式安装的，请参考 YYImage 里 手动安装的方法添加依赖的 framework
