### ISSUE TITLE
输入英文单词重复.

### ISSUE THREAD

**Issue by Ycong** [ibireme/YYText#460]
# 输入英文单词,比如who 然后选择whole就会变成whowhole.
![img_0560](https://cloud.githubusercontent.com/assets/10216202/17661158/0f531956-6310-11e6-9755-8dd9574b8130.PNG)
![img_0561](https://cloud.githubusercontent.com/assets/10216202/17661198/426d90aa-6310-11e6-99a3-e3c04ba37a05.PNG)

**Comment by ibireme** [comment]
Duplcated: https://github.com/ibireme/YYText/issues/89
