### ISSUE TITLE
老郭 如何生成这种注释哦 不会是手敲吧？

### ISSUE THREAD

**Issue by blackchena** [ibireme/YYText#463]
![336f3a61-acdf-4145-bf5f-cf7a00748d92](https://cloud.githubusercontent.com/assets/8891002/17731656/ba1cc080-64a0-11e6-89f0-213899228020.png)

**Comment by ibireme** [comment]
好像是手敲的？记不太清了。。
一般这种 ASCII 画图都有现成工具，比如 http://asciiflow.com/ 这样的，也有 Native 的 App。

**Comment by blackchena** [comment]
很好很强大呀，很实用谢谢啦
