### ISSUE TITLE
YYTextView有没有办法对一个完整的string判断显示区域不够的时候不要截断分开两行显示,而是另起一行显示呢

### ISSUE THREAD

**Issue by xinlidexiaoman** [ibireme/YYText#464]
![2016-08-18 16 41 10](https://cloud.githubusercontent.com/assets/3995236/17767490/c029b088-6562-11e6-8d40-8bc1127004d8.png)

像这个 百老汇 应该是一个完整的   要是区域不够的话 那么可否对这个另起一行显示呢

我看这个对英文支持的比较好

**Comment by ibireme** [comment]
可以看下这个问题: https://github.com/ibireme/YYText/issues/62
