### ISSUE TITLE
UILabel 实现YYLabel 的文字点击效果

### ISSUE THREAD

**Issue by DozEuto** [ibireme/YYText#469]
项目需要用到 cell 的自适应高度，用 storyboard 创建的 UILabel 无法实现文字的点击效果，UILabel 的交互已打开，是我用的方法不对还是目前 storyboard 创建的 UILabel 无法实现这个效果？

**Comment by HoneyLuka** [comment]
其实YYLabel是一个UIView，所以你需要将你storyboard里的UILabel换成UIView

**Comment by DozEuto** [comment]
@HoneyLuka 控件UIView 的class换成YYLabel 可以实现点击效果，新的问题，UIView怎么自动的去适应文字的高度呢？

**Comment by HoneyLuka** [comment]
给YYLabel设置好preferredMaxLayoutWidth属性，然后他自己就可以适应高度了，我自己在做这块的时候是代码内控制的。 
xib里为了防止约束报错我设置了一个固定height的约束，然后选中这个约束的remove at build time选项。

**Comment by DozEuto** [comment]
@HoneyLuka 设置好preferredMaxLayoutWidth属性后，自适应了，谢谢
