### ISSUE TITLE
请问两个问题

### ISSUE THREAD

**Issue by 38598312** [ibireme/YYText#47]
1、插入图片后，字体会变的很小，好像是一个默认字体。
2、如何获取我插入的附件数组？比如我要输入很多文字，很多图片，最后我要做一个“提交文章”的功能，这些图片我要上传到服务器上。
3、输入很多文字的时候，内存还是会变得很大，有被系统杀掉的风险。

**Comment by ibireme** [comment]
1. 不知道你是怎么插入图片的。。如果字体不对，可以通过 typingAttributes 控制，也可以直接取出 attributedText 修改后设置回去。

2. 直接取出 attributedText，然后遍历 YYTextAttachmentAttributeName 属性就可以获得到所有 YYTextAttachment 附件了；另外也可以直接通过textView.textLayout.attachments 访问附件数组。

3. 关于大量文本的输入，可以见这个讨论: #16

**Comment by 38598312** [comment]
你好。问题1:
UIImage *image = img;
            attachment = [NSMutableAttributedString yy_attachmentStringWithContent:image contentMode:UIViewContentModeScaleAspectFit attachmentSize:CGSizeMake(CGRectGetWidth(_textView.frame), CGRectGetWidth(_textView.frame) * image.size.height / image.size.width) alignToFont:_textView.font alignment:YYTextVerticalAlignmentCenter];
            [text appendAttributedString: attachment];
            [text appendAttributedString:[[NSAttributedString alloc] initWithString:@"\n" attributes:nil]];
            _textView.attributedText = text;
![Uploading 111.gif…]()

**Comment by 38598312** [comment]
你好。问题1:
UIImage *image = img;
            attachment = [NSMutableAttributedString yy_attachmentStringWithContent:image contentMode:UIViewContentModeScaleAspectFit attachmentSize:CGSizeMake(CGRectGetWidth(_textView.frame), CGRectGetWidth(_textView.frame) * image.size.height / image.size.width) alignToFont:_textView.font alignment:YYTextVerticalAlignmentCenter];
            [text appendAttributedString: attachment];
            [text appendAttributedString:[[NSAttributedString alloc] initWithString:@"\n" attributes:nil]];
            _textView.attributedText = text;

我自己试验发现这么做（文档里面介绍的方法）会导致字体变成默认值，我只有自己重新赋值
_textView.font = _textViewFont;后，才能恢复正常。可能是个bug吧？

**Comment by ibireme** [comment]
在这一行` [text appendAttributedString:[[NSAttributedString alloc] initWithString:@"\n" attributes:nil]];` 里新建了一个没有属性的 AttributedString，然后附加到了整个 text 后面，这会让text 结尾处是没有属性的。

**Comment by 38598312** [comment]
多谢回答。希望这个库可以越做越好。

**Comment by 38598312** [comment]
啊，不好意思，刚忘了问一个问题，那就是我插入图片（uiimage）可以点击吗（我希望做一个点击放大效果）,我用view debug看了一下，没看到uiimageview，请问我可以做到这个吗？

**Comment by ibireme** [comment]
创建 attachment 时，传入的 UIImage 会通过绘制的方式展现出来。你可以传入一个 UIImageView 或者 UIButton 来接收触摸事件。

**Comment by 38598312** [comment]
好像不行哎，用debug看了一下，表面有一层YYTextSelectionView，好像点击事件被它截获了，YYTextContainerView上面的uimageview点击没反应。求助～

**Comment by ibireme** [comment]
那个SelectionView 不会截获事件。。。
看看你的ImageView 是不是没开启 userInteractionEnabled？

**Comment by 38598312** [comment]
不会的按理说。。。不会这么低级的错误。代码如下：
UIImageView *imageView = [[UIImageView alloc] initWithImage:imageToSave];
    imageView.userInteractionEnabled = YES;
    CGFloat fWidth = CGRectGetWidth(textView.frame) - 3 * fSideSpace;
    imageView.frame = CGRectMake(fSideSpace, 0, fWidth, bVideo ? PHOTO_MAX_HEIGHT : fWidth * imageToSave.size.height / imageToSave.size.width);
    attachment = [NSMutableAttributedString yy_attachmentStringWithContent:imageView contentMode:UIViewContentModeScaleAspectFit attachmentSize:imageView.frame.size alignToFont:_textViewFont alignment:YYTextVerticalAlignmentBottom tag:tag];
    [attachment addAttribute:NSFontAttributeName value:_textViewFont range:NSMakeRange(0, attachment.length)];
    [text appendAttributedString: attachment];
    [text appendAttributedString:[[NSAttributedString alloc] initWithString:@"\n" attributes:@{NSFontAttributeName:_textViewFont}]];
    
    [imageView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(clickPhoto:)]];
    _textView.attributedText = text;

什么地方有问题吗？

**Comment by ibireme** [comment]
我检查了一下，是有问题：
为了防止附件触摸事件阻碍文本选择，附件所在的内部视图触摸事件被禁用了。

目前的 workaround 是创建一个 YYTextHighlight 添加到 Attachment 上来接收触摸事件，稍后我会尝试看看是否能有更好的解决办法。

**Comment by ibireme** [comment]
Fixed

**Comment by ParryGao** [comment]
怎么解决的呢
