### ISSUE TITLE
关于自定义表情异步绘制

### ISSUE THREAD

**Issue by leehonn** [ibireme/YYText#470]
我看见异步绘制里面，第一次异步绘制的时候已经绘制了一次表情，后来在主线程里面又绘制了一次表情，为什么要这么做呢？去掉会有什么后果？

**Comment by leehonn** [comment]
是YYLabel部分的异步

**Comment by ibireme** [comment]
你是说 `task.display` 和 `task.didDisplay` 里面的 `[drawLayout drawInContext:...]` 方法吗？
这里，第一次是绘制文本相关内容，可以在非主线程执行；第二次是添加 UIView、CALayer 附件，这个只能在主线程进行。两次方法调用的参数不一样，执行的任务也是有区别的。

**Comment by leehonn** [comment]
明白了，谢谢
