### ISSUE TITLE
YYTextView字体加粗

### ISSUE THREAD

**Issue by leibaozai** [ibireme/YYText#472]
1、长按选中，选中自定义加粗
YYTextRange *yyRange = (YYTextRange *)self.yyTextView.selectedTextRange;
 self.selectRange = [yyRange asRange];
发现删除的时候selectedTextRange也会有值，会导致下一次切换加粗按钮会自动给一个字体附上属性。另外字体加粗会让屏幕跳动，因为长按选中替换时替换整个attributedText，而不是设置typingAttributes属性，不知道你能不能看懂？
`- (void)fontButtonAciton:(UIButton *)btn{
    btn.selected = !btn.selected;
    NSMutableDictionary *dic = [[NSMutableDictionary alloc] init];
    NSMutableAttributedString *text = self.yyTextView.attributedText.mutableCopy;
    
    //长按切换字体属性
    if (self.selectRange.length) {
        if ([btn isSelected]) {
            if (self.selectRange.location + self.selectRange.length <= self.yyTextView.attributedText.length) {
                [text setAttributes:@{NSFontAttributeName:YYTextViewBlodFont} range:self.selectRange];
            }
        }else{
            if (self.selectRange.location + self.selectRange.length <= self.yyTextView.attributedText.length) {
                [text setAttributes:@{NSFontAttributeName:YYTextViewFont} range:self.selectRange];
            }
        }
        //记录光标位置
        __block NSInteger lastCurPosition = self.yyTextView.selectedRange.location;
        dispatch_async(dispatch_get_main_queue(), ^{
            lastCurPosition += self.selectRange.length;
            self.yyTextView.attributedText = text;
            self.yyTextView.selectedRange = NSMakeRange(lastCurPosition, 0);
            [self.yyTextView scrollRangeToVisible:self.selectRange];
            self.selectRange = NSMakeRange(0, 0);
        });
    }
    
    //设置字体属性
    if ([btn isSelected]) {
        [dic setObject:YYTextViewBlodFont forKey:NSFontAttributeName];
    }else{
        [dic setObject:YYTextViewFont forKey:NSFontAttributeName];
    }
    self.yyTextView.typingAttributes = dic;
}`

**Comment by ibireme** [comment]
Bold Font 实际上是相当于替换了一个新字体，如果和原来字体的字形宽度不一样，那就会有跳动吧。

**Comment by leibaozai** [comment]
谢回复。
那回删，selectedTextRange也会有值，这个怎么解决？因为在下次设置字体，selectedTextRange会有一个字的length。

**Comment by Leyal** [comment]
作者你好。给selectedRange加粗之后，后面输入的字符自带bold属性，这应该是个bug。
