### ISSUE TITLE
YYTextView 问题

### ISSUE THREAD

**Issue by devSC** [ibireme/YYText#48]
`    YYTextContainer *newContainer = _innerContainer.mutableCopy;`
这快会Crash.

Log信息:
`reason: '-[YYTextContainer mutableCopyWithZone:]: unrecognized selector sent to instance 0x7ff7da64b690'`

暂时改为Copy可以用.

**Comment by ibireme** [comment]
YYTextContainer 只实现了 NSCopying 协议，并未实现 NSMutableCopying 协议。

**Comment by devSC** [comment]
对, So,这里您用的是mutableCopy.

**Comment by ibireme** [comment]
找到了，我改下，感谢提出问题～

**Comment by devSC** [comment]
嘿嘿. 共勉.

**Comment by ibireme** [comment]
Fixed~

**Comment by victor-ZK** [comment]
你好，我在使用YYTextView的时候，第三方日语输入法中inline输入不支持吗？
