### ISSUE TITLE
YYTextView 竖排时，修改frame 之后，删除文字有bug。

### ISSUE THREAD

**Issue by yfusong** [ibireme/YYText#483]
假设初始化的YYTextView 的frame 为frame1，修改textView的frame = frame2，运行时，运行之后在原有文字之上删除任意一个字符，YYTextView 会还原到frame1。

**Comment by ibireme** [comment]
Fixed

**Comment by yfusong** [comment]
你有引入了新bug，而且很明显，具体就不描述了。
在YYTextView 里面的setFrame 函数里
`BOOL changed = _innerContainer.isVerticalForm ? CGSizeEqualToSize(oldSize, newSize) : (oldSize.width != newSize.width);`
应该改成
`BOOL changed = _innerContainer.isVerticalForm ? !CGSizeEqualToSize(oldSize, newSize) : (oldSize.width != newSize.width);`
这句代码原来的也没有什么错，这里之前我也有看过，没有找到原因所以在才在这里问你。
不过更新了新版本之后，突然发现原来的bug好像是由自动布局引起的，和你的插件本身没有太大关系。
谢谢费心解答。

**Comment by ibireme** [comment]
啊抱歉，犯蠢了。。
