### ISSUE TITLE
关于YYTextLayout导致内存暴增的案例

### ISSUE THREAD

**Issue by bitnpc** [ibireme/YYText#485]
我做的页面是一个聊天的UI，包含了很多个YYTextView，当YYTextView增加到760个的时候，此时内存占用正常，再增加20个之后，出现了这个问题，内存暴增，然后被系统杀死。
以下是Instruments的截图：

- 如图，正常情况下

![normal](https://cloud.githubusercontent.com/assets/4088941/18245339/3f84a22e-7397-11e6-8c66-177bb09e7e75.jpg)

- 内存暴增

![overflow](https://cloud.githubusercontent.com/assets/4088941/18245366/62598b16-7397-11e6-9a8b-742011ca7fe1.jpg)

- 调用关系

![calltree](https://cloud.githubusercontent.com/assets/4088941/18245381/76ac8c80-7397-11e6-81f3-aa9a8568cee4.jpg)

不知道有没有人遇到和我类似的问题。

**Comment by bitnpc** [comment]
把YYTextView替换为UITextView则无此问题

**Comment by HoneyLuka** [comment]
好奇究竟是什么功能，居然需要700多个textview

**Comment by bitnpc** [comment]
@HoneyLuka IM的UI啊，一开始就说过了

**Comment by atom2ueki** [comment]
@bitnpc 这个链接没了，是什么原因能分享下么

**Comment by bitnpc** [comment]
@atom2ueki 是emoji表情的问题
