### ISSUE TITLE
selectedRange不准确

### ISSUE THREAD

**Issue by 38598312** [ibireme/YYText#49]
您好。在这个代理方法里面- (void)textViewDidChangeSelection:(YYTextView *)textView，返回回来的selectedRange不准确，具体的说是长按后处于选定状态下，返回的range.length为0，但是按一下空白区域，让蓝色选定状态消失，这次返回的range的结果是正确的，length为选定的文本的长度。

刚刚又试了一下，这个range始终返回的是上一次操作的range

**Comment by ibireme** [comment]
Fixed~
