### ISSUE TITLE
iOS10 似乎计算不准确 iOS9以下就可以显示全文字 10就出现了...

### ISSUE THREAD

**Issue by lixiang1994** [ibireme/YYText#496]
计算代码

// 创建文本容器
    
    YYTextContainer *container = [YYTextContainer new];
    
    container.size = CGSizeMake(size.width, size.height);
    
    container.maximumNumberOfRows = _numberLine;

    // 生成排版结果
    
    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:self.yyLabel.attributedText];
    
    CGSize lSize = layout.textBoundingSize;

**Comment by dustturtle** [comment]
这个问题解决了吗？  我这里只要设置了行间距，计算出来的高度就不对（大量文本时很容易出现） @lixiang1994

**Comment by leirenbaobao** [comment]
我也出现了类似的问题  在iOS8上设置了行间距  计算出的高度就不对  导致截断。

**Comment by leirenbaobao** [comment]
> 我也出现了类似的问题 在iOS8上设置了行间距 计算出的高度就不对 导致截断。
我试了下 lineSpace为小数时 在iOS8 iOS9上会出现高度计算不对的情况。
