### ISSUE TITLE
链接中有斜体的问题

### ISSUE THREAD

**Issue by SiTianyu** [ibireme/YYText#497]
在文章内容中有链接，链接的文字用斜体表现，如:
`内容内容<a href="https://xxx.com"><i>链接文字</i></a>内容内容`
我先遍历了Italic倾斜文字，然后再加了Highlight事件，这时候“链接文字”不会正常显示成链接的蓝色。应如何解决。
具体代码如下所示：
` 

    NSMutableAttributedString *pStr = [[NSMutableAttributedString alloc]
                                       initWithData:[[NSString stringWithFormat:@"%@", text] dataUsingEncoding:NSUnicodeStringEncoding]
                                       options:@{ NSDocumentTypeDocumentAttribute: NSHTMLTextDocumentType }
                                       documentAttributes:nil
                                       error:nil];
    NSRange range = (NSRange){0,[pStr length]};
    
    //Italic font for words
    [pStr enumerateAttribute:NSFontAttributeName inRange:range options:NSAttributedStringEnumerationLongestEffectiveRangeNotRequired usingBlock:^(id value, NSRange range, BOOL *stop) {
        UIFont* currentFont = value;

        if ([currentFont.fontName rangeOfString:@"Italic" options:NSCaseInsensitiveSearch].location != NSNotFound) {
            
            [pStr addAttributes:@{NSFontAttributeName: font,
                                  NSParagraphStyleAttributeName: paragraphStyle} range:range];

            [pStr yy_setTextGlyphTransform:YYTextCGAffineTransformMakeSkew(-0.3, 0) range:range];
            
        } else {
            [pStr addAttributes:attributes range:range];
        }
    }];`

**Comment by ibireme** [comment]
按正常的文字颜色设置方法处理就行。
highlight 事件只是处理高亮后的属性变化。

**Comment by SiTianyu** [comment]
嗯，非常感谢。
确实 setcolor:range可以解决该问题。

不过我想说的是如果 注释掉        
`[pStr yy_setTextGlyphTransform:YYTextCGAffineTransformMakeSkew(-0.3, 0) range:range];
`
利用系统默认的文本解析，就可以为正常的链接的蓝色。所以是否在哪里覆盖了链接的颜色属性？
