### ISSUE TITLE
Demo build错误

### ISSUE THREAD

**Issue by magic3584** [ibireme/YYText#5]
Demo build时候飘红了
![image](https://cloud.githubusercontent.com/assets/6275110/10988551/432f92d0-8478-11e5-97a3-fa1c9e9073ce.jpeg)

**Comment by ibireme** [comment]
感谢提出～
请先用 Xcode 7 构建，这个问题稍后修复

**Comment by magic3584** [comment]
嗯，我是6.4。

**Comment by ibireme** [comment]
_Nunnull 是 Xcode 7 开始支持的。
现在已经去掉了，你可以再试试。

**Comment by magic3584** [comment]
大神，新错误。。。
![image](https://cloud.githubusercontent.com/assets/6275110/10988834/fc83cf06-847a-11e5-93d1-48610163081e.jpeg)

**Comment by ibireme** [comment]
需要链接 libz.dylib 库。。
怕麻烦的话，还是换 Xcode 7 吧。。

**Comment by magic3584** [comment]
添加上ibz.dylib后显示LaunchScreen.storyboard非法，我把库连接里的libz.tbd删了，也删了LaunchScreen.storyboard的reference，成功运行！
希望自己可以看得懂源码。。。
最后还要再加一句，多谢大牛分享！！！
