### ISSUE TITLE
请问可以导出HTML格式吗

### ISSUE THREAD

**Issue by 38598312** [ibireme/YYText#50]
比如粗体、颜色这种，甚至附件的包裹

eg :       img src=...

**Comment by ibireme** [comment]
目前不支持。
你可以手动转换，或者找第三方库 (例如 Ashton) 修改来实现。

另外，如果富文本方案是基于 HTML 的，推荐尝试 https://github.com/nnhubbard/ZSSRichTextEditor 这个项目。

**Comment by 38598312** [comment]
ZSS不错，但是对于非文字的支持远不如您的库，多谢解答，谢谢。
