### ISSUE TITLE
关于TextBinding自定义

### ISSUE THREAD

**Issue by shenguanjiejie** [ibireme/YYText#51]
想把邮箱替换为 @联系人 这种样式的字符串,删除的时候直接删除掉该字符串,但是怎么写正则都不起作用,求教这个正则该怎么写,多谢!!!

//    NSString *pattern = @"[-_a-zA-Z@\\.]+[ ,\\n]";
    NSString *pattern = @"^[@]+[ ,\\n]";

**Comment by ibireme** [comment]
可以试试这个：

    \b([a-zA-Z0-9%_.+\-]+)@([a-zA-Z0-9.\-]+?\.[a-zA-Z]{2,6})\b

但具体还要看你的业务需求了。

**Comment by shenguanjiejie** [comment]
真是多谢了! 我发现我的需求用Demo里的YYTextTagExample中的
[tagText yy_setTextBinding:[YYTextBinding bindingWithDeleteConfirm:NO] range:tagText.yy_rangeOfAll];
这行代码就行了.

真的是强大的框架啊,在文字处理这方面独一无二,厉害,祝越做越好!
