### ISSUE TITLE
YYTextView 问题

### ISSUE THREAD

**Issue by devSC** [ibireme/YYText#52]
编辑过程中, 会遇到下面Crash.
`Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds'`
Code:
`- (NSDictionary *)attributesAtIndex:(NSUInteger)index {
    if (self.length > 0 && index == self.length) index--;
    return [self attributesAtIndex:index effectiveRange:NULL];
}
`

**Comment by ibireme** [comment]
能贴出更详细的代码片段吗，比如崩溃处的使用方法，附近的代码？

**Comment by ibireme** [comment]
没有回复，关闭问题。

**Comment by ilaoxia** [comment]
这个问题会出现的，在YYTextView中
<img width="1372" alt="2017-04-21 11 12 00" src="https://user-images.githubusercontent.com/11848254/29758316-1d02b864-8be5-11e7-8e45-39e73c6aa07d.png">
