### ISSUE TITLE
计算高度时如果文字带有大量空格Container的宽度限制无效

### ISSUE THREAD

**Issue by baojuan** [ibireme/YYText#53]
YYLabel *label = [YYLabel new];
    label.attributedText = text;
    label.width = self.view.width;
    label.height = self.view.height - (kiOS7Later ? 64 : 44);
    label.top = (kiOS7Later ? 64 : 0);
    label.textAlignment = NSTextAlignmentCenter;
    label.textVerticalAlignment = YYTextVerticalAlignmentCenter;
    label.numberOfLines = 0;
    label.backgroundColor = [UIColor colorWithWhite:0.933 alpha:1.000];
    [self.view addSubview:label];

    NSMutableAttributedString *tt = [[NSMutableAttributedString alloc] initWithString:@"1                                                                                     1"];
    
    // Create text container
    YYTextContainer *container = [YYTextContainer new];
    container.size = CGSizeMake(100, CGFLOAT_MAX);
    container.maximumNumberOfRows = 0;
    
    // Generate a text layout.
    YYTextLayout *layout = [YYTextLayout layoutWithContainer:container text:tt];
    
    label.width = layout.textBoundingSize.width;
    label.height = layout.textBoundingSize.height;
    label.attributedText = tt;
结果：
![e579fa84-97c7-44db-947f-9770ded95de1](https://cloud.githubusercontent.com/assets/5085967/11550816/58d16f96-99ae-11e5-8211-8abd0b1cd85a.png)

**Comment by ibireme** [comment]
这是文本系统 (或者说CoreText) 的 Feature。
你可以在系统的 UITextView 或备忘录中输入空格试试，并不会触发换行。

**Comment by baojuan** [comment]
虽然是系统Feature 但是现在数据源存在这样大量空格的情况 然而我的label显示是有最大宽度的，这种情况下怎么计算高度比较好呢？

**Comment by ibireme** [comment]
空格是不会导致换行的，所以大量空格只会显示在一行。
由于空格不会被绘制，所以当超出一行宽度时，也完全没问题，这个和 UILabel 的表现应该是一样的。

如果你需要做额外的处理，可以在字符串中加上些不可见字符等。

**Comment by mohuilin** [comment]
所以 这个问题是怎么解决的？
