### ISSUE TITLE
YYTextView 和UITapGestureRecognizer

### ISSUE THREAD

**Issue by yfusong** [ibireme/YYText#534]
在 super view 上添加UITapGestureRecognizer手势之后 YYTextView 就无法进入编辑状态。
示例代码如下：
    ```
YYTextView *textView = [YYTextView new];
    UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 300, 400)];
    textView.frame = CGRectMake(0, 0, 200, 200);
    [view addSubview:textView];

```
UITapGestureRecognizer *tap = [[UITapGestureRecognizer alloc]initWithTarget:self action:@selector(tapView:)];
[view addGestureRecognizer:tap];
```

```

```

**Comment by liuyongjiesail** [comment]
你好，这个问题你解决了吗？

**Comment by yfusong** [comment]
问题本身没有解决，你看一下源代码，好像是手势冲突吧，时间太久忘了
我好像是用其他方式实现的，我添加了一个按钮来打开关闭编辑状态的；
我用YYTextView 主要是想使用文字竖排，后面ios系统升级之后各种莫名其妙的bug，最后放弃了YYText。所以我也忘了当初怎么搞的。你可以换一种方式去实现，反正根源好像是手势冲突。

**Comment by liuyongjiesail** [comment]
嗯嗯，好的，谢谢了，我也放弃了，为了一个小功能没必要导入这么大个文件，不如自己来实现了
