### ISSUE TITLE
YYLabel的HighLight.tapAction不起作用

### ISSUE THREAD

**Issue by zhangnet** [ibireme/YYText#538]
在自定义tableViewCell中，我使用一个UIImageView作为背景图（聊天界面的气泡）并添加了UITapGestureRecognizer来处理点击事件。当添加一个YYLabel在UIImageView中来显示文本内容时，因为需要对链接进行突出显示，就按demo中的例子添加了highLight效果，发现高亮的效果是正常的（点击时链接变色，并显示设置的背景色），但是添加的tapAction事件不会被执行，当我把UIImageView的点击事件去掉后，tapAction就正常了，所以应该是UIImageView拦截了YYLabel的tapAction，这个如何处理？

**Comment by zhangnet** [comment]
- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event {
    [self _updateIfNeeded];
    UITouch *touch = touches.anyObject;
    CGPoint point = [touch locationInView:self];
    
    _highlight = [self _getHighlightAtPoint:point range:&_highlightRange];
    _highlightLayout = nil;
    _shrinkHighlightLayout = nil;
    _state.hasTapAction = _textTapAction != nil;
    _state.hasLongPressAction = _textLongPressAction != nil;
    
    if (_highlight || _textTapAction || _textLongPressAction) {
        _touchBeganPoint = point;
        _state.trackingTouch = YES;
        _state.swallowTouch = YES;
        _state.touchMoved = NO;
        [self _startLongPressTimer];
        if (_highlight) [self _showHighlightAnimated:NO];
    } else {
        _state.trackingTouch = NO;
        _state.swallowTouch = NO;
        _state.touchMoved = NO;
    }
    if (!_state.swallowTouch) {
        [super touchesBegan:touches withEvent:event];
    }
}

- (void)_startLongPressTimer {
    [_longPressTimer invalidate];
    _longPressTimer = [NSTimer timerWithTimeInterval:kLongPressMinimumDuration
                                              target:[YYTextWeakProxy proxyWithTarget:self]
                                            selector:@selector(_trackDidLongPress)
                                            userInfo:nil
                                             repeats:NO];
    [[NSRunLoop currentRunLoop] addTimer:_longPressTimer forMode:NSRunLoopCommonModes];
}

- (void)_trackDidLongPress {
    [self _endLongPressTimer];
    if (_state.hasLongPressAction && _textLongPressAction) {
        NSRange range = NSMakeRange(NSNotFound, 0);
        CGRect rect = CGRectNull;
        CGPoint point = [self _convertPointToLayout:_touchBeganPoint];
        YYTextRange *textRange = [self._innerLayout textRangeAtPoint:point];
        CGRect textRect = [self._innerLayout rectForRange:textRange];
        textRect = [self _convertRectFromLayout:textRect];
        if (textRange) {
            range = textRange.asRange;
            rect = textRect;
        }
        _textLongPressAction(self, _innerText, range, rect);
    }
    if (_highlight) {
        YYTextAction longPressAction = _highlight.longPressAction ? _highlight.longPressAction : _highlightLongPressAction;
        if (longPressAction) {
            YYTextPosition *start = [YYTextPosition positionWithOffset:_highlightRange.location];
            YYTextPosition *end = [YYTextPosition positionWithOffset:_highlightRange.location + _highlightRange.length affinity:YYTextAffinityBackward];
            YYTextRange *range = [YYTextRange rangeWithStart:start end:end];
            CGRect rect = [self._innerLayout rectForRange:range];
            rect = [self _convertRectFromLayout:rect];
            longPressAction(self, _innerText, _highlightRange, rect);
            [self _removeHighlightAnimated:YES];
            _state.trackingTouch = NO;
        }
    }
}
从这里看，YYLabel的点击必须写在longPressAction或highLight的 longPressAction中？我测试的时候发现 如果单步调试至[self _startLongPressTimer]，那么longPressAction会执行，直接运行的话，longPressAction不会运行;

**Comment by zhangnet** [comment]
sorry，是我没弄清楚手势和触摸之间的关系，代码没有问题。

**Comment by willbetter** [comment]
请问怎么解决的？我也遇到同样的问题了，在一个cell中，只能响应长按时间，highlighttap和 tap不响应

**Comment by zhangnet** [comment]
你的YYLabel的superview是不是添加了手势？例如UITapGestureRecognizer，把手势的cancelsTouchesInView属性设置为NO就可以响应了 @willbetter

**Comment by willbetter** [comment]
感谢回复，查了下文档，你说的确实正确。但我这是加到了一个collectionView的cell中，这个cell并没有什么手势，我还在找原因中...依然很感激

**Comment by sensencoder** [comment]
> 感谢回复，查了下文档，你说的确实正确。但我这是加到了一个collectionView的cell中，这个cell并没有什么手势，我还在找原因中...依然很感激

请问你怎么解决的呢

**Comment by oxiangyang** [comment]
> 感谢回复，查了下文档，你说的确实正确。但我这是加到了一个collectionView的cell中，这个cell并没有什么手势，我还在找原因中...依然很感激

设置如下即可：
self.tableView.delaysContentTouches = NO;
    self.tableView.canCancelContentTouches = YES;

**Comment by oxiangyang** [comment]
> > 感谢回复，查了下文档，你说的确实正确。但我这是加到了一个collectionView的cell中，这个cell并没有什么手势，我还在找原因中...依然很感激
> 
> 请问你怎么解决的呢

如下设置：
self.tableView.delaysContentTouches = NO;
    self.tableView.canCancelContentTouches = YES;

**Comment by jiangxiaopeng** [comment]
> 你的YYLabel的superview是不是添加了手势？例如UITapGestureRecognizer，把手势的cancelsTouchesInView属性设置为NO就可以响应了 [@willbetter](https://github.com/willbetter)

说的太对了，解决了我的问题。
