### ISSUE TITLE
YYText支持html标签吗？

### ISSUE THREAD

**Issue by bulice** [ibireme/YYText#54]
YYText支持html标签吗？

**Comment by ibireme** [comment]
不支持。
你可能需要用 NSAttributedString 的方法从 html 文本创建对象，或者用其他第三方库进行转换。

**Comment by bulice** [comment]
好的

**Comment by volcanoljy** [comment]
现在呢？现在YYText  支持解析HTML，然后显示文本 吗？

**Comment by atom2ueki** [comment]
@volcanoljy 目前貌似还没有支持
