### ISSUE TITLE
YYLable 使用 mutableAttributedString的颜色问题

### ISSUE THREAD

**Issue by bulice** [ibireme/YYText#55]
我有一个NSAttributedString *body是一个经html转换之后的attributedString @“http://www.baidu.com 你好”, 这里url的文字部分是设置了颜色的，
然后调用：            _bodytextLayout = [YYTextLayout layoutWithContainer:container text:body];
之后，设置的颜色就失效了？请问YYTextLayout里面有这个去掉颜色的逻辑吗？

**Comment by ibireme** [comment]
YYabel 底层是用 CoreText 绘制的，转换后的属性字符串中，颜色属性是用 CTForegroundColor 标记的，你可以检查一下。

有些方法转换后，颜色是用 NSColor 标记的，那样的字符串只能用 UIKit 相关的控件来显示。

**Comment by bulice** [comment]
最终是绘制的_innerText吗？

**Comment by ibireme** [comment]
绘制的是 _innerLayout

**Comment by bulice** [comment]
好奇怪，看_innerLayout的_text 值是正确的
Printing description of self->_bodyTextLabel->_innerLayout->_text:
http://www.baidu.com{
    CTForegroundColor = "<CGColor 0x7fe46bee0020> [<CGColorSpace 0x7fe46bd91a60> (kCGColorSpaceDeviceRGB)] ( 0 0.501961 0 1 )";
    CTForegroundColorFromContext = 1;
    DTGUID = "DADE38A1-8F79-44BD-A0E0-A590920AEA42";
    DTLinkHighlightColor = "UIDeviceRGBColorSpace 1 0 0 1";
    NSFont = "<UICTFont: 0x7fe46bee4ad0> font-family: \"STHeitiSC-Light\"; font-weight: normal; font-style: normal; font-size: 14.00pt";
    NSLink = "http://www.baidu.com";
    NSParagraphStyle = "<CTParagraphStyle: 0x7fe46be316c0>{base writing direction = -1, alignment = 4, line break mode = 0, default tab interval = 36\nfirst line head indent = 0, head indent = 0, tail indent = 0\nline height multiple = 1.3125, maximum line height = 0, minimum line height = 0\nline spacing adjustment = 0, paragraph spacing = 0, paragraph spacing before = 0\n}";
    NSUnderline = 1;
} 你好{
    CTForegroundColor = "<CGColor 0x7fe46bcc1fd0> [<CGColorSpace 0x7fe46bcc0b70> (kCGColorSpaceDeviceGray)] ( 0 1 )";
    NSFont = "<UICTFont: 0x7fe46bee4ad0> font-family: \"STHeitiSC-Light\"; font-weight: normal; font-style: normal; font-size: 14.00pt";
    NSParagraphStyle = "<CTParagraphStyle: 0x7fe46beb8ca0>{base writing direction = -1, alignment = 4, line break mode = 0, default tab interval = 36\nfirst line head indent = 0, head indent = 0, tail indent = 0\nline height multiple = 1.3125, maximum line height = 0, minimum line height = 0\nline spacing adjustment = 0, paragraph spacing = 0, paragraph spacing before = 0\n}";
}

CTForegroundColor 的值是正确的，但是就是没有颜色，下划线能画出来

**Comment by bulice** [comment]
Printing description of self->_bodyTextLabel->_innerLayout->_text:
http://www.baidu.com{
    CTForegroundColor = "<CGColor 0x7fe46bee0020> [<CGColorSpace 0x7fe46bd91a60> (kCGColorSpaceDeviceRGB) ( 0 0.501961 0 1 )";
    CTForegroundColorFromContext = 1;
    DTGUID = "DADE38A1-8F79-44BD-A0E0-A590920AEA42";
    DTLinkHighlightColor = "UIDeviceRGBColorSpace 1 0 0 1";
    NSFont = "<UICTFont: 0x7fe46bee4ad0> font-family: \"STHeitiSC-Light\"; font-weight: normal; font-style: normal; font-size: 14.00pt";
    NSLink = "http://www.baidu.com";
    NSParagraphStyle = "<CTParagraphStyle: 0x7fe46be316c0>{base writing direction = -1, alignment = 4, line break mode = 0, default tab interval = 36\nfirst line head indent = 0, head indent = 0, tail indent = 0\nline height multiple = 1.3125, maximum line height = 0, minimum line height = 0\nline spacing adjustment = 0, paragraph spacing = 0, paragraph spacing before = 0\n}";
    NSUnderline = 1;
} 你好{
    CTForegroundColor = "<CGColor 0x7fe46bcc1fd0> [<CGColorSpace 0x7fe46bcc0b70> (kCGColorSpaceDeviceGray) ( 0 1 )";
    NSFont = "<UICTFont: 0x7fe46bee4ad0> font-family: \"STHeitiSC-Light\"; font-weight: normal; font-style: normal; font-size: 14.00pt";
    NSParagraphStyle = "<CTParagraphStyle: 0x7fe46beb8ca0>{base writing direction = -1, alignment = 4, line break mode = 0, default tab interval = 36\nfirst line head indent = 0, head indent = 0, tail indent = 0\nline height multiple = 1.3125, maximum line height = 0, minimum line height = 0\nline spacing adjustment = 0, paragraph spacing = 0, paragraph spacing before = 0\n}";
}

**Comment by ibireme** [comment]
把 CTForegroundColorFromContext 这个属性移掉试试

**Comment by bulice** [comment]
确实，去掉就可以了

**Comment by bulice** [comment]
基于这个问题再问个问题啊，就是想这样的attributedString，我现在想要只在link上加点击操作，这个基于YYText有现成的方法吗？

**Comment by ibireme** [comment]
项目首页的 readme 里有文本点击的用法介绍
