### ISSUE TITLE
YYTextView 放在scrollView上用来做文本显示。粘贴复制功能 会受到scrollView的上下滚动影响。

### ISSUE THREAD

**Issue by GIKIios** [ibireme/YYText#552]
对于贴边的光标也是非常不好选中。。选中光标也经常会被系统导航栏侧滑影响。 UITextView的menu 功能不会受影响。 作者能否优化一下

**Comment by wdpeng** [comment]
Hi，这个问题你如何解决的？还是有其他替代方案

**Comment by shanbozhu** [comment]
我也有同样的问题, 请问两位是解决了吗? 能分享下吗

**Comment by GIKICoder** [comment]
https://github.com/GIKICoder/GRichLabel

**Comment by GIKICoder** [comment]
https://github.com/GIKICoder/GRichLabel

**Comment by yyb-vip** [comment]
我也遇到这个问题了, 不知道有没有解决?

**Comment by GIKICoder** [comment]
@YangYiBo23  自己撸了库。解决了这个问题。其实是受系统边缘手势的影响。 https://github.com/GIKICoder/GRichLabel 这个解决了
