### ISSUE TITLE
请问，YYTextView可以集成一些view进去吗？

### ISSUE THREAD

**Issue by 38598312** [ibireme/YYText#56]
这种场景很常见：我上面是一些texifield，比如什么姓名、性别，然后下面是YYtextview，如果融合成一体，yytextview的frame可以从0,0(0,64?)开始，我往上滑动，那些view可以划上去，我下面输入面积就大了。我尝试textview addsubview:myview,然后修改文字的inset，但是不行啊好像，排版都错乱了，请问支持这个需求吗？

**Comment by ibireme** [comment]
描述没太懂。。。

**Comment by 38598312** [comment]
语文不太好哈哈，就是您的textview不就是一个光秃秃的输入框嘛，我希望加一些textfield和label进去，比如“姓名 : __________”,这个view放到textview里，这样滑动的时候，view跟textview的“内容的一部分”一样，跟着滑动。不知道这么描述，能否理解我的意思？

**Comment by ibireme** [comment]
可以使用 YYLabel 来显示文本，然后把 TextField 当作一个 Attachment 嵌入文本中。
具体可以参考 https://github.com/ibireme/YYText/blob/master/Demo/YYTextDemo/YYTextAttachmentExample.m

**Comment by 38598312** [comment]
多谢解答。不过我还是建议，YYTextView里面可以增加一个类似uitableview的header属性，可以添加自定义的view，这种个性化定义我觉得还是比较多的。
