### ISSUE TITLE
发现一个bug，使用YYTextview会自动改变status bar 的颜色为黑色

### ISSUE THREAD

**Issue by tysenlau** [ibireme/YYText#57]
本来Status bar 的颜色是白色的，使用[YYTextview new] 状态就变成黑色了。
info.list 中的 View controller-based status bar appearance 改为 NO不会受影响，白色仍然是白色，
当改为YES（迎合IOS9的策略）后，白色的status bar就会变成黑色！

**Comment by ibireme** [comment]
已知问题，详情见 #28 。
请更新代码到最新版本试试。

**Comment by tysenlau** [comment]
多谢大神~~！
