### ISSUE TITLE
YYTextView当光标在第一个位置时，收不到删除回调

### ISSUE THREAD

**Issue by makefantasy** [ibireme/YYText#585]
项目有个需求，类似新浪微博的发布头条文章，当textView光标在首位时，键盘删除键收不到回调，这个有办法解决吗？

**Comment by mixiu7992** [comment]
我也遇到了这个  有办法解决么 @makefantasy

**Comment by makefantasy** [comment]
YYTextView点击退格键的时候调用deleteBackward方法，在这个方法里做处理

**Comment by makefantasy** [comment]
@mixiu7992
