### ISSUE TITLE
异步模式下如何计算tableview cell 的高度

### ISSUE THREAD

**Issue by Abel94** [ibireme/YYText#589]
看了一下微博的demo和readme，微博的demo好像是先把所有的布局算出来，然后再显示。但是在tableview里cell的高度是展示的时候就确定了，等异步完成后根本没法修改他的高度，这个应该怎么处理呢？

**Comment by bupojung** [comment]
可以再后台线程计算高度，存在数据model中，在heightforcell的时候取值，不需要再进行计算

**Comment by bupojung** [comment]
异步计算完成后再加到datasource就可以了

**Comment by Abel94** [comment]
发出来之后想到了这个，把计算的时差归到网络请求里用户也不会有太多差的体验。

现在遇到个问题就是数据库用的realm。。这玩意不支持跨线程。。。不知道有没有同使用这个库的给点意见。

**Comment by Abel94** [comment]
非常感谢！ @bupojung
