### ISSUE TITLE
YYTextLayout问题

### ISSUE THREAD

**Issue by devSC** [ibireme/YYText#59]
用TextLayout计算含有数字的字段时, 计算错误.
打印:
`    NSLog(@"price: %@, %@", self.priceLayout.text, NSStringFromCGSize(self.priceLayout.textBoundingSize));`
输出内容
`
 price: 100023{
    CTForegroundColor = "<CGColor 0x15f6587f0> [<CGColorSpace 0x15df34250> (kCGColorSpaceDeviceRGB)] ( 1 1 1 1 )";
    NSColor = "UIDeviceRGBColorSpace 1 1 1 1";
    NSFont = "<UICTFont: 0x15f23fcc0> font-family: \".SFUIText-Regular\"; font-weight: normal; font-style: normal; font-size: 16.00pt";
}, {0, 0}
`

**Comment by ibireme** [comment]
是不是计算时给的 Container Size 太小，导致连第一行文本都放不下？

**Comment by devSC** [comment]
不会吧. 我用全部中文就没错.

**Comment by ibireme** [comment]
打印一下 layout.container.size 看看。
英文字体的 ascent+descent 比中文要大。

**Comment by devSC** [comment]
额. 好像真是, 16的字体. 竟然需要19的高度.
谢谢你啦.
