### ISSUE TITLE
设置YYLabel行数问题

### ISSUE THREAD

**Issue by wanglianghd** [ibireme/YYText#592]
结合Masonry使用YYLabel，设置了YYLabel的行数，为了限制文本行数，当文本很长的时候，比如限制为6行，实际行数不正常，只显示了两行，请问这样的需求该怎么实现呢？

**Comment by xfxj23** [comment]
+1

**Comment by BulletWu** [comment]
设置玩之后 update 一下高度就好了，重新设置下约束的高度，因为他是view，并不会自己扩大

**Comment by onlysee** [comment]
好烦哟

**Comment by onlysee** [comment]
> `什么的`

**Comment by wanglianghd** [comment]
解决了，记得设置YYLabel的preferredMaxLayoutWidth这个属性，然后用约束做就OK了@楼上几位

**Comment by jinlongzhu** [comment]
果然好用了！！搞了一晚上!!看到你的回答才解决！非常感谢！！ @wanglianghd
