### ISSUE TITLE
BUG: YYTextUnarchiver  

### ISSUE THREAD

**Issue by adad184** [ibireme/YYText#6]
https://github.com/ibireme/YYText/blob/master/YYText%2FString%2FYYTextArchiver.m#L245

```objc
    } else if ([object class] == [_YYCGColor class]) {
        _YYCGColor *color = object;
        return (id)color.CGColor;
    } else if ([object class] == [_YYCGColor class]) {
        _YYCGImage *image = object;
        return (id)image.CGImage;
    }
```

**Comment by ibireme** [comment]
感谢提出🙏
已修复

**Comment by adad184** [comment]
https://github.com/ibireme/YYText/blob/master/YYText%2FUtility%2FNSAttributedString%2BYYText.m#L742

这句貌似也多余了 

另外 kCTParagraphStyleAttributeName <-> NSParagraphStyleAttributeName

**Comment by ibireme** [comment]
嗯，我删掉～

之前我也整理了一份 CoreText 和 TextKit 的属性对比：https://github.com/ibireme/YYText/blob/master/Attributes/CoreText%20and%20TextKit%20Attributes.pdf

**Comment by adad184** [comment]
great
