### ISSUE TITLE
YYText not resizing within UITableViewCell, Storyboard and Constraints

### ISSUE THREAD

**Issue by a1cooke** [ibireme/YYText#61]
Hi,

I have added a YYLabel element to a UITableViewCell with a set of constraints, at runtime, I set the attributedText property of the label, however the height is consistently 0.

Additionally the dynamic cell height doesn't seem to respond to the change.

Is this something anyone has experience with? At the moment I haven't seen any storyboard examples running.

Any help with this would be great.

**Comment by ibireme** [comment]
YYLabel is aimed at high performance asynchronous rendering, for performance reasons, it does not support automatic height calculation.

You may use YYTextLayout to generate the text layout in the background thread, and then add constraints with layout.textBoundingSize.

I may try to do more performance optimization and add AutoLayout support in the future.

**Comment by a1cooke** [comment]
Thanks for the feedback, the library is certainly very powerful but AutoLayout support would be a really great addition

**Comment by zyt520ham** [comment]
你好，YYText 很强大，但是当我在一个view上放置一个YYLabel时，当这个view有触摸事件时，yyLabel的超链接就都无法响应了，想请教下，这个问题，怎么解决呢？

**Comment by ibireme** [comment]
Added: https://github.com/ibireme/YYText/commit/e8c86c1b098e27521945a0ba32739ae87ea292f5
