### ISSUE TITLE
使用YYTextView 中文场景下，输入符号后 键盘不能自动恢复为字母键盘。UITextView是没有问题的，请问有什么思路么？

### ISSUE THREAD

**Issue by NSaylor** [ibireme/YYText#613]
如题

**Comment by NSaylor** [comment]
该问题同 九宫格问题
解决方法：
- (void)_replaceRange:(YYTextRange *)range withText:(NSString *)text notifyToDelegate:(BOOL)notify 
在该方法中  注释其中两句
 // if (notify) [_inputDelegate textWillChange:self];
  //if (notify) [_inputDelegate textDidChange:self];

- (BOOL)_parseText 
改方法中 注释其中两句
 //if(!_isExcludeNeed)[_inputDelegate textWillChange:self];
 //if(!_isExcludeNeed)[_inputDelegate textDidChange:self];

暂时不知道 这样有什么影响

**Comment by FlutterDown** [comment]
请问这么改 有其他影响吗？

**Comment by NSaylor** [comment]
@FlutterDown  上述列出的方法中，需要补充常用标点符号（中英文），自己做个集合只要输入了这些标点集中的任意一个，就把上面列出的被注释方法跳过去。
example: 
NSString *strPunctuate = @",.!?#，。！@"; //只是一个示例不完整

if(如果不包含标点符号){
   [_inputDelegate textWillChange:self]; 
   [_inputDelegate textDidChange:self];
}

已经应用在上线项目中，没有再出现问题。

**Comment by NSaylor** [comment]
@FlutterDown @ibireme  解决该问题的完整代码 
YYTextView.m  
157 行 新增属性   BOOL _isExcludeNeed; //用于控制iOS10 键盘标点符号Bug  是否开启排除操作

- (void)_replaceRange:(YYTextRange *)range withText:(NSString *)text notifyToDelegate:(BOOL)notify{
//函数体头部插入如下语句
if（_isExcludeNeed）{
  notify = NO;
}
...
}

- (BOOL)_parseText {
    if (self.textParser) {
        YYTextRange *oldTextRange = _selectedTextRange;
        NSRange newRange = _selectedTextRange.asRange;
        //增加排除判断
        if(!_isExcludeNeed)[_inputDelegate textWillChange:self];
        BOOL textChanged = [self.textParser parseText:_innerText selectedRange:&newRange];
         //增加排除判断 
        if(!_isExcludeNeed)[_inputDelegate textDidChange:self];
        
        YYTextRange *newTextRange = [YYTextRange rangeWithRange:newRange];
        newTextRange = [self _correctedTextRange:newTextRange];
        
        if (![oldTextRange isEqual:newTextRange]) {
            [_inputDelegate selectionWillChange:self];
            _selectedTextRange = newTextRange;
            [_inputDelegate selectionDidChange:self];
        }
        return textChanged;
    }
    return NO;
}

- (void)replaceRange:(YYTextRange *)range withText:(NSString *)text {    
    if (!range) return;
    if (!text) text = @"";
    if (range.asRange.length == 0 && text.length == 0) return;
    //控制排除设置 ---Fix iOS10下标点符号Bug  @Saylor
    //此处拦截
    //需要排除的字符集
    NSString *strExclude = @"#。，、？！；（）@“”【】｛｝#%^*+=_\\|《》&·,?!'/.:";
    _isExcludeNeed = NO;
    
    for (int i=0; i< strExclude.length -1; i++) {
        NSString *str= [NSString stringWithFormat:@"%c",[strExclude characterAtIndex:i]];
        
        if ([strExclude containsString:str]) {
            _isExcludeNeed = YES;
            break;
        }
    }

    range = [self _correctedTextRange:range];
    
    if ([self.delegate respondsToSelector:@selector(textView:shouldChangeTextInRange:replacementText:)]) {
        BOOL should = [self.delegate textView:self shouldChangeTextInRange:range.asRange replacementText:text];
        if (!should) return;
    }
    
    BOOL useInnerAttributes = NO;
    if (_innerText.length > 0) {
        if (range.start.offset == 0 && range.end.offset == _innerText.length) {
            if (text.length == 0) {
                NSMutableDictionary *attrs = [_innerText attributesAtIndex:0].mutableCopy;
                [attrs removeObjectsForKeys:[NSMutableAttributedString allDiscontinuousAttributeKeys]];
                _typingAttributesHolder.attributes = attrs;
            }
        }
    } else { // no text
        useInnerAttributes = YES;
    }
    BOOL applyTypingAttributes = NO;
    if (_state.typingAttributesOnce) {
        _state.typingAttributesOnce = NO;
        if (!useInnerAttributes) {
            if (range.asRange.length == 0 && text.length > 0) {
                applyTypingAttributes = YES;
            }
        }
    }
    
    _state.selectedWithoutEdit = NO;
    _state.deleteConfirm = NO;
    [self _endTouchTracking];
    [self _hideMenu];

    [self _replaceRange:range withText:text notifyToDelegate:YES];


    if (useInnerAttributes) {
        [_innerText setAttributes:_typingAttributesHolder.attributes];
    } else if (applyTypingAttributes) {
        NSRange newRange = NSMakeRange(range.asRange.location, text.length);
        [_typingAttributesHolder.attributes enumerateKeysAndObjectsUsingBlock:^(id key, id obj, BOOL *stop) {
            [_innerText setAttribute:key value:obj range:newRange];
        }];
    }
    [self _parseText];
    [self _updateOuterProperties];
    [self _update];
    
    if (self.isFirstResponder) {
        [self _scrollRangeToVisible:_selectedTextRange];
    }
    
    if ([self.delegate respondsToSelector:@selector(textViewDidChange:)]) {
        [self.delegate textViewDidChange:self];
    }
    [[NSNotificationCenter defaultCenter] postNotificationName:YYTextViewTextDidChangeNotification object:self];
    
    _lastTypeRange = _selectedTextRange.asRange;
}

**Comment by FlutterDown** [comment]
非常感谢，有个情况，粘贴文本的时候，键盘上的发送按钮会收不到通知，我参照你的，自己加了变量控制了

**Comment by NSaylor** [comment]
@FlutterDown  不太明白你说的意思，能否细化一点儿~

**Comment by FlutterDown** [comment]
恩，比如textView的UIReturnKeyType 设置为 send, 当文本内容为空的时候，发送按钮会置灰，按你现在的修改方法，在第一次给textView直接粘贴内容的时候，发送按钮还是置灰不可点击状态，正常情况应该是会变亮可点击

**Comment by NSaylor** [comment]
@FlutterDown  我是这样使用的，发送按钮一直是高亮状态。

    NSMutableAttributedString *attr = [[NSMutableAttributedString alloc] initWithString:@"我想对Ta说..."];
    attr.color = UIColorHex(b4b4b4);
    attr.font = [UIFont fontWithName:DP_FONTNAME size:14];
    _txtView.placeholderAttributedText = attr;
    _txtView.extraAccessoryViewHeight = ExViewHeight;
    _txtView.returnKeyType = UIReturnKeySend;

**Comment by NSaylor** [comment]
测试了一下 UITextView  
_txtView.returnKeyType = UIReturnKeySend;
原生的发送按钮状态也一直是高亮的，和我项目中更改过的YYTextView是一致的效果。没能测出你说的问题~

**Comment by FlutterDown** [comment]
@NSaylor  能否给个联系方式，改了之后，我这有点其他问题

**Comment by NSaylor** [comment]
@FlutterDown  QQ594134288
