### ISSUE TITLE
YYLable border 问题：如何在显示标签时不触发换行

### ISSUE THREAD

**Issue by bulice** [ibireme/YYText#62]
![image](https://cloud.githubusercontent.com/assets/4455550/11634410/42c38860-9d4b-11e5-9d38-a8eb51feb6af.png)
YYLable 用setTextBackgroundBorder 方法来实现添加bolder的效果。我是用这个来做标签的效果，但是有个问题，如果当前行剩余的宽度无法显示一个完整的标签，有没有办法让这个标签到下一行显示吗？现在的效果是当前标签会拆成2个带border的lable，分别列在两行。

**Comment by ibireme** [comment]
首先先确保换行模式是 NSLineBreakByWordWrapping。

对于单个英文单词的 Tag 来说（比如 "Music"）默认就会保持字母连在一起换行；
对于多个英文单词的 Tag 来说（比如 "Harry Potter"），把中间的空格替换为非换行空格 \u00A0 (no-break space)，即 @"Harry\u00A0Potter" 即可；
对于中文 Tag 来说（比如"小王子"），把每个字用零宽连字符 \u180E （mongolian vowel separator）连接，即 @"小\u180E王\u180E子"，即可保证不换行。

**Comment by yimiaodaren** [comment]
要求就显示一行，多余的标签或者显示不全的标签就直接不显示。numberOfLines = 1 ，但是NSLineBreak不管选哪一个都打不到想要的效果╮(╯▽╰)╭

**Comment by ibireme** [comment]
楼上可以参考二楼的实现方式：用 NSLineBreakByWordWrapping 触发换行和裁剪，然后用 \u180E(非换行空格) 和 \u00A0(零宽非换行空格) 连接需要保持在一起的内容片段。

如果觉得这个方式实现不好、或者不够优雅，那仍然推荐用多个 UILabel / YYLabel 计算和显示。

**Comment by bulice** [comment]
你说的unicode的方法我搞不定啊，有代码样例吗？

**Comment by ibireme** [comment]
说得很清楚了啊，直接把上面的字符串复制到你的代码里试一下就明白了。

**Comment by bulice** [comment]
我用你建议的多个YYLabel来做了，自己计算，效果还不错，多谢。

**Comment by donggelaile** [comment]
\u180E会出现问题貌似。换行问题解决了，但是绘制多了点东西。。。，有其它的占位符可以替代吗
<img width="155" alt="default" src="https://cloud.githubusercontent.com/assets/7498868/12136477/0d8d90ec-b483-11e5-832b-823f5987fc91.png">

**Comment by ibireme** [comment]
哎。。这都属于不得已而弄的啊。。CoreText 换行只能用这种方式勉强来干预一下。。
上面那个白色的东西，可以通过把 `\u180E` 所在字符设置成 [UIColor clearColor] 来避免。。

**Comment by ghost** [comment]
我也遇到这个问题，中文间使用\u180E是这样的：
<img width="382" alt="4f2e1165-8988-4b96-ac23-664d98285d8c" src="https://user-images.githubusercontent.com/11642603/40835524-430c1828-65c6-11e8-80c4-212d78c11f2d.png">

我查了下零宽连字符是\u200D，但用了好像没效果：
<img width="392" alt="dc4a7a03-291e-481d-9ace-d6cd42941da3" src="https://user-images.githubusercontent.com/11642603/40835578-64e759b2-65c6-11e8-9447-4a41d3c31c32.png">

我使用Swift4.0
let tags = ["番\u{200d}茄",
                    "西\u{200d}红\u{200d}柿",//
                    "花\u{200d}菜",
                    "酱\u{200d}油\u{200d}位",
                    "你",
                    "不\u{200d}要\u{200d}碰\u{200d}我",
                    "红\u{200d}肿"]

**Comment by charlesYun** [comment]
我也遇到了类似的问题，中文换行有问题。不过在英文的情况下是正常的
