### ISSUE TITLE
YYTextView 插入图片后卡顿问题

### ISSUE THREAD

**Issue by Namunaka** [ibireme/YYText#637]
您好在下demo中text 下 copy and paste 向其中粘贴大概7张图片以后 打字就有明显的卡顿问题 图片大小均属于宽度满屏幕 高度一般为超出一屏幕高度 实际使用中插入照片大概4张以后 也会有打字卡顿情况 ,麻烦问下YYTextView是否也有机制帮助解决这种问题 ,测试机器为iphone 6 plush   iphone 6s  iphone 7 系统都是10.2.1 输入法使用系统输入法 如果选用搜狗输入法,则卡款问题缓解但依旧存在,  目前只有一台10.2的6s 貌似可以插入15+以上的图还没有打字明显卡顿的问题 麻烦问下有好的解决方法么

在多图情况插入TextView后,cpu占用率在打字时会在90%-99%的占用率.

复现测试用图片地址:
https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1490272065124&di=1025655f957ca9eba418966a27a02248&imgtype=0&src=http%3A%2F%2Fh5.86.cc%2Fwalls%2F20160708%2F1440x900_12a184bfe0f2ed0.jpg

使用手机浏览器如safari打开 复制图片 在demo的textView中粘贴

**Comment by Namunaka** [comment]
看源码每次输入文字 其实都要重新绘制所有图片,这部分行为在主线程 换了个思路 还是不要用粘贴 或者 限制粘贴图片数量了.然后使用View或者layer代替存Image

**Comment by Wuzo** [comment]
我也遇到这个问题了  每次输入 都会绘制一遍 请问找到解决方法了么

**Comment by Namunaka** [comment]
用ImageView代替Image

**Comment by Wuzo** [comment]
我以前也是用的imageview诶  我现在换成layer了
