### ISSUE TITLE
[Xcode 8.3]array parameter is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

### ISSUE THREAD

**Issue by CodeEagle** [ibireme/YYText#642]
array parameter is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
CGAffineTransform YYTextCGAffineTransformGetFromPoints(CGPoint before[3], CGPoint after[3]);

**Comment by qmkCamel** [comment]
same error

**Comment by yanqizhao** [comment]
The same as you.

**Comment by hssdx** [comment]
Me too

**Comment by hssdx** [comment]
how fix it?

**Comment by CodeEagle** [comment]
```CGAffineTransform YYTextCGAffineTransformGetFromPoints(CGPoint before[_Nullable 3], CGPoint after[_Nullable 3]);```

**Comment by Bruce9487** [comment]
Same issue Xcode 8.3

**Comment by CodeEagle** [comment]
fixed #651
