### ISSUE TITLE
如何设置字符间距？

### ISSUE THREAD

**Issue by huogh** [ibireme/YYText#65]
请问，如何设置字符间距？NSMutableAttributedString 的Category中，有设置字符间距的属性吗？

**Comment by ibireme** [comment]
可以设置 NSKernAttributeName 属性，或者直接用 `[text yy_setKern:@(10) range:NSMakeRange(10, 2)];`。

**Comment by huogh** [comment]
@ibireme 谢谢。望能早日友好的支持AutoLayout。
我现在AutoLayout使用的Masonry。

//////////// 以下为 UILabel 代码
UILabel *aLabel = [UILabel new];
aLabel.backgroundColor = [UIColor whiteColor];
aLabel.font = [UIFont systemFontOfSize:20];
aLabel.textColor = [UIColor redColor];
aLabel.numberOfLines = 0;
aLabel.preferredMaxLayoutWidth = [UIScreen mainScreen].bounds.size.width - 20 * 2;
aLabel.text = @"七旬老人店面失火，因不会用灭火器导致店内商品都被烧光。12月6日早上，遵义市红花岗区北京路一店面开始起火，七旬的店主刚好来到开门，准备营业，但由于老人不会用灭火器，导致小火变大火，老人眼睁睁看着店里数万元的商品被烧光。";

[self.view addSubview:aLabel];

@weakify(self);
[aLabel makeConstraints:^(MASConstraintMaker *make) {
    @strongify(self);
    make.top.equalTo(self.view.top).offset(40);
    make.centerX.equalTo(self.view.centerX);
}];

//////////// UILabel代码结束


希望将UILabel换成YYLabel后，上述代码依然能够良好的运行。
