### ISSUE TITLE
bug :delegate didTapHighlight 返回的characterRange 参数错误 不能正确的获取到高亮文字

### ISSUE THREAD

**Issue by lsm307742191** [ibireme/YYText#66]
1 场景：表情 + 识别“手机号网址”
核心代码：
 (1)parser.emoticonMapper = mapper;
YYTextView *textView = [YYTextView new];
textView.textParser = parser;
 (2)textView.dataDetectorTypes = UIDataDetectorTypePhoneNumber|UIDataDetectorTypeLink;

2 bug:
delegagte 返回的characterRange错误：
- (void)textView:(YYTextView *)textView didTapHighlight:(YYTextHighlight *)highlight inRange:(NSRange)characterRange rect:(CGRect)rect

3 代码：
NSMutableDictionary *mapper =   [NSMutableDictionary new];
mapper = [NSMutableDictionary new];
        mapper[@":smile:"] = [self imageWithName:@"002"];
        mapper[@":cool:"] = [self imageWithName:@"013"];
        mapper[@":biggrin:"] = [self imageWithName:@"047"];
        mapper[@":arrow:"] = [self imageWithName:@"007"];
        mapper[@":confused:"] = [self imageWithName:@"041"];
        mapper[@":cry:"] = [self imageWithName:@"010"];
        mapper[@":wink:"] = [self imageWithName:@"085"];
    YYTextSimpleEmoticonParser *parser = [YYTextSimpleEmoticonParser new];
    
    parser.emoticonMapper = mapper;
    
    YYTextLinePositionSimpleModifier *mod = [YYTextLinePositionSimpleModifier new];
    mod.fixedLineHeight = 22;
    
    YYTextView *textView = [YYTextView new];
    self.cellTextView =  textView;   
 textView.text = @"sss:confused::confused:Hahahah:smile::cry::cry::cry::cry::cry::cry::cry:, it\'s emoticons::cool::arrow::cry::wink:\n\nYou can input \":\" + \"smile\" + \":\" to display:arrow::arrow::arrow::arrow: smile emoticon, or you can :biggrin::biggrin::biggrin:copy and :arrow::arrow::arrow::arrow:paste these emoticons.:wink::wink::wink::wink::wink::wink::wink::wink::wink::wink::wink::wink::wink::wink::wink:\n 13488675561 http://www.baidu.com";
  
    textView.font = [UIFont systemFontOfSize:17];
    textView.textParser = parser;
    textView.size = CGSizeMake(self.frame.size.width, 0.0f);
    textView.linePositionModifier = mod;
    //textView.textContainerInset = UIEdgeInsetsMake(10, 10, 10, 10);
    textView.delegate = self;
    textView.scrollEnabled = NO;
    if (kiOS7Later) {
        textView.keyboardDismissMode = UIScrollViewKeyboardDismissModeInteractive;
    }
    textView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0);
    textView.scrollIndicatorInsets = textView.contentInset;
    
    self.cellTextView.editable = NO;
    [self.cellTextView sizeToFit];
    self.cellTextView.dataDetectorTypes = UIDataDetectorTypePhoneNumber|UIDataDetectorTypeLink;

**Comment by ibireme** [comment]
能给一下 delegate didTapHighlight 里面访问高亮文本的代码片段吗？

**Comment by ibireme** [comment]
看到了代码。。

当纯文本解析成富文本时，应该直接访问 textview.attributedText 来获取解析后的文本。

**Comment by lsm307742191** [comment]
能否给哥例子或者demo


谢谢！


麻烦您能否帮忙把附件中的demo修改正确 


谢谢！




在 2015-12-09 14:00:25，"Yaoyuan" <notifications@github.com> 写道：


看到了代码。。

当纯文本解析成富文本时，应该直接访问 textview.attributedText 来获取解析后的文本。

**Comment by ibireme** [comment]
NSString* str = [self.cellTextView.attributedText.string substringWithRange:characterRange];

之后就可以判断文本类型了。

**Comment by lsm307742191** [comment]
在git上看到了您的回复了 可以正常使用了
谢谢！







在 2015-12-09 14:00:25，"Yaoyuan" <notifications@github.com> 写道：


看到了代码。。

当纯文本解析成富文本时，应该直接访问 textview.attributedText 来获取解析后的文本。
