### ISSUE TITLE
YYTextView无法向UITextView一样由内容自适应高度。

### ISSUE THREAD

**Issue by liangdahong** [ibireme/YYText#666]
我们在开发中经常会出现多行文本输入框由输入的内容自适应高度，如：输入标注等信息。使用 UITextView可以设置 scrollEnabled = NO不设置高度约束达到此需求，但YYTextView目前好像不行，不知是否为我的姿势不对，如果没有此功能，YY大神是否可以增加此功能呢，其他同学是否有好的解决方案。
效果如下：
![untitled](https://cloud.githubusercontent.com/assets/12118567/26182367/909bdfa2-3baa-11e7-8a23-01e899012669.gif)

**Comment by zhangxiongwen** [comment]
你可以改一下 调用更新光标的代码即可

**Comment by zhangxiongwen** [comment]
/**
 * 注意：这里是修改了YYTextView，添加了一个更新光标的方法
 */
- (void)_updateSelectionView;

把这个方法加在YYTextView.h 里面，然后你删除全部文字的时候 调用这个方法更新光标即可

**Comment by asiosldh** [comment]
@zhangxiongwen  不太明白您的意思。现在的问题是在我输入内容的增加 YYTextView不会自动变高。

**Comment by zhangxiongwen** [comment]
@asiosldh 我用的不是自动布局

**Comment by asiosldh** [comment]
@zhangxiongwen  谢谢了，说的好像不是同一件事情。😆

**Comment by fllyyou** [comment]
这个自定义高度有解决了吗？我在键盘弹出的时候怎么改变他的高度，也确实更新了，但是，实际可是区域依然没变动，除了把键盘回收起来的时候才产生效果，依然没办法做到自适应，YYtextview是放在scrollview上面的

**Comment by mikemag-dev** [comment]
curious if there is a workaround anybody has found?
