### ISSUE TITLE
YYText 和 YYImage 的长按处理

### ISSUE THREAD

**Issue by lsm307742191** [ibireme/YYText#67]
作者，你好，使用YYKit，应用程序如何得到用户长按了 YYTextView 或者 YYImageView 的事件回调，不是长按可高亮的文字，而是长按了普通文字。
长按后，（弹出UIMenuController）目前出现的是系统的选择文字的放大镜和选择光标，我需要自定义长按后的用户行为菜单。

**Comment by huogh** [comment]
作者你好。YYLabel中的内容是分段落的(也就是文字之间有\n换行)。如何让整个段落可以点击？段落里是有部分高亮文字的，所有将整个段落设置为高亮文字会冲突。

**Comment by ibireme** [comment]
楼上两个问题，都可以直接在 View 上添加 UILongPressGestureRecognizer 来获得点击位置，然后再用 textLayout 来查询对应位置的文本范围和位置等信息。

如果需要改样式，可以直接取出 attributedText 修改后设置回去。
