### ISSUE TITLE
点击手势问题

### ISSUE THREAD

**Issue by lsm307742191** [ibireme/YYText#68]
作者，你好：
- (void)textView:(YYTextView *)textView didTapHighlight:(YYTextHighlight *)highlight inRange:(NSRange)characterRange rect:(CGRect)rect
这个函数是在手指按下的时候就会被触发，有没有回调是在手指抬起的时候触发的

**Comment by ibireme** [comment]
这个是在抬起时触发的。

如果你感觉表现不对，可以检查下是否被其他 Gesture 影响到。

**Comment by lsm307742191** [comment]
确定没有其他的 Gesture 影响，通过代码调试，手指按下不抬起，大概过1秒，这个函数就被执行了。

**Comment by lsm307742191** [comment]
关闭，经过再次确认，抬起的时候触发
