### ISSUE TITLE
YYTextView 使用 YYTextMagnifier 放大镜，放大镜出来后无法持续移动就消失了

### ISSUE THREAD

**Issue by moonfisher** [ibireme/YYText#69]
ibireme，你好。

长按 YYTextView，可以显示圆形放大镜，里面的内容也正常，但当我往左右移动时，只能移动一个字符，然后放大镜就自己消失了。

断点调测，发现走到如下代码：
- (void)touchesCancelled:(NSSet *)touches withEvent:(UIEvent *)event {
    [self _endTouchTracking];
    [self _hideMenu];

    if (!_state.swallowTouch) [super touchesCancelled:touches withEvent:event];
}

感觉很奇怪，touchesBegan，touchesMoved 都正常调用，但很快来了一个 touchesCancelled 导致放大镜消失，此时我的手并未离开屏幕，不知道是什么原因。

**Comment by ibireme** [comment]
touchesCancelled 被调用说明有其他逻辑（比如某些 Gesture）给取消了。

检查一下是否有其他手势加到了相关视图层级上，并把对应的 cancelsTouchesInView 设置为 NO。

**Comment by moonfisher** [comment]
已检查，确实是有其他手势冲突，导致放大镜无法移动，已解决，3q
