### ISSUE TITLE
中文粗斜体问题

### ISSUE THREAD

**Issue by iwenan** [ibireme/YYText#696]
请问怎么支持中文粗斜体。使用YYTextFontWithBoldItalic(); 设置了font，中文只变成了粗体，英文倒是可以支持粗斜体。
我想通过设置matrix来简单的旋转字体，但是这样设置貌似会造成绘制的时候坐标会偏移。
CGAffineTransform matrix = CGAffineTransformMake(1, 0, tanf(15 * (CGFloat)M_PI / 180), 1, 1000, 0);
UIFontDescriptor *desc = [UIFontDescriptor fontDescriptorWithName:[UIFont boldSystemFontOfSize:17].fontName matrix:matrix];
UIFont *font = [UIFont fontWithDescriptor:desc size:17];

**Comment by huoda1237** [comment]
你的问题解决了吗？我也遇到了这个问题

**Comment by iwenan** [comment]
> 你的问题解决了吗？我也遇到了这个问题
改了下 YYTextDrawRun 内部的实现：
https://github.com/iwenan/YYText/commit/fbeeb11c056f8c1abb0abd104fa44c029479107e
