### ISSUE TITLE
iOS 11  YYTextborder 换行 bug

### ISSUE THREAD

**Issue by KittenYang** [ibireme/YYText#699]
如果所示：
![img_0468](https://user-images.githubusercontent.com/5517281/28374162-84362260-6cd6-11e7-9cad-7b638283f330.PNG)
![img_0470](https://user-images.githubusercontent.com/5517281/28374164-849f3cbe-6cd6-11e7-8b26-5936fa5141a3.PNG)

iOS 10上通过插入回车的 unicode : `"\u{180E}"` 可以解决，但是 iOS 11 上回车的 unicode 会占位，如下图。

<img width="302" alt="screen shot 2017-07-19 at 23 18 08" src="https://user-images.githubusercontent.com/5517281/28374860-93f755e6-6cd8-11e7-806d-d00510058b1d.png">

**Comment by Uonlyliveonce** [comment]
貌似可以也可以使用\u{00A0}来填充，并且将其yy_font设置很小的字体就解决了

**Comment by KittenYang** [comment]
@2016321  是的，iOS11 下只能用 `\u{00A0}`。
