### ISSUE TITLE
IB 中的问题

### ISSUE THREAD

**Issue by lsm307742191** [ibireme/YYText#70]
根据你的demo，我自己制作了一个demo，发现一个问题：
一个VC，里面有一个table，使用代码的方式（就是你写的demo中的方式）创建cell，然后在cell中加入YYTextView，这个YYTextView需要显示表情、URL、手机号，其中 url、手机号是高亮并可以点击。这种情况下，一切正常。
但是，同样的代码，这个 cell 我使用 IB 的方式创建，然后 new 出 YYTextView，还是显示表情、URL、手机号，URL和手机号还是使用高亮并可以点击。奇怪的事情发生了，表情、文字显示正常，URL、手机号，这些高亮的元素没有绘制出来，点击这些URL、手机号，有高亮状态，但还是没有显示出URL、手机号的元素。
请帮忙解决这个问题，如果需要我写的demo，请留言。

**Comment by ibireme** [comment]
请尽量提供 Demo。。

**Comment by lsm307742191** [comment]
demo发了，请收邮件。

**Comment by ibireme** [comment]
目前没有收到，垃圾邮件也没有

Guo Yaoyuan
Email: ibireme@gmail.com

2015-12-09 18:17 GMT+08:00 lsm307742191 <notifications@github.com>:

**Comment by lsm307742191** [comment]
在 2015-12-09 18:32:17，"Yaoyuan" <notifications@github.com> 写道：
目前没有收到，垃圾邮件也没有

Guo Yaoyuan
Email: ibireme@gmail.com

2015-12-09 18:17 GMT+08:00 lsm307742191 <notifications@github.com>:

> demo发了，请收邮件。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ibireme/YYText/issues/70#issuecomment-163177665>.
>


—
Reply to this email directly or view it on GitHub.

从网易163邮箱发来的云附件
2YYText-master - 复件.zip (28.25M, 2016年1月8日 18:36 到期)
下载

**Comment by ibireme** [comment]
抱歉，到现在为止仍然未收到。
推荐用 Gmail 发送，或者把 Demo 上传到其他地方。

Guo Yaoyuan
Email: ibireme@gmail.com

2015-12-09 18:40 GMT+08:00 lsm307742191 <notifications@github.com>:

**Comment by lsm307742191** [comment]
1 通过XIB方式不能识别电话号码与网址  但是通过手写代码的方式可以展示手机号与网址
2 cell动态高度调整  YYTextView  不能正确设置动态自适应高度
从网易163邮箱发来的云附件
3YYText-master.zip (25.22M, 2016年1月8日 19:40 到期)
下载

**Comment by ibireme** [comment]
已下载 Demo，自动高亮应该设置 tintColor 或 linkTextAttributes 属性。
