### ISSUE TITLE
YYText 高度的问题

### ISSUE THREAD

**Issue by lsm307742191** [ibireme/YYText#71]
我在table中的每个cell都会插入一个 YYTextView，用来显示表情、高亮URL、高亮手机号，每个cell的内容不一样，高度也不一样，我如何计算每个cell中的YYTextView的高度？

**Comment by ibireme** [comment]
见 readme.md。
另外，如果只需要显示，不需要编辑，用 YYLabel 更好。

**Comment by isbase** [comment]
这种情况,我其实只需要选择复制的功能,还是只能用textview吧

**Comment by ibireme** [comment]
如果只需要复制全部，而不需要选择范围，那也可以用 YYLabel。
YYLabel 更轻量，并且还支持一步绘制。
