### ISSUE TITLE
deleteBackward 删除的时候，肿么知道删除了某一个YYTextBinding，这里好像没有专门的代理和回调通知吧

### ISSUE THREAD

**Issue by SmallBlackBeans** [ibireme/YYText#720]
需求就是和微博发帖一样，@一堆人，但是去人员列表的时候要把选择过的人也勾选上，这样，我如果在编辑页键盘回退删除了某个@的人，肿么去相应的保存的容器里删除对应的人，难道要遍历YYTextBindingAttributeName，对比吗

**Comment by cjnwan** [comment]
请问你是怎么解决这个问题的啊。
