### ISSUE TITLE
深度了解

### ISSUE THREAD

**Issue by lsm307742191** [ibireme/YYText#73]
作者你好，今天向你提了很多问题，还有几个问题想向你再请教一下，能否加我的qq：1196932361

**Comment by ibireme** [comment]
抱歉，QQ 不加陌生人的。
如果有问题，可以看 readme 或直接查看源码，bug 或其他反馈可以提 Issues。

**Comment by lsm307742191** [comment]
很多问题和用法正因为 readme 中没有才问的，这个沟通方式效率有点低，所以才要加QQ，向提高提问效率。
研究一天YYKit了，不错的库。
就差最后一个问题了，readme 上没有详细描述。
我在table中，每个cell 都会使用YYTextView显示表情、高亮URL、高亮手机号，每个cell高度都不一样，我如何得到YYTextView的高度。
感谢你的回答。

**Comment by ibireme** [comment]
计算文本高度见 readme 中的这一段：https://github.com/ibireme/YYText/blob/master/README.md#文本布局计算 ，YYTextView 的文本宽高计算方式一样。

另外，如果不需要文本编辑，推荐用 YYLabel，YYTextView 不支持异步绘制，不支持设置 textLayout，并且资源消耗要更大。

**Comment by hydyy** [comment]
@ibireme  我又来了 测试了一下， 如果添加 10个左右的yytextview 内存暴增。 并且是随着文本框变大一直在增长的。 请问这样正常嘛？

**Comment by ibireme** [comment]
文本是最终渲染成 bitmap 的，所以占用内存会随着显示面积而变大。

**Comment by hydyy** [comment]
@ibireme 谢了啊 我想想办法
