### ISSUE TITLE
在第一个控制器使用YYTextView会造成crash，这算是bug么？

### ISSUE THREAD

**Issue by hello--world** [ibireme/YYText#74]
创建一个工程，就一个普通控制器，然后创建YYTextView，添加到view上，然后就crash，应该是你的代码在window上添加了东西。将控制器添加到UINavigationController就没事。这算bug么？

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'

**Comment by ibireme** [comment]
请更新到最新代码。
关于这个问题的讨论，详情见 #28

**Comment by hello--world** [comment]
嗯，谢谢。
