### ISSUE TITLE
稍微用力拖动的时候出现放大镜效果

### ISSUE THREAD

**Issue by hello--world** [ibireme/YYText#75]
测试了系统的UITextView没有出现

![untitled](https://cloud.githubusercontent.com/assets/9261185/11710952/13c35e40-9f5e-11e5-9119-b3c8f185a70c.png)

<img src="https://github.com/hello--world/image/blob/master/Untitled.gif" width="320">

![image](https://github.com/hello--world/image/blob/master/Untitled.gif )

**Comment by ibireme** [comment]
这是当出现放大镜时，又进行了较大滑动，导致后续操作被取消产生的。
这个出现的概率很小，也不影响使用，暂时不改了。

以后有时间可能会做一下优化。

**Comment by hello--world** [comment]
你好反馈一个问题，在YYTextView上的任意位置滑动，都会出现放大镜效果，如果自定义了inputView，在inputView上滑动也会出现放大镜。

**Comment by ibireme** [comment]
Fixed
