### ISSUE TITLE
你好，请教一个YYTextView在setAttributedText后为啥需要调用一下代理方法？谢谢。

### ISSUE THREAD

**Issue by hello--world** [ibireme/YYText#79]
我用UITextView实现了一个功能，就是每次的输入，字体和颜色都是随机的（就是为了让每次输入的内容带的属性都不一样），textView:shouldChangeTextInRange:replacementText:是在这个代理方法里面改的输入的内容，然后把新输入的增加属性，插入到已有的里面去。然后使用YYTextView时，发现使用setAttributedText后还会调用代理方法，导致一直在循环。请问下，我能用YYTextView实现上面的功能么？谢谢。

**Comment by ibireme** [comment]
当文本将要被替换前，这个方法将会被调用：
textView:shouldChangeTextInRange:replacementText

如果你需要在这时来调整文本，你可能需要放置一个标志位，标记这个方法是被你自己，而不是用户触发的。

**Comment by hello--world** [comment]
按你说的意思是，是在调用setAttributedText之前，标记这个是手动调用的，然后在textView:shouldChangeTextInRange:replacementText:返回NO吗？目前我做出来的效果是，设置了AttributedText，文本没有带属性，就是普通文本。尝试了其他方法，依然不对。当我把回调代理注解掉测试，能设置上。

**Comment by ibireme** [comment]
举个例子：

    @implementation {
    	BOOL _onSetText;
    }

    - (BOOL)textView:(LFTextView *)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString *)text {
    	if (!_onSetText) {
    		// change color and font
    	}
    	return YES;
    }

    - (void)setText {
    	_onSetText = YES;
    	self.textView.attributedText = ...;
    	_onSetText = NO;
    }

**Comment by hello--world** [comment]
![](https://github.com/hello--world/image/blob/master/2.png)
