### ISSUE TITLE
使用yy_setBackgroundColor没有效果，直接setAttributes里面加背景色也没用效果

### ISSUE THREAD

**Issue by clgwd** [ibireme/YYText#81]
YYLabel添加背景色都没有效果
[attributeString setAttributes:@{NSFontAttributeName:[UIFont systemFontOfSize:17],NSForegroundColorAttributeName:[UIColor whiteColor],NSBackgroundColorAttributeName:[UIColor colorWithW:97]} range:NSMakeRange(i, length)];

[attributeString yy_setBackgroundColor:[UIColor colorWithW:97] range:NSMakeRange(i, length)];
2者都没有效果

**Comment by ibireme** [comment]
这个方法注释上标明了只支持 UIKit，不支持 CoreText/YYText。
如果要加背景颜色，可以使用 backgroundBorder。

**Comment by clgwd** [comment]
thankyou
