### ISSUE TITLE
YYTextLayout 获取宽度问题，默认必须大于15才有效么？

### ISSUE THREAD

**Issue by lzcdgit** [ibireme/YYText#818]
- (CGFloat)getFontSizeOfWidthWithStr:(NSMutableAttributedString *)str fontHeigt:(CGFloat)fontHeight
{
    CGFloat w = self.frame.size.width;
    //fontHeight 为什么12 时算不出来? 15哪来的???我的 NSMutableAttributedString 明明设置了字体和图片都是12的高度.
    //高端默认是15了么??高于15才行
    YYTextLayout *layout = [YYTextLayout layoutWithContainerSize:CGSizeMake(CGFLOAT_MAX, 17) text:str];
    w = layout.textBoundingSize.width + 10;
    DLog(@"计算出的宽 %f",w);
    return w;
}

**Comment by yoshimoto91** [comment]
#~~~~

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
