### ISSUE TITLE
你好，请教个问题，关于YYTextView、NSAttributedString、HTML、Image、Parser

### ISSUE THREAD

**Issue by hello--world** [ibireme/YYText#82]
如果只考虑本地归档，可以用yy_archiveToData。
NSAttributedString文字可以转换成HTML，然后用WebView显示出来，也可以转换回来，如果带图片，转换的时候就没有图片的属性了。
然后带Parser表达的时候，Image的信息又可以在text里。
是否拥有一种方法，解决使用YYTextView排版后，在安卓端也能解出来？

**Comment by ibireme** [comment]
抱歉没有，YYText 目前只关注于 iOS 上的文本的渲染。
对于你的需求来说，推荐自定义富文本存储格式，来合理的处理图片数据。
