### ISSUE TITLE
你好，YYLabel使用XIB创建初始化，yy_attachmentStringWithContent图片和视图控件无法显示

### ISSUE THREAD

**Issue by jxaufang168** [ibireme/YYText#83]
0.9.14 YYLabel使用XIB创建初始化，yy_attachmentStringWithContent图片和控件视图无法显示。
手动代码创建YYLabel，设置这些属性可以显示，上一个版本还是可以通过XIB创建 YYLabel，使用这些属性，可以正常显示。

     NSString *title = @"This is UIImage attachment:";
        [text appendAttributedString:[[NSAttributedString alloc] initWithString:title attributes:nil]];
        
        UIImage *image = [UIImage imageNamed:@"dribbble64_imageio"];
        image = [UIImage imageWithCGImage:image.CGImage scale:2 orientation:UIImageOrientationUp];
        
        NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithContent:image contentMode:UIViewContentModeCenter attachmentSize:image.size alignToFont:font alignment:YYTextVerticalAlignmentCenter];
        [text appendAttributedString:attachText];
        [text appendAttributedString:[[NSAttributedString alloc] initWithString:@"\n" attributes:nil]];

**Comment by ibireme** [comment]
Fixed

**Comment by jxaufang168** [comment]
thanks，666666
