### ISSUE TITLE
iOS12上有崩溃

### ISSUE THREAD

**Issue by YasinTian** [ibireme/YYText#858]
0 CoreGraphics | CGColorSpaceEqualToColorSpaceIgnoringRange + 28
-- | --
1 QuartzCore | _CARequiresColorMatching + 256
2 QuartzCore | CACGContextEvaluator::update_with_color_components(CGColorSpace*, double const*) + 120
3 QuartzCore | draw_glyphs(CGContextDelegate*, CGRenderingState*, CGGState*, CGAffineTransform const*, unsigned short const*, CGPoint const*, unsigned long) + 184
4 CoreGraphics | _draw_glyphs + 604
5 CoreText | DrawGlyphsAtPositions(TFont const*, unsigned short const*, CGPoint const*, unsigned long, CGContext*, CGAffineTransform, CGAffineTransform, bool) + 2940
6 CoreText | CTFontDrawGlyphsAtPositions + 192
7 CoreText | TRun::DrawGlyphsAtPositions(CGContext*, CFRange, CGPoint const*, bool) const + 228
8 CoreText | CTRunDraw + 176
9 PengPeng | YYTextDrawRun (YYTextLayout.m:2233)
10 PengPeng | -[YYTextLayout drawInContext:size:point:view:layer:debug:cancel:] (YYTextLayout.m:3358 [Inline: YYTextDrawText])
11 PengPeng | __30-[YYLabel newAsyncDisplayTask]_block_invoke.330 (YYLabel.m:1135)
12 PengPeng | -[YYTextAsyncLayer _displayAsync:] (YYTextAsyncLayer.m:222)
13 PengPeng | -[YYTextAsyncLayer display] (YYTextAsyncLayer.m:115)
14 QuartzCore | CA::Context::commit_transaction(CA::Transaction*) + 548
15 QuartzCore | CA::Transaction::commit() + 608
16 QuartzCore | CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
17 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
18 CoreFoundation | ___CFRunLoopDoObservers + 412
19 CoreFoundation | ___CFRunLoopRun + 1264
20 CoreFoundation | CFRunLoopRunSpecific + 436
21 GraphicsServices | GSEventRunModal + 100
22 UIKitCore | UIApplicationMain + 212
23 PengPeng | main (main.m:25)
24 libdyld.dylib | _start + 4

**Comment by WZBbiao** [comment]
我也遇到了同样的问题，线上目前情况来看，每天的异常机型占比：
iPhone 5S 27.50%
iPhone 6 Plus 25.00%
IPAD7,5 10.00%
iPhone 6 10.00%
iPad mini 27.50%

基本上都是iOS12的系统
12.1.2 (16C101) 22.50%
12.1.1 (16C50) 22.50%
12.1.2 (16C104) 17.50%
12.0 (16A366) 12.50%
12.0.1 (16A404) 12.50%

希望尽快修复吧

**Comment by sum123** [comment]
我的也是

**Comment by YasinTian** [comment]
@Sum123 @WZBbiao 我发现可能是特殊字符的问题，但是目前还不能确定如何引起的

**Comment by a244676199** [comment]
现在有结果了么？可以给个联系方式一起讨论下么？

**Comment by YasinTian** [comment]
> 现在有结果了么？可以给个联系方式一起讨论下么？

太久了，都忘记这个是哪个Bug了。

**Comment by a244676199** [comment]
目前我这还没有头绪 最后怎么改好的有印象么？

**Comment by YasinTian** [comment]
> 目前我这还没有头绪 最后怎么改好的有印象么？

好像改过一个阿拉伯文的问题，不知道是不是这个，你显示阿拉伯文看看会不会崩溃。

**Comment by a244676199** [comment]
我这不支持阿拉伯文，现在展示的普通的汉字和表情 都会崩溃，

**Comment by a244676199** [comment]
看样子是复用导致的这个问题，但是复用不使用的话 我难道要给他置为nil么

**Comment by xichen744** [comment]
@YasinTian 
所以最后你们怎么修复的?

**Comment by YasinTian** [comment]
> @YasinTian
> 所以最后你们怎么修复的?

好像有一个布局的最大size，设置一下。这个问题好像是特殊字符导致的宽度计算出来是一个极大值，导致的崩溃。

**Comment by xichen744** [comment]
@YasinTian 
还记得是哪个特殊字符吗?
我之前改过YYTextContainerMaxSize这个,  设置了一个合理的最大宽度吗? 你也是吗?
