### ISSUE TITLE
当YYlabel添加图片的时候，前边的文本如果有空格，则后边添加的东西会有间距

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#88]
NSMutableAttributedString*  attachment = [NSMutableAttributedString yy_attachmentStringWithContent:image contentMode:UIViewContentModeCenter attachmentSize:image.size alignToFont:[UIFont systemFontOfSize:16] alignment:YYTextVerticalAlignmentCenter];
     //   [name yy_setKern:@5 range:NSMakeRange(name.length-1, 1)];
        [name appendAttributedString:attachment];
当前边的name中有空格，后边的Image就会和name多出一个空格的间距。小bug，希望fix一下。

**Comment by ibireme** [comment]
如果 name 有空格，那多出一个空格的间距不是正常的吗？
能给一下更详细的说明吗，比如代码片段、屏幕截图？

**Comment by wy19901227** [comment]
name结尾有空格是有间距是正常的，可是当name中间有空格，结尾没的时候，图片也会和name有空格
![image](https://cloud.githubusercontent.com/assets/8086633/11887520/fe68ec0a-a56f-11e5-8283-a2640393d507.png)

**Comment by wy19901227** [comment]
如图 中间的那个折 字 理论上应该和 式 挨着。

**Comment by wy19901227** [comment]
不好意思  仔细检查了下，是我们服务端 在后边加了空格。。。，这个服务端。。。不好意思，我关了。
