### ISSUE TITLE
效率的问题   

### ISSUE THREAD

**Issue by Ewithome** [ibireme/YYText#90]
NSString *title = @"This is Animated Image attachment:";
        [text appendAttributedString:[[NSAttributedString alloc] initWithString:title attributes:nil]];

        
        YYImage *image = [YYImage imageNamed:@"pia"];
        image.preloadAllAnimatedImageFrames = YES;
        YYAnimatedImageView *imageView = [[YYAnimatedImageView alloc] initWithImage:image];
        imageView.autoPlayAnimatedImage = NO;
        [imageView startAnimating];
        
        NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithContent:imageView contentMode:UIViewContentModeCenter attachmentSize:imageView.size alignToFont:font alignment:YYTextVerticalAlignmentBottom];
        [text appendAttributedString:attachText];
        
        [text appendAttributedString:[[NSAttributedString alloc] initWithString:@"\n" attributes:nil]];

这是你demo  里的代码   如果  我现在有比较多的（也不是很多不到1K） 文字 和图片  而且是随机的   就要循环 加载吗   这样有卡动的现象    有没有什么很好的办法     还有计算Label  高度的时候也有在写一个Label   在计算  效率很低啊   有点卡     求帮助  谢谢

**Comment by ibireme** [comment]
1. 如果是 emoticon 类型的动画表情，则尽量复用已创建的图片对象，而不要重复创建。autoPlayAnimatedImage 设为 YES 就可以，没必要手动启动动画。

2. 文本的设置、布局计算尽量放入后台线程进行，不要放到主线程。

3. 使用异步排版和渲染：https://github.com/ibireme/YYText#异步排版和渲染

**Comment by Ewithome** [comment]
label.displaysAsynchronously = YES; //开启异步绘制
//        label.ignoreCommonProperties = YES;   
一写这个就不会加载了

**Comment by ibireme** [comment]
这两个属性的用法见 readme 和注释。
简单说：

label.displaysAsynchronously = YES; //开启异步绘制
label.ignoreCommonProperties = YES; //忽略除了 textLayout 之外的其他属性

**Comment by Ewithome** [comment]
![Uploading A24229B3-E129-4C9D-BE88-8893E6E9F4D3.png…]()
还是不行啊  
   我不知道  这算多不啊  就是在加载这个Cell的时候会卡一下    但是看demo   最后一个  也没有哪么卡   啊   不知道  怎么解决    YY 能不能给些一个 异步加载的demo 啊

**Comment by Ewithome** [comment]
![Uploading A24229B3-E129-4C9D-BE88-8893E6E9F4D3.png…]()

**Comment by Ewithome** [comment]
![Uploading A24229B3-E129-4C9D-BE88-8893E6E9F4D3.png…]()

**Comment by Ewithome** [comment]
我发了  20 几个  gif  文件知道这算多不

**Comment by Ewithome** [comment]
20 几个  gif  表情

**Comment by ibireme** [comment]
图片的读取和解码，都要放到后台线程进行。

**Comment by Ewithome** [comment]
是在后台的

**Comment by ibireme** [comment]
那你需要拿 Instruments 自己来判断卡顿发生的位置了。
