### ISSUE TITLE
Autolayout支持以及文本正则表达式识别支持

### ISSUE THREAD

**Issue by dengbotian** [ibireme/YYText#91]
你好,请问什么时候可以支持Autolayout吗? 还有文本高亮能不能进一步封装,同时支持正则匹配,设置匹配的文本颜色,以及对应的回调函数. 这样会及其易用.

**Comment by ibireme** [comment]
1. 文本高亮刚刚加了几个更方便的方法封装，详情见 readme 中的`文本高亮`。
2. 正则匹配这个没有做，这块儿每个人的需求都不一样，封装也不会有太好的方法。但是简单的链接识别可以用 YYTextView.dataDetectorTypes 来做。
