### ISSUE TITLE
【not  issue】 针对iOS13下双光标、深色模式适配、以及更多问题的解决方案

### ISSUE THREAD

**Issue by NSaylor** [ibireme/YYText#912]
首先感谢作者的开源贡献，在持续使用的过程中解决了一些遇到的问题。共享在这里，希望能给大家提供帮助~

针对YYTextView、YYLabel的相关问题解决记录
https://www.jianshu.com/p/4bae9e942630
改造YYTextView 实现类似IQKeyboardManager的功能
https://www.jianshu.com/p/4cb53ca40b13
针对iOS13的适配
https://www.jianshu.com/p/d2a0fa7bcbef

**Comment by wangyanlong** [comment]
感谢您的分享，帮助我解决了很多问题🙏

**Comment by NSaylor** [comment]
@wangyanlong 　真巧，我的名字也是　WYL　能帮到你就好　🤝
