### ISSUE TITLE
iOS 13 CTFontRef控制台报错

### ISSUE THREAD

**Issue by yangjw** [ibireme/YYText#916]
CoreText performance note: Client called CTFontCreateWithName() using name ".SFUI-Regular" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.

**Comment by yangjw** [comment]
> 
修改UIFont+YYAdd.m
-  CTFontRef font = CTFontCreateWithName((__bridge CFStringRef)self.fontName, self.pointSize, NULL);
+  CTFontRef font = CTFontCreateWithFontDescriptor((__bridge CTFontDescriptorRef)self.fontDescriptor, self.pointSize, NULL);

**Comment by CoderYLZhang** [comment]
UIFont+YYAdd.m 没有这个文件呢
