### ISSUE TITLE
YYTextView 的一个问题.

### ISSUE THREAD

**Issue by isbase** [ibireme/YYText#93]
YYTextView *textView = [YYTextView new];
    textView.backgroundColor = [UIColor greenColor];
    textView.frame = CGRectMake(0, 100, size.width, 100);
    textView.font = [UIFont systemFontOfSize:17];
    textView.textColor = [UIColor redColor];
    textView.textAlignment = NSTextAlignmentLeft;
    textView.editable  = NO;
//////

origin.y 不等于0的是时候,textview 上面默认有空白.

![img_4438](https://cloud.githubusercontent.com/assets/2680393/11989257/a1a4da64-aa34-11e5-962c-59b8d20420d3.PNG)

**Comment by ibireme** [comment]
设置 ViewController.automaticallyAdjustsScrollViewInsets = NO;
