### ISSUE TITLE
关于YYtextview 一个小问题.

### ISSUE THREAD

**Issue by isbase** [ibireme/YYText#94]
假如YYTextview加在scrollview .之后长按选择文本,uiscrollview 会拦截touch事件.这个怎么解决?

系统的uitextview 是没有这个问题的.

**Comment by isbase** [comment]
scrollView.delaysContentTouches = NO;
    scrollView.canCancelContentTouches = NO;

**Comment by shanbozhu** [comment]
这么设置的话直接不接收滑动了, 没有达到效果啊
