### ISSUE TITLE
使用YYText之后如何跟安卓交互?

### ISSUE THREAD

**Issue by HuaZao** [ibireme/YYText#95]

**Comment by ibireme** [comment]
与安卓有什么关系啊。。

**Comment by HuaZao** [comment]
我这边做出来..通过NSData上传服务器..安卓那边怎么解析..或者有什么其他办法 毕竟客户端都是安卓和IOS互通的

**Comment by ibireme** [comment]
你可能需要定义一套自己的简单的标记语言（比如 UBB、简化版 HTML），用于和其它平台做交互。

**Comment by HuaZao** [comment]
用YYText可以实现这种效果吗?

**Comment by ibireme** [comment]
不能，你多少需要自己写一些解析与合成的代码，制定一些自己的规则。

如果怕麻烦，推荐用基于 WebView 的一些富文本方案。
