### ISSUE TITLE
删除YYTextBinding 时，怎么知道删掉了哪一个 。 如何把字符串 和 用户信息绑定在一起

### ISSUE THREAD

**Issue by HT204370534** [ibireme/YYText#957]
我们的需求类似微博，选中@的用户，删除时移除用户，那么我怎么在删除时判断删的是哪一个，是否有把字符串绑定用户信息的方法？

**Comment by HT204370534** [comment]
我目前解决方法：在@拼接 用户名的时候，给【@xxx】这个富文本设置了 YYTextAttachment 这个对象，里面存了一个 字典@{userid:xxxxxx},当我删除用户时做了一个判断，如果是删除的是@xxx 这个绑定的 富文本，那么我就遍历这个文本的富文本属性 用到的代码是：textView.attributedText enumerateAttribute:YYTextAttachmentAttributeName，如果得到了 value[YYTextAttachmentAttributeName]的值 就可以拿到 userId,然后在删除的时候判断 数据源中的user 和 要删除的userid 是相同的,我就直接从数据源中删除这个Model

感觉会有其他逻辑问题且不是很方便，如果大家有啥好建议请回复我

**Comment by AYJk** [comment]
看这里，作者给出的方案 https://github.com/ibireme/YYText/issues/163
