### ISSUE TITLE
CoreText note: Client requested name ".SFUI-Regular" 如何解决

### ISSUE THREAD

**Issue by CoderYLZhang** [ibireme/YYText#969]
CoreText note: Client requested name ".SFUI-Regular", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[UIFont systemFontOfSize:].

出现该问题的时候会有明显的UI 卡顿

**Comment by li-qingnan** [comment]
同样遇到这个问题。
