### ISSUE TITLE
YYTextLayout Question

### ISSUE THREAD

**Issue by devSC** [ibireme/YYText#98]
请问下如果有如下用法:
`        attribuatedString.alignment = NSTextAlignmentCenter;
`
则计算后的宽度和显示的UI不正确.
请教下这里该如何使用.

**Comment by ibireme** [comment]
计算时，给定宽度。计算后，宽度还用给定值，高度用计算结果中值。

**Comment by devSC** [comment]
刚才试了,通过Textlayout计算是不行, 设置完
`
attribuatedString.alignment = NSTextAlignmentCenter; 
` 
按照你的方法来赋值后还是在左边(NSTextAlignmentLeft)模式..

**Comment by ibireme** [comment]
能给下你计算与显示文本的代码片段吗？我看看是什么问题。

**Comment by devSC** [comment]
计算TextLayout:
`
    self.introLabelLayout = ({
        NSMutableAttributedString *attribuatedString = [[NSMutableAttributedString alloc] initWithString:[self producevalidStringIfNecessary:self.entity.intro]];
        attribuatedString.color = NHStyle.grayColor_999999;
        attribuatedString.font = NHStyle.font_13;
        attribuatedString.alignment = NSTextAlignmentCenter;
        NSMutableParagraphStyle *style = [[NSMutableParagraphStyle alloc] init];
        [style setLineSpacing:5];
        [attribuatedString addAttribute:NSParagraphStyleAttributeName
                                  value:style
                                  range:NSMakeRange(0, attribuatedString.length)];

        YYTextContainer *container = [YYTextContainer containerWithSize:CGSizeMake(kNameLabelWidht, CGFLOAT_MAX)];
        container.maximumNumberOfRows = 0;
        [YYTextLayout layoutWithContainer:container text:attribuatedString];
    });
`
设置Layout:
`
    self.introLabel.textLayout = layout.introLabelLayout;
    self.introLabel.height = layout.introLabelLayout.textBoundingSize.height;
    self.introLabel.width = kNameLabelWidht;
`
用到的宏:
#define kNameLabelWidht kScreenWidth - MARGIN_20 * 2

**Comment by ibireme** [comment]
alignment 这个属性，实际上是对内部的 NSParagraphStyle.alignment  的封装，所以稍后你重新设置了 NSParagraphStyle，就会把之前设置的 alignment 覆盖掉。

你这里可以这样设置：

    attribuatedString.color = NHStyle.grayColor_999999;
    attribuatedString.font = NHStyle.font_13;
    attribuatedString.alignment = NSTextAlignmentCenter;
    attribuatedString.lineSpacing = 5;

另外，如果你只用到 textLayout 属性来显示文本，那可以设置 label.ignoreCommonProperties = YES 来节省计算量。

**Comment by devSC** [comment]
的确是. 很感觉回答.

另外我在初始化的时候有设置
````
 label.ignoreCommonProperties = YES 
````
