### ISSUE TITLE
YYLabel 换行问题。

### ISSUE THREAD

**Issue by wy19901227** [ibireme/YYText#99]
_name=[[YYLabel alloc]init];
   _name.frame=CGRectMake(128, 15, [UIScreen width]-130, 19);

然后 我设置了他的text。 文本比设置的宽度宽，正常应该是出现缩略，但是却出现这样的情况。
![image](https://cloud.githubusercontent.com/assets/8086633/12060392/a0572372-afa9-11e5-9604-a44680f97d0e.png)

**Comment by ibireme** [comment]
_name.lineBreakMode = NSLineBreakByTruncatingTail;
_name. numberOfLines = 1;
_name.text = xxx

这样试试呢

**Comment by wy19901227** [comment]
这样可以，但是会因为有字母或者数字，label的frame必须要调大点。

发自我的 iPhone

**Comment by ibireme** [comment]
嗯嗯～最好留些空间出来～

**Comment by wy19901227** [comment]
settext 和settextlayout有什么区别？

发自我的 iPhone

**Comment by ibireme** [comment]
setText 后，Label 内部会根据 label 的 frame，生成一个 text layout，然后显示。
setTextLayout 时，是调用者已经根据某个大小计算好了文本排版结果，label 会直接拿这个来绘制，而不管 label 的 frame 了。
